### ISSUE TITLE
Deploy button must be disabled if node was not selected (manually or from automatic suggestion)

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#100]
Otherwise, it will raise some irrelevant errors.

Also, maybe it's better to say it's not auto-selection, but something like auto suggestions (we don't select nodes by ourselves)

**Comment by xmonader** [comment]
What I already did 
- renamed automatic to `Capacity filter`
- changed apply filters to `Apply filters and suggest nodes`
- updated the isValidInteger to reject 0 (which null is casted to with +val)
- Triggered checks for `nodeExists` and `validateNode` on change of the nodeId value

the only missing thing is disabling the deploy button in case of `doesn't exists or doesn't have enough resources errors`

**Comment by MohamedElmdary** [comment]
### PR
https://github.com/threefoldtech/grid_weblets/pull/122
