### ISSUE TITLE
Unable to login to peertube instance when certain domains are used

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1000]
So to make sure that the nodes are working i tried almost every solution that needs a gateway `peertube, funkwhale, ownCloud, subsquid, casperlabs, etc ...` and the connection was secure for the 2 domains `libra.tfcloud.us` & `devops.tfcloud.us` 

however i encountered a couple of weird cases, the first one is related to `peertube` and i encountered this using the 2 domains. after successfully deploying 2 instances one on each gateway node i got the following error when i tried to access these instances. 

![image](https://user-images.githubusercontent.com/101194226/188307153-fdec55c8-4a5f-49ca-8710-98855e9602d0.png)

and when i tried to login using admin email/password or using `ThreeFold Connect` i got the same error.

![image](https://user-images.githubusercontent.com/101194226/188307235-7c838073-7105-45a4-b2bf-91940ff66d5b.png)

and to verify that this issue was only related to these domains i then deployed another peertube instance but this time i deployed it on `gent01.dev.grid.tf` and it worked and the login was working using both methods.

_Originally posted by @mohamedamer453 in https://github.com/threefoldtech/grid_weblets/issues/964#issuecomment-1236302112_

**Comment by ramezsaeed** [comment]
it worked fine because this domain is configured correctly.
