### ISSUE TITLE
UI: Add confirmation message before removing workers from k8s clusters

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1001]
### Description

Add a confirmation message before removing a worker from a k8s cluster instead of deleting it immediately 

![TF Playground (31)](https://user-images.githubusercontent.com/101194226/189103119-4948190d-cfe3-497d-8faa-e477bb2f9dea.gif)

**Comment by khaledyoussef24** [comment]
verified on devnet

steps made to verify :

1. go to kubernetes
2. deploy a master with one worker
3. go to deployments > kubernetes > choose the master > choose manage workers
4. choose remove worker
5. a pop up message will ask if you really want to remove worker
![Screenshot from 2022-09-19 06-07-56](https://user-images.githubusercontent.com/110984055/190948654-0b369d76-2a27-4a51-bfe8-8376af14bd62.png)

**Comment by A-Harby** [comment]
[TC757 - Delete Kubernetes Worker](https://app.testlodge.com/a/26076/projects/40893/suites/195824?expand_section=311053#case_3574046)
