### ISSUE TITLE
Get the full deployment data from contract's id

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#1004]
If a user has some contracts and doesn't know which contract belongs to which deployment, there is no way to know that, so it can be safely deleted. Also if developers want to troubleshoot why this contract is not deleted with deployment, it would be good to ask the user to get the deployment data in an easy way.

### Suggestion 
Allow getting the contract's deployment data from the node by clicking on the contract's id

**Comment by mohamedamer453** [comment]
Verified on devnet.

A button for showing the details of each contract was added in the contracts list.

![image](https://user-images.githubusercontent.com/101194226/200889578-e247f19a-cb73-465c-9a90-ca54c4794c58.png)

and it includes all of the contracts' details.

![image](https://user-images.githubusercontent.com/101194226/200889816-1be3b5f6-d8bf-4004-bd1a-91bcb38a39ac.png)

even when the contract is deployed from another service like terraform it also appear and full details for it can be retrieved from this option. example: the screenshot below is the contract details of a vm deployment from terraform.

![image](https://user-images.githubusercontent.com/101194226/200890443-8975b763-f216-4f2d-912c-4a639dbb0b51.png)
