### ISSUE TITLE
Subsquid Input Validation

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1005]
### Description

The input validation for the `Subsquid` weblet is not working correctly in some fields and these fields are:

### Subsquid Endpoint

There is no defined format validation for this field and it accepts anything except for leaving it empty. i'm not sure if there's a defined format for this endpoint but if there is then it should be added for this field

![image](https://user-images.githubusercontent.com/101194226/189638061-2b07dd46-99b0-400f-8393-fc87f1931fcd.png)

### CPU

The Deploy button is not disabled when the field is empty or when the value is invalid

![image](https://user-images.githubusercontent.com/101194226/189640108-8332fa0d-abd9-43d5-a961-896908a0aecf.png)

![image](https://user-images.githubusercontent.com/101194226/189639912-a5ad2b8f-8a5b-414a-802b-97722a169935.png)

### Memory 

The Deploy button is not disabled when the field is empty or when the value is invalid

![image](https://user-images.githubusercontent.com/101194226/189640192-76444c7e-2c5c-40af-9926-b754318f14fd.png)

![image](https://user-images.githubusercontent.com/101194226/189640154-c40ef24e-90a9-41b3-b631-723670c3d3d3.png)

### Disk 

The Deploy button is not disabled when the field is empty.

![image](https://user-images.githubusercontent.com/101194226/189640393-67cfcaeb-2ebc-4da8-8696-19ab66263506.png)

**Comment by zaelgohary** [comment]
Fixed the validation for the endpoint field as per the endpoints [here](https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/endpoints/production.ts).

Memory, CPU & disk were removed earlier as they're now part of the solution flavor so no validation is needed for them.

**Comment by mohamedamer453** [comment]
Validation for the `Subsquid Endpoint` was added according to the endpoints mentioned [here](https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/endpoints/production.ts) in the form of `wss://<something>.<something>`

![image](https://user-images.githubusercontent.com/101194226/190371208-ea715409-837e-4c9c-942f-a3cca058085a.png)

in the first part of the url the user is not allowed to enter any special characters or spaces but after typing `.` and any 2 characters the user is then allowed to enter any special character or spaces

![image](https://user-images.githubusercontent.com/101194226/190371882-50e68cc9-ae09-4954-bd35-eb796514b4db.png)

and for the second part of the issue, the cpu, memory, and disk options are still available upon choosing the `Custom` option from the solution flavor dropdown and it still produces the mentioned issues.


![TF Playground (33)](https://user-images.githubusercontent.com/101194226/190372996-38f7a463-d04c-4f73-8814-de474f0bed7d.gif)

**Comment by zaelgohary** [comment]
Edited the regex so the endpoint won't have any spaces or special chars at the end.

**Comment by zaelgohary** [comment]
Also disabled the button on invalid CPU, Memory, or disk.

**Comment by mohamedamer453** [comment]
### Subsquid Endpoint

The validation was fixed to not accept spaces and special characters at the end of the url.

![image](https://user-images.githubusercontent.com/101194226/191275799-1d901ccb-ddf9-4df6-b091-915e1947f42d.png)

![image](https://user-images.githubusercontent.com/101194226/191275892-d792c9c8-a60e-4c02-a304-5e4e109a29fd.png)


however by checking the endpoints available [here](https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/endpoints/production.ts), i found that some endpoints contain `-` and it triggers the validation as an invalid character or endpoint format even though it's a valid endpoint.

![image](https://user-images.githubusercontent.com/101194226/191280973-d1cee42f-0ed9-4865-9445-841afafb9c25.png)

![image](https://user-images.githubusercontent.com/101194226/191281104-3083a5d1-8a7e-4ecd-a7fc-b05557b37c5f.png)

### CPU, Memory, Disk

For these fields the deploy button was disabled when there's a validation error.

![image](https://user-images.githubusercontent.com/101194226/191285351-8ca42071-fe94-4349-bb6f-20e161932dd2.png)

![image](https://user-images.githubusercontent.com/101194226/191285509-885fdf2f-9d34-4419-8376-f962de5a3b6c.png)

![image](https://user-images.githubusercontent.com/101194226/191285647-cd1cc192-12b7-49f3-acb2-869512568103.png)

**Comment by A-Harby** [comment]
Everything is working fine, 
expect endpoints ending with ports like `wss://mainnet.uniarts.vip:9443`
![image](https://user-images.githubusercontent.com/109473873/193857213-c5a167d7-bba7-4133-a996-9ded29d6f5b6.png)

**Comment by khaledyoussef24** [comment]
endpoint issue fixed and working fine
![Screenshot from 2022-10-09 14-01-02](https://user-images.githubusercontent.com/110984055/194755722-83f4b06d-c4a8-4743-a7c5-bda3dd50a8fb.png)

**Comment by A-Harby** [comment]
Test steps: [TC1120 - Subsquid Input/Configuration Validation](https://app.testlodge.com/a/26076/projects/40893/suites/195824?expand_section=337537#case_3698513)
