### ISSUE TITLE
The manual filter reports nodes with invalid ids as dedicated nodes

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1007]
### Description

When you enter an invalid id in the manual filter it doesn't mention that a node with this id doesn't exist, however it mentions that the node `is dedicated and not reserved for your account, please check the dashboard.`

![image](https://user-images.githubusercontent.com/101194226/189642507-91d07e16-03e8-47d2-8551-737e374ff10e.png)

for example the last created node on devnet has the id of `57` and and when you enter `58` for example it'll tell you that the node is dedicated while in fact there is no node with that id 

![image](https://user-images.githubusercontent.com/101194226/189642977-47f98a13-b778-440b-abb2-6c8e0b857a0f.png)

![image](https://user-images.githubusercontent.com/101194226/189643050-4c9f9f6e-861e-40d0-bb9a-29285817a948.png)

**Comment by mohamedamer453** [comment]
Verified on devnet

The error message for invalid nodes was changed from reporting it as a dedicated node to reporting it as node not found.

![image](https://user-images.githubusercontent.com/101194226/191239125-fb8551a6-656a-4136-9faf-92d5b699a9d0.png)

![image](https://user-images.githubusercontent.com/101194226/191239193-e57a5a7a-4fa1-4ff4-bc90-2fd427d7d94a.png)

**Comment by A-Harby** [comment]
Test steps: [TC783 - Verify Manual Filter (Dedicated Nodes)](https://app.testlodge.com/a/26076/projects/40893/suites/195824?expand_section=346849#case_3614634)
