### ISSUE TITLE
UI: confirmation msgs

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/grid_weblets#1012]
### Description

Can we convert window confirmation msgs to dialog msgs
 
### Implementation

- In case of deletion or adding new items

### More

This dialog is an example

![Screenshot from 2022-09-14 16-32-29](https://user-images.githubusercontent.com/47260239/190184065-51f92002-1878-4eca-9cf3-b4b915837cc0.png)

**Comment by khaledyoussef24** [comment]
### verified on devnet
steps made to verify

1. go to weblets
2. add profile
3. remove the profile
4. notice the dialog

![Screenshot from 2022-10-25 12-06-54](https://user-images.githubusercontent.com/110984055/197745812-4c803770-1921-4478-9314-b5f3e527bf18.png)
