### ISSUE TITLE
Capacity filter does not work on testnet for PRE deployment

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#1013]
Tried to deploy a PRE node on testnet, using the capacity filter. But it only shows FreeFarm2 and SmithTacTestOps, not FreeFarm despite the fact I know that capacity is available. Selecting a Freefarm node manually works well. 

<img width="1142" alt="Screenshot 2022-09-15 at 11 13 15" src="https://user-images.githubusercontent.com/30384423/190365151-d0c40142-dab2-4f16-b08e-d63c039f9ea0.png">

**Comment by khaledyoussef24** [comment]
### verified on testnet

1-open a deployment 
2-in the node selection choose capacity filter
3-verify that all the free farms are found
4-verify that all the free nodes are found
![Screenshot from 2022-10-30 09-43-12](https://user-images.githubusercontent.com/110984055/198867838-eb135d99-e19b-45bd-b4ef-84b4e769638f.png)

![Screenshot from 2022-10-30 09-41-30](https://user-images.githubusercontent.com/110984055/198867795-a9f563d2-0d8e-4185-ad71-04d081957358.png)
![Screenshot from 2022-10-30 09-39-45](https://user-images.githubusercontent.com/110984055/198867796-20c203b1-b6c6-4046-8f34-7f4aafc1845f.png)
![Screenshot from 2022-10-30 09-39-34](https://user-images.githubusercontent.com/110984055/198867804-fe6abd7b-3840-4904-866b-420d2a80c676.png)
