### ISSUE TITLE
Remove the Environment Variables tab & the Mount Point option from the Full VM Deployment

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1015]
### Description

The `Environment Variables` tab and the `Mount Point` option int the `Full Virtual Machine` deployment should be removed since they are not used.

In the case of the `Mount Point`: the disks added to the full vm are not mounted and the user has to mount them manually. so the `Mount Point` field should be removed since it will not be used. 

Also in the full vm  deployment the environment variables added to the deployment are not used and the only env var used is the ssh key and it's injected directly to the vm so the `Environment Variable` tab should also be removed from the full vm since it's not used.

**Comment by khaledyoussef24** [comment]
### verified on devnet

previously the enviroment tab was found in weblets

![Screenshot from 2022-11-01 17-13-16](https://user-images.githubusercontent.com/110984055/199267918-d45a73e0-0144-42f8-b14d-b9453eff9cd9.png)

now it is removed succesfully

![Screenshot from 2022-11-01 17-13-08](https://user-images.githubusercontent.com/110984055/199268031-533a6076-290e-42eb-949c-9e6a44d422ba.png)
