### ISSUE TITLE
Add a separate documentation for the full virtual machine deployment

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1016]
### Description

A separate documentation for the full vm should be added since the only available docs are for the micro vm and there are differences between these 2 types of vms. 
- The docs should point out the difference between a full and a micro vm.
- Instructions on how to manually mount disks in a full vm should be added since it's not mounted automatically like the micro vm as mentioned in #1015 
-  The quick start docs link for the full vm should be replaced once these docs are created.

**Comment by maayarosama** [comment]
The docs should also point out that only cloud init flist that already contains a kernal will be deployed, other than that the user will get this error message.
![fullvm_error](https://user-images.githubusercontent.com/66883096/193562898-2159550d-8933-4ecd-8dad-fde7ab02dc9f.jpg)

**Comment by khaledyoussef24** [comment]
the docs of the full vm and micro vm is still the same
they both opens the same url 
and the manual isn't updated yet
https://library.threefold.me/info/manual/#/manual__weblets_vm

![Screenshot from 2022-11-09 16-15-51](https://user-images.githubusercontent.com/110984055/200854424-dff930b6-374a-4a02-aea8-b6db359be2d3.png)

**Comment by mohamedamer453** [comment]
Verified.

The content of the docs was verified from https://github.com/threefoldfoundation/info_manual3/blob/development/wiki/weblets/weblets_fullvm%20.md 

Separate documentation for the full vm was added with explanation on the difference between full and micro vms and also steps on how to manually mount the added disks in a full vm and after following the steps i was able to successfully mount the added disk inside the VM.

![image](https://user-images.githubusercontent.com/101194226/201047524-606a1c7c-b9b3-4c0a-9b6b-0991b40936b5.png)

the quick start link for the docs is still not available in the weblets since it's not available yet in https://library.threefold.me/info/manual/#/  so i created a separate issue for the quick start link and some minor fixes in the docs.

#1094
