### ISSUE TITLE
upgrade ubuntu to 22.04 for microVM

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1017]
it only exists in full VM

**Comment by zaelgohary** [comment]
Created a new flist for Ubuntu22.04 [here](https://hub.grid.tf/zaelgohary.3bot/threefolddev-ubuntu-22.04.flist.md) and pending converting it to an tf-official-flist in order to include it in the microVM.

**Comment by maxux** [comment]
It's a VM ? It should go to tf-official-vms then, what name do you want ?

**Comment by AhmedHanafy725** [comment]
it's not a clould init vm. maybe https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-22.04.flist

**Comment by maxux** [comment]
https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-22.04.flist.md

**Comment by A-Harby** [comment]
Verified on Devnet.
Ubuntu version updated on MicroVM.

![image](https://user-images.githubusercontent.com/109473873/193541880-be0e8f01-77ce-40eb-9880-82e788bbdd3d.png)
Deployed and checked.
![image](https://user-images.githubusercontent.com/109473873/193542184-bcb72efa-4715-4742-b3bc-8b7531f8aa74.png)
