### ISSUE TITLE
gridproxy should update capacity information more often

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#102]
We should ask gridproxy if the node have enough resources, it caches this info every 15 minutes, so, let's make it like every two minutes instead, which make it less likely to give false positives.

**Comment by xmonader** [comment]
Please open another issue in the gridproxy repo for @waleedhammam

**Comment by waleedhammam** [comment]
issue created and resolved, release made, update issues are here:
https://github.com/threefoldtech/tf_operations/issues/469
https://github.com/threefoldtech/tf_operations/issues/470

**Comment by abom** [comment]
Closing as related issues are all resolved now.
