### ISSUE TITLE
The `Delete All` Contracts button also deletes rent contracts

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1027]
### Description

The `Delete All Contracts` or `Delete Selected` when you select all contracts will also delete rent contracts even though rent contracts are not listed in the `Contracts List` .

as seen in the screenshot below i had a rent contract for node `205` with the id of `13051`

![image](https://user-images.githubusercontent.com/101194226/192251737-874ac4a3-3a00-4a9e-afa4-0ea683d12314.png)

in the video below you can see in the console after the 4 contracts appearing in the contracts list get deleted, the rent contract also gets deleted even though it's not displayed in the contracts list nor is it mentioned anywhere that the rent contracts will also be deleted.

[Untitled_ Sep 26, 2022 12_16 PM.webm](https://user-images.githubusercontent.com/101194226/192253062-5e4132ca-4a53-483b-a71c-65a7ceda7b76.webm)

**Comment by khaledyoussef24** [comment]
### verified on devnet

make a rent contract
rent contracts are now visible in the contract list

![Screenshot from 2022-10-30 08-19-09](https://user-images.githubusercontent.com/110984055/198865423-938ae443-b7cf-4e5e-ab8a-0f8c8bdfdbac.png)
