### ISSUE TITLE
mention it would take sometime for any solution to start (CapRover, Peertube...)

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#103]

**Comment by xmonader** [comment]
Indeed. It's also mentioned in the docs https://library.threefold.me/info/manual/#/manual__weblets_home?id=limitations

**Comment by rkhamis** [comment]
"Your solution is now starting. please be patient"

**Comment by MohamedElmdary** [comment]
### Updated

#### PR
https://github.com/threefoldtech/grid_weblets/pull/153

**Comment by waleedhammam** [comment]
verified at play.dev.grid.tf
![image](https://user-images.githubusercontent.com/10658229/145808101-96313ea5-ca79-47c7-867e-b1281d54b7cc.png)
