### ISSUE TITLE
Most of deployment aren't loading

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1030]
Can't use or deploy any of [ CapRover - Peertube - Funkwhale - Mattermost - Discourse - Taiga - Owncloud - Subsquid - Casperlabs ] deployments on devnet d0cf03a .

all the same 
![image](https://user-images.githubusercontent.com/109473873/193552886-cc794f4d-4652-40b5-903e-36c53c84b34d.png)

**Comment by MohamedElmdary** [comment]
After investigating this issue it seems like `SelectCapacity` Component is broken due to the binding of fields for validation
working on it right now

**Comment by A-Harby** [comment]
Yes, but this just happened.
In [ Full Virtual Machine - Algorand -Node Pilot ] 
![image](https://user-images.githubusercontent.com/109473873/193600295-373511a5-6c56-4403-a065-4890c770a291.png)

**Comment by A-Harby** [comment]
Verified on Devnet. 
All deployment now works fine.
![image](https://user-images.githubusercontent.com/109473873/193602672-71c84f91-fd8c-4efe-8f10-143b3b083bcb.png)
