### ISSUE TITLE
kubernates does not deploy and filters are broken

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#104]
Choosing a worker with a master (nodes selected is remove when switching between tabs)
It's disabled for now until these issues are fixed

**Comment by MohamedElmdary** [comment]
### Fixed
After fixing `SelectNodeID` this issue was fixed automaticly

**Comment by ranatrk** [comment]
verified:
- filter working with messages regarding the state of the node according to the filter
- when switching between worker/master tabs, the selected nodes remain
