### ISSUE TITLE
Subsquid solution labels

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/grid_weblets#1042]
Great first version!

Some changes requested by the subsquid team:

## 1

![photo_2022-10-12_10-47-23](https://user-images.githubusercontent.com/17138347/195296073-4248d494-19e4-4e41-ab4c-045b1c44dfdf.jpg)

Change from `Subsquid instance` to `Subsquid Archive(s)`

## 2

Change `Subsquid Endpoint` to `Websocket Endpoint`

Maybe with a hint: `A substrate based chain websocket endpoint`

**Comment by khaledyoussef24** [comment]
verified on devnet

Changed Subsquid Endpoint to Websocket Endpoint
Changed from Subsquid instance to Subsquid Archive

![Screenshot from 2022-10-24 13-58-40](https://user-images.githubusercontent.com/110984055/197521480-a5bb079b-9710-4226-adbc-d4b4d7034f25.png)
