### ISSUE TITLE
Select package field

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/grid_weblets#1045]
### Description

There is an error appears when switching between 2 tabs (one of them has `select package` field)

### Steps to reproduce

- Open any solution that has (>= 2 tabs and one of them includes `select package` field)
- switch to `mail server` tab
- switch back to `config` tab
- UI inside the tab will disappear

### logs

![Screenshot from 2022-10-16 16-58-45](https://user-images.githubusercontent.com/47260239/196042595-6ba14d6e-4eb0-427f-83b8-cc9110556d12.png)

**Comment by khaledyoussef24** [comment]
### verified on devnet

**steps made to verify :**

1. go to [weblets](play.dev.grid.tf)
2. go to any solution that has 2 or more tabs
3. fill the deployments info
4. switch to the mail server
5. go back to the config
6. verify that the UI of the config is visible

the issue before fixing
[Screencast from 10-25-2022 09:22:35 AM.webm](https://user-images.githubusercontent.com/110984055/199202654-915a8b20-a733-4877-8157-10fdd1dba610.webm)


the issue after fixing
[Screencast from 11-01-2022 10:52:47 AM.webm](https://user-images.githubusercontent.com/110984055/199202394-2c91bb75-19a3-480a-bb6d-3c819ea073f7.webm)
