### ISSUE TITLE
weblet broke after changing tabs

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#1046]
https://user-images.githubusercontent.com/32527347/196131967-e9a5802e-8ed9-487a-a3da-0e58ed5c6d7e.mp4

in (mattermost, taiga, owncloud, discourse) on play.dev. the main tab brokes after go to another tab and return. 
got this error in the console
![image](https://user-images.githubusercontent.com/32527347/196132470-4d38eb1e-df1a-4940-b7dc-62c2ffe26191.png)

**Comment by xmonader** [comment]
duplicate of https://github.com/threefoldtech/grid_weblets/issues/1045
