### ISSUE TITLE
Disable deploying weblets on release with github workflow

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#1056]
qa, test, and main nets are deployable by the ops team now, so let's disable deploying them with the workflows.
only devnet can be deployed with the workflow.

**Comment by mohamedamer453** [comment]
Verified.

The build workflow was removed from the ci-cd workflow for all networks except for devnet.  in https://github.com/threefoldtech/grid_weblets/pull/1065
