### ISSUE TITLE
`Delete selected` button on contracts list deletes all contracts

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#1057]
![contracts](https://user-images.githubusercontent.com/41957921/197388934-1dafd77e-4c0c-4ff4-bb63-d0638c91f975.gif)

**Comment by khaledyoussef24** [comment]
### verified on devnet
steps made to verify
1-deploy multipe contract
2-go to contracts
3-select one contract
4-delete selected
5-make sure that only one contract is deleted
![Screenshot from 2022-10-25 10-56-30](https://user-images.githubusercontent.com/110984055/197730331-2461a6a7-b8d2-4d45-944d-74de278bd491.png)
![Screenshot from 2022-10-25 10-51-24](https://user-images.githubusercontent.com/110984055/197730341-180289e3-d3a1-4d49-9fcc-af66dd1775d8.png)
