### ISSUE TITLE
Rented node does not allow VM deployments

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/grid_weblets#1059]
Rented a dedicated node:
![image](https://user-images.githubusercontent.com/13766992/197163337-59de905b-3324-4da0-9976-fba6b288fa63.png)

And  when I try to deploy, 
![image](https://user-images.githubusercontent.com/13766992/197163782-764bc2f5-24a5-4077-ab7a-c9c18ed6e114.png)

![image](https://user-images.githubusercontent.com/13766992/197163246-def8f00a-eef6-43b5-a6b3-c2c6552ceb5d.png)

**Comment by maayarosama** [comment]
I rented a dedicated node on qa:
![DedicatedNodes](https://user-images.githubusercontent.com/66883096/197771850-bb1efdfd-4cff-4a04-bc1d-d5f4f15e4db7.jpeg)
After that I deployed a machine on the reserved node without any issues:
![DeployDedicatedNodes](https://user-images.githubusercontent.com/66883096/197771571-35d57fb4-3948-4d76-a6a9-f6aadde28262.gif)

**Comment by khaledyoussef24** [comment]
### verified on QAnet
**steps made to verify this case**
1-open dashboard 
2-go to dedicated nodes from the side menu
3-reserve a node
4-go to the play ground
5-choose node manually and choose the reserved node
![Screenshot from 2022-10-27 17-50-21](https://user-images.githubusercontent.com/110984055/198340072-1dd40a46-560d-419c-af60-29d561b7afff.png)
![Screenshot from 2022-10-27 17-50-11](https://user-images.githubusercontent.com/110984055/198340208-b6e538b7-b844-452d-85ea-30bc64b5f9a9.png)
