### ISSUE TITLE
prevent or indicate the user should not go away from current in-progress deployment

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#106]
as multiple concurrent deployments are not supported for now.

**Comment by xmonader** [comment]
I agree, also i mentioned it in the docs https://library.threefold.me/info/manual/#/manual__weblets_home?id=limitations

**Comment by MohamedElmdary** [comment]
# Updated

### PR
https://github.com/threefoldtech/grid_weblets/pull/119
