### ISSUE TITLE
Named gateways on devnet

### ISSUE THREAD

**Issue by LennertDefauw1** [threefoldtech/grid_weblets#1061]
When deploying a VM with named gateway such as lennertapp2.gent01.dev.grid.tf works fine, same for deleting all the related contracts.

But even when the named gateway contract is deleted for lennertapp2.gent01.dev.grid.tf, a new VM deployment with named gateway lennertapp2.gent01.dev.grid.tf results in a "Named gateway is already in use"

**Comment by LennertDefauw1** [comment]
![image](https://user-images.githubusercontent.com/43674202/197497012-eb10985a-8b35-47ce-9678-198548e84c59.png)

Dont have any of the contracts for named gateways

**Comment by AhmedHanafy725** [comment]
which solution has this issue?

**Comment by LennertDefauw1** [comment]
@AhmedHanafy725 available in the PR of feature/freeflow in https://github.com/threefoldtech/grid_weblets

**Comment by AhmedHanafy725** [comment]
There is a key stored on the chain that holds the deployment's name. This key is deleted in case the deployment is deleted from the deployments list. But if the contract is deleted only, this key won't be removed. So it needs to be invalidated before deploying the new instance with the same name.

This is one of the solutions that require a domain, please have a look at the gateway part.
https://github.com/threefoldtech/grid_weblets/blob/development/src/utils/deployPeertube.ts#L119-L148

**Comment by LennertDefauw1** [comment]
> There is a key stored on the chain that holds the deployment's name. This key is deleted in case the deployment is deleted from the deployments list. But if the contract is deleted only, this key won't be removed. So it needs to be invalidated before deploying the new instance with the same name.
> 
> This is one of the solutions that require a domain, please have a look at the gateway part. https://github.com/threefoldtech/grid_weblets/blob/development/src/utils/deployPeertube.ts#L119-L148

Thanks, worked for me!
