### ISSUE TITLE
remove the subnet from public IPs in the UI

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1073]
![image](https://user-images.githubusercontent.com/64129/199434715-7ae10ec0-6474-48e3-8cb0-9e4cbef4adb5.png)

it's annoying when copying

**Comment by mohamedamer453** [comment]
Verified on devnet.

The subnet was removed from the public ip in the deployment list.

![image](https://user-images.githubusercontent.com/101194226/202131496-69b2d654-b9d0-4400-80b7-cbf51ac890e4.png)
