### ISSUE TITLE
remove the flash messages after the successful deployment of the solution

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1074]
![image](https://user-images.githubusercontent.com/64129/199435084-a344dfa4-417d-4417-9e07-ac805200c4a7.png)

**Comment by ramezsaeed** [comment]
verify its disappear after two minutes ..

**Comment by khaledyoussef24** [comment]
### the problem still exist

**steps made to produce:**

1. go to [weblets](https://play.dev.grid.tf/#/)
2. make any deployment
3. the message of "your solution is now starting should  after two minutes but it didn't

![Screenshot from 2022-11-09 15-01-56](https://user-images.githubusercontent.com/110984055/200838516-beec0451-2cbc-4f7d-87c6-6efbbea4ad69.png)
![Screenshot from 2022-11-09 15-05-13](https://user-images.githubusercontent.com/110984055/200838505-b2d6a962-4a83-4289-8211-73f5a0242ec4.png)

**Comment by khaledyoussef24** [comment]
### verified on devnet

**steps made to verify:**

1. go to [weblets](https://play.dev.grid.tf/#/)
2. make any deployment
![Screenshot from 2022-11-15 15-06-39](https://user-images.githubusercontent.com/110984055/201927810-1500b81d-1d82-422d-80fd-588b1c85c358.png)

3. the message of "your solution is now starting" will disappear   after two minutes
![Screenshot from 2022-11-15 15-08-24](https://user-images.githubusercontent.com/110984055/201927874-ac22238b-c88e-413e-9d78-6861b12f5094.png)

**Comment by khaledyoussef24** [comment]
### the problem still exists on testnet

### steps to produce

1. go to the play ground
2. insert your info
3. make a deployment
4. wait for 3 minutes
5. the flash message is not removed

![Screenshot from 2023-02-06 09-33-15](https://user-images.githubusercontent.com/110984055/216918379-f1d4c790-a9a1-4acc-b31d-664ff3e6ae3a.png)
![Screenshot from 2023-02-06 09-29-35](https://user-images.githubusercontent.com/110984055/216918400-abceeee8-40e3-417e-89d7-22e30139b190.png)

**Comment by zaelgohary** [comment]
@khaledyoussef24 only 2nd message needed to disappear as some solutions take more time to be ready. The first message will remain unless the user presses the back button.

**Comment by xmonader** [comment]
@khaledyoussef24 @zaelgohary I don't understand the difference between the two screenshots :S does that mean the issue is fixed or still needs more work?

**Comment by zaelgohary** [comment]
@xmonader no work is needed for this one. Only 2nd msg is supposed to be removed after some time which happens as seen [here](https://github.com/threefoldtech/grid_weblets/issues/1074#issuecomment-1418674310).

**Comment by A-Harby** [comment]
Verified on Devnet, e8ee5aa.

Deployed a VM and the message disappeared beofre the 2 min, the VM was successfully accessible.
![image](https://user-images.githubusercontent.com/109473873/221415779-79ab5be4-682a-4975-b808-43d515123845.png)

Tried also with Tiaga and same as above
![image](https://user-images.githubusercontent.com/109473873/221416162-67952378-d92b-4a86-a55f-7aa68b2277fc.png)
