### ISSUE TITLE
FullVM: update the default to 22.04

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1075]
![image](https://user-images.githubusercontent.com/64129/199435617-58b24fdb-2bdd-4aee-8258-1971f9745697.png)

should be the latest 22.04 not 18.04

**Comment by khaledyoussef24** [comment]
### verified on devnet

**steps made to produce**

1. go to [weblets](https://play.dev.grid.tf/#/)
2. go to full virtual machine tab
3. check if vm image contains 22.04
4. deploy a machine
5. ssh on the machine 
6. run lsb_release -a on the machine
7. check if the version is 22.04

![Screenshot from 2022-11-09 15-11-32](https://user-images.githubusercontent.com/110984055/200839687-f1634533-fcbb-4adf-ae40-d63c2dbf3925.png)
![Screenshot from 2022-11-09 15-09-55](https://user-images.githubusercontent.com/110984055/200839689-9d4dc33f-962c-4426-9949-b66d626cfd8e.png)
