### ISSUE TITLE
Twin ID, TFT balance, and bridge QR do not load under Profile Manager

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldtech/grid_weblets#1077]
When activating the profile manager in Testnet and Mainnet - the Twin ID, TFT balance, and bridge QR code does not seem to be generating. Please refer to the image:

![197629827-cad2d2f8-d939-4469-b54f-e113fab7ff71](https://user-images.githubusercontent.com/31733464/198286378-53004588-79f3-4eb4-ad50-1624ec62dbd2.png)

Browser screenshots:

Chrome
![197845961-b2929805-35e4-431d-8ed9-8eeeed3228d9](https://user-images.githubusercontent.com/31733464/198286439-d8c14c74-81ba-4b76-8650-7f68086d9936.png)

Firefox
![197846226-49252175-1383-4952-9b88-9be5078c6492](https://user-images.githubusercontent.com/31733464/198286491-0abeeb60-5a63-4a3e-ab4d-a9813c787a3d.jpg)

**Comment by zaelgohary** [comment]
Twin Id, address & QR code are not shown as the user does not have an active twin Id on the selected net. I added validation for that and the error message is now shown to the user in this case but it won't be removed if the user activated another profile.

**Comment by AhmedHanafy725** [comment]
closing in favor of #1119

**Comment by A-Harby** [comment]
Verified on devnet, e51d47f.
This issue has been solved by the new profile manager.
![image](https://user-images.githubusercontent.com/109473873/210210630-72c0ee59-b27f-4141-b138-2185a74bffe1.png)
