### ISSUE TITLE
Add workflow to build the project

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#1078]
For earlier build error detection, we should have a workflow to build the project on PRs and pushing to the development branch.

**Comment by mohamedamer453** [comment]
Verified.

A workflow to build the weblets on pushing to development branch and on prs was added to the weblets in #1108.

and as it can be seen from the actions tab from its latest [run](https://github.com/threefoldtech/grid_weblets/actions/runs/3487253920/jobs/5834666815) it was executed successfully on development branch and the weblets were built successfully without any issues.

![image](https://user-images.githubusercontent.com/101194226/202426442-63d6a088-3ecc-4e39-999d-8acdce11dac3.png)
