### ISSUE TITLE
Mastodon Weblet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1080]
A weblet for [mastodon](https://mastodon.social/explore) 

There should be a checkbox to indicate if TF Connect is enabled or not; if it is, we may use the forked image with TF Connect, and if it is not, we can use their default image.

It should be exposed on freefarm gateways ending with `.grid.tf` 

Let's make sure it's scripted first before doing the weblet [script in typescript](https://github.com/threefoldfoundation/fediverse/issues/8)

**Comment by Mahmoud-Emad** [comment]
##### WIP:
- Created an image that prepares the environment and installs the requirements and dependencies.
- Created scripts to run SSHD and set user pub key to the authorization keys, then scripts to install UFW, run mastodon docker-compose
- Created ZINIT services to run SSD, Docker, and docker-compose file

##### Hint:
- I'm facing an issue with the mastodon Redis container and I'm working on it.

**Comment by Mahmoud-Emad** [comment]
WIP: 
- Updated some confs in the created image.
- Convert the image to flist and tested it and it works.
- Created domain and passed it to the VM, then the server listened to it.


![image](https://user-images.githubusercontent.com/57001890/200836707-e0bceb4c-1e32-4b37-a265-012f93c3e19d.png)

**Comment by Mahmoud-Emad** [comment]
WIP: 
- [x] Created a script to execute grid3 functionality and deploy instances from mastodon using its flist.
- [x] The script totally depends on the parameters that will be set at the beginning of the file by a user.
- [x] Created a `CustomResponse` class to return what they actually needed from the response of VM and GW.
- [x] Created a `PlayGround` class to interact with grid3 functions, containing some helpers methods especially `deploy`, `clean`
    - deploy will take the parameters and deploy what is needed.
    - clean will clean everything deployed by the user based on the instance name.
- [x] Still working on the image, want to create a superuser and then update its password in the script based on the password parameter
    
Response:

![image](https://user-images.githubusercontent.com/57001890/201140017-916cf80b-1398-41e9-aacc-ef35c5be75d0.png)

**Comment by Mahmoud-Emad** [comment]
WIP:
- [x] Mastodon weblet has been implemented as any solution we have
- [ ] Integrate 3fold-connect based on the check box
- [ ] update the official flist to sync with the latest version

**Comment by Mahmoud-Emad** [comment]
WIP:

deploying an instance using all-in-one script 

https://user-images.githubusercontent.com/57001890/201954709-b2f1a3e6-fc94-41ef-8511-4e9b42514c34.mp4

**Comment by Mahmoud-Emad** [comment]
WIP:

https://user-images.githubusercontent.com/57001890/202115981-dc1f8c70-03d6-473c-833c-cc335dbe2577.mp4

**Comment by AhmedHanafy725** [comment]
docs on the wiki still needed

**Comment by Mahmoud-Emad** [comment]
@AhmedHanafy725 
Should be implemented here
[Added mastodon manual](https://github.com/threefoldfoundation/info_manual3/pull/128)

**Comment by A-Harby** [comment]
The `Back` button isn't working.
![Screenshot from 2022-11-23 14-01-34](https://user-images.githubusercontent.com/109473873/203543558-1bce903e-39a1-4c40-bab5-a38fdbae67f2.png)

**Comment by Mahmoud-Emad** [comment]
@A-Harby 
yes it related to https://github.com/threefoldtech/grid_weblets/issues/1115

**Comment by A-Harby** [comment]
Admin username default contains an underscore but It don't allow me to have it when I try to change it. 
![image](https://user-images.githubusercontent.com/109473873/203593829-43d024b1-25b9-44d6-88f9-f912ca8adbb7.png)
![image](https://user-images.githubusercontent.com/109473873/203594320-fa3d5be3-c8b6-40a2-885d-06ae799a62ed.png)
So could u try to change default usernam

**Comment by Mahmoud-Emad** [comment]
@A-Harby 
should be fixed here https://github.com/threefoldtech/grid_weblets/pull/1126

**Comment by mohamedamer453** [comment]
Closing this issue in favor of #1167 since the weblet is going to be removed from the playground.
