### ISSUE TITLE
select in the contracts tab

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#1085]
###tested in mainnet

select in the contracts tab in the playground
the first contract can't be selected or unselected and it only can be selected by the select all box

steps made to produce

1. go to the playground
2. go to contracts tab
3. try to select the first contract it won't
4. use the select all and try to unselect the first option it won't

[Screencast from 11-07-2022 10:29:01 AM.webm](https://user-images.githubusercontent.com/110984055/200294376-590909a9-285e-4e27-8bfa-6e864dc17be8.webm)

 [Screencast from 11-07-2022 10:32:29 AM.webm](https://user-images.githubusercontent.com/110984055/200294193-93630958-4d7e-4d58-8470-e87d3f8fa15a.webm)

**Comment by xmonader** [comment]
it's fixed on devnet

**Comment by khaledyoussef24** [comment]
### verified on devnet

steps made to verify

1. open [weblets](https://play.dev.grid.tf/)
2. go to the [contracts tab](https://play.dev.grid.tf/#/contractslist)
3. in the contract lists try to choose the first contract
4. choose the select all and try to unselect the first contract
5. verify that it is working effectively
[Screencast from 11-15-2022 02:08:39 PM.webm](https://user-images.githubusercontent.com/110984055/201916709-5596f49e-a6d5-4d4e-94a0-62ade5c6a047.webm)
