### ISSUE TITLE
profiles: better validation message for invalid mnemonics

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#109]
mention that maybe account is not activated or wrong network, otherwise the user will be confused why it's invalid?

**Comment by xmonader** [comment]
b36dfe23cadb3e90bf9a08ca59f41489e475ee97

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/144497938-41fcb478-12ed-469d-92be-13697ec46c19.png)
