### ISSUE TITLE
Weblets tutorial 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1090]
Create a tutorial on weblets, starting with 
- What are webcomponents
- Svelte role developing weblets
- Choosing a solution like https://github.com/lus/pasty
- Preparing docker images
- Preparing the flist
- Testing the deployment with grid3_client
- Creating a weblet in a separate website
- Set the solution provider id
- Using the weblet to deploy the solution

**Comment by maayarosama** [comment]
The following points are now well prepared for the video recording

- What are webcomponents
- Svelte role developing weblets
- Choosing a solution like https://github.com/lus/pasty
- Preparing docker images
- Preparing the flist
- Testing the deployment with grid3_client

I'm now working on creating a weblet in a separate website using svelte, I'll most probably start to video record on Thursday.

**Comment by maayarosama** [comment]
For the last couple of days I was working on connecting my separate weblet to the grid3_client, Multiple errors would appear upon importing the grid3_client package. Those errors are resolved now. 

I've also started writing the tutorial, it's still missing a couple of sections.
### What's left?
- Now that the grid client is imported, next step is integrating its methods with my frontend application
- Setting the solution provider id

**Comment by maayarosama** [comment]
- Solution provider is now set.
- Error messages are shown on deployment from the separate weblet so I'm working on fixing those.

**Comment by maayarosama** [comment]
[Written Tutorial](https://github.com/maayarosama/Web_Components) is almost done, I'm working on fixing some comments.
Next step is going to be the video recording.

**Comment by xmonader** [comment]
Great job @maayarosama Well done!!
