### ISSUE TITLE
New flist to Matodon.

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/grid_weblets#1092]
We have a new solution `Mastodon` now, then we have to change the local flist to the official flist.

- Current flist.
    - `https://hub.grid.tf/omda.3bot/mahmoudemmad-mastodon-latest.flist`

**Comment by xmonader** [comment]
@maxux please update it to `mastodon-latest.flist`

**Comment by maxux** [comment]
Promoted to: `tf-official-apps/mastodo-latest.flist`
