### ISSUE TITLE
Add quick start docs link for the full vm weblet and minor fixes in the docs

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1094]
### Description

The documentation itself was verified in https://github.com/threefoldtech/grid_weblets/issues/1016 but some minor issues in the Full VM docs need to be revised and a quick start docs link needs to be added to the weblet when the the docs are available in the threefold manual.

The issues are: 

- After this issue https://github.com/threefoldtech/grid_weblets/issues/1015 the environment variables tab and the mount point for the disk were removed from the full vm weblet but some of the screenshots in the docs still contain these options.

- Other than the screenshots mentioned above any mention of adding environment variables or disk mount point from the weblet needs to be removed.

- When it's available in the threefold manual add a quick start link for it in the weblets.

**Comment by zaelgohary** [comment]
Link should be added after https://github.com/threefoldtech/tf_operations/issues/1266 is closed.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The quick start docs link was added in now it redirects the user to the [Full Vm docs](https://library.threefold.me/info/manual/#/manual__weblets_fullvm).

and all of the screenshots related to the environment variables tab, disk mount point were removed.

however there's still a single mention to the disk `Mount Point` in the docs but since everything is verified from the weblets side i'll close this issue and i opened another one for the docs fix https://github.com/threefoldfoundation/info_manual3/issues/127
