### ISSUE TITLE
Failed to deploy fullvm

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/grid_weblets#1096]
### Description

I tried to deploy full vm and I faced the error below

### Steps to reproduce

- go to [weblets](https://play.dev.grid.tf/#/)
- create a fullvm deployment

### Logs/Alerts

![image](https://user-images.githubusercontent.com/40770501/201130452-ec457d4a-7e3a-4d4a-bb8b-3bcd08c3ec01.png)

**Comment by AhmedHanafy725** [comment]
the node was down, there is a check added to the weblet to ping the node before starting the deployment in #1117

**Comment by A-Harby** [comment]
Closing as the issue was reported and solved on [do a real-time check on the node before deploying](https://github.com/threefoldtech/grid_weblets/issues/1117)
