### ISSUE TITLE
Twin on devnet reporting massive amount of locked TFTs with no active contracts.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1100]
### Description

One of my twins on devnet is reporting massive amount of locked tfts.

![image](https://user-images.githubusercontent.com/101194226/201659314-148dcffa-2acc-441d-832b-9ac67dc8dfc1.png)

the mentioned twin is twin `60` on devnet.

![image](https://user-images.githubusercontent.com/101194226/201660592-2830a174-6d76-4ec5-a479-40f79528acfd.png)

i haven't used this twin in a while and as it can be seen in the screenshot below it has no active contracts.

![image](https://user-images.githubusercontent.com/101194226/201659690-6cc7c85b-1b69-4eb7-91c1-4802d53e6af5.png)

**Comment by DylanVerstraete** [comment]
Could have been accumulated by https://github.com/threefoldtech/tfchain/issues/479
