### ISSUE TITLE
Create VM with an empty ssh key

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/grid_weblets#1107]
If the user turned off the SSH key in the profile, then deployed a QVM, for example, there is no validation on the SSH key:
https://github.com/threefoldtech/grid_weblets/blob/50c9b8aa6f0a26d34c537b966604b6643758b115/src/utils/deployVM.ts#L32
so the Ssh key in VM details was empty
![image](https://user-images.githubusercontent.com/62248851/202149870-58b94738-a9f9-4bf9-84f4-688bdb1de5ff.png)

**Comment by mohamedamer453** [comment]
The ssh key is now mandatory after this issue https://github.com/threefoldtech/grid_weblets/issues/1120 so this issue is not valid anymore.
