### ISSUE TITLE
profiles: remove "PM" or replace it with a user avatar/icon 

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#111]
It's somehow confusing for some people

![photo_2021-12-02_20-13-44](https://user-images.githubusercontent.com/511438/144479570-9d28075c-614a-4b3e-b6d0-2be597f338cf.jpg)

**Comment by xmonader** [comment]
fixed in https://github.com/threefoldtech/grid_weblets/commit/adfaf6baaeb15e8f4b7e2c4beb56773155fba018

**Comment by xmonader** [comment]
it's changed for now to `Manage`

**Comment by MohamedElmdary** [comment]
change to use fontawesome icon 
![image](https://user-images.githubusercontent.com/31689104/144826613-0cc70828-238d-411e-b47a-620d3c2d5da8.png)
