### ISSUE TITLE
The `Back` button doesn't work after successful deployment/errors in some cases

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1115]
### Description

In some solutions after a successful deployment or an error from the weblets, if you click on the `Back` button to return to the weblet configuration it doesn't return and the the `Solution Deployed ` message also disappears.

[Untitled_ Nov 17, 2022 2_33 PM.webm](https://user-images.githubusercontent.com/101194226/202451034-dc94cf0b-8e59-41f8-9f74-7089439b3b5b.webm)

And in another case the after an error when i clicked on the `Back` button it started to deploy the solution then it failed with the same error again as seen in the logs.

[Untitled_ Nov 17, 2022 2_45 PM.webm](https://user-images.githubusercontent.com/101194226/202451655-9ef45050-05ff-4015-b3eb-565925b0acca.webm)

### Steps to reproduce

- Navigate to https://play.dev.grid.tf/
- Deploy a solution like (funkwhale, mastodon, etc ...)
- After successful deployment click on the `Back` button to return to the deployment configuration tab.

**Comment by A-Harby** [comment]
This issue is still happening to me after a successful/failed deployment.
![image](https://user-images.githubusercontent.com/109473873/212543420-0bcd29ab-8c14-45e2-b7d1-d9e6940c9a62.png)

**Comment by xmonader** [comment]
closed in favor of https://github.com/threefoldtech/grid_weblets/issues/1287
