### ISSUE TITLE
Error while deleting contracts on devnet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1116]
### Description

While deleting some contracts from the contracts list i got the following error message

![image](https://user-images.githubusercontent.com/101194226/202455061-0910da94-90fb-406d-8fa4-4c29f33c47e4.png)

```
Failed to get deployment due to Error: Request failed with status code 502 due to failed to submit message: Post "http://300:d205:aee5:1d1e::1:8051/zbus-cmd": dial tcp [300:d205:aee5:1d1e::1]:8051: i/o timeout
```

Which is similar to an error i have been getting multiple times in the last couple of days as seen in https://github.com/threefoldtech/grid3_client_ts/issues/411

and even after the contracts were deleted the error message did not disappear.

![image](https://user-images.githubusercontent.com/101194226/202456817-d1cb07fe-06b6-4aba-8080-0f8668eae301.png)

**Comment by rkhamis** [comment]
we cannot force the contract to be canceled because the network will be cleaned up this way
but we should have a better error "Node is currently unreachable, please try again later"

**Comment by khaledyoussef24** [comment]
tried to delete multiple times
works fine now on devnet
[Screencast from 04-04-2023 11:19:49 AM.webm](https://user-images.githubusercontent.com/110984055/229747541-c29ac22c-0971-4518-8d75-699b52b69c23.webm)
