### ISSUE TITLE
do a real-time check on the node before deploying

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1117]
![image](https://user-images.githubusercontent.com/64129/202652446-32c07529-8f9a-413d-b91c-7fa71e6eedfc.png)

because here the node was reporting it's online in the latest uptime report, but still needs to be realtime checked, also the message is more confusing because it tried to get wireguard ports, which failed, but the original reason the node was offline

**Comment by xmonader** [comment]
now on the client there's a pingNode helper https://github.com/threefoldtech/grid3_client_ts/pull/439 https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/checkNodeAlive.ts

**Comment by 0oM4R** [comment]
add to most of the solutions 
the current method I'm using is to add pingNode to every deploy function as follows:
```
try {
      await grid.zos.pingNode({ nodeId: machine.node_id });
      return grid.machines
        .deploy(machines)
        .then(() => grid.machines.getObj(name))
        .then(([vm]) => vm);
    } catch (error) {
      throw error;
    }
```

**Comment by 0oM4R** [comment]
should be applied on the deploy gateway also? @AhmedHanafy725

**Comment by AhmedHanafy725** [comment]
> should be applied on the deploy gateway also? 

yes please

**Comment by 0oM4R** [comment]
I convert the ping method to be on selecting the node, as Hanafy suggested.
only need to be applied on multiselect.
also, eslint gives me an error so I can't commit my changes

`error Parsing error: '>' expected `

**Comment by A-Harby** [comment]
@0oM4R is this relevant? 
![image](https://user-images.githubusercontent.com/109473873/205089050-8f634dec-2cf3-4400-865d-503a604fe42f.png)

**Comment by 0oM4R** [comment]
@A-Harby , This is not relevant as the main idea is to check if the node is up or not, it looks like there is a problem with public ips but the node is up

**Comment by A-Harby** [comment]
Verified, 

Deployed a vm using all the resource on a node and then trying to deploy another vm on the same node but capacity filter quickly removing it from the list.
![image](https://user-images.githubusercontent.com/109473873/205623411-9a3ee33a-a6a9-439b-9aa9-fb5cda1cba99.png)
