### ISSUE TITLE
support tf-connect enabled version of mastodon

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1118]
Continuation of #1080 let's have an option to choose to use tf-connect enabled image or not, if the user the chooses tf-connect enabled it should deploy our own fork (4.x version)

- [x] image
- [x] deployment script
- [x] weblet

**Comment by Mahmoud-Emad** [comment]
WIP:
working on the integration stage using `omniauth/strategies/threefold`.

**Comment by Mahmoud-Emad** [comment]
WIP:
can log in using tf-connect now

![image](https://user-images.githubusercontent.com/57001890/203008844-e0c8d549-df09-4d2b-bef1-5e909544ca90.png)

working on the image.

**Comment by Mahmoud-Emad** [comment]
Now can log in with TF-connect

![image](https://user-images.githubusercontent.com/57001890/203122314-f91c821c-ba52-44bd-ad16-d9013f1f8aa3.png)


![image](https://user-images.githubusercontent.com/57001890/203122126-c9aaf1ed-9fc4-4262-bcdd-893c6c7bf846.png)


also, you can log in with Admin Credentials that we generated for you.

**Comment by mohamedamer453** [comment]
Closing this issue in favor of #1167 since the weblet is going to be removed from the playground.
