### ISSUE TITLE
profile manager update

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1119]
The flow should be 
- use mnemonics to activate the profile
- have a migrate tab where the user enters a password and it migrates the old metadata to a new one on kvstore based on mnemonics

**Comment by xmonader** [comment]
@AhmedHanafy725 please make sure this is in 3.7.3 project

**Comment by A-Harby** [comment]
Verified on devnet, e51d47f.
Profile manager updated has been added and works fine with loading different profiles or generating it, and all issue found has been reported and being solved. (e.g. [issue](https://github.com/threefoldtech/grid_weblets/issues/1199)), 
![image](https://user-images.githubusercontent.com/109473873/210212302-72693200-1799-4b42-8647-7e305ae18c2e.png)
