### ISSUE TITLE
make SSH mandatory 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1120]
as per kds request: 
![image](https://user-images.githubusercontent.com/64129/202897614-1c007165-30bd-46fa-8e71-54ab4b7d754c.png)
let's remove the toggle button, always use it.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The toggle button was removed and now the ssh key is always used.

![image](https://user-images.githubusercontent.com/101194226/202996834-dddbcb53-bfc6-4e38-ae61-da19d04bf5f0.png)

and the user will not be able to save or activate the profile unless a valid ssh key is entered.

![image](https://user-images.githubusercontent.com/101194226/202997600-7dc366bb-bd10-498d-936c-5af0d5aa53c0.png)
