### ISSUE TITLE
Capacity filter sometimes provide nodes that doesn't have enough space

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/grid_weblets#1124]
### Description

trying to deploy a vm using capacity filter and I got the following error

![Screenshot from 2022-11-21 16-47-00](https://user-images.githubusercontent.com/1689456/203085509-de9dc008-a61b-4ae9-a57d-c7c2abcc6735.png)
Node: 33
required capacity: 50G

**Comment by ramezsaeed** [comment]
can you please try on another node

**Comment by mohamedamer453** [comment]
I've encountered this issue before from tsclient https://github.com/threefoldtech/grid3_client_ts/issues/412 and unfortunately it was not reproducible at the time and it's still not reproducible. i tried multiple deployments on the mentioned node and on other nodes but the deployments were successful and when the node was full, it didn't appear in the capacity filter. i'll close this issue for now but please feel free to reopen it if you encountered this issue again with more steps on how to reproduce.
