### ISSUE TITLE
Got You must pass a valid ID when trying to deploy a mastodon instance

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/grid_weblets#1125]
### Description
trying to deploy the mastodon instance on the playground and got an invalid ID instead of the result.

the problem happens because when I develop a mastodon instance I have an environment variable with an undefined type, so when passed as a string it works!

### Logs/Alerts
![image](https://user-images.githubusercontent.com/57001890/203085348-f55cdbed-14b5-422e-893c-f2ffbeae40ac.png)

![image](https://user-images.githubusercontent.com/57001890/203085428-60035e3a-671e-4785-98a6-33d58a2b0772.png)

**Comment by AhmedHanafy725** [comment]
this happens when sending an empty environment variable in the deployment. But it should roll back the deployment without any errors.

**Comment by AhmedHanafy725** [comment]
Done on the grid3 client. it will be available after releasing the client

**Comment by mohamedamer453** [comment]
Closing this issue in favor of #1167 since the weblet is going to be removed from the playground.
