### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#113]
User documentation for weblets

**Comment by xmonader** [comment]
initial docs here https://library.threefold.me/info/manual/#/manual__weblets_home

**Comment by rkhamis** [comment]
- [x] terraform updated
 - [x] typescript client updated
 - [ ] graphql API
 - [x] farming docs updated
 - [ ] kubernetes

**Comment by asamirr** [comment]
profile manager too should be done by now

**Comment by rkhamis** [comment]
profile manager docs will have to be updated once #143 is done

**Comment by mhost39** [comment]
Verified 
https://github.com/threefoldtech/grid_weblets/issues/154#issuecomment-995902740
