### ISSUE TITLE
`undefined` expiration date for contracts in grace period on devnet.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1131]
### Description

Some of my contracts that are in grace period have `undefined` expiration date on devnet.

Twin ID: `152`
Contracts IDs: `14658`, `14660`, `14662`

![image](https://user-images.githubusercontent.com/101194226/203730302-b374f33a-6914-4a91-ae71-3a434d78e001.png)

**Comment by AhmedHanafy725** [comment]
a fix is done on the ts client, and it will be available on weblets once it's released

**Comment by A-Harby** [comment]
Weblets, 586d077.
Still giving me `undefined` value.
![image](https://user-images.githubusercontent.com/109473873/209187584-54ad3bb9-3485-4e99-ab55-5101e5c77f39.png)

**Comment by AhmedHanafy725** [comment]
the ts client is upgraded, can you give it another try?

**Comment by A-Harby** [comment]
Verified on Devnet, ae37d61.

Expiration data have values and not undefined.
![image](https://user-images.githubusercontent.com/109473873/209567690-2ec39468-df4a-47bc-b3d7-e73fc4050e1d.png)
