### ISSUE TITLE
Node Filtering is not working correctly

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1133]
### Description

The node filtering in both the `Capacity` & `Manual` filters is not working correctly.

As seen in the video below firstly i got the available sru capacity of node 34 from the [gridproxy](https://gridproxy.dev.grid.tf/nodes/34) which was `108383264768 bytes` = `100.94 GB` then i went back to weblets and i tried to deploy a full vm with `150GB` and the node appeared as available both in the capacity and manual filters even though the node only has `100gb` free. and when i tried to deploy, the deployment then immediately failed due to insufficient resources. and when i returned to the deployment after that the node was stuck as unavailable for deployment even when i lowered the disk size to `15GB`

[Untitled_ Nov 24, 2022 12_18 PM.webm](https://user-images.githubusercontent.com/101194226/203763946-b142d8cf-f06c-4c93-a9e6-3c1e28f786a7.webm)

and the sane exact thing happened with memory filtering when i entered a value more than the available the node appeared in both filters.

[Untitled_ Nov 24, 2022 12_50 PM.webm](https://user-images.githubusercontent.com/101194226/203766588-8f39ff46-3801-4129-a01b-1e36f6473779.webm)

and another case where i tried to filter with `10000 GB` disk size the filters returned some nodes as available. even though the highest sru capacity on devnet is on node 49 and its only 1tb

![image](https://user-images.githubusercontent.com/101194226/203767060-9c2e8eeb-9bad-4a10-898c-083c7dd69d73.png)

![image](https://user-images.githubusercontent.com/101194226/203767173-72d448c2-2ad7-49d4-8c0d-e4e8099dac7a.png)

![image](https://user-images.githubusercontent.com/101194226/203767243-90ff2395-d7b8-4d41-a94c-4e370f9696c6.png)

**Comment by A-Harby** [comment]
Tried on node 33, with free sru = 188.
![image](https://user-images.githubusercontent.com/109473873/230388211-1b34ac61-80f8-4bc7-8e77-c0d9ca092423.png)
Tried 188 GB and node 3 was found and retrieve.
![image](https://user-images.githubusercontent.com/109473873/230388845-7833369f-2bda-4a1c-9b3a-3abc88542ad6.png)
But when increasing it more than 188, node 33 was removed.
![image](https://user-images.githubusercontent.com/109473873/230388700-8026cedf-835a-4d06-ac4e-4853e6136a37.png)
