### ISSUE TITLE
peertube/funkwhale confusing gateway and domain in the code

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#114]
![image](https://user-images.githubusercontent.com/64129/144496381-a78a5a41-8fd8-458a-992f-7cf5f617667e.png)

this is the domain the application running on, gateway is a service running on ZOS you can reach over a domain

**Comment by ranatrk** [comment]
it is still not updated [here](https://github.com/threefoldtech/grid_weblets/blob/development/src/utils/deployFunkwhale.ts#L89) .
should it be updated or will remain gateway?
