### ISSUE TITLE
no way to see related contract IDs of deployments

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#115]
In details window, there isn't any contract information, need to show related contract IDs

![photo_2021-12-02_22-20-55](https://user-images.githubusercontent.com/511438/144497062-ef6b5aed-c778-4818-a0f4-39d64ea4024b.jpg)

**Comment by xmonader** [comment]
Requires input from @AhmedHanafy725

**Comment by AhmedHanafy725** [comment]
requires https://github.com/threefoldtech/grid3_client_ts/issues/131

**Comment by AhmedHanafy725** [comment]
contract Id available now on the new release of the client 0.0.32

**Comment by MohamedElmdary** [comment]
### Added

#### PR
https://github.com/threefoldtech/grid_weblets/pull/155

**Comment by ranatrk** [comment]
verified 

![Screenshot from 2021-12-13 14-34-39](https://user-images.githubusercontent.com/17128393/145813223-91a3cc73-1ba1-4ef5-9aed-b7423d94fa3b.png)
