### ISSUE TITLE
(Mainnet verification)  Simulator - lock entry price to minimum of .08

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#1160]
Since the entry price of TFT for farmers is set by the DAO, not the market, and will not be reduced below .08, let's validate this field in the simulator to avoid confusion.

## Current

`Price of TFT at point of registration on blockchain (USD)` field in the simulator can be set to any value by the user.

## Proposed

Limit inputs to `Price of TFT at point of registration on blockchain (USD)` to a minimum of .08, but allow users to specify higher values if they desire.

**Comment by mohamedamer453** [comment]
Validation for the TFT price field was added, and it shows a validation message for any value lower than `0.08 tft`, however as seen below, it still calculates the Profit, Return On Investment, etc.. for the `invalid values` <0.08 and another issue is when the user enters `0` in this field all the calculated values are changed to `Infinity`.

[Svelte app.webm](https://user-images.githubusercontent.com/101194226/206905849-646a11f1-6579-477a-9622-99b388bf1d17.webm)

**Comment by A-Harby** [comment]
Verified on Mainnet Dashboard.
Any value lower then 0.08 wont calculate a value for it. 
![image](https://user-images.githubusercontent.com/109473873/220928352-43810ca1-f772-41d2-88ff-9ef2c49ed64b.png)
Till it's update to a value equal or higher than 0.08.
![image](https://user-images.githubusercontent.com/109473873/220928399-696ac808-0ca4-4b91-b50e-abb574500c38.png)
