### ISSUE TITLE
Add a note about which browsers are supported

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#1162]
Users are having bad experiences with Firefox, particularly that their TFT balance doesn't load. Let's add a note somewhere that only Chrome based browsers are supported. Or maybe detect when an unsupported browser is used and display a warning.

**Comment by mohamedamer453** [comment]
Verified on devnet.

An alert message was added before loading the weblets mentioning that only chromium based browsers are supported. this message only appears in unsupported browsers like firefox.

![2022-12-06_17-32](https://user-images.githubusercontent.com/101194226/205955495-51c72c41-d638-4b70-a300-d93c8027be1c.png)

![2022-12-06_17-32_1](https://user-images.githubusercontent.com/101194226/205955513-21492be1-dd44-4271-9a92-efccb0704a43.png)
