### ISSUE TITLE
Error while deleting contracts on qanet

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/grid_weblets#1166]
### Description

While deleting some contracts from the contracts list i got the following error message after [1, 2] sec

![image](https://user-images.githubusercontent.com/57001890/205630961-7d13741f-81b3-4305-94d8-60d9b2e3e2a6.png)

```
Cannot read properties of null (reading 'state')
```

### Logs
![image](https://user-images.githubusercontent.com/57001890/205631669-5501895a-304a-4e15-88ba-4d6c9078a1f9.png)

**Comment by rkhamis** [comment]
closed in favor of https://github.com/threefoldtech/grid3_client_ts/issues/555
