### ISSUE TITLE
remove mastodon weblet from the playground

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1167]
hide it from the sidebar for now

**Comment by Mahmoud-Emad** [comment]
@xmonader 
Totally remove it or just comment it out?

**Comment by Mahmoud-Emad** [comment]
Should be removed in https://github.com/threefoldtech/grid_weblets/pull/1169

**Comment by khaledyoussef24** [comment]
verified 
![image](https://user-images.githubusercontent.com/110984055/207814236-6124c046-93c8-463e-b970-28fd88f69e5c.png)
