### ISSUE TITLE
Can't switch between tabs in development mode

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/grid_weblets#1173]
### Description
The playground is broken on the development mode. The tabs are  broken and I can't switch between them.

### Steps to reproduce

- Use the ```yarn dev``` command to run the weblets
- Try to switch between tabs

### Logs/Alerts

Shown logs in console
![Screenshot from 2022-12-21 14-36-23](https://user-images.githubusercontent.com/66883096/208911327-81fe09b7-8b21-4b6f-a30f-f1be4e0c642b.png)

**Comment by A-Harby** [comment]
Verified.
Can switch between tabs on any depolyments
![image](https://user-images.githubusercontent.com/109473873/216023748-105b2506-0607-41ed-9f55-3b007fceb657.png)
