### ISSUE TITLE
Validations doesn't work correctly

### ISSUE THREAD

**Issue by Mahmoud-Emad** [threefoldtech/grid_weblets#1174]
### Description
I was working on [this issue](https://github.com/threefoldtech/grid_weblets/issues/1024) and everything was working well, then after some time the QA change the status of the mentioned issue to in progress which is return me back to work on it, and I saw this issue in the mentioned video below.

Also, all nodes are down I don't know if the dev net is down or if it's another issue

https://user-images.githubusercontent.com/57001890/209098911-8879a8b1-637e-4200-a367-14e4291f97c7.mp4

**Comment by A-Harby** [comment]
Verified on Devnet, e51d47f.
Validation is still active whatever any other changes happens (including applying capacity filter).
![image](https://user-images.githubusercontent.com/109473873/209979933-450eac68-18d6-4381-825e-03aac7ac1ad6.png)
