### ISSUE TITLE
Failed to deploy Kubernetes master.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1184]
### Description

Failed to deploy Kubernetes master.

### Steps to reproduce

1. Load profile 
2. Choose Kubernetes.
3. Choose Capacity filter and apply.
4. Deploy

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/209474101-47dc2361-c3e9-423e-8659-b72166c71e1c.png)
![image](https://user-images.githubusercontent.com/109473873/209474247-1472769c-1e22-4b68-a547-29721d9b6c9d.png)

**Comment by zaelgohary** [comment]
Unable to reproduce the issue as I could create 3 K8s deployments without any errors.

![image](https://user-images.githubusercontent.com/40770501/212662470-785ecc40-16b8-434f-ae2f-0bef0e40a563.png)

**Comment by A-Harby** [comment]
Closing the issue, as error isn't producible now

**Comment by A-Harby** [comment]
Closing the issue, as error isn't producible for the current weblets release b116d46.
![image](https://user-images.githubusercontent.com/109473873/212677437-d26898c2-81ff-4784-9af3-941d399d6881.png)
