### ISSUE TITLE
remove build warnings 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/grid_weblets#1187]
![image](https://user-images.githubusercontent.com/62248851/209550850-7dbfb63b-79ab-4024-9a4b-e7cbf0e8c019.png)
![Screenshot from 2022-12-26 14-39-54](https://user-images.githubusercontent.com/62248851/209550870-6caab258-dc9e-4c70-853b-4481552408cb.png)

**Comment by A-Harby** [comment]
Verified, Build warnings are no longer visbles.
![image](https://user-images.githubusercontent.com/109473873/209979623-1347ba55-24f2-4d31-8fd2-d6ed86683d0c.png)
