### ISSUE TITLE
The new profile manager's colors are not consistent with the weblets' colors

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#1194]
![image](https://user-images.githubusercontent.com/41957921/209645258-8893fbe6-d35a-4b4d-a35b-9140d79bcff2.png)

![image](https://user-images.githubusercontent.com/41957921/209645227-92af2403-69f6-43d8-8a13-b13a79fe5966.png)

**Comment by A-Harby** [comment]
Verified on Dvenet, e51d47f.
New colors are consistent with the weblets' .
![image](https://user-images.githubusercontent.com/109473873/209966635-5e668af7-25a7-4703-b5c7-5cb745d1890c.png)
