### ISSUE TITLE
Can't delete a deployment

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#1196]
### Steps
- deploy a vm
- try to delete the vm from the deployed list

![image](https://user-images.githubusercontent.com/41957921/209657303-ed7cbed3-13e5-4991-b74a-817f293633b0.png)

**Comment by sameh-farouk** [comment]
I hit the same issue.
I can deploy VM but can't deploy solutions like discourse or funkwhale, also still can't delete VM. it gives the same error.

**Comment by A-Harby** [comment]
Verified on Devnet, b116d46.
Same issue was reported and solved in other [issue](https://github.com/threefoldtech/grid_weblets/issues/1217).
![image](https://user-images.githubusercontent.com/109473873/212680792-6d59ed6f-4fa3-4a4b-a81a-3d45b71b4665.png)
![image](https://user-images.githubusercontent.com/109473873/212680873-0c00a911-0dad-4f76-b6e3-1c2a5f1d2680.png)
