### ISSUE TITLE
After creating a new profile and set the sshkey, it keeps storing forever

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#1199]
### Steps
- Open the profile
- Click on the create account button
- Set the sshkey

### Result

it can't store the sshkey cause the balance is low

![image](https://user-images.githubusercontent.com/41957921/209804015-5922b378-216d-4c72-b110-d802f1a731bb.png)

### Expected

it should show a warning message to ask the user to fund the wallet first and disable the sshkey field, also the QRcode should be available to let the user funds the wallet

**Comment by A-Harby** [comment]
Issue still happens with me
![image](https://user-images.githubusercontent.com/109473873/210534640-9d05bbb7-4665-4ebc-b548-a85ead3d11d7.png)

**Comment by A-Harby** [comment]
This issue is solved when trying to store an already created ssh key, but when trying to create a new account and generating a ssh key it still happens
![image](https://user-images.githubusercontent.com/109473873/212683094-05546a11-6127-4d04-8fce-6b34244a1b22.png)

**Comment by A-Harby** [comment]
Verified on Devnet, 98c3d15.
Creation of the new account was successfully and warning are clear.
Also preventing user from creating a ssh key without enough resources.
![image](https://user-images.githubusercontent.com/109473873/213449045-842a7e01-c762-4c06-a77d-0e5b55740f8a.png)
