### ISSUE TITLE
No indication after migrating the profile if it fails or passes

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#1200]
### Steps 

- enter any password as the old profile's password

### Result
 
it keeps loading, then stopped without saying it's done migrating the profile, or it's failed

![image](https://user-images.githubusercontent.com/41957921/209806260-fc3e2790-de7c-4ade-8f92-a2cb448743a5.png)

**Comment by A-Harby** [comment]
It's Always saying ` keys was already migrated.`, However what password I gives.

wrong passwords.
![image](https://user-images.githubusercontent.com/109473873/213213179-9acf67dd-c9c0-41f2-9cf4-aeec7e82e4d9.png)
![image](https://user-images.githubusercontent.com/109473873/213212188-94de6f71-b47e-408d-94cf-620edc9a1708.png)
correct password.
![image](https://user-images.githubusercontent.com/109473873/213211236-c915b44c-222e-402d-b773-61507a81096a.png)

**Comment by A-Harby** [comment]
Verified on Devnet, 98c3d15.
Now message is more descriptive about  Migrated keys, Already migrated keys and Failed to migrate.
![image](https://user-images.githubusercontent.com/109473873/213443444-4fc11e5c-514d-4773-a0f6-ea215c540302.png)
