### ISSUE TITLE
Update repo's docs

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#1201]
docs should have

- [x] project intro
- [x] how to use
- [ ] how to run tests (if any)
- [ ] where to find the docs
- [ ] where to find the examples 
- [ ] pipelines
- [x] contribution guide

**Comment by A-Harby** [comment]
Verified.
[Readme](https://github.com/threefoldtech/grid_weblets/blob/development/README.md) is updated with all info and test workflow and badge will be added (follow in [here](https://github.com/threefoldtech/grid_weblets/issues/1219)).
