### ISSUE TITLE
user the same precision for the balances shown 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1203]
![image](https://user-images.githubusercontent.com/64129/209926516-1b06ba65-0291-4706-b115-f86962697da4.png) 

and TFT should be on the same line too

**Comment by A-Harby** [comment]
Verified on Devnet, cf2486d.
Balance and Locked have same precision.
![image](https://user-images.githubusercontent.com/109473873/212546151-3e538dc5-603a-4dbe-ae17-1896a8ac088d.png)
