### ISSUE TITLE
Generate sshkey button in the profile shouldn't be enabled while no mnemonics are provided

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#1204]
![image](https://user-images.githubusercontent.com/41957921/209931931-8849a54b-7067-44da-ae69-4a9203e3b15a.png)

**Comment by A-Harby** [comment]
Verified on Devnet, cf2486d.
![image](https://user-images.githubusercontent.com/109473873/212546056-5f1fbf87-a9b0-44d6-9f2d-19788e7449ed.png)
