### ISSUE TITLE
repo documentation

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1208]
![image](https://user-images.githubusercontent.com/64129/210217068-f5b4267a-ab74-43b6-825d-25a0e526e7d6.png)

home page doesn't tell much, it asks to run `yarn deps` and `yarn serve:app` in some unknown directory, lacking instructions

## checklist 
- have an introduction to the project
- show status of the tests and code coverage
- how to run in production e.g if it was a binary or something the enduser needs to download 
- how to run in development as a developer (it's fine to link to another page)
- should have a link to internal docs for development
  - how to get the code  
  - how to configure the editor/IDE
  - how to run the tests
  - how to write new tests
  - have the workflows documented
  - have the releasing process documented

**Comment by A-Harby** [comment]
Verified, Repo Readme is filled out with checklist requirements.
