### ISSUE TITLE
wrong network env on QA playground

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#1225]
it looks network env on QA playground is set to "test", all requests goes to TEST instances of gridproxy and graphql.
![image](https://user-images.githubusercontent.com/32527347/211269019-cf246cec-0e98-4128-94f4-5085061fd844.png)

**Comment by A-Harby** [comment]
Verified on Qanet, v1.6.0-qa3.
Now QA is using the correct network 'qanet'.
![image](https://user-images.githubusercontent.com/109473873/212679471-84b0d58f-a154-42c8-924a-051b4dace722.png)
