### ISSUE TITLE
playground report my balance incorrectly

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#1226]
### Description

playground misreport my balance, possibly  related to https://github.com/threefoldtech/grid_weblets/issues/1225

### Steps to reproduce

1. check your balance on dashboard.qa.grid.tf 
2. activate your profile and check your balance on play.qa.grid.tf

### Logs/Alerts

Uncaught (in promise) Error: Balance is not enough to apply an extrinsic

![Screenshot from 2023-01-09 10-45-42](https://user-images.githubusercontent.com/42457449/211271351-2ac4df74-b67a-4cc9-9e21-c861194a20d6.png)

![Screenshot from 2023-01-09 10-46-31](https://user-images.githubusercontent.com/42457449/211271332-e1271987-d773-4355-8a7b-8a7de261dac0.png)

**Comment by A-Harby** [comment]
Verified on Qanet, v1.6.0-qa3.
Same balance is reported on both.
![image](https://user-images.githubusercontent.com/109473873/212679239-1bfe2a65-2ff8-4a56-b19e-71b015d1686a.png)
![image](https://user-images.githubusercontent.com/109473873/212679269-3db407b3-3382-487a-9be2-aec8ffa4b304.png)
