### ISSUE TITLE
wordpress solution

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1228]

**Comment by 0oM4R** [comment]
I have added wordpress with mysql  image that also support ssh and zinit to tf-image [branch](https://github.com/threefoldtech/tf-images/tree/development_wordpress/tfgrid3/wordpress)

**Comment by 0oM4R** [comment]
now the image is ready!
note that if it is deployed behind a reverse proxy with https, this CSP header will be added `Content-Security-Policy "upgrade-insecure-requests;" `

**Comment by 0oM4R** [comment]
I have added a new image that installs the WordPress website with `wp-cli` and makes it ready for login directly,
also for the other image, i made some modifications on env variables, that will make it simple to take the values from the weblet

**Comment by 0oM4R** [comment]
login image [branch](https://github.com/threefoldtech/tf-images/tree/development_wp_login/tfgrid3/wordpress)

**Comment by 0oM4R** [comment]
images are almost ready, getting the WP_url will be enhanced with the script that Sameh provides,
holding PR cause we need to select one of the two images, also image may need some modifications while creating weblet.
I start working on wordpress weblet.

**Comment by 0oM4R** [comment]
wordpress weblet created but its functionality is still under development,
![image](https://user-images.githubusercontent.com/62248851/215830132-40cdb4fd-4ccd-4116-9ce3-fe9565d25de4.png)

**Comment by 0oM4R** [comment]
some questions :
- Can I always set the website title by default to `TF WordPress solution`?
- we need Ip4/6 ?
- should we add disks and env tabs? if no should we provide a disk for the machine as in the flavors here?
- the domain name to be created is random and not easy to remember, should we make it the same as machine name?
     - for example `name.gent02.qa.grid.tf`

**Comment by AhmedHanafy725** [comment]
> * Can I always set the website title by default to `TF WordPress solution`?

where do you mean?

> * we need Ip4/6 ?

no need

> * should we add disks and env tabs? if no should we provide a disk for the machine as in the flavors here?

only the disk in the flavor and its mount point should be the path you store the data in

> * the domain name to be created is random and not easy to remember, should we make it the same as machine name?

make it unique, like `wp{twinId}{name}.gent02.qa.grid.tf`

**Comment by 0oM4R** [comment]
- almost complete the weblet,and I did a successful deployment with it, but got stuck while testing another deployment; as rollback was not performed because of this error 
  ![image](https://user-images.githubusercontent.com/62248851/216091846-0748f0f4-3599-467f-ac0a-7b06ed024e7b.png)
  

- I tried to deploy `subscuid` on `https://play.dev.grid.tf/#/subsquid`
and I got the same error 
   ![image](https://user-images.githubusercontent.com/62248851/216092782-4ab1103d-987f-4c87-9494-e0ddcd4b3a7e.png)

for now, I'm holding this pr to make more tests and modify the docker image with the network part.

**Comment by 0oM4R** [comment]
a successful  deployment on qa, the modal contains the domain < the gw name > 
there are some errors on `yarn run dev` and the rollback error as well 

    ![image](https://user-images.githubusercontent.com/62248851/216838333-70feaf69-d739-40fd-ac3e-5bd91937739c.png)


#### for the wordpress image, I'm preparing the PR right now ! :dancers:

**Comment by 0oM4R** [comment]
now all done :dancers:  :100: 
just need to `Replace flist link with the official one`  after  [Image PR](https://github.com/threefoldtech/tf-images/pull/125) approval

**Comment by A-Harby** [comment]
Verified on Devnet, e8ee5aa.
Deployment was successful and all the data was displayed. 
![image](https://user-images.githubusercontent.com/109473873/221421636-c3a3aac7-b48d-4152-a481-c166182c3291.png)
Site and admin works fine
![image](https://user-images.githubusercontent.com/109473873/221421764-8f9eb4d5-8f99-45dd-8a96-e6bf4ca74108.png)
![image](https://user-images.githubusercontent.com/109473873/221421750-2158bf40-8c73-4d00-82ad-32dde21c2337.png)

But is it normal to have 355 gb 75% used? @0oM4R 
![image](https://user-images.githubusercontent.com/109473873/221422341-8b972477-5c05-4f02-af18-2338ce2513d9.png)

And also waiting for the docs to keep verifying and close the issue

**Comment by A-Harby** [comment]
And deployment is appearing in the micro vm contract list.
![image](https://user-images.githubusercontent.com/109473873/221422952-1815fb87-ae53-4b64-903f-2a4f36790777.png)

**Comment by 0oM4R** [comment]
> But is it normal to have 355 gb 75% used? @0oM4R ![image](https://user-images.githubusercontent.com/109473873/221422341-8b972477-5c05-4f02-af18-2338ce2513d9.png)

I discussed it with @AhmedHanafy725  and this is a known issue and not related with weblet

> And also waiting for the docs to keep verifying and close the issue

docs should be done in https://github.com/threefoldtech/info_grid/pull/3

**Comment by 0oM4R** [comment]
> And deployment is appearing in the micro vm contract list. ![image](https://user-images.githubusercontent.com/109473873/221422952-1815fb87-ae53-4b64-903f-2a4f36790777.png)

@A-Harby  please check 
- https://github.com/threefoldtech/grid_weblets/issues/1339

**Comment by A-Harby** [comment]
Verified on devnet.
since other issue was reported on other [issue](https://github.com/threefoldtech/grid_weblets/issues/1339), And storage  is a known issue.
 Closing the issue and following docs https://github.com/threefoldtech/info_grid/pull/3.
