### ISSUE TITLE
Capacity filter not working correctly

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1237]
### Description

After choosing the deployment, filling of all inputs, selecting the capacity filter as node selection, and pressing apply, it loads for like 2 minutes or more and then display a down node.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/211856751-abbeb347-bc14-4c42-ac2d-3c70fa53c671.png)
![image](https://user-images.githubusercontent.com/109473873/211856794-1a4073b8-1173-4572-a67a-5edf5f9d80c1.png)

**Comment by MohamedElmdary** [comment]
This issue is cause by `grid3_client` trying to reach the node ( 3 times ) while it's offline but this issue should be changed to `only 1 time` by @AhmedHanafy725

**Comment by A-Harby** [comment]
Verified on Devnet, afe1b11.
Node capacity filter working now and if node is down it doesn't load like before.
