### ISSUE TITLE
A lot of locked TFT without having any contract in my twin

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1239]
### Description

The twin 1161 have a locked TFT of amount `Locked: 65.32 TFT` and couldn't list any contracts in the weblets or TSClient, and the amount have been the same for a few days now.
Devnet, Weblets version 79a4459.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/212078013-3e25ccdf-5935-40d3-b967-c9ba4a48baf5.png)
![image](https://user-images.githubusercontent.com/109473873/212078223-4bcd8b59-d15d-4183-9451-5c0d8f6fab4e.png)
![image](https://user-images.githubusercontent.com/109473873/212078290-9caf7bcf-6b3d-49fc-a432-87d5434866dc.png)

**Comment by A-Harby** [comment]
still happening to me, also noticed that when I make a new deployment, the balance is added to it. 
And when I delete it, it comes to back to the same 65.32 TFT (as if it's the default zero value for the twin).
![image](https://user-images.githubusercontent.com/109473873/212687850-d8b09d53-1003-41a3-afcc-1dd0e6260f4b.png)

**Comment by despiegk** [comment]
whats happening here? will it still be resolved in this release or next release?

**Comment by DylanVerstraete** [comment]
It's difficult to judge the age of this account, there were a lot of issues before with locking / unlocking tokens for contracts, see: https://github.com/threefoldtech/tfchain/issues?q=is%3Aissue+is%3Aclosed+lock

The locking / unlocking right now is working without issues, we can maybe create a runtime migration that unlocks all balance and properly locks the right amounts back in place.

**Comment by A-Harby** [comment]
Verified locked tft on the twin are now back to 0.
![image](https://user-images.githubusercontent.com/109473873/221893785-d2349c1a-7810-4e6b-9b15-5d579ff616a2.png)
![image](https://user-images.githubusercontent.com/109473873/221893823-1dc818d9-b722-4627-8f58-4283bb6b3b9b.png)
