### ISSUE TITLE
Profile balance not updated correctly

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/grid_weblets#124]
on https://play.grid.tf/#/ , when the balance is updated (funded the account from polkadot on devnet), this update is not reflected on the balance shown for the profile.

To be able to see the updated balance, had to deactivate the account then activate it again.

**Comment by MohamedElmdary** [comment]
### Updated
#### PR
https://github.com/threefoldtech/grid_weblets/pull/132

**Comment by dmahmouali** [comment]
Verifying

**Comment by dmahmouali** [comment]
verified on play.grid.tf 
still need to refresh the page to get the updated balance

### Suggestion
- apply `setInterval` 1 min to update the balance

**Comment by MohamedElmdary** [comment]
### PR
https://github.com/threefoldtech/grid_weblets/pull/294
