### ISSUE TITLE
Manual filter isn't working in the Kubernetes

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1240]
### Description

After choosing manual node filtering in the Kubernetes deployment the weblets stop responding.
Devnet, cf2486d.

### Steps to reproduce

1. Enter mnemonics.
2. Choose Kubernetes.
3. Navigate to Master tab.
4. choose manual as Node selection.

### Logs/Alerts

[Untitled_ Jan 12, 2023 4_15 PM.webm](https://user-images.githubusercontent.com/109473873/212090665-c01568bb-cb49-4512-9ce5-e5b8cfd4ee74.webm)

**Comment by Mahmoud-Emad** [comment]
This happens also with the Mattermost solution.

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/grid_weblets/pull/1252

**Comment by A-Harby** [comment]
Verified on Devnet, 98c3d15.
Manual filter is now displaying filed and checking the node capacity correctly.
Checked also all of other deployment including Mattermost and manual filtering is working fine.
![image](https://user-images.githubusercontent.com/109473873/213929556-82a50318-f7a3-41fa-a08c-3e0c1aff7725.png)
