### ISSUE TITLE
[Bug 🐞]: Failed to load 18 out of 21 Deployments

### ISSUE THREAD

**Issue by s-areal** [threefoldtech/grid_weblets#1246]
### What happened?

Not expected to see such % of failure. This is from at least 3 different nodes, i've noticed this yesterday and the situation remains the same today.... I also suspect that the contracts are being fully charged... as I am trying to track costs.... not sure though.
In this circumstance a billing sheet per node/deployment with accumulated cost would be handy.

![Captura de ecrã 2023-01-10, às 17 21 56](https://user-images.githubusercontent.com/49781569/211619485-cb85f55a-7db3-443a-9d88-bff60edfd834.png)

### What did you expect?

I would expect that at least the nodes that are failing would be present in the deployment list. Not very pratical to understand the exact nodes/deployments that are offline/failing this way.
I would suggest:
1) Show full list of active deployments flagging deployments with failures instead of not displaying them
or even better:
2) merge contracts and deployments in one single list with all info available, flagging contract/deployment failures. AFAIK, terraform deployments won't be showing on deployments list (not sure thought) Is this the reason for 2 lists? In my view, as a user, I don't find it useful tbh

**Comment by khaledyoussef24** [comment]
made a multiple deployments and every thing works fine
can not reproduce the same issue on the current version
![image](https://user-images.githubusercontent.com/110984055/221912165-2ede1542-0cf4-4a04-96da-9ec83e06c5a0.png)
if the same issue exist reopen with more descriptive comment to solve it
