### ISSUE TITLE
MicroVm with docker converted flist isn't reachable

### ISSUE THREAD

**Issue by fl0wm0ti0n** [threefoldtech/grid_weblets#1251]
cant ping all given IP's from following microVM. The flist was created thru the docker converter in flist.hub!
while custom made containers as flists are pingable!

grid: dev

              {
    "version": 0,
    "contractId": 15614,
    "nodeId": 45,
    "name": "ConvertedPgAdm",
    "created": 1670781906,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/flowmotion.3bot/dpage-pgadmin4-latest.flist",
    "publicIP": {
        "ip": "162.205.240.242/25",
        "ip6": "2600:1700:c1e0:1150:a021:54ff:fe92:7803/64",
        "gateway": "162.205.240.254"
    },
    "planetary": "300:9bd8:6f95:d606:49e9:26ce:6dd:e1a9",
    "interfaces": [
        {
            "network": "NWa2d56278",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 8,
        "memory": 8192
    },
    "mounts": [],
    "env": {
        "SSH_KEY": "removed",
        "PGADMIN_DEFAULT_PASSWORD": "postgres",
        "PGADMIN_DEFAULT_EMAIL": "initial@postgres.com"
    },
    "entrypoint": "/entrypoint.sh",
    "metadata": "{\"type\":\"vm\",\"name\":\"ConvertedPgAdm\",\"projectName\":\"\"}",
    "description": "",
    "corex": false
}

**Comment by 0oM4R** [comment]
@fl0wm0ti0n  Is that image the same as the one mentioned in this [replay](https://github.com/threefoldtech/test_feedback/issues/334#issuecomment-1345589897) ?

**Comment by fl0wm0ti0n** [comment]
> @fl0wm0ti0n Is that image the same as the one mentioned in this [replay](https://github.com/threefoldtech/test_feedback/issues/334#issuecomment-1345589897) ?

no in this issue i tried the docker convert function on https://hub.grid.tf/docker-convert

while in the other issue i made the containers with my own dockerfile and script

**Comment by 0oM4R** [comment]
> > @fl0wm0ti0n Is that image the same as the one mentioned in this [replay](https://github.com/threefoldtech/test_feedback/issues/334#issuecomment-1345589897) ?
> 
> no in this issue i tried the docker convert function on https://hub.grid.tf/docker-convert
> 
> while in the other issue i made the containers with my own dockerfile and script

but the same dockerfile and script that is mentioned in the repo, right?
if it is the same, I think the entered entrypoint is wrong and it should be `/start.sh`

**Comment by fl0wm0ti0n** [comment]
no separated from the other issue and my repo

i used just the official dockerhub imagename and pasted it into https://hub.grid.tf/docker-convert
on deployment i used the original entrypoint.sh from dockerhub 

As far as I know even if the entrypoint is wrong i should be able to ping right? but that doesnt work

**Comment by 0oM4R** [comment]
can you provide the docker image link please ? 
I tried to create vm with the same flist and set the entry point to `/start.sh` and I can ping it normally.
```
{
    "version": 0,
    "contractId": 15667,
    "nodeId": 11,
    "name": "VMbee68649",
    "created": 1670855795,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/flowmotion.3bot/dpage-pgadmin4-latest.flist",
    "publicIP": null,
    "planetary": "302:9e63:7d43:b742:aeb4:d903:e89e:4345",
    "interfaces": [
        {
            "network": "NW9016200a",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 4,
        "memory": 8192
    },
    "mounts": [],
    "env": {
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEM3xrJ7IJiz0A+OOrdf3adA+GMHvC1qmpaw1CpU2ApH1eCb70pGYo39FXdnnuekr3l7saXbpI9ug9QgKH/ONIEEpyBaaxsLVRFK45UFJ/NjUmydkfecKN2ti8zeQH/POjIc8z/NjpZYDlpY9lhdJOzmHPGcsJUhcpHsOw0PVdk3BoXzy+NBBFhxwQPB1YSBkVMGejP93sGHrYGvJv8ZQFLdZ4UqfvJEUkc/2/IHQ8tLbxm603f4a5QaFSZd6mQqWGUcyhkbhPpRcaMzQ44hJHa4QVgP2esiI89ONUyWqdUjNKNsaU+kq25Y93MMP14QoF2MgDSoEwDIZphVfzClKRoY3NgdVkk2YcthSd7XQFsx8fJ1ojcpspEtocjzU10HvpCMUHz6IDbR3uU+7Hyplc2OG57hga7XqbeB8ndy5l12Nr9/ZOjqeUnmOyK8TFDpLRHozA8AbSnzs2vRFSgeOUa9R7WwzwWaKDcLA0f8bV5BRJgwRCCpA+flMd+o9KNy0= kassem@kassem-Predator",
        "PGADMIN_DEFAULT_PASSWORD": "postgres",
        "PGADMIN_DEFAULT_EMAIL": "initial@postgres.com"
    },
    "entrypoint": "/start.sh",
    "metadata": "{\"type\":\"vm\",\"name\":\"VMbee68649\",\"projectName\":\"\"}",
    "description": "",
    "corex": false
}
```
![image](https://user-images.githubusercontent.com/62248851/207074670-7d283276-4637-46ab-9f08-beb1ce32578e.png)

**Comment by fl0wm0ti0n** [comment]
https://hub.docker.com/r/dpage/pgadmin4

maybe its an error which has nothing todo with the flist.

**Comment by 0oM4R** [comment]
try to set `"entrypoint": "/pgadmin4/entrypoint.sh"`
it also worked with me 
````
          {
    "version": 0,
    "contractId": 15671,
    "nodeId": 11,
    "name": "VMbee686496",
    "created": 1670858181,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/flowmotion.3bot/dpage-pgadmin4-latest.flist",
    "publicIP": {
        "ip": "",
        "ip6": "2a10:b600:1:0:90b4:d6ff:fe2d:e7d2/64",
        "gateway": ""
    },
    "planetary": "302:9e63:7d43:b742:c50:987f:50f2:9331",
    "interfaces": [
        {
            "network": "NW3cd31ec9",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 2,
        "memory": 8192
    },
    "mounts": [],
    "env": {
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDEM3xrJ7IJiz0A+OOrdf3adA+GMHvC1qmpaw1CpU2ApH1eCb70pGYo39FXdnnuekr3l7saXbpI9ug9QgKH/ONIEEpyBaaxsLVRFK45UFJ/NjUmydkfecKN2ti8zeQH/POjIc8z/NjpZYDlpY9lhdJOzmHPGcsJUhcpHsOw0PVdk3BoXzy+NBBFhxwQPB1YSBkVMGejP93sGHrYGvJv8ZQFLdZ4UqfvJEUkc/2/IHQ8tLbxm603f4a5QaFSZd6mQqWGUcyhkbhPpRcaMzQ44hJHa4QVgP2esiI89ONUyWqdUjNKNsaU+kq25Y93MMP14QoF2MgDSoEwDIZphVfzClKRoY3NgdVkk2YcthSd7XQFsx8fJ1ojcpspEtocjzU10HvpCMUHz6IDbR3uU+7Hyplc2OG57hga7XqbeB8ndy5l12Nr9/ZOjqeUnmOyK8TFDpLRHozA8AbSnzs2vRFSgeOUa9R7WwzwWaKDcLA0f8bV5BRJgwRCCpA+flMd+o9KNy0= kassem@kassem-Predator",
        "PGADMIN_DEFAULT_PASSWORD": "postgres",
        "PGADMIN_DEFAULT_EMAIL": "initial@postgres.com"
    },
    "entrypoint": "/pgadmin4/entrypoint.sh",
    "metadata": "{\"type\":\"vm\",\"name\":\"VMbee686496\",\"projectName\":\"\"}",
    "description": "",
    "corex": false
}
````

**Comment by fl0wm0ti0n** [comment]
i sshed into this container locally and the entrypoint.sh is in rootpath, but i can try

**Comment by fl0wm0ti0n** [comment]
with this microVm is generally something faulted...

today it isn't shown anymore with an error message:
![image](https://user-images.githubusercontent.com/24993288/207105730-71d12c75-3796-464e-b889-898dd2a0c1c9.png)

And in contracts I have 2 with the same name:
![image](https://user-images.githubusercontent.com/24993288/207105958-1f49821e-e9f0-4180-82af-db4f36025f25.png)

So i assume the problem is more deployment-error related then container and configs

**Comment by 0oM4R** [comment]
It's normal to have 2 contracts with the same name, due to the machine having public IP.
so one of them is for the machine, and the other is for the network workload.

**Comment by fl0wm0ti0n** [comment]
also with the solution type "virtual machine" and not network?

**Comment by 0oM4R** [comment]
yes that's a bug and will be fixed on the next release

**Comment by AhmedHanafy725** [comment]
closing in favor of #1320
