### ISSUE TITLE
back button after discourse deployment doesn't make any action

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#1253]
after deploying discourse successfully back button appears (to return to the deploying options page) it doesn't work

steps to produce:

1. go to playground.
2. go to discourse tab.
3. fill the fields.
4. deploy and wait for the success screen. 

![Screenshot from 2023-01-19 10-52-28](https://user-images.githubusercontent.com/110984055/213397860-77b8a242-a10e-4015-9cfb-08a64356941d.png)

**Comment by A-Harby** [comment]
Issue was reported before and still reproducible.
https://github.com/threefoldtech/grid_weblets/issues/1115#issuecomment-1383150957

**Comment by xmonader** [comment]
closed in favor of https://github.com/threefoldtech/grid_weblets/issues/1287
