### ISSUE TITLE
UI discourse mail server settings

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#1254]
the username field is the discourse tab require inserting a mail with a mail format

so it may be renamed to email to be more clear instead of username if it has email regex

steps to produce:

1. open playground
2. go to discourse tab
3. choose mail server tab from deployment options

![Screenshot from 2023-01-19 11-02-07](https://user-images.githubusercontent.com/110984055/213413395-d8a60d38-1a50-4373-ba31-38937bd69757.png)
![Screenshot from 2023-01-19 11-01-56](https://user-images.githubusercontent.com/110984055/213413403-06c59e25-804f-48f5-bddb-7d64c1d03713.png)

**Comment by Omarabdul3ziz** [comment]
It should be a username. SMTP servers provide their configurations as a username even if the format is an email. but not all SMTP providers do this, for example, I am using mailtrap for testing and it gives a username as raw text so I need to work around opening the console and removing the disable from the button. And all goes well, so the discourse server doesn't require the username to be in a mail format.

so it will be a better solution to remove the validation and placeholder instead and keep the field as Username. what do you think?

Note: this can be applied across all the weblets not just discourse

**Comment by rkhamis** [comment]
I suggest we do "usrername/email" instead. validation should work against either option

**Comment by A-Harby** [comment]
Verified on Devnet, https://github.com/threefoldtech/grid_weblets/commit/7259306c40068e99c708caedb8737621f921fd9d.
Changed to `Usrername/Email` in discourse
![image](https://user-images.githubusercontent.com/109473873/230378728-81a3d711-c3ab-4e20-a06a-048bcccde658.png)
