### ISSUE TITLE
`Null TFT` is displayed when refreshing the weblets

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1259]
### Description

When you log into weblets using mnemonics, your balance and locked TFT will be retrieved and displayed correctly.
But once you refresh the site it willl display null TFT in both field.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/213929345-7b4441a4-4267-4274-9b28-36d1f97b12ab.png)
![image](https://user-images.githubusercontent.com/109473873/213929347-2aeb5fe6-0d95-4e42-a274-12a34b0b1a4d.png)

**Comment by MohamedElmdary** [comment]
@A-Harby I can't reproduce this issue neither on local nor on play.dev

**Comment by A-Harby** [comment]
@MohamedElmdary  Steps to reproduce:
- Enter your mnemonics.
- wait for profile to load and open.
- refresh page.

Dvenet 98c3d15
[Untitled_ Jan 23 2023 2_12 PM.webm](https://user-images.githubusercontent.com/109473873/214036911-5ea63628-c109-4997-a546-6b9018ea6afd.webm)

**Comment by MohamedElmdary** [comment]
@A-Harby tried to reproduce it even with slow connection
https://user-images.githubusercontent.com/31689104/214039432-a911f577-9667-4a89-8b6e-d9b2dfe2542b.mp4

**Comment by A-Harby** [comment]
Closing the issue as I couldn't reproduce it with the current weblets version 5ef6de6.
