### ISSUE TITLE
Parts of deployment are listed under different ones

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/grid_weblets#126]
When deploying peertube, 3 vms are deployed. 
- Listing peertube the deployment is shown:
![Screenshot from 2021-12-06 15-46-33](https://user-images.githubusercontent.com/17128393/144857074-fb9a308a-c5e5-4b59-a09c-416a2a2bb230.png)
 
- Listing virtual machines, 3 VMs are shown (from the peertube deployment):
![Screenshot from 2021-12-06 15-46-11](https://user-images.githubusercontent.com/17128393/144857137-6c30cf36-e48a-480a-8a08-7e5722c77b54.png)

This could be solved if peertube was contained in one image, but the bug would still arise for similar scenarios in the future for different deployment types that consist of more than one vm deployment

**Comment by asamirr** [comment]
@Omarabdul3ziz and I are working on it

**Comment by rkhamis** [comment]
Peertube VMs are still VMs. no reason to filter them out
