### ISSUE TITLE
Uncaught (in promise) TypeError: t.includes is not a function Error

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#1261]
### Description

this happens sometimes. probably when a deployment rolled back for any reason.

### Steps to reproduce

Can be reproduced by deploying a container/regular flist with the full VM weblet.

### Logs/Alerts

![Screenshot from 2023-01-24 17-51-25](https://user-images.githubusercontent.com/42457449/214366927-b01d3e45-ec62-4db6-a7f7-29aa2f081e8f.png)

**Comment by A-Harby** [comment]
Closing the issue as unproducible.
Tried different deployment with different configuration and different node and there was no error with them.
![image](https://user-images.githubusercontent.com/109473873/228594813-23faeb48-3e1f-4681-ba90-0d94161e846f.png)
