### ISSUE TITLE
profile manager invalid Mnemonics insertion

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#1264]
### Description

once you enter an in invalid Mnemonics it will keep loading

even create account button is not disabled when no characters are inserted
![Screenshot from 2023-01-26 14-39-11](https://user-images.githubusercontent.com/110984055/214838973-5636a5d9-2d15-410a-b17b-5f7e196fcd0f.png)
[Screencast from 01-26-2023 02:38:52 PM.webm](https://user-images.githubusercontent.com/110984055/214838983-7c4a331a-763b-427e-bf8a-4e1ddc3fc093.webm)
and then it freezes

### Steps to reproduce

1. go to [playground](https://play.qa.grid.tf/#/)
2. open the profile manager
3. insert an incorrect Mnemonics or account that doesn't have a twin
4. click create account
5. the profile manager freezes

[Screencast from 01-26-2023 02:36:46 PM.webm](https://user-images.githubusercontent.com/110984055/214839714-76dca8a6-16bb-4e3a-991b-0b2c1722bb09.webm)

**Comment by A-Harby** [comment]
Qanet, v1.6.0-qa4.
Issue isn't reproducible anymore.

![image](https://user-images.githubusercontent.com/109473873/215315230-082154bd-b864-4167-b81d-811587c29187.png)
