### ISSUE TITLE
domain created in mattermost is missing in details page after deployment

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#1266]
### after creating a mattermost solution the domain doesnt show up in the deatils page when it pops up like in other solution
mattermost :
![Screenshot from 2023-01-26 16-54-12](https://user-images.githubusercontent.com/110984055/214869448-fc664328-9553-40d0-8947-703d35a29e4d.png)

other solutions:
![image](https://user-images.githubusercontent.com/110984055/214870035-f9acaab0-a918-455d-bb1b-b3de94c0c992.png)

### Steps to reproduce

1. open [playground](https://play.qa.grid.tf/#/mattermost) and go to mattermost
2. fill the deployment data
3. deploy solution
4. after deployment the details page will pop-up you will notice that the domain is missing

**Comment by A-Harby** [comment]
Verified on Devnet, 31ff1ae.
Domain now is visible om deployments info.
![image](https://user-images.githubusercontent.com/109473873/215755775-8d6b1f27-4f62-4cb7-b10f-ede0d05b6dcc.png)

**Comment by khaledyoussef24** [comment]
the same issue is found at owncloud
![image](https://user-images.githubusercontent.com/110984055/218407861-c6a31ab3-a7a9-4a3f-b5ca-6665f61afe41.png)

**Comment by khaledyoussef24** [comment]
verified on devnet 
![image](https://user-images.githubusercontent.com/110984055/221404809-fc7dbc66-c248-4c19-a7bc-bef1fc7defa3.png)
