### ISSUE TITLE
tf connect gives bad gateway in mattermost

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#1267]
### Steps to reproduce

go to play ground and open mattermost tab
fill the deployment details and deploy a solution
open the created domain page  ![Screenshot from 2023-01-26 17-24-16](https://user-images.githubusercontent.com/110984055/214878061-aeb1d4e1-eb6e-445d-a62d-545befd603be.png)
choose to create an account using tf connect or sign-in using tf connect
it will take time then gives bad gateway
![Screenshot from 2023-01-26 17-30-20](https://user-images.githubusercontent.com/110984055/214878052-6ceb990f-f3ee-43cf-bcbe-b8536bcc7f1d.png)

**Comment by A-Harby** [comment]
Qanet, v1.6.0-qa4.
Issue is still reproducible 
![image](https://user-images.githubusercontent.com/109473873/215321144-32cce327-3ea2-4a36-a9e1-a4de84afc7e2.png)
![image](https://user-images.githubusercontent.com/109473873/215321176-f65a6ed8-6701-4987-8668-d9fe1e8eff23.png)

**Comment by sameh-farouk** [comment]
I checked this issue and can confirm that the threefold login is broken. the HTTP server is **panicking** in the middle of the auth process. 
I didn't go deep into the code, but I noticed that the threefold login logic implemented in this image **depends** on the **grid Oauth proxy remote service** at https://oauth.threefold.io which seems to **not exists** these days.
We can fix this by either 
- Running our OAuth server (python implementation already available) next to Mattermost server and changing the Oauth proxy URL (could be a faster fix in the short-term) or, 
- Implementing the login logic as a GOlang plugin for Mattermost (which is more portable and clean and is easier to maintain in the feature).

I want to highlight that if we have other solutions that depend on the above-mentioned service, the threefold connect functionality will be **broken** as well.

**Comment by hossnys** [comment]
https://oauth.threefold.io/ is live again now , @khaledyoussef24 could you please verify that issue is fixed ?

**Comment by hossnys** [comment]
verified by @alichaddad

**Comment by khaledyoussef24** [comment]
works fine now 
[Screencast from 02-08-2023 02:47:17 PM.webm](https://user-images.githubusercontent.com/110984055/217533825-3f0a1d3e-1bfd-455c-a4ed-e06292a7f72f.webm)
