### ISSUE TITLE
Manual filtering only works once

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1269]
### Description

Qanet, v1.6.0-qa4.
Manual capacity filter only check once but if you wanted to repeat filtering again it will not work.

### Steps to reproduce

- Choose any deployment.
- Fill in all needed inputs.
- Choose manual as capacity filter.
- Enter a node id.
- Delete it and enter it again.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/215312951-b8b2ae89-681f-4bac-874b-88eaf382d61a.png)

**Comment by maayarosama** [comment]
The manual filter is working fine as follows:
![Peek 2023-01-31 15-35](https://user-images.githubusercontent.com/66883096/215775828-ba3ebdf1-1ef1-4cc3-b6e1-9336be7b4e5a.gif)

**Comment by A-Harby** [comment]
@maayarosama  It occurs when I check the same node repeatedly; a new check is not done, or maybe only the message is removed.

[Untitled_ Feb 1 2023 10_40 AM.webm](https://user-images.githubusercontent.com/109473873/215992836-85dd2de9-9866-4c7f-b255-161d5f3bd40a.webm)

**Comment by A-Harby** [comment]
Verified on Devnet, 4443780.
The filter will repeatedly check the same node, and a message will always be displayed.
![image](https://user-images.githubusercontent.com/109473873/218486747-36275d1d-97e5-426e-8c9e-ab9255baf20a.png)
