### ISSUE TITLE
Invalid Created at value

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/grid_weblets#1271]
### Description

The created at values in the contracts list are invalid. It's mostly shown that all the contracts are created on the same wrong day even though they're not.
![photo_٢٠٢٣-٠١-٣٠_١٢-٤٠-٣٦](https://user-images.githubusercontent.com/66883096/215487715-49968fdb-7156-4de0-bace-0e5aa5ba3e0d.jpg)

### Steps to reproduce
- Enter your mnemonics
- deploy multiple machines
- navigate to the contracts section

**Comment by A-Harby** [comment]
Verified on Devnet, 31ff1ae.
Values are now back to normal.
![image](https://user-images.githubusercontent.com/109473873/215756625-7c2125c2-676b-485e-83f5-ab8eb570ed8d.png)
