### ISSUE TITLE
How to point a play deployment to a specific grid backend

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_weblets#1274]
### Description

There does not seem to be a way to set specific urls that a play deployment will use.

Can we set env vars like tfchain public node, graphql, gridproxy, .. so call's are directed to defined url's.
Currently the urls seem hard-coded.

**Comment by MohamedElmdary** [comment]
The urls is defined based on the passed network
- For weblets: https://github.com/threefoldtech/grid_weblets/blob/development/rollup.config.js#L60
- For playgound: https://github.com/threefoldtech/grid_weblets/blob/development/playground/vue.config.js#L13

**Comment by coesensbert** [comment]
Thanks @MohamedElmdary , we need the ability to set custom url's. Not pre-defined url's based on a network variable. Would that be possible? It's needed for the new grid backend. Since every backend deployment will have all the services, playground needs to connect to it's own graphql, own tfchain public node, ..

**Comment by MohamedElmdary** [comment]
@coesensbert Will update it to be able to pass env variables while running docker image. is that ok?

**Comment by MohamedElmdary** [comment]
@coesensbert I will update it so it accepted variables while running docker image

**Comment by Omarabdul3ziz** [comment]
PR is merged now on development. check the [docs](https://github.com/threefoldtech/grid_weblets/blob/development/docs/build.md)

**Comment by A-Harby** [comment]
Verified.
https://github.com/threefoldtech/grid_weblets/blob/development/docs/build.md

![image](https://user-images.githubusercontent.com/109473873/221915329-88374164-5781-4dd6-9cc3-f31c78ee2c1f.png)
![image](https://user-images.githubusercontent.com/109473873/221915593-72506372-ce1b-4717-bcd5-73acedceb0df.png)
