### ISSUE TITLE
Do you need the `node-sass` dependency? There's already `sass`

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/grid_weblets#1276]
- The `node-sass` dependency is very old and depends on an old version of node-gyp which is broken on Python 3.11
-  `sass` is also in the dependencies, which is a pure javascript implementation and does not depend on gyp( so not on g++, make and Python)

**Comment by MohamedElmdary** [comment]
@robvanmieghem Remove `node-sass` in https://github.com/threefoldtech/grid_weblets/pull/1294
