### ISSUE TITLE
node selection does not perform well when changing the selection type

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/grid_weblets#1277]
### Description
after changing the selection type while it validating the node id, the apply filters and node id field were disabled, but also cleared, so when the ping node returns the node id will be displayed as 'null'
### Steps to reproduce
- choose the manual selection 
- enter any node id that make the weblet ping it, while weblet validating the node id change the type to capacity filter 
![image](https://user-images.githubusercontent.com/62248851/215999932-2f97068f-842c-4d19-b1cc-7e7b646ad5ca.png)

https://user-images.githubusercontent.com/62248851/215995990-7151630d-dc05-4286-8a74-29e0f761e119.mp4

**Comment by A-Harby** [comment]
Verified on weblets, 122028a.
Now node selection input and list are both disabled preventing the issue from occuring.
![image](https://user-images.githubusercontent.com/109473873/216316840-d04e50b9-7d7e-443c-b205-912b16c0d4bb.png)
![image](https://user-images.githubusercontent.com/109473873/216317080-df812922-58d0-429e-9006-bf9f2523d859.png)
