### ISSUE TITLE
node filter assign farm or country to "null"

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/grid_weblets#1279]
### Description

if you are using the capacity filter, and leave the farm name and county as it you will retrieve many nodes 
![image](https://user-images.githubusercontent.com/62248851/216023056-66741ce0-bad2-43cb-8de7-1f538c827a79.png)
now change the farm name or county to any of their options, and you will retrieve some node also 
![Screenshot from 2023-02-01 12-45-54](https://user-images.githubusercontent.com/62248851/216023607-38b75ecd-019a-474f-a608-6e39b7f24cfd.png)
but If you want to return to the default case < all farms and all countries > you will retrieve nothing
and the changed field becomes empty 
![image](https://user-images.githubusercontent.com/62248851/216024121-ef1769c9-6b32-4275-adac-5e8b89f2b76b.png)

### Logs/Alerts
````
Error findNodes Error: Couldn't find any node with options: {"publicIPs":false,"country":null,"farmName":"null","cru":4,"mru":8,"sru":2,"availableFor":800}
    at f.<anonymous> (nodes.js:199:19)
    at Generator.next (<anonymous>)
    at a (nodes.js:4:58)

````

**Comment by A-Harby** [comment]
Verified on Devnet, 1c38bc0.
Tested with switching between farms, country and defaults, no error showns.   

![image](https://user-images.githubusercontent.com/109473873/224538146-049f3458-4c22-4fb7-8653-d2292570c074.png)
![image](https://user-images.githubusercontent.com/109473873/224538206-b8edab43-9472-4655-9577-a28ed851a7b1.png)
