### ISSUE TITLE
Deleting peertubevms doesnt delete all associated deployments

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/grid_weblets#128]
When deploying peertube, there is one peertube deployment shown in peertube and 3 virtual machinne deployments in vm deployments. When deleting one of the VM deployments , the peertube deployment is deleted as well but the associated VMs aren't deleted and so 2 VMs are left that should be associated with the deleted peertube deployment
- Before deletion:
peertube listing
![Screenshot from 2021-12-06 15-46-33](https://user-images.githubusercontent.com/17128393/144861288-7e8c8c69-2d5c-4893-aecc-7456843768e5.png)
vm listing
![Screenshot from 2021-12-06 15-46-11](https://user-images.githubusercontent.com/17128393/144861290-0dbafa69-5eb6-4155-ac5e-33be0a42d7d9.png)
- After deletion
peertube listing
![Screenshot from 2021-12-06 16-12-32](https://user-images.githubusercontent.com/17128393/144861170-2f6ab921-6ee0-482a-87b7-045ee7478ee5.png)
vm listing
![Screenshot from 2021-12-06 16-12-17](https://user-images.githubusercontent.com/17128393/144861173-705ab572-f162-42a6-949d-1169e7dbd2f4.png)

**Comment by rkhamis** [comment]
should be easier to do once we have #96 
let's check after it's done

**Comment by xmonader** [comment]
It won't be relevant after using all in one image
