### ISSUE TITLE
destroy function returns error at rollback 

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/grid_weblets#1289]
### Description
while creating the new weblet for Wordpress, I tried to test the rollback flow, after gw deployment failed 
but there is an error 
![image](https://user-images.githubusercontent.com/62248851/217206925-892ceabf-41cc-4c41-8819-6feb4b515a70.png)
the same error occurred on subscuid as well;
after `console.log(error)`
i got this log:
![image](https://user-images.githubusercontent.com/62248851/217207196-20a60b3e-7c73-4da1-b1d3-4feac9808570.png)

List of steps to reproduce the problem if it's a bug
- try to use destroy function in any weblet .

**Comment by Omarabdul3ziz** [comment]
client was not connecting before it tries delete so `client.machines.delete` has machines as `undefined` and that produce the issue. fixed in the mentioned PR with extra explicit types for solution names.

**Comment by mohamedamer453** [comment]
Verified on devnet.

Deployment Rollback is working fine and doesn't produce the mentioned error anymore.

[Screencast from 22-03-23 16:47:47.webm](https://user-images.githubusercontent.com/101194226/226942928-b2323b5b-69cb-4e10-b795-5905a6f4c4af.webm)
