### ISSUE TITLE
Input Nmeonic field on test net profile manager not behaving.  

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/grid_weblets#1290]
### Description

When typing your words to add account on the profile manager that is on test net, it only allows keyboard input of one letter at a time. Each time you type a letter the focus is removed from the box and you have to re click the text box. 

### Steps to reproduce

visit [playground](https://play.test.grid.tf)

click the gear, Attempt to manually type in your words without pasting. 

### Logs/Alerts

https://user-images.githubusercontent.com/44621168/217314618-b7353594-7f16-4780-b27c-945024d6ff7e.mp4

**Comment by zaelgohary** [comment]
Duplicate with https://github.com/threefoldtech/grid_weblets/issues/1292

**Comment by A-Harby** [comment]
Closing the issue as the Mnemonics field input's intended use is to paste it rather than write it.

**Comment by Parkers145** [comment]
That's an entirely unacceptable answer and it's embarrassing you think that an appropriate standard to maintain. 

I don't keep my words stored digitally as anyone with any experience in crypto currency would tell you to do. This is why our program is such financial trouble. Lets not publish broken technology to main net just for fun.

**Comment by xmonader** [comment]
@Parkers145 Please be reminded that this is an open source project with best intention / effort. This language doesn't really help anyone. 

I'll consider this the first warning

**Comment by Parkers145** [comment]
> @Parkers145 Please be reminded that this is an open source project with best intention / effort. This language doesn't really help anyone. 
> 
> 
> 
> I'll consider this the first warning
> 
> 
> 
> 

Sorry I didn't feel like I used any inappropriate language. I have removed the response. It's disappointing that nearly EVERY issue I or any member of the community open is always treated in these ways. It always seems the answer that is provided is "well your using it wrong" and I feel like that is entirely unacceptable and needs to be addressed. 

We have zero community engagement in the development enviroment. And I think we are clearly displaying why.

I'll consider this my departure.

**Comment by delandtj** [comment]
@Parkers145 , it was not an inappropriate comment. Things get heated and misunderstood faster than it can get read, I'm sorry for that. 
Keep up the good work... (that is, if you're still willing).

**Comment by despiegk** [comment]
Hi @Parkers145 , I do agree, the team is so passionate they might come across too defensive, but personally I do believe if it doesn't work for you then its wrong and needs to be fixed, you are an advanced user so in other words wont work for others for sure and not be good enough. Hi ThreeFold team, please lets fix this soon.

**Comment by Parkers145** [comment]
#> Hi @Parkers145 , I do agree, the team is so passionate they might come across too defensive, but personally I do believe if it doesn't work for you then its wrong and needs to be fixed, you are an advanced user so in other words wont work for others for sure and not be good enough. Hi ThreeFold team, please lets fix this soon.

Ill be the first to acknowledge the passion issue, its a two sided coin. I ultimately generated this thread because I was attempting to create a video tutorial of how to use the new tool and when I discovered this, I immediately recognized after 

- nearly 10 hours of recorded and published podcast time doing support for deploying on the grid, 
- writing numerous guides that having some of the highest view counts of any tutorial on the forum,  
- Being one of only three people to hold the "aficionado" badge on the forums. 

that this was going to be a problem. 99% of users that deploy on the grid assume every problem they encounter is complete failure of the grid. there is not a day that goes by that our community does not voice that are tools are "under-developed" and "to hard to use". There are entire community projects that are working entirely independently of our development team to create replacement interfaces that provide what the playground does but a better interface. thats it. 

 When I originally wrote the installing umbrel i attempted to write it as a single document that would introduce someone to threefold and allow them to achieve this from windows. that document was made up by these two documents 
 
https://github.com/Parkers145/ThreefoldDeployerManual/blob/basic/src/playground/setupthreefoldconnect.md

https://github.com/Parkers145/ThreefoldDeployerManual/blob/basic/src/applicationhowto/umbrel.md
 
sorry i dont have the all in one anymore, that document was so large that the forums can not  physically handle it in its current state. so instead i built 
 
https://deploy.threefold.dev
https://deploy.threefold.dev/playground/setupthreefoldconnect.html
https://deploy.threefold.dev/applicationhowto/umbrel.html
 
 In addition to these resources i provided and published a live demo installing in the community call recordings, along side of the videos that coincide and and cover all the guide topics i created. 
 
 https://www.youtube.com/channel/UCrf3_tCzDdPIV1ZGRyyfbOQ
 
 Even with all of these resources available to them, I am still struggling to teach people to create even basic playground deployments and our chats are filled with people asking how our "nodes blockchain encryption tech removes the need for ip addresses" and some of our most active members suggesting we "use QSFS to create redundant hosting workloads". We have everything we need to succeed but no one has a clue guys. 
 
 Its been over a year and ive purchased nearly 1000$ in equipment trying to provide a 5 gigabit unmetered connection with a /25 address block to the grid. i still cant get the darn thing working. 
 
 
 If did offend someone, I apologize, A good portion of the time I  personally have/had  to defend the answers that are given here in face to face conversations  with our community. There is no time for me to prepare or come up with a solution when someone comes to my podcast and says "So im supposed to trust threefold with all of my important data, but i cant have a working text box, Or delete files on an HDD". Thus this stuff also gets me pretty fired up. hopefully we can all move forward with a better understanding of what my purpose here is :).

**Comment by khaledyoussef24** [comment]
verified now profile manager can take characters 
[Screencast from 03-05-2023 04:16:20 PM.webm](https://user-images.githubusercontent.com/110984055/222966032-eae4e3d0-844c-4cb2-bdac-2f9b37b03958.webm)

**Comment by Parkers145** [comment]
this is happening on main net now
