### ISSUE TITLE
The Mnemonics field does not accept more than one character at a time

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#1292]
### Search first

is similar to this issue in mastodon https://github.com/threefoldtech/www-mastodon/issues/38

### Description

The Mnemonics field does not accept more than one character at a time. and to enter a full word you have to click inside the field after every character.
[Screencast from 02-08-2023 11:42:44 AM.webm](https://user-images.githubusercontent.com/110984055/217493393-36ea48ae-15cf-46ab-ab40-f3e93ffbda77.webm)

**Comment by zaelgohary** [comment]
This is a known issue as all users paste their mnemonics directly in the field.

**Comment by A-Harby** [comment]
> This is a known issue as all users paste their mnemonics directly in the field.

Closing the issue as the Mnemonics field input's intended use is to paste it rather than write it.
