### ISSUE TITLE
Listing deployments does not work

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/grid_weblets#1293]
### Description
version 1.6.0-rc1 = version currently on testnet

![Screenshot 2023-02-08 at 10 54 47](https://user-images.githubusercontent.com/3511318/217496825-36f61ccc-488c-4c22-87b8-f60a4f765a8c.png)

**Comment by AhmedHanafy725** [comment]
I was trying to reproduce that on testnet but seems it's working fine, also working with the QA team.
I wonder why it tries to connect to a websocket on localhost and the chain websocket is set on the docker image by default to `wss://tfchain.test.grid.tf`
are there any steps to reproduce it?

**Comment by ramezsaeed** [comment]
@robvanmieghem ?

**Comment by robvanmieghem** [comment]
It was a tab that was still open from before the upgrade, refresh did not solve it.
After a chrome restart I had to"migrate" ( this is really not clear to an end user)  the profile manager, re-entering my mnemonic and ssh key. After this, it works again.

**Comment by AhmedHanafy725** [comment]
okay then gonna close this issue as it works, and opened a new one for making the migration button clear #1318
