### ISSUE TITLE
Update the create account part after upgrading grid client to set the relay on the twin

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#1295]
require: https://github.com/threefoldtech/grid3_client_ts/pull/501

once the client is released with this feature, the grid client dependency to be updated to be able to create twins

**note:** when creating the account, the relay input should depend on the networkEnv

**Comment by A-Harby** [comment]
Getting this error when trying to create new account on weblets, devent 9c324d5.
![image](https://user-images.githubusercontent.com/109473873/218512529-ed0085b9-1052-4be9-aba0-cd9cf620e537.png)

**Comment by MohamedElmdary** [comment]
@A-Harby After some investigation I figured out that this issue is cause only in production but working on development. Will continue working on it

**Comment by A-Harby** [comment]
Verified on devnet fa79484.
Was able to create an account and add tft to it.
![image](https://user-images.githubusercontent.com/109473873/220140855-baf1f2c3-5820-45c8-a274-6666957935e6.png)
