### ISSUE TITLE
Farming calculator Weblet

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#13]
using  [tft_farming_calculator_v3.0.1.xlsx](https://github.com/threefoldtech/grid_weblets/files/7533525/tft_farming_calculator_v3.0.1.xlsx).

where:
  parameters can be configurable
  parameters are: 
   - CPU cores
   - mem
   - HDD
   - SDD
   - public ip available (boolean)
   - certified (boolean)
   - power utlilization
   - power cost (kw/h)
   - price of TFT at point of registration on blockchain
   - token price after 5 years

which is used to calculate *TFT farming rewards*

visualize with a graph how as the TFT price goes up, the return on investment goes up

design can be resued from: https://github.com/threefoldfoundation/home/issues/200

**Comment by rkhamis** [comment]
Next step would be to have pre-configured parameters (Titan Nodes)

**Comment by rkhamis** [comment]
changes:

In Basic View:
  - [ ] create a new field "Maximum Token Price". Allow editing.
  - [ ]  remove field Token Price In 5 Years
  - [ ] use new field as X-axis
  - [ ] remove calculations. Keep only SU, CU, NU, reward per....
  
 General:
  - [ ] numbers don't match between tabs.
  - [ ] HDD gets overwritten in Advanced when starting with 0
  - [ ] numbers don't match sheet

**Comment by MohamedElmdary** [comment]
**numbers don't match sheet** cannot find any difference between output and sheet values.

**Comment by rkhamis** [comment]
new feedback
 

- [ ] add field input "price of hardware"
- [ ] max price and token price in 5 years ---> default on 2
- [ ] toggle button, either ROI or net profit. graph then shows return on investment

**Comment by xmonader** [comment]
- [ ] should include `required NU per CU` field
- [ ] add investment of HW
