### ISSUE TITLE
Deploying a workload gives 'insufficient TFT on account', where account is funded

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#130]
I deploy a Peertube workload on play.grid.tf, and I use devnet. 
I get an error message for reason 
<img width="1280" alt="Screenshot 2021-12-07 at 09 49 34" src="https://user-images.githubusercontent.com/30384423/144998278-74e8274c-40fa-42af-a559-0fb8986059a2.png">

While the account is funded, see 
<img width="1280" alt="Screenshot 2021-12-07 at 09 30 47" src="https://user-images.githubusercontent.com/30384423/144998184-f05bbd09-a517-4575-8c63-7f20193daaba.png">

**Comment by rkhamis** [comment]
should be working now.
Can you retest, @gmachtel ?

**Comment by gmachtel** [comment]
It works now, thanks !
