### ISSUE TITLE
the solution type is empty in contracts when deploying taiga 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#1303]
### Description
when deploying taiga the contract of the deployment doesn't show the solution type
### steps to produce:

1. go to the playground
2. insert your credentials
3. deploy taiga
4. go to contracts
5. check for solution type field

![image](https://user-images.githubusercontent.com/110984055/218413450-5308703c-6e69-4552-85fe-a7010fd7c48a.png)

**Comment by maayarosama** [comment]
Cannot reproduce this issue.
When a node contract is created it has a solution type which is shown, However a name contract is created with every node contract and it doesn't have a solution type which is normal. 
![Screenshot from 2023-02-23 15-53-47](https://user-images.githubusercontent.com/66883096/220928367-37d9eb4f-bd8f-4573-a212-f3b6115fac18.png)

**Comment by A-Harby** [comment]
Verified on devnet, e8ee5aa.
Solution type was shown.
![image](https://user-images.githubusercontent.com/109473873/221416404-325cc8a2-0290-4530-9aa8-a8eb4ca8fedd.png)
