### ISSUE TITLE
umbrel weblet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1304]
child of https://github.com/threefoldtech/home/issues/1394

**Comment by A-Harby** [comment]
Verified on Devnet,
Umbrel deployments works fine.
![image](https://user-images.githubusercontent.com/109473873/227219762-96559102-cd8f-43f7-bda3-3b4b1fd40485.png)
![image](https://user-images.githubusercontent.com/109473873/227220325-e51a8ffb-d45a-4040-af8d-42f8140f6ada.png)
