### ISSUE TITLE
Find a way to detect you have introduced the right seed words in Weblet profile Mgr

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#131]
Linked to bug report https://github.com/threefoldtech/grid_weblets/issues/130

It might be that I introduced wrong seed words, but there is no way to discover that as the polkadot extension nor the portal give a possibility to see the words back. 
And in the profile, there is no public address shown that could be derived from these seed words. So there is no check at all possible to see whether you have made a mistake as a user or not. 

Feature needed to make an easy (visual) check possible to see whether all is introduced well.

**Comment by abom** [comment]
Showing a derived address e.g. underneath the user avatar would be sufficient IMHO.

**Comment by gmachtel** [comment]
That would indeed be sufficient for now. But if possible, based on this info you can also read whether the address exists of the blockchain and if so, the balance of TFT on the blockchain. Would give a better user experience.

**Comment by abom** [comment]
Before activating any profile, mnemonics get validated if it's already on the selected network, also, after activation, the balance is shown.

_Mnemonics validation:_

![Screenshot from 2021-12-07 14-50-24](https://user-images.githubusercontent.com/511438/145175062-1c070ea8-929b-4442-81fd-750a51e8865c.png)


_Current activated profile balance:_
![Screenshot from 2021-12-08 10-33-30](https://user-images.githubusercontent.com/511438/145175356-aba2fd95-e75b-4fe4-984e-e3aeceea3fb4.png)

**Comment by asamirr** [comment]
Solved in PR https://github.com/threefoldtech/grid_weblets/pull/147

**Comment by abom** [comment]
@asamirr please attach a screenshot add more information on where the new information is shown.

**Comment by asamirr** [comment]
![image](https://user-images.githubusercontent.com/9322121/145372956-d917fda8-989b-4e47-bc2d-9cb6c8a20df6.png)

**Comment by waleedhammam** [comment]
verified
