### ISSUE TITLE
Pressing enter during deployment has confusing behavior

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#1311]
During the deployment process, if my cursor is in an entry field and I press `Enter`, the following window pops up:

![image](https://user-images.githubusercontent.com/17682591/219563334-7341ad54-8cc0-447f-94cd-3e1bf8de47f5.png)

If I hit `Delete` nothing seems to happen. If I hit `Cancel`, then deployment begins, even if the `Deploy` button was greyed out.

Minimal path to reproduce:

1. Select any solution
2. Place the cursor in an input field
3. Press `Enter`
4. Hit `Cancel`

If some validation fails, an error is thrown, but otherwise the deployment proceeds. This is actually a way to bypass validation, in the case that no network toggles are enabled, but I [don't think](https://github.com/threefoldtech/grid_weblets/issues/1310) that should block deployment anyway.

**Comment by A-Harby** [comment]
Verified on Devnet, c807b1b.
Tried most of the solutions input, pressing enter in any of the input do nothing now.
