### ISSUE TITLE
Randomly show error _undefined_ after a success deployment on `devnet`

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#1317]
![image](https://user-images.githubusercontent.com/31689104/220613885-37d59d50-f7b4-4154-974e-3cf072f447d8.png)

I'm not able to reproduce this issue but it appears *randomly* after a successful deployment

**Comment by MohamedElmdary** [comment]
Couldn't reproduce this issue

**Comment by AhmedHanafy725** [comment]
try it again and if you couldn't reproduce it, please close it

**Comment by mohamedamer453** [comment]
After deploying multiple different solutions on different nodes i wasn't able to reproduce this issue, closing it for now but please reopen it if you found a way to reproduce it.
