### ISSUE TITLE
the migration button is not clear for the end users

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#1318]
see: https://github.com/threefoldtech/grid_weblets/issues/1293#issuecomment-1429256659

**Comment by A-Harby** [comment]
Verified on devnet.
A clarifying message have been added to the migration tab.
![image](https://user-images.githubusercontent.com/109473873/222952884-98253843-d020-4638-ba75-5884b1139174.png)
