### ISSUE TITLE
set the network as solution type on the contract in case the contract only has a network workload

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#1320]
this needs to be done first on the grid client ts first

**Comment by AhmedHanafy725** [comment]
done on grid client but still not released

**Comment by A-Harby** [comment]
Verified on Devnet,
![image](https://user-images.githubusercontent.com/109473873/230769401-48231fc9-7d15-42cf-9445-c7b038701943.png)
