### ISSUE TITLE
dev run with `yarn dev` is broken

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#1321]
After removing the hard-coded values here [8c66094](https://github.com/threefoldtech/grid_weblets/commit/8c66094b72924a4badaf287ee95e22c4388c5481) a running server with `webpack` will not work properly cause values are set in the playground app.

**Comment by khaledyoussef24** [comment]
verified 
![image](https://user-images.githubusercontent.com/110984055/223115806-dcef75bb-e4fd-403c-ab75-d912fe83cad1.png)
