### ISSUE TITLE
Can't delete my contracts or login to the account cause my balance is not enough

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1323]
### Description

Mainnet,v1.6.0.
I couldn't delete the contract in the grace period cause I don't have enough balance (which is the cause of making all of the contract goes to the grace period) giving the error like below, and after refreshing the page I couldn't get into the account again. 

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/220937825-49ed451b-3b5b-4399-8c47-f5cc5a7e7662.png)

![image](https://user-images.githubusercontent.com/109473873/220940275-f09eba5c-1d99-471f-9bc9-f45f8c4da4dd.png)

**Comment by xmonader** [comment]
I think that makes sense, because now you're in graceperiod too. @DylanVerstraete what do you suggest?

**Comment by DylanVerstraete** [comment]
Deposit TFT?
