### ISSUE TITLE
Deployed sollutions billing rate incorrectly assumes bills come in every hour

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/grid_weblets#1324]
### Search first

Search for similar issues first, if not complete the following template

### Description

When a solution is deployed, the billing rate incorrectly states that is is per hour, while it seems to be the value of the last bill, irrespective of how long it was since the previous bill

### Steps to reproduce

Checking graphql.test.grid.tf/graphql, with following query:

```graphql
query MyQuery {
  contractBillReports(orderBy: timestamp_DESC, where: {contractID_eq: "16914"}, limit: 10) {
    amountBilled
    contractID
    discountReceived
    timestamp
  }
}
```

In the output, notice the 3rd event has the exact value shown in the below screenshot for contract 16914

![image](https://user-images.githubusercontent.com/22023708/220964984-8e20cae7-4a50-4c59-8684-b40bf9db9609.png)

However, if you check the time since the previous payment (4th), it is clear that this payout is actually the result of 161 hours of accrued billing, therefore the _actual_ rate is closer to 0.15 TFT/hour

**Comment by AhmedHanafy725** [comment]
solved on https://github.com/threefoldtech/grid3_client_ts/pull/525 , it will reflect when releasing and updating the weblets

**Comment by s-areal** [comment]
I am facing the same issue on mainet. Also the contracts show different billing rates on contract lists and deployment list.

**Comment by khaledyoussef24** [comment]
fixed on devnet
![image](https://user-images.githubusercontent.com/110984055/222948501-036471a7-6dc2-4ff5-9bbd-21cabcf68719.png)

**Comment by khaledyoussef24** [comment]
live now on qanet
![image](https://user-images.githubusercontent.com/110984055/222965221-e2d545bf-0ac6-403e-a15e-931e45b98d10.png)![image](https://user-images.githubusercontent.com/110984055/223078790-00312315-f780-4d64-b49a-06462d952645.png)

**Comment by khaledyoussef24** [comment]
fixed on testnet now
was
![Screenshot from 2023-03-08 17-40-35](https://user-images.githubusercontent.com/110984055/223762029-8d6fa760-8767-4252-a383-c81ad2c08387.png)
now
![photo_2023-03-08_17-24-50](https://user-images.githubusercontent.com/110984055/223762091-e00fbbda-ff25-4e0d-988f-09a5287d1233.jpg)
