### ISSUE TITLE
Feature Request: Output Wiregaurd Config on Playground

### ISSUE THREAD

**Issue by Parkers145** [threefoldtech/grid_weblets#1326]
I would like to be able to output the configuration necessary to connect to a vm over Wiregaurd when deploying with the playground. 

My use case is this tutorial but without Terraform.
 
https://forum.threefold.io/t/how-to-deploying-umbrel-on-the-threefold-grid/3752

**Comment by mohamedamer453** [comment]
Verified on devnet.

Outputting wireguard config was added as a network option for vms in the weblets.

![image](https://user-images.githubusercontent.com/101194226/232305760-0c557841-8ce6-44de-96b3-6b491f94e375.png)

And the config output can be found in the deployment details after a successful deployment.

![image](https://user-images.githubusercontent.com/101194226/232305715-c60d8ca2-89e7-40ef-b788-54f503302fab.png)
