### ISSUE TITLE
sort out 1.7.0 milestone

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#1327]
The milestone seems to be unachievable with 81 open issues

![image](https://user-images.githubusercontent.com/64129/221395014-5940c504-4051-47cc-a477-7feb1a46663f.png)

**Comment by AhmedHanafy725** [comment]
should be matching the same number on 3.9 
![image](https://user-images.githubusercontent.com/41957921/221406866-6a5202d6-acdd-4ab7-ab50-8cc3f6f1f47c.png)
