### ISSUE TITLE
[profile manager] does not remember my account

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/grid_weblets#1332]
### Description
Profile manager is confusing. it's not clear what is the proper way to use:
- Why the button called migrate (migrate what to where) 
- Do I need to insert my mnemonic everytime i visit the weblets? If so why do I set a password?
  - Wouldn't it make sense once i add my account, i can only login with the password ?
- After i copy in my mnemonics:
  - it's not clear if I need to click close or migrate
![image](https://user-images.githubusercontent.com/10920323/221533692-c4426914-b17c-457b-a2b9-9c2d15c49967.png)
  - It does not ask for the password
- Because i am not sure if i need to click close or migrate, i then click migrate:
  - It then asks for the password
  - Then after it say it was successful, It still show a migrate button that is calling for action
  
![image](https://user-images.githubusercontent.com/10920323/221534202-191a0a1c-d2b8-4554-878a-e6e55032f21f.png)

  - If i click it again, it will do it again! (i assume i should have clicked close but again, it's not clear at all)
  
### Steps to reproduce
Check above

**Comment by AhmedHanafy725** [comment]
> Why the button called migrate (migrate what to where)

the migrate button is used to migrate your keys stored on the chain from being encrypted by a password(the old password used in the profile manager) to use the mnemonic as no longer the user will be asked to set a password for the profile manager

> Do I need to insert my mnemonic everytime i visit the weblets? If so why do I set a password?

yes. you will be asked for the password once in the migration flow to migrate the keys and then it shouldn't be used again

> Wouldn't it make sense once i add my account, i can only login with the password ?

this flow got removed and the only way to login is to set the mnemonic

**Comment by muhamadazmy** [comment]
Okay, in that case what you need to do instead is have the login (or profile manager) only show the mnemonic with a `login` button
with a tip that if u want to import something from older manager then u click here. But now it feels like the normal action to login is always migrate. it's the `highlighted` button with call to action.

**Comment by rkhamis** [comment]
let's make the text clearer

**Comment by zaelgohary** [comment]
Already done [here](https://github.com/threefoldtech/grid_weblets/commit/3823688751a458d9ba0f65707ddaf54454cda80c)

**Comment by A-Harby** [comment]
Verified on Devnet.
Message changed to `Got Old Deployments? Migrate Now!`
![image](https://user-images.githubusercontent.com/109473873/230385172-3f027287-1260-4bf4-bc4c-40d2c9571fed.png)
