### ISSUE TITLE
It's unclear what the difference is between a Full and a Micro Virtual Machine 

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/grid_weblets#1334]
### Description

I see there is a different list of VM Images but have no idea what the difference is.

**Comment by rkhamis** [comment]
DOCUMENTATION

**Comment by khaledyoussef24** [comment]
verified on devnet every solution has it's own documentation now
![Screenshot from 2023-04-05 11-50-16](https://user-images.githubusercontent.com/110984055/230046244-035c5261-3b35-4854-bc9f-0b1e3c5025dd.png)
![Screenshot from 2023-04-05 11-50-13](https://user-images.githubusercontent.com/110984055/230046265-68f2176e-4f86-45a3-9432-4f8ccabd7d09.png)
