### ISSUE TITLE
Inconsistent solution names

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#1336]
It is a little confusing the solution names some functions require it lowercase (`"peertube"`) others in uppercase (`"Peertube"`). it will be better if this unified in all the codebase
https://github.com/threefoldtech/grid_weblets/blob/70b29181a40aba2197132c9e3091aa0d6dd8f0c9/src/utils/deployPeertube.ts#L99-L100

Also, methods that takes solutionType as argument doesn't expect explicit type

here it accepts type as string.
https://github.com/threefoldtech/grid_weblets/blob/70b29181a40aba2197132c9e3091aa0d6dd8f0c9/src/utils/deleteDeployment.ts#L9

here it doesn't set type for type argument.
https://github.com/threefoldtech/grid_weblets/blob/70b29181a40aba2197132c9e3091aa0d6dd8f0c9/src/utils/prepareDeployment.ts#L17

**Comment by A-Harby** [comment]
Verified on Devnet.
All Peertube name changed to `Peertube` in the code and site.
