### ISSUE TITLE
Other solutions are displayed in the microvm deployment tables

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/grid_weblets#1339]
### Description

Tiaga deployments and Owncloud deployments are displayed in the microvm's deployment list.

### Steps to reproduce
1. Deploy an Owncloud/Tiaga instance
2. Navigate to the microvm weblet
3. Deployments will be shown in the deployments list

![MICROVM](https://user-images.githubusercontent.com/66883096/221879899-bd0ee63c-051c-4b40-ada1-252699a8b48d.png)

**Comment by robvanmieghem** [comment]
This also happens to a Full Virtual Machine I deployed on devnet ( grid_weblets version 49b74a5 ). It does not show up in the Full VM deployments but in the Micro VM deployments list. 
The metadata in the json details shows that is is indeed a full VM:
`metadata": "{\"type\":\"Fullvm\",\"name\":\"VM33360bba\",\"projectName\":\"Fullvm\"}", `

**Comment by mohamedamer453** [comment]
Verified on devnet weblets `bbfb99d`

The issue was fixed and the deployments now appear in its correct tab.

[Screencast from 28-03-23 12:13:05.webm](https://user-images.githubusercontent.com/101194226/228204861-62edc324-6264-481a-81d0-857b85b035ea.webm)
