### ISSUE TITLE
Balance error appears during account creation

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#1340]
I created an account using the new profile manager. Immediately after creation, I see this error:

![image](https://user-images.githubusercontent.com/109473873/220940275-f09eba5c-1d99-471f-9bc9-f45f8c4da4dd.png)

I can't enter my SSH key until I add TFT, which I don't understand.

Then I add TFT but the error doesn't clear on it's own. I had to copy the newly generated seed phrase and repaste it to proceed.

### Desired Experience

Let the user proceed with entering SSH key and close the profile window before TFT balance is detected. If they add TFT at this step, detect it and clear the error automatically.

Guide the user through the steps of account creation, funding, and SSH key generation without showing messages in red that look like errors :slightly_smiling_face:

**Comment by rkhamis** [comment]
Unfortunately, there's no clean way to do this.
Instead, let's at least show a clear message saying "please  fund your wallet then refresh"

**Comment by A-Harby** [comment]
Verified on Devnet.
Message is changed to `Please fund your wallet then refresh.` to give more clear steps.
![image](https://user-images.githubusercontent.com/109473873/230384578-835eeb4e-2961-4e85-a80a-ce53984459e7.png)
