### ISSUE TITLE
Validating SSH key takes way too long

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#1341]
When I add a public SSH key to my profile, it does some validation and there's a spinning circle inside the blue `Generate SSH Keys` button. This takes about 20 seconds, which seems way too long.

**Comment by rkhamis** [comment]
It really shouldn't take more than 6/7 seconds. will check

**Comment by MohamedElmdary** [comment]
@rkhamis Validation doesn't take a second but storing into kvstore takes long time
