### ISSUE TITLE
Text improvement

### ISSUE THREAD

**Issue by robvanmieghem** [threefoldtech/grid_weblets#1343]
### Description
Version v1.6.0-rc1

![Screenshot 2023-03-01 at 05 48 41](https://user-images.githubusercontent.com/3511318/222052709-130e1b79-728b-4db5-aaea-a8ff68c5549f.png)

"warning" ( especially in bold and with an exclamation mark) looks pretty bad while this is a normal thing to happen.
The description can also be improved.
I would just state "Another action Deleting Deployment VMxxxx is in progress".
So I would 
- drop " warning!"
- replace deployment with action
- drop "of type"
- drop " with name"
- replace "in-progress" with "in progress"

**Comment by A-Harby** [comment]
Verified.
![image](https://user-images.githubusercontent.com/109473873/224538333-1080a635-99a6-4e53-a450-82bb1625d732.png)
![image](https://user-images.githubusercontent.com/109473873/224538435-7a37413b-c764-49e7-946f-51ce4a2f0882.png)
