### ISSUE TITLE
Error on initial loading

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#1345]
![image](https://user-images.githubusercontent.com/31689104/222143230-fdfc2cb3-c6f1-42b0-9ab8-ba1d7edb7faa.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The issue was fixed and the mentioned error doesn't appear anymore.

[Untitled_ Mar 19, 2023 2_10 PM.webm](https://user-images.githubusercontent.com/101194226/226174303-f1a1ed19-1374-4f61-8d3e-4157985ef0e3.webm)
