### ISSUE TITLE
umbrel domain is missing from deployment page 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#1346]
### Search first

Search for similar issues first, if not complete the following template

### Description

umbrel domain is missing from deployment page info
![Screenshot from 2023-03-06 10-11-36](https://user-images.githubusercontent.com/110984055/223059449-a976af62-0abc-498d-b8db-5f5cb1af7758.png)

and the deployment details actions  shows control panel instead of visit and ui of webpage if it is used to visit domain
![image](https://user-images.githubusercontent.com/110984055/223059553-b7a70cab-ffe5-442c-b539-3f38ad813199.png)
like this in other solutions
![image](https://user-images.githubusercontent.com/110984055/223059869-245008e7-c1e2-453f-b5db-c335db9f5e1c.png)

### Steps to reproduce

1. go to playground
2. insert your credentials
3. go to umbrel
4. make a deployment
5. wait for the deployment info page to appear
![Screenshot from 2023-03-06 10-11-36](https://user-images.githubusercontent.com/110984055/223060205-0c90d5f0-13a2-4bb9-9e29-acb612053e97.png)

**Comment by rkhamis** [comment]
We should show the public IP, not the domain here.

**Comment by 0oM4R** [comment]
> We should show the public IP, not the domain here.

the public IP is optional,
- if the deployment has public IP :
  ![image](https://user-images.githubusercontent.com/62248851/229520813-d447c092-0e4d-424f-86ee-9657e911226e.png)
- if there is no public IP the Planetary Network IP is there to,
  ![image](https://user-images.githubusercontent.com/62248851/229521447-0f892c1d-71a0-4fc1-bab9-3781575a1350.png)

**Comment by 0oM4R** [comment]
>![image](https://user-images.githubusercontent.com/62248851/229522425-fa411e1e-8274-4c87-9f22-ef292b92c6dc.png)

@khaledyoussef24 actually I made this because the umbrel page is only a dashboard for the user to control the machine, I think the appropriate usage here is the Admin panel, the visit is if we have hosted website or something, let me know what you think
