### ISSUE TITLE
Building FarmingCalculator is no longer working as expected

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#1347]

**Comment by MohamedElmdary** [comment]
Built using vite and moved farmingCalc into it's own repo
https://github.com/threefoldtech/tf-farming-calculator

**Comment by rkhamis** [comment]
@MohamedElmdary what's the status here? Where's the PR?

**Comment by xmonader** [comment]
project got replaced into a separate one here https://github.com/threefoldtech/tf-farming-calculator
