### ISSUE TITLE
Profile Manager Displays an error message before validating the mnemonics

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1348]
### Description

The Mnemonics field displays an error mentioning that the mnemonics is required before validating it and loading the twin info.

![TF Playground](https://user-images.githubusercontent.com/101194226/223097892-043bdebe-2154-4182-be84-1b614286e375.gif)

### Steps to reproduce

- Navigate to play.dev.grid.tf
- Open the profile manager.
- Enter your Mnemonics.

**Comment by mohamedamer453** [comment]
Same issue happens while creating a new account.

![TF Playground (3)](https://user-images.githubusercontent.com/101194226/223761669-3093e7ac-3168-4473-a264-195a034397e1.gif)

**Comment by A-Harby** [comment]
Verified on Devnet,
loading label was added to indicate validating process
![image](https://user-images.githubusercontent.com/109473873/230394586-5899eb9c-cd7e-4075-ac3d-43e04198de42.png)
