### ISSUE TITLE
Profile Manager: Update the placeholder of the Public SSH Key

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1349]
### Description

The Placeholder of the Public SSH Key needs to be updated instead of displaying `Textarea`.

![image](https://user-images.githubusercontent.com/101194226/223099369-744d1254-455f-48d8-a4a6-ec27a7bb7099.png)

### Steps to reproduce

- Navigate to play.dev.grid.tf
- Open the profile manager.

**Comment by A-Harby** [comment]
Verified on Devnet, e698b0b.
![image](https://user-images.githubusercontent.com/109473873/230383621-8a045185-8878-4505-be84-c7bcc1e81a28.png)
