### ISSUE TITLE
Allow user to set cpu, memory and disk size for peertube deployments

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#135]
Blocked on #96, as it's done with three separate deployments for now. Also, make the defaults a bit higher e.g. 4 CPUs, 16GB memory, 200GB disk (these values can be discussed here).

**Comment by abom** [comment]
Check [_Should I have a big server for PeerTube_](https://joinpeertube.org/faq#should-i-have-a-big-server-to-run-peertube) as a guide for default values.

**Comment by abom** [comment]
as @xmonader suggested, Let's keep it 2 cores and 2GB ram as defaults and the user can increase them if needed

> 
> As a real life example, the PeerTube demonstration server https://peertube.cpy.re runs on 2 vCores and 2GB of RAM. Average consumption is:
> 
> CPU: nginx ~ 2%, peertube ~ 10%, postgres ~ 1%, redis ~ 1%
> RAM: nginx ~ 1MB, peertube ~ 150MB, postgres ~ 30MB, redis ~ 20MB
> Network: ~200GB sent per month (https://framatube.org: ~1.5TB sent per month)

**Comment by sameh-farouk** [comment]
not able to verify this issue
> as @xmonader suggested, Let's keep it 2 cores and 2GB ram as defaults and **the user can increase them if needed**

no options were given to the user in the UI to allow such customization mentioned above.

![Screenshot from 2021-12-21 21-49-37](https://user-images.githubusercontent.com/42457449/146989431-1b589ac9-6740-4288-9690-475af5b3c6b5.png)

**Comment by abom** [comment]
@sameh-farouk Thank you,  you didn't find it because it's not deployed yet as #312 is still in review.

**Comment by sameh-farouk** [comment]
Verifying this.

**Comment by sameh-farouk** [comment]
verified on play.dev.grid.tf

![Screenshot from 2021-12-22 18-47-11](https://user-images.githubusercontent.com/42457449/147126885-3d2f4fb5-390c-405b-b063-9f88f9b2dca5.png)
