### ISSUE TITLE
There is no way to return to the profile manager after clicking on the `Migrate` Button

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1350]
### Description

Currently there is no way to return to the Profile Manager if you click on the `Migrate` button and you will have to reload the whole page to be able to access the profile manager again. 

a `Back` button should be added or if you close or click outside the window and open the profile manager again it shouldn't redirect you to the migration page again.

![TF Playground (1)](https://user-images.githubusercontent.com/101194226/223101877-256d7ab6-bb16-4976-82ad-f9887ed2de3d.gif)

### Steps to reproduce

- Navigate to play.dev.grid.tf
- Click on the profile manager.
- Enter your Mnemonics.
- Click on Migrate.
- Close the profile manager and open it again.

**Comment by A-Harby** [comment]
Verified on Devnet.
`Back to profile` button was added.
![image](https://user-images.githubusercontent.com/109473873/228591371-81352d16-5600-4847-9125-cb5e3174cb45.png)
