### ISSUE TITLE
Deployment tab selects the second option by default

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1351]
### Description

The deployment list selects the `Micro Virtual Machine` tab when you open it even though it's the second option in the list and the `Full Virtual Machine` is the first option.

![TF Playground (2)](https://user-images.githubusercontent.com/101194226/223104586-28126075-f80e-47b5-8f50-8f4e55c246e0.gif)

### Steps to reproduce

- Navigate to play.dev.grid.tf
- Open the profile manager.
- Enter your mnemonics.
- Navigate to the Deployments tab from the sidebar.

**Comment by A-Harby** [comment]
Verified on Devnet,
![image](https://user-images.githubusercontent.com/109473873/230769349-84b6bd00-f623-440e-815f-1b3aa79e0041.png)
