### ISSUE TITLE
An error appears in the console when you open play.dev.grid.tf

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1353]
### Description

An error appears in the console when you open play.dev.grid.tf before performing anything.

[Untitled_ Mar 6, 2023 3_07 PM (1).webm](https://user-images.githubusercontent.com/101194226/223120041-4ba4cccc-db22-4900-83b1-2316b824b221.webm)

### Steps to reproduce

- Navigate to play.dev.grid.tf

### Logs/Alerts

```
Uncaught (in promise) TypeError: Cannot destructure property 'mnemonics' of 'e' as it is null.
    at ae (deployedlist.wc.js:1:5842)
    at deployedlist.wc.js:8:187733
    at t (deployedlist.wc.js:1:61)
    at Array.map (<anonymous>)
    at j.connectedCallback (deployedlist.wc.js:8:194)
    at customElements.define (base.wc.js:1:8280)
    at deployedlist.wc.js:8:194666
    at deployedlist.wc.js:8:195144
```

**Comment by khaledyoussef24** [comment]
still facing the same problem on qanet 
![image_2023-03-15_12-27-06](https://user-images.githubusercontent.com/110984055/225282328-86ad86a3-9a79-42a6-bc53-06979baec7b6.png)

**Comment by mohamedamer453** [comment]
verified in https://github.com/threefoldtech/grid_weblets/issues/1345#issuecomment-1475233356
