### ISSUE TITLE
Profile Manager: Typo in the migration error message

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1355]
### Description

There is a typo in the error message for the migration. 

![image](https://user-images.githubusercontent.com/101194226/224018369-7b603d37-3504-4e3a-be08-4e04bb1c310a.png)

`Failed to migrated ` -> `Failed to migrate `

**Comment by A-Harby** [comment]
Verified on Devnet, https://github.com/threefoldtech/grid_weblets/commit/7259306c40068e99c708caedb8737621f921fd9d.
![image](https://user-images.githubusercontent.com/109473873/230379324-0f0a612f-a6a9-45a8-b65b-5ade24293112.png)
