### ISSUE TITLE
Profile Manager: Add a clear indication that the account is loading after reloading the page

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1357]
### Description

A clear indication that the profile manager is loading your account needs to be added after reloading the page.

[TF Playground (4).webm](https://user-images.githubusercontent.com/101194226/224030452-39bdf8dc-d5d8-486f-81b2-98404cc30020.webm)

### Steps to reproduce

- Navigate to play.dev.grid.tf
- Open the profile manager and wait for it to load then close the profile manager.
- Reload the page.

**Comment by A-Harby** [comment]
Verified on Devnet,
![image](https://user-images.githubusercontent.com/109473873/230396096-670e6142-d33a-45f3-a468-88e3b2450389.png)
