### ISSUE TITLE
Capacity Filter: `Node ID` field improvement 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1359]
### Description

The `Node ID` field in the capacity filter doesn't have a placeholder and it has a drop down list that doesn't do anything unless you click on `Apply Filters and Suggest Nodes`

[Untitled_ Mar 9, 2023 4_06 PM.webm](https://user-images.githubusercontent.com/101194226/224051202-d4ce5099-9ff5-41b4-85f9-04a67227f788.webm)

### Steps to reproduce

- Navigate to play.dev.grid.tf
- Load your account and select any weblet.
- Select the `Capacity Filter` option.

**Comment by ramezsaeed** [comment]
This is a known issue, cannot be changed right now.
