### ISSUE TITLE
Can't create new account from profile manager

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1366]
### Description

Devnet, 9babcbe.
Can't create new account from profile manager these errors are shown int the console and button keeps loading forever.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/224955769-4162bb1f-d75b-49aa-bd82-d6ace0f4abf9.png)

**Comment by Mahmoud-Emad** [comment]
This error appears once you open the profile manager not when you create a new account, so I assume its a bug inside the profile manager itself.

**Comment by A-Harby** [comment]
No, Second error is occurring when you press the create account button. 
[Untitled_ Mar 19, 2023 12_31 PM.webm](https://user-images.githubusercontent.com/109473873/226169520-0713ed36-b8ec-47e1-a710-57a0b5b03bea.webm)

**Comment by Mahmoud-Emad** [comment]
both of them should be fixed in https://github.com/threefoldtech/grid_weblets/pull/1377

**Comment by A-Harby** [comment]
Verified, Devnet 0995c41.
Both warning are removed and create account is fixed.
![image](https://user-images.githubusercontent.com/109473873/226173194-4d5009f5-1257-47f4-b408-90706b187bc9.png)
