### ISSUE TITLE
QA-net: Full VM is listed under Micro VM

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_weblets#1370]
### Description
After deploying a full vm, it's listed under 'Micro Virtual Machine'
![image](https://user-images.githubusercontent.com/88312671/225064380-a37dfc58-d30a-457c-947f-4beb9d8ae49e.png)
![image](https://user-images.githubusercontent.com/88312671/225064452-266258a7-287b-40bf-8290-bf6776b9c78a.png)
![image](https://user-images.githubusercontent.com/88312671/225065044-a7f095a7-ba52-4099-90c4-60b6486c7e62.png)

### Steps to reproduce

Deploy a Full Virtual Machine
Try to list it under Full Virtual Machine
List workloads under Micro Virtual Machine

**Comment by A-Harby** [comment]
Yes this issue was found and reported before on devnet https://github.com/threefoldtech/grid_weblets/issues/1339.

**Comment by ramezsaeed** [comment]
please verify on a new created solutions, as the old created ones cannot be changed.

**Comment by coesensbert** [comment]
qa-net: seems to work fine indeed for new vm's on v1.7.0-qa4

**Comment by mohamedamer453** [comment]
Verified in https://github.com/threefoldtech/grid_weblets/issues/1339#issuecomment-1486600650
