### ISSUE TITLE
The manual filter in the Kubernetes weblet doesn't work and breaks the whole weblet in some cases

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1371]
### Description

The manual filter in the Kubernetes weblet doesn't work and breaks the whole weblet if you select the capacity filter and then the manual filter again. and the issue doesn't get fixed until the page is reloaded.

[Untitled_ Mar 15, 2023 2_16 PM.webm](https://user-images.githubusercontent.com/101194226/225307224-0266a854-1ebc-41e6-bb79-d748740d54e6.webm)

```
kubernetes.wc.js:8 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'p')
    at Object.p (kubernetes.wc.js:8:100130)
    at z (kubernetes.wc.js:1:2581)
    at B (kubernetes.wc.js:1:2269)
    at it (kubernetes.wc.js:1:4902)
    at new er (kubernetes.wc.js:8:66429)
    at Array.ti (kubernetes.wc.js:8:88204)
    at Object.p (kubernetes.wc.js:8:100215)
    at z (kubernetes.wc.js:1:2581)
    at B (kubernetes.wc.js:1:2269)

```

### Steps to reproduce

- Navigate to play.qa.grid.tf
- Load your account and select the `Kubernetes` tab.
- Switch to the master tab and select the manual filter.
- Enter the id of any valid node. (notice that it will try to validate the node but then the message will disappear).
- Switch to the capacity filter (notice how the node id is displayed as `undefined` )
- Switch to the manual filter again.
- Try to switch to the worker tab or any other tab.
- Navigate to any other weblet then return to the `Kubernetes` weblet.

**Comment by A-Harby** [comment]
Master Manual capacity filter is fixed and works fine.
![image](https://user-images.githubusercontent.com/109473873/230381209-fa048bd4-dfde-4246-aa9d-2d34759fc2f4.png)

But worker is removed.
![image](https://user-images.githubusercontent.com/109473873/230381376-721ba5a2-3819-40a4-90ef-f65ea9846f41.png)
![image](https://user-images.githubusercontent.com/109473873/230381448-934e94f5-ea5e-46f8-987c-8c8f4c577ca4.png)

**Comment by A-Harby** [comment]
Verified on Devnet,
Worker is also fixed as master/
![image](https://user-images.githubusercontent.com/109473873/230769683-8736fde0-2df3-4972-86a3-3dcac11f9a14.png)
