### ISSUE TITLE
Remove old/hidden weblets from the `Deployment List`.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1376]
### Description

Remove old/hidden weblets from the `Deployment List`. `Mastodon` and `QSFS Virtual Machine` are still available in the deployment list while their weblets are hidden/removed.

![image](https://user-images.githubusercontent.com/101194226/225371697-5ac3c47d-5e41-4989-bf3f-c3e4b2eb29a9.png)

### Steps to reproduce
- Navigate to https://play.dev.grid.tf/
- Load your account and click on `Deployments`

**Comment by 0oM4R** [comment]
@AhmedHanafy725  Do you think it should be commented or totally removed?

**Comment by AhmedHanafy725** [comment]
> @AhmedHanafy725 Do you think it should be commented or totally removed?

commented

**Comment by mohamedamer453** [comment]
Verified on devnet.

The deployment list was updated and the mentioned weblets were removed.

![image](https://user-images.githubusercontent.com/101194226/228198216-9fb60f36-7f03-4b2a-8654-03cd6cfe861e.png)
