### ISSUE TITLE
In the Caprover weblet we suggest/generate a weak Caprover password and should increase its characters domain.

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#138]
we should use **alphanumeric characters** (62+ char) for the Caprover password suggestion instead of the **hexadecimal digits** (16 char) currently used in the Caprover weblet.

![Screenshot from 2021-12-07 18-16-17](https://user-images.githubusercontent.com/42457449/145065942-c0c6ce48-6466-4dae-89d4-1e01474b26cb.png)

for an 8 char long password, by only using lower case {abcdef} and numeric chars {0123456789} then the attacker only has to try 16^8 but if you use both upper, lower case letters and numeric chars then the search space becomes 62^8, if special chars are allowed then the search domain for the brute force or other password attacks get increased which makes such passwords computationally secure.

**Comment by waleedhammam** [comment]
verified
