### ISSUE TITLE
Successful deployment message in peertube is `Successfully Deployed Wordpress.`

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1382]
### Description

After deploying a Peertube Instance the successful deployment message was saying that Wordpress was deployed successfully not the Peertube `Successfully Deployed Wordpress.`.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/226595314-b55b16d6-d486-472b-9931-8d782d3b37ed.png)

**Comment by A-Harby** [comment]
Issue is occurring in most of the other deployment also.
![image](https://user-images.githubusercontent.com/109473873/226601470-43b9f31c-2504-4c17-9285-21644e64daea.png)

**Comment by Mahmoud-Emad** [comment]
Should be fixed in https://github.com/threefoldtech/grid_weblets/pull/1384

**Comment by A-Harby** [comment]
Verified.
![image](https://user-images.githubusercontent.com/109473873/226621713-bef342fb-2be5-40e2-a44c-039fdf996596.png)
