### ISSUE TITLE
deleting deployments not deleting the gw contracts

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/grid_weblets#1383]
### Description

deleting solutions that have gw not deleting gw contract,
I tried it on `subsquid` and `wordpress` and it happens on both.
![image](https://user-images.githubusercontent.com/62248851/226598665-629b704f-36e4-4583-9f2a-e003f9f332a5.png)

### Steps to reproduce

- open play.dev.grid.tf
- deploy a solution with a gateway, in my case `subsquid` and `wordpress` 
- delete the deployment 
- navigate to contracts list 
- you should find two contracts related to the deleted deployment

**Comment by A-Harby** [comment]
Verified on Devnet, d6fc918.
Deployed a wordpress instance.
![image](https://user-images.githubusercontent.com/109473873/226959075-994b5e34-c394-4bdf-81c5-8d74973f2311.png)
And checked contract list to make sure that there's a contract for the gateway.
![image](https://user-images.githubusercontent.com/109473873/226959194-a78dbd0f-9396-4fae-849d-68713c626a01.png)
And delete only the contract from wordpress deployment table.
![image](https://user-images.githubusercontent.com/109473873/226959137-0fe234d1-1145-4d5b-b431-29ad6d2e7e67.png)
And All the contract belong to it was successfully delete including gateway. 
![image](https://user-images.githubusercontent.com/109473873/226960278-79014794-b11b-413e-b535-eb0e68824c58.png)

**Comment by mohamedamer453** [comment]
Verified also from a Peertube and an ownCloud deployment and both were deleted successfully with no contracts remaining from both deployments.

![image](https://user-images.githubusercontent.com/101194226/226965595-e77885e4-de77-4741-9bda-4adc4569afdd.png)
