### ISSUE TITLE
action section dose not appears on wordpress

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/grid_weblets#1385]
### Description
![image](https://user-images.githubusercontent.com/62248851/226623071-caed07b0-8627-4993-9b5f-4f97ed031a16.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The actions section was added to wordpress. the first icon displays the deployment data, second on redirects the user to the instance and the third redirects the user to the admin panel

![image](https://user-images.githubusercontent.com/101194226/228199544-10fb86d4-f119-4668-8951-a0363e1d2586.png)
