### ISSUE TITLE
Got an error while deploying CapRover weblet: TypeError: Cannot read properties of undefined(reading 'machines')

### ISSUE THREAD

**Issue by shng4you** [threefoldtech/grid_weblets#1389]
Description
While deploying, the capRover got an error TypeError: Cannot read properties of undefined(reading 'machines')
Network: Mainnet
Version: 1.6.1
![CapRover error](https://user-images.githubusercontent.com/95933607/226874433-31ed36b3-1922-4525-8322-3a1e5c2b488c.jpg)

### Steps to reproduce
But once I reloaded the page, It showed the deployment CapRover list.

https://user-images.githubusercontent.com/95933607/226874755-3a0a1cc4-f9e2-4d57-ad7a-c4ea7a2874c2.mp4

**Comment by khaledyoussef24** [comment]
this issue exist and reproachable on testnet

**steps to produce:**

1. go to playground
2. go to caprover tab
3. deploay a caprover
4. details of the deployment will be shown but empty and error `TypeError: Cannot read properties of undefined (reading 'env')`
5. ![Screenshot from 2023-03-26 12-50-04](https://user-images.githubusercontent.com/110984055/227771037-998aca68-6b1b-4163-bbb2-af0702cb11d2.png)

![Screenshot from 2023-03-26 12-45-51](https://user-images.githubusercontent.com/110984055/227771038-956f08e3-5ed0-4956-ab71-fcdfa53f397f.png)
 
![Screenshot from 2023-03-26 12-46-00](https://user-images.githubusercontent.com/110984055/227771040-5c7cf24a-35c6-4755-8774-3e0e911ecd06.png)

**Comment by khaledyoussef24** [comment]
TypeError is not reproducable but caprover is broken

![Image](https://user-images.githubusercontent.com/110984055/229759450-6ad28ccb-977a-4b95-949b-03c674973d84.png)
![Image](https://user-images.githubusercontent.com/110984055/229759451-cfb3d2e3-9510-4050-8fbf-59dad4219655.png)

**Comment by khaledyoussef24** [comment]
verified on devnet works fine now

![image](https://user-images.githubusercontent.com/110984055/229785802-bcffe8e9-38df-4981-8c1c-a72230fda1df.png)

![image](https://user-images.githubusercontent.com/110984055/229785500-b3102dfe-25c4-49d6-962a-c08e6b3189aa.png)
