### ISSUE TITLE
Funkwhale deployment fails

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/grid_weblets#139]
![Screenshot from 2021-12-08 11-13-52](https://user-images.githubusercontent.com/17128393/145182095-2b03b51b-fd14-4b30-a741-5333bee39102.png)

network: devnet
node to deploy on: 5
![Screenshot from 2021-12-08 11-22-13](https://user-images.githubusercontent.com/17128393/145182804-eedd68c6-eb4f-4dd5-a101-2f7dfdcecbb1.png)

**Comment by asamirr** [comment]
Currently both play.grid.tf and play.dev.grid.tf are being to solve this issue

**Comment by waleedhammam** [comment]
![Screenshot from 2021-12-14 16-41-47](https://user-images.githubusercontent.com/10658229/146019807-0253f648-d049-4352-90b4-04c9f06902b8.png)

verified
