### ISSUE TITLE
capacity filer suggesting nodes with no free public IPs

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1392]
### Description

Devnet, d217ae7.

After filling out all the inputs in the Caprover and applying the capacity filer.
![image](https://user-images.githubusercontent.com/109473873/226950409-b8a0472b-357a-45bd-adf6-3114af3dbf20.png)
I got this error telling me that Farm hasn't enough free public IPs but it was suggested by filter.
![image](https://user-images.githubusercontent.com/109473873/226949929-d5a0b1cb-3162-4d8d-8ecc-07510d75fccb.png)

**Comment by rkhamis** [comment]
should be fixed by https://github.com/threefoldtech/tfchain_graphql/issues/102

**Comment by A-Harby** [comment]
Verified on Devnet, b4b84b3.
Deployed multiple instance and issue wasn't reproducible.
re-opining if it occurred again.
