### ISSUE TITLE
"undefined" error when deploying on mainnet

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#1398]
Multiple users have reported error `undefined` blocking their deployments on mainnet. It does not happen consistently, so don't have steps to reproduce. Here's an example with console output:

![image](https://user-images.githubusercontent.com/17682591/227403224-c477b06e-a17d-452d-bb34-056e59278c69.png)

**Comment by sameh-farouk** [comment]
**reproduced on devnet:**

![Screenshot from 2023-03-28 10-43-08](https://user-images.githubusercontent.com/42457449/228184434-f01ff0ec-3d9e-4e92-92ed-8b02522f6adc.png)

![Screenshot from 2023-03-28 10-40-29](https://user-images.githubusercontent.com/42457449/228184551-d67d0407-5e12-4406-97f9-55eedc00c3fa.png)


I toggled IPV4 off and the deployment went fine.

**Comment by A-Harby** [comment]
Verified on Devnet,
Tried to deploy different solutions and error wasn't shown in any of them.
