### ISSUE TITLE
Funkwhale validation check doesn't show the error message

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/grid_weblets#140]
When using invalid characters for the name, the deploy button is disabled but it doesn't mention that the issue was because of that. An error message should be shown upon validation to indicate that the button was disabled because of the invalid characters of the name(or any other reason for different validation scenarios)

![Screenshot from 2021-12-08 11-32-41](https://user-images.githubusercontent.com/17128393/145184675-4290ba10-96ad-4404-a1fe-4abef4489e7d.png)

**Comment by rkhamis** [comment]
not only in funkwhale. should be fixed everywhere

**Comment by MohamedElmdary** [comment]
Added validation to name field
### PR
https://github.com/threefoldtech/grid_weblets/pull/150

**Comment by ranatrk** [comment]
verified
![Screenshot from 2021-12-12 11-45-36](https://user-images.githubusercontent.com/17128393/145707941-bde6bf2f-7b0e-4700-98da-15a0c1a34c14.png)
