### ISSUE TITLE
Can't create new twin `Request failed with status code 500`

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1400]
### Description

Dashboard Testnet v1.7.0-rc1.
Can't create new twin `Request failed with status code 500`.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/227783435-84561ace-b135-4e98-acaf-aa0f2371b62b.png)
[Untitled_ Mar 26 2023 4_43 PM.webm](https://user-images.githubusercontent.com/109473873/227783480-dcf39a44-baf0-4105-b68e-03a357f3a706.webm)

**Comment by khaledyoussef24** [comment]
verified on devnet
works fine now
![Screenshot from 2023-04-03 10-57-55](https://user-images.githubusercontent.com/110984055/229462490-0a71c231-8dbb-4289-8eb0-ea5220598fae.png)
