### ISSUE TITLE
Playground Adjust Delete All Button

### ISSUE THREAD

**Issue by mik-tf** [threefoldtech/grid_weblets#1401]
# Playground Delete All Button, add safety parameter

## Issue

A user deleted all their workloads by accident with the delete all button on the Threefold Playground.

## Solution

Deleting the button might be too drastic. Can we add the function that ask the user to write something to confirm deletion of ALL deployments, like Github has with deleting a repository?

Note: Not sure it's the proper sub-repository.

**Comment by A-Harby** [comment]
Verified on Devnet, https://github.com/threefoldtech/grid_weblets/commit/7259306c40068e99c708caedb8737621f921fd9d.
Delete ALL button was removed from weblets.
![image](https://user-images.githubusercontent.com/109473873/230380671-5721809c-f468-42cc-872f-7b9ea814be3d.png)

Deleting all can now be done by selecting all contract and delete them.
