### ISSUE TITLE
Can't deploy a VM with IPV6

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1408]
### Description

Testnet, v1.7.0-rc1

Whenever I check in the IPV6 option in the deployment, it fails with `undefined` error.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/227963597-2ed85acb-a4d2-4644-b1c0-13c9409141e6.png)

![image](https://user-images.githubusercontent.com/109473873/227961553-ca759a5a-ee6a-429c-80ce-5ba01a1882f7.png)

**Comment by khaledyoussef24** [comment]
fixed and working fine on devnet
![Screenshot from 2023-03-29 11-06-19](https://user-images.githubusercontent.com/110984055/228488587-9a155fb3-e093-49ac-a2db-4b91d26015f4.png)

![image](https://user-images.githubusercontent.com/110984055/228488555-a4b7feb9-6b0f-462e-bfa8-aa93b589d470.png)
