### ISSUE TITLE
No direct link to domain of deployment

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/grid_weblets#141]
- After deployment the domain is shown as text, should be clickable
![Screenshot from 2021-12-08 11-56-41](https://user-images.githubusercontent.com/17128393/145190028-73ba75f1-a92a-4737-9b0f-b8f7d116ba84.png)
- In listing deployments, a link to the domain can be available to open a new tab with the domain of the deployment

**Comment by MohamedElmdary** [comment]
### Fixed
Added anchor tag between link and added target=`"_blank"`
![image](https://user-images.githubusercontent.com/31689104/145351553-5588522c-2cf8-4350-a0ed-5bb7adf981b6.png)

**Comment by waleedhammam** [comment]
![Screenshot from 2021-12-14 16-41-47](https://user-images.githubusercontent.com/10658229/146019858-a43dc5da-31a0-40ac-b963-396e9381944c.png)

verified
