### ISSUE TITLE
Deployment details and JSON aren't displeayed after deploying a CapRover 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1411]
### Description

After deploying a CapRover, deployment info isn't shown. 

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/227976890-0225b415-9473-44a2-bd4b-5b14d8c76a44.png)

![image](https://user-images.githubusercontent.com/109473873/227977637-8c6cceb4-b951-4f0d-a6e7-1e7d26610916.png)

![image](https://user-images.githubusercontent.com/109473873/227975134-815c6783-99ff-402e-b9b8-455f53798b2e.png)

**Comment by khaledyoussef24** [comment]
verified and tested
![Screenshot from 2023-04-02 13-02-58](https://user-images.githubusercontent.com/110984055/229349181-75708283-4636-49ea-a271-acca91a1fc26.png)
