### ISSUE TITLE
No trailing/leading white spaces trim in SSH key field profile manager

### ISSUE THREAD

**Issue by amiraabouhadid** [threefoldtech/grid_weblets#1415]
### Search first

Search for similar issues first, if not complete the following template

### Description

The profile manager does not accept locally created ssh key if it has leading or trailing white space

### Steps to reproduce

1. create ssh key using key-gen
2. copy local ssh key from ~/.shh/id_rsa.pub
3. enter a white space followed by the ssh key with trailing white spaces too

### Logs/Alerts

Logs/Alerts if available

**Comment by A-Harby** [comment]
Verified on Devnet, 7259306.
Added SSH key with white in the beginning and the end, key was accepted and spaces were removed
