### ISSUE TITLE
change favicon

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#142]

**Comment by MohamedElmdary** [comment]
Can you provide the required favicon ?

**Comment by rkhamis** [comment]
@ehab-hassan @samaradel can either of you suggest a favicon?

**Comment by ehab-hassan** [comment]
While we don't have logo let's use same favicon for threefold.

**Comment by MohamedElmdary** [comment]
### PR
https://github.com/threefoldtech/grid_weblets/pull/151

**Comment by ranatrk** [comment]
verified
![Screenshot from 2021-12-12 15-16-43](https://user-images.githubusercontent.com/17128393/145713925-87137928-dfdd-4f0c-9087-c3ccafa1b3b9.png)

**Comment by waleedhammam** [comment]
verified at play.dev.grid.tf and play.grid.tf
![image](https://user-images.githubusercontent.com/10658229/145802590-be9ec18a-23ce-4151-9719-6b30ccb95600.png)
