### ISSUE TITLE
Feature request: Add Contract Details for `Rent` & `Name` Contracts.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#1421]
### Description

Add Contract Details for Rent & Name Contracts.

Currently both types of contracts don't have `Contract Details`

![image](https://user-images.githubusercontent.com/101194226/229346731-63a3d65f-f6be-48fd-a170-5fe24dbceffa.png)

**Comment by ramezsaeed** [comment]
won't fix
