### ISSUE TITLE
Capacity Filter: the sru is not updated if cpu, or memory value changed

### ISSUE THREAD

**Issue by 0oM4R** [threefoldtech/grid_weblets#1428]
### Description

if you change the value of disk the filters will be updated normally to 504+10
![Screenshot from 2023-04-03 16-40-31](https://user-images.githubusercontent.com/62248851/229544361-6e8d9192-28b7-41d8-9a7b-afd6af7fcc7f.png)
but now if we change any other field the value of the disk will be reverted back to 50+10
![Screenshot from 2023-04-03 16-41-05](https://user-images.githubusercontent.com/62248851/229544812-50a95583-ca02-44f9-8849-cec8ad1b8826.png)

### Steps to reproduce

- open any weblet that has custom Solution Flavor, for example, umbrel
- select a custom flavor
- enter in disk 5000, or any huge value, to make the result no node available
- increment CPU field by one will make some nodes appears 

### Logs/Alerts

Logs/Alerts if available

**Comment by A-Harby** [comment]
Verified on Devnet,
![image](https://user-images.githubusercontent.com/109473873/230769524-50bb21a2-f0d6-49e5-925f-5ec8a1ba36fd.png)
