### ISSUE TITLE
Make Profile Manager flow less confusing

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#143]
We need to update the browser session secret flow, maybe guide the user to either "enter the previously set secret" or "create a new store secret" in two different windows e.g. like a wizard or something.

Quoting some testers questions (from testers group):

> .....I've put in a ten word secret but I'm still getting the password incorrect response, as if I'm supposed to be using a password (note, if you mean secret the error message should say Incorrect Secret, not password).

> The "browser session secret" - does this only last as long as my browser session?
> 
> The docs say that I should "Fill in the secret you want to use to remember your profile information (do not forget please)"
> 
> But when I type in something that I've made up, it says Password incorrect.

**Comment by abom** [comment]
I also suggest we use the same session secret for kvstore (tfchain configuration secret), because it's confusing too to have 3 different password like inputs of "session secret", "mnemonics" and "tfchain configuration secret"

**Comment by MElborolossy** [comment]
- yes, it is confusing, I try it and found it not easy to understand what to do?
If it is hard to change the flow or we can't detect if there is an old store, we can add a message like `If it is the first time, please enter your password and create a new store`

**Comment by rkhamis** [comment]
Suggestion:

 - [ ] two buttons at the beginning:
     - Use previously configured Profile Manager 
     - Create a new Profile Manager
     - if new --> set new Profile Manager password
     - if use --> enter your Profile Manager password
    
 - [ ] remove TFChain Configuration Secret. Use Profile Manager password for TFChain Secret
 - [ ] make sure to be backwards compatible (check if TFChain Secret is defined in the profile ---> use instead)
 - [ ] Mnemonics ---> Mnemonics from your TFChain account

**Comment by rkhamis** [comment]
Suggestion:

![profile_manager drawio](https://user-images.githubusercontent.com/8425762/145712530-24a06b3b-b503-4a22-89b4-324a849dc954.png)


where 

 - [ ]  remove TFChain Configuration Secret. Use Profile Manager password for TFChain Secret

 - [ ] Mnemonics ---> Mnemonics from your TFChain account (12 words)


first #92 needs to be implemented so existing users can first cancel their contracts

**Comment by abom** [comment]
It should be done now, @MohamedElmdary helped identifying a wired error related to "field indexes", maybe we can refactor it later.


![Screenshot from 2021-12-14 15-17-07](https://user-images.githubusercontent.com/511438/146005525-bacbb2f7-5382-41e5-a7e9-1696b7c3ebbe.png)
