### ISSUE TITLE
Can't get deployed list

### ISSUE THREAD

**Issue by zaelgohary** [threefoldtech/grid_weblets#1435]
![image](https://user-images.githubusercontent.com/40770501/230111714-35495806-2974-4d8f-9f03-f7866a78dba5.png)

**Comment by A-Harby** [comment]
Verified on Devnet.
![image](https://user-images.githubusercontent.com/109473873/230769291-87324e5c-b18d-4764-b021-912a5f9cdfc7.png)
![image](https://user-images.githubusercontent.com/109473873/230769302-68d9d8b4-e183-4dad-8b61-e7e0f1282a49.png)
