### ISSUE TITLE
Deployment List table isn't displayed

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1442]
### Description

Deployment List is not displayed, same with all the solutions.

### Logs/Alerts

![image](https://user-images.githubusercontent.com/109473873/230382254-f270a5ec-7bcc-4ab4-850f-b4d90b9b0321.png)
![image](https://user-images.githubusercontent.com/109473873/230382470-b83b8601-5a3a-4d53-8201-f7b8cc5d9702.png)

**Comment by AhmedHanafy725** [comment]
duplicate #1435
