### ISSUE TITLE
Gateway isn't deleting after a failing deployment

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#1455]
### Description

Mainnet, v1.7.0.
I tried to deploy Funkwhale instance but it failed and after the cascade delete of the contract, I tried to deploy again with same inputs but got a error that previous deployment was successful and there's another gateway deployment with the same name.

### Logs/Alerts

The error.
![image](https://user-images.githubusercontent.com/109473873/231451371-bdaeff01-24a2-4d1c-be30-5f5f1b705d41.png)
My contract list.
![image](https://user-images.githubusercontent.com/109473873/231451321-922ced86-e4ad-4a87-b0e9-a0d858c1e161.png)

**Comment by ramezsaeed** [comment]
should be fixed in 3.10
it also can be deleted from contract for now.

**Comment by mohamedamer453** [comment]
After multiple deployments from multiple different solutions i was not able to reproduce this issue on devnet `01de9dc`. i think it might have been a network error that happened during deletion but if it was reproducible from your side please reopen it with steps on how to reproduce.
