### ISSUE TITLE
Updates in the docs

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/grid_weblets#154]
edit: part of #113 

#### Farming calculator 
there are no docs for the farming calculator 

##### Profile manager

https://library.threefold.me/info/manual/#/manual__weblets_profile_manager

- the screenshots need to be updated as `profile manage` is no longer in the side menu 

- `TF Configuration Secret` 
we could  explain why we need this password (ex. to encrypt and decrypt your data in the key-value store) 
for sure in this case, we need to explain what is the key-value store

##### Caprover page
- In the Requirements section, in the second point 
 `Make sure your profile has been filled in in the weblets playground`
 there is `in in`  little bit confusing 
 just use `fill` instead `fill in`  

- How to access the admin interface ? 
make sure your public IP address (in my case 185.206.122.136) is filled `in in` the domain name record.

`in in ` is confusing so we can use `fill `  or `use` instead to make it more clear

- In `Use the weblet`
In case he choose `Node selection`  to be automatic, we need to explain that he will get a list of matching nodes and he needs to select the one he needs and we need to add a screenshot for that 

##### Virtual machine 
there must be space in the title 
`VirtualMachine` we should add space 

in process section 
`Planetary Network` we can add also link to explain planetary network in details

- `Choose the node to deploy on which can be`
in the `automatic` part
we need to explain that he will get a list of matching nodes and he needs to select the one he needs and we need to add a screenshot for that

##### Funkwhale and 

- explain the node selection options and in `automatic` one 
e need to explain that he will get a list of matching nodes and he needs to select the one he needs and we need to add a screenshot for that
and in the case of `manual`, he needs to make sure that the nodes used have enough resources for him

#####  peertube

- explain the node selection options and in `automatic` one 
we need to explain that he will get a list of matching nodes and he needs to select the one he needs and we need to add a screenshot for that and in case of `manual` he needs to make sure that the nodes used have enough resources for him

**Comment by asamirr** [comment]
@RafyAmgadBenjamin can you provide a link that explains `Planetary Network` well?

**Comment by asamirr** [comment]
https://github.com/threefoldfoundation/info_manual3/tree/development_weblets_new_docs

**Comment by mhost39** [comment]
Verified

Caprover page
![image](https://user-images.githubusercontent.com/31102305/146396267-5569ef75-cd57-4bd7-b214-eb696cfe0c8f.png)

profile manager 
![image](https://user-images.githubusercontent.com/31102305/146396473-fd505518-35dc-4529-8c33-fa5e3ab7ad17.png)

VirtualMachine: https://library.threefold.me/info/manual/#/manual__weblets_vm
