### ISSUE TITLE
Funkwhale deployment fails on testnet (even with freefarm node)

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#163]
<img width="1273" alt="Screenshot 2021-12-09 at 16 04 38" src="https://user-images.githubusercontent.com/30384423/145421270-b35b32d4-6b54-4549-acfb-e13ae0c50b79.png">

network: testnet
node to deploy on: testnet Freefarm node 18

<img width="1273" alt="Screenshot 2021-12-09 at 16 04 46" src="https://user-images.githubusercontent.com/30384423/145421318-d74dea11-abdd-4ce5-9360-5439e880ca2f.png">

**Comment by Omarabdul3ziz** [comment]
it works fine on play.dev.grid.tf now.  play.grid.tf needs to be updated

the below example deployed on node: 18 on testnet at play.dev.grid.tf
![Screenshot from 2021-12-22 12-28-56](https://user-images.githubusercontent.com/32527347/147078676-877091b6-745a-4cc6-9ae8-378e390dcb71.png)

**Comment by abom** [comment]
Verified again, it's deploying on testnet

![Screenshot from 2021-12-23 20-10-10](https://user-images.githubusercontent.com/511438/147277676-a32cf0fe-45c5-488d-8522-6b64a32278e7.png)
