### ISSUE TITLE
Farming Calculator: unmark certified

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/grid_weblets#165]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/18591016/145424228-f16f4ba9-bb5b-427b-a563-23833d005caa.png">

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/169

**Comment by ranatrk** [comment]
verifying
