### ISSUE TITLE
CapRover: incorrect password

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#166]
environment : testnet

I deployed a Caprover and I receive a password. 

<img width="1273" alt="Screenshot 2021-12-09 at 16 19 05" src="https://user-images.githubusercontent.com/30384423/145424109-33082002-c906-4d09-b691-5108e8e32d9c.png">

<img width="1273" alt="Screenshot 2021-12-09 at 16 19 27" src="https://user-images.githubusercontent.com/30384423/145424174-2c105f96-0012-4539-81a8-1f331ba6c0ea.png">

But I can't log in for reason 'password incorrect': 

<img width="1273" alt="Screenshot 2021-12-09 at 16 19 53" src="https://user-images.githubusercontent.com/30384423/145424264-49a8c6b3-4260-4b62-a5e2-8138adceeec4.png">

**Comment by MohamedElmdary** [comment]
@sameh-farouk Please check this `environment variable` ... is it correct ?

**Comment by sameh-farouk** [comment]
@MohamedElmdary I checked it first when changing the initial password was implemented on Caprover weblet, and the Env Var was set correctly.
I also was unable to reproduce, I deployed two instances, and both work flawlessly so @gmachtel can you try again, there were a lot of updates recently maybe something was broken in between.

**Comment by waleedhammam** [comment]
Verified, can't reproduce

**Comment by gmachtel** [comment]
I have the same issue again, so there is a problem.

**Comment by gmachtel** [comment]
<img width="587" alt="Screenshot 2021-12-14 at 10 22 17" src="https://user-images.githubusercontent.com/30384423/145970242-84785cee-dc7f-4a7e-a35a-9435f9f301b4.png">

<img width="681" alt="Screenshot 2021-12-14 at 10 24 02" src="https://user-images.githubusercontent.com/30384423/145970434-e3c38747-7f09-4ed2-90d6-b03a167d3469.png">

**Comment by sameh-farouk** [comment]
I’ll double check, in the meantime, could you check and report back If the DNS record for that domain was updated with  this caprover vm Public IP address and it's not pointing to diffrent instance.

**Comment by gmachtel** [comment]
Ha true that could be the case. Let me check indeed.

**Comment by gmachtel** [comment]
But there is a weird thing ongoing anyway, as I deleted all my old peertube deployments.

**Comment by gmachtel** [comment]
It worked changing IP. Sorry for the inconvenience.

**Comment by sameh-farouk** [comment]
Never mind, I'm glad I was able to help.
