### ISSUE TITLE
Farming Calculator: negative entries should not be possible 

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/grid_weblets#168]
Please remove the possibility to enter negative numbers:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/18591016/145527933-e84b0828-ca19-4673-9764-6b1806983374.png">

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/169

**Comment by ranatrk** [comment]
verifying
