### ISSUE TITLE
Peertube weblet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#17]
Should ask for 

## inputs

- solution name: 
- package: Silver / Gold /Diamond

## packages
-  silver : TODO
- gold: TODO
- diamond: TODO

don't fill in node id manually, the capacity planner should do the filtration for you
 

## output 

deployed solution on $solutionname_tube.GATEWAYDOMAIN

in the listing, i should see the solution name, machine ip, domain to access, and another button to show all of the deployment info

**Comment by xmonader** [comment]
@OmarElawady please fill the appropriate specs for the sizes

**Comment by waleedhammam** [comment]
Packages is not done, If it's not in this milestone please close the issue and create another one with packages only
