### ISSUE TITLE
the deploy button on the Caprover Weblet is disabled

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#172]
### Description

I keep trying to deploy an instance of Caprover using the Weblets, but failed as the deploy button is disabled regardless the network or the node selection mode, something seems broken.

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/173

**Comment by waleedhammam** [comment]
verified on play.dev.grid.tf and deployed a caprover instance
