### ISSUE TITLE
Funkwhale deployment fails: isUrl constraint failed

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/grid_weblets#174]
### Description

Funkwhale deployment fails

### Steps to reproduce
- deploy funkwhale on https://play.grid.tf/#/

### Logs/Alerts
 error: `An instance of ce has failed the validation: - property backends has failed the following constraints: isUrl `
![Screenshot from 2021-12-12 11-54-47](https://user-images.githubusercontent.com/17128393/145708764-a131bf02-f710-42f0-8192-8573bbdcbc31.png)

**Comment by asamirr** [comment]
@ranatrk try deploying one now through http://play.dev.grid.tf

**Comment by ranatrk** [comment]
@asamirr let us verify http://play.dev.grid.tf is up to date first

**Comment by waleedhammam** [comment]
![image](https://user-images.githubusercontent.com/10658229/145806802-23541dd7-edaa-490c-99ea-183a14267c69.png)

happening in play.dev.grid.tf

**Comment by asamirr** [comment]
Should be good once https://github.com/threefoldtech/grid_weblets/pull/193 gets merged

**Comment by waleedhammam** [comment]
merged but still the same
![image](https://user-images.githubusercontent.com/10658229/146015016-c8784da6-5c5e-47f0-a631-d328c7960f87.png)

**Comment by waleedhammam** [comment]
verified on play.dev.grid.tf
