### ISSUE TITLE
No Choose Node option working in Funkwhale 

### ISSUE THREAD

**Issue by asamirr** [threefoldtech/grid_weblets#175]
Both Capacity Filter and Manual options in choosing a node to deploy Funkwhale on aren't working

![image](https://user-images.githubusercontent.com/9322121/145708993-0d1c2b7a-bac3-4a86-a4f6-ac68a1af2b8d.png)

![image](https://user-images.githubusercontent.com/9322121/145708997-aacc4c9f-b279-40f9-8e3a-30cfa1ed21b6.png)

**Comment by Omarabdul3ziz** [comment]
it works on the latest version on development branch

**Comment by sameh-farouk** [comment]
verified on play.dev.grid.tf / latest commit 2dc02733467c74131def0524bd55e311f9a83d38

![Screenshot from 2021-12-21 22-10-38](https://user-images.githubusercontent.com/42457449/146991623-0574d877-0d2e-4f15-a9b5-42230b21324e.png)
