### ISSUE TITLE
List countries that have nodes only.

### ISSUE THREAD

**Issue by MElborolossy** [threefoldtech/grid_weblets#176]
### Description

It isn't making sense to list all countries.
It is better to list countries that have nodes only.

**Comment by MohamedElmdary** [comment]
How exactly should we get countries with nodes only ?
getting all nodes and filter countries is kinda overkill @MElborolossy

**Comment by MElborolossy** [comment]
It is not that hard to implement,
Already implement it in grid3_deployment_builder
You already have all nodes,
Make 2 sets for country and farmId, you make sure that no thing is repeated,
Get all farms and save it as a map, where key is the farmId, value is the farmName.
Then create a new one let us call it farmsPerCountry the key will be the country name and value will be the farm name.
You will have an empty value at first to get all countries which will have all the farms with available nodes.

**Comment by MohamedElmdary** [comment]
Added new implementation which fixing this issue & #394 
Please checkout implementation locally for now at https://github.com/threefoldtech/grid_weblets/pull/405

**Comment by abom** [comment]
@xmonader  @MohamedElmdary  We need to decide if the node selection component is going to be refactored/rewritten or we just try to fix this issue.

**Comment by AhmedHanafy725** [comment]
I think it can be easily done now with gridproxy's node distribution
https://gridproxy.dev.grid.tf/stats?status=up

**Comment by mohamedamer453** [comment]
Verified on devnet.

The capacity filter now lists the countries with nodes only.

![image](https://user-images.githubusercontent.com/101194226/179391502-fd653130-0f82-403c-8c61-1448bb7c40d3.png)
