### ISSUE TITLE
Funkwhale weblet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#18]
Should ask for 

## inputs

- solution name: 
- package: Silver / Gold /Diamond

## packages
-  silver : TODO
- gold: TODO
- diamond: TODO

don't fill in node id manually, the capacity planner should do the filtration for you
 

## output 

deployed solution on $solutionname_audio.GATEWAYDOMAIN

in the listing, i should see the solution name, machine ip, domain to access, and another button to show all of the deployment info

**Comment by xmonader** [comment]
@Omarabdul3ziz @asamirr please fill in the packages specs

**Comment by waleedhammam** [comment]
Packages is not done

**Comment by abom** [comment]
It's resolved now with packages.
