### ISSUE TITLE
Let's have deployment pipeline for the play

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#181]
### Description

we can set up and configure a CI/CD pipeline using GitHub Actions

### Implementation

the release created events -> deploy to play.grid.tf
push on master -> deploy to play.dev.grid.tf

**Comment by xmonader** [comment]
We should move to using development branch as per our process. 

merges/commits on development should deploy to play.dev.grid.tf and merges on master should deploy on play.grid.tf

**Comment by sameh-farouk** [comment]
@abom @rkhamis @ashraffouda @xmonader What do you think guys, In case of multiple immediate pushes/merges, we can handle the repeated trigger of the pipeline within a short time in such different ways:

1- run in parallel, faster to finish, however, **a race-condition** could happen, imagine the build and deployment of the first commit merged takes longer than the second one, it will render the server outdated, or at worst case, maybe copying the files to the server could be mixed.

2- allow only one instance of the workflow per branch to be running, the new workflow will cancel the one in progress, and start immediately with the latest merged one. Still fast as the first one, maybe better, but in case the workflow is canceled when it copies the files to the server, it could leave the server in **an unstable state** till the newer workflow finish (less than 4 minutes).

3- allow only one instance to be run, and put any incoming workflow in the waiting queue, this is more stable in my opinion, but will **take longer**, so in case of three merges, you need to wait for the three sequential deployments to finish.

4- on **master use pessimistic flow**:  allow only one instance to run and put the incoming job in the waiting queue. On **development use optimistic flow**: allow the incoming job to cancel the in-progress job, we don’t mind some shit happening o our staging server in very rare cases if ever.

5- not sure if this implementation will be straightforward, but I can (try) no.2 but the workflow would be canceled only if it prior to the copying files process otherwise it will be allowed to finish. This will require splitting the workflow into two jobs, specifying concurrency at every job level, and uploading and downloading the artifacts between the jobs. Could be a better flow **if GitHub actions allowed such customizations** and implementation went successfully.

**my personal opinion:**
I already went with **no 4**, and the [PR](https://github.com/threefoldtech/grid_weblets/pull/204) is ready. it can be merged and put in service immediately if we agree that it is a good flow. Then 5 can be implemented later (if needed).

**Comment by xmonader** [comment]
I'm good with option 4

**Comment by ashraffouda** [comment]
I would say go always for pessimistic flow, deploy each commit after another leaving the new ones in the waiting queues. it is ok to take a long time, this will always leave the server in clean state and also will have a workflow run for each commit so u can always tell which commit goes wrong
