### ISSUE TITLE
K8s weblet: in capacity filter mode, the node selection for master and workers should be persisted

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#182]
### Description

![Peek 2021-12-12 16-26](https://user-images.githubusercontent.com/42457449/145716554-2cf38e47-cb34-4dc1-a9d2-87005bddd658.gif)

in capacity filter mode, the node selection for master and workers should be persisted when switching between Kubernetes tabs.

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/192

**Comment by waleedhammam** [comment]
verified and fixed
