### ISSUE TITLE
K8s weblet: Planetary Network IP is undefined

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#184]
### Description
in K8s Weblet, the Planetary Network IP is undefined, but it is correctly displayed in JSON. other Weblets possibly affected. 

![Screenshot from 2021-12-12 17-13-35](https://user-images.githubusercontent.com/42457449/145718153-53f6bb3b-e65f-4793-80c1-9d663ecd2f8f.png)

**Comment by OmarElawady** [comment]
Verifying

**Comment by dmahmouali** [comment]
Planetary Network IP fixed in `show details` but not in the table

![image](https://user-images.githubusercontent.com/36021484/146377516-9d586d77-aa1f-4389-99f1-2d77e6f8cc0d.png)

**Comment by mhost39** [comment]
Verified
