### ISSUE TITLE
K8s weblet: blank details after k8s deployment

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#185]
### Description

Blank details after k8s deployment

![Screenshot from 2021-12-12 17-09-25](https://user-images.githubusercontent.com/42457449/145718274-42d82c32-0d2b-489e-b6ed-fe2c4fb64997.png)

although the console errors and the blank output, I got this deployment listed in my solutions list.

### Logs/Alerts

![Screenshot from 2021-12-12 17-10-32](https://user-images.githubusercontent.com/42457449/145718262-839c7e4f-12b1-4dcd-ad3e-d01ac96b1d7b.png)

**Comment by MohamedElmdary** [comment]
### Related issues
https://github.com/threefoldtech/grid_weblets/issues/198
