### ISSUE TITLE
K8s Weblet: cannot read properties of undefined (reading: 'includes')

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#186]
### Description

trying to deploy k8s, got this

![Screenshot from 2021-12-12 16-59-50](https://user-images.githubusercontent.com/42457449/145718368-17c8b49e-1468-434d-952c-51a3ed27195c.png)

**Comment by xmonader** [comment]
This should be in verification now

**Comment by mhost39** [comment]
Verified 
![image](https://user-images.githubusercontent.com/31102305/146380208-ba32c444-b84d-4040-ac65-bda94ac37579.png)
