### ISSUE TITLE
When a deployment fails, the deploy button is disabled until i refresh the page

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#187]
### Description

when a deployment fails, the deploy button is disabled until I refresh the page, this happens in K8s but is possibly related to other weblets as well.

![Screenshot from 2021-12-12 16-52-35](https://user-images.githubusercontent.com/42457449/145718500-b93d86de-4bc0-4e72-9f00-88e11a1eb6df.png)

### Steps to reproduce

List of steps to reproduce the problem if it's a bug

### Logs/Alerts

Logs/Alerts if available

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/195

**Comment by sameh-farouk** [comment]
Verified

**Comment by sameh-farouk** [comment]
I found that under certain circumstances, when deployment finished but the validation process failed, the back button will be disabled, and if you navigate to other tabs deploy button is also disabled as well.

**Comment by sameh-farouk** [comment]
verified on play.dev.grid.tf or a9260e9681ddfa
