### ISSUE TITLE
K8s deployment fails: 'not enough space left in pools of this type ssd'

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#188]
### Description

got this when I was trying to deploy a Kubernetes cluster consisting of one master and two workers all with the default capacity, although I was able to deploy a cluster later on different nodes.

![Screenshot from 2021-12-12 16-52-35](https://user-images.githubusercontent.com/42457449/145719410-b3366a26-6cb9-49b8-b0bd-fe183d81c920.png)

@xmonader was suggesting that the capacity reported by zos could be incorrect

**Comment by xmonader** [comment]
caused by https://github.com/threefoldtech/zos/issues/1508

**Comment by AhmedHanafy725** [comment]
this was happening as over-provisioning was allowed for `sru`
disabled in https://github.com/threefoldtech/tfgridclient_proxy/issues/144, https://github.com/threefoldtech/grid3_client_ts/issues/275

please reopen it if still happening
