### ISSUE TITLE
VM image field should be mandatory in VM weblet

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#189]
### Description

VM weblet allows you to deploy VM with an empty image field, it should be a required field. the deployment will end eventually with Alpine instance, but this should be explicitly decided by the user before starting the deployment.

![Screenshot from 2021-12-12 19-26-15](https://user-images.githubusercontent.com/42457449/145722900-d7fe6e4e-ad8e-4280-9040-9bd55ad8e3e3.png)

### Logs/Alerts

Logs/Alerts if available

**Comment by MohamedElmdary** [comment]
It might appear as `non required` however its just a visual bug that enables `deploy` button
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/208

**Comment by waleedhammam** [comment]
The PR will select the first one however it's not shown in the screen, it may be confusing while deployment button is on

![Screenshot from 2021-12-14 15-59-01](https://user-images.githubusercontent.com/10658229/146012478-7db51e71-3ccb-4270-ba73-b097b9f400bc.png)

**Comment by sameh-farouk** [comment]
@waleedhammam probably the staging server wasn't up to date
verified on play.dev.grid.tf or on a9260e9
