### ISSUE TITLE
Peertube Weblet: cannot read properties of undefined (reading: 'domain')

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#191]
### Description

Peertube deployment broken ATM, tried on different nodes.
![Screenshot from 2021-12-12 20-40-31](https://user-images.githubusercontent.com/42457449/145725648-5e639cc2-b3f8-4aff-b202-67bed32a6908.png)

Network: Testnet
Node ids: 54, 12, 11, 5

### Logs/Alerts
![Screenshot from 2021-12-12 20-54-12](https://user-images.githubusercontent.com/42457449/145725653-f00ef08f-d811-4db7-84b4-5954dc0542a2.png)

**Comment by rkhamis** [comment]
let's wait for #96

**Comment by dmahmouali** [comment]
got the same error in Funkwhale deployment

![image](https://user-images.githubusercontent.com/36021484/145790583-93c6fff0-ad51-4efe-9b8e-4a2a20bda7b3.png)

**Comment by dmahmouali** [comment]
can't reproduce locally on commit: 2a92a85aca934541455f5f3ff26cce31e05ea674

**Comment by rkhamis** [comment]
happens on Funkwhale as well

**Comment by Omarabdul3ziz** [comment]
this is fixed, verified it works fine on play.dev
