### ISSUE TITLE
Peertube weblet: cannot login

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#194]
I created a Peertube weblet (on TFGrid3 devnet) but I can't log in to upload video's, not using username/password, and not throough ThreeFold Connect. Oauth issues. 

<img width="1078" alt="Screenshot 2021-12-13 at 09 49 13" src="https://user-images.githubusercontent.com/30384423/145780637-56638961-b994-4442-bf74-33d6dc5ba355.png">

<img width="322" alt="Screenshot 2021-12-13 at 09 37 36" src="https://user-images.githubusercontent.com/30384423/145780193-1a537d38-d7eb-470a-9019-ce04e3a63fee.png">

<img width="1273" alt="Screenshot 2021-12-13 at 09 36 53" src="https://user-images.githubusercontent.com/30384423/145780129-0211fc69-e672-4087-850e-b2c2d756241f.png">

Domain name: https://VMb59a772f.gent02.dev.grid.tf
Contract ID 2154
flist https://hub.grid.tf/omar0.3bot/omarelawady-peertube-grid3-tfconnect.flist

**Comment by rkhamis** [comment]
let's wait for #96

**Comment by abom** [comment]
Need to re-verify if this is resolved now.

**Comment by Omarabdul3ziz** [comment]
this is fixed and login with email/password and threefold connect works well.
