### ISSUE TITLE
rollback deployment in case of failure

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/grid_weblets#196]
## Description

![image](https://user-images.githubusercontent.com/10658229/145804827-ee2b1a4e-b3f5-47dc-99d0-357836852697.png)

I've a failed deployment and it's still listed in the deployments, should be cleaned up

**Comment by dmahmouali** [comment]
The rollback is responsible by the grid client [here](https://github.com/threefoldtech/grid3_client_ts/blob/d49fe5e41a1683e256d8966182135508af49a5b7/src/high_level/twinDeploymentHandler.ts#L385), as @xmonader expected, but we have two complex deployments right now [ `deployFunkwhale`, `deployPeertube` ]

### the suggestion:
1. Add rollback logic in the weblets utils and wrap the complex deployments with it.
2. update the same deployment with adding name contract but after discussions that will need workarounds and a lot of work.

**Comment by dmahmouali** [comment]
After discussion with @abom, we will go with the first suggestion (catch the deployment error) for now until we get more info about the second suggestion (update the same deployment).

**Comment by Omarabdul3ziz** [comment]
to verify this, I need to hardcode the node id which the gateway is supposed to be deployed in with a node that does not support the gateway model. 
and it does rollback deleting the VM after failing to deploy the gateway
![Screenshot from 2021-12-30 11-08-41](https://user-images.githubusercontent.com/32527347/147737924-fd161f52-3708-4376-af1f-9a3332805fae.png)
