### ISSUE TITLE
failed to deploy kubernetes on play.dev.grid.tf

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/grid_weblets#198]
![image](https://user-images.githubusercontent.com/10658229/145816583-6c8d01bc-a952-4989-978e-cd0a22cc2828.png)

```
kubernetes.wc.js:15 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at Ge (kubernetes.wc.js:15)
    at Object.p (kubernetes.wc.js:15)
    at H (kubernetes.wc.js:1)
    at F (kubernetes.wc.js:1)
```

**Comment by dmahmouali** [comment]
I think the cluster deployed successfully but the error in presenting the data because I can access the cluster normally after getting the same error.

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/207

**Comment by waleedhammam** [comment]
still the same on play.dev.grid.tf

**Comment by xmonader** [comment]
Kubernetes was tested yesterday, I'll move to verification

**Comment by mhost39** [comment]
Verifying...
