### ISSUE TITLE
improvements for farming widget

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/grid_weblets#20]
- start with defaults (Titan)
- Power price
- basically: make graph where (margin)
    -  X = TFT price after 5 Y
        -  start = 0.15, end is 20 (20 is in advanced)
     - Y = USD price (total income of the farming - costs) over 5Y, aggregate all TFT
- no CU/SU/NU in the main one, put to expert tab
- tab for advanced:
   - TFT price max, default on 20

**Comment by rkhamis** [comment]
done.

issues regarding farming are tracked here: https://github.com/threefoldtech/grid_weblets/issues/13
