### ISSUE TITLE
VM details after deployment doesn't show contract ID and the public IP isn't show as well

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#203]
![image](https://user-images.githubusercontent.com/64129/145880460-2c72e219-76ef-4a01-8fde-ba205f139f79.png)

while in the listing now 
![image](https://user-images.githubusercontent.com/64129/145880547-cb454282-9550-4265-9770-0466d0102cab.png)

clicking on the show details
![image](https://user-images.githubusercontent.com/64129/145880626-50965cf7-7630-43bf-98ad-00201363fc4e.png)

the contract doesn't show up, and in json the public ip exists

![image](https://user-images.githubusercontent.com/64129/145880704-124bccc9-f570-4a06-9441-4cd4f6e58b5a.png)

**Comment by MohamedElmdary** [comment]
@xmonader for some reason contractID isn't available in `JSON`
So I gonna check if it exists or not

**Comment by MohamedElmdary** [comment]
### Fixed
![image](https://user-images.githubusercontent.com/31689104/145966436-bbed38a4-29a6-4dd9-87f9-0e46ecb0099f.png)
#### PR
https://github.com/threefoldtech/grid_weblets/pull/205

**Comment by abom** [comment]
I think we need to check why it has no contract ID returned, @AhmedHanafy725 what do you think?

**Comment by AhmedHanafy725** [comment]
> I think we need to check why it has no contract ID returned, @AhmedHanafy725 what do you think?

I think it wasn't on the latest version of grid3_client. It is available on `0.0.32`

**Comment by waleedhammam** [comment]
seems a problem on play.dev.grid.tf
![image](https://user-images.githubusercontent.com/10658229/146013434-ef06eb6e-b302-4412-864f-e5e0c9eb3d3f.png)

code version:
![image](https://user-images.githubusercontent.com/10658229/146013527-3fabd52c-939e-4abb-8797-5e11326fa876.png)

**Comment by mhost39** [comment]
Verifying ...
