### ISSUE TITLE
In CapRover Domain should be flagged as required

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#206]
Trying to set up a CapRover deployment. I am able to select a node, but the `Deploy` button remains unclickable. 

<img width="1078" alt="Screenshot 2021-12-14 at 10 07 39" src="https://user-images.githubusercontent.com/30384423/145968287-c2753d94-93fe-4d55-a082-36d450c5bbed.png">

**Comment by MohamedElmdary** [comment]
@gmachtel cause `domain` is empty

**Comment by rkhamis** [comment]
@MohamedElmdary perhaps non-optional fields should be marked

**Comment by MohamedElmdary** [comment]
@rkhamis 
sure! what about add `*` after label name
e.g `Domain` => `Domain*`

Also We should add validation for almost every input (maybe next milestone)

**Comment by gmachtel** [comment]
Correct, able to deploy now, now blocked on https://github.com/threefoldtech/grid_weblets/issues/194 

so this one is simply that it’s not clear that this domain name is mandatory.

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/146418613-986e5fde-4c85-42ce-aa85-eac48761d746.png)
verified
