### ISSUE TITLE
Can't see what is the button behind the profile manager in farm calculator

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#211]
![image](https://user-images.githubusercontent.com/41957921/145994773-a9a5177a-04f5-496d-a35f-3000e1f65106.png)

**Comment by xmonader** [comment]
A bug indeed, can't get back to the previous screen to choose different configuration (the only solution is going to another page and go to the farmer calculator again)

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/grid_weblets/pull/301/files

**Comment by dmahmouali** [comment]
verifying

**Comment by dmahmouali** [comment]
works fine on play.dev.grid.tf

![image](https://user-images.githubusercontent.com/36021484/146929961-77994c57-6436-4758-b182-c83565a8ab3f.png)
