### ISSUE TITLE
vm deployment: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/grid_weblets#214]
### Description

![image](https://user-images.githubusercontent.com/10658229/146012018-6b5096fa-ce24-4a4b-838a-3e2b521f1cdb.png)

on play.dev.grid.tf

**Comment by AhmedHanafy725** [comment]
I think it's related to this one https://github.com/threefoldtech/grid3_client_ts/issues/105

**Comment by ranatrk** [comment]
verifying

**Comment by ranatrk** [comment]
verified
![Screenshot from 2021-12-16 14-48-05](https://user-images.githubusercontent.com/17128393/146376799-ba11e300-8add-4d4f-ae25-9e584d0d2ad0.png)
![Screenshot from 2021-12-16 14-57-43](https://user-images.githubusercontent.com/17128393/146376793-fe2e7051-0cbf-4de5-a997-b46ed576cd84.png)
