### ISSUE TITLE
contracts shows on my contracts Weblet without visible deployments

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#217]
### Description

I have Three contracts on DevNet shows on my contracts Weblet without visible deployments on the deployment list Weblet
![Screenshot from 2021-12-14 17-37-47](https://user-images.githubusercontent.com/42457449/146037901-3225a8a9-a225-4f9e-8d10-cce792c56601.png)

![Screenshot from 2021-12-14 18-26-00](https://user-images.githubusercontent.com/42457449/146038512-2b7a2f8a-9b10-4416-a465-46ad85f4c544.png)

and on my TestNet profile, i deleted all my deployments and still have one contract 1384

![Screenshot from 2021-12-14 18-27-41](https://user-images.githubusercontent.com/42457449/146039054-c66b52ec-f842-4ef0-9587-4e99f72656e7.png)

![Screenshot from 2021-12-14 18-28-51](https://user-images.githubusercontent.com/42457449/146039069-35b31e88-ae85-4ecc-b256-d098c3e6e145.png)

### Steps to reproduce

on play.grid.dev.tf or a9260e9681ddfa123b0f100e3deb3fb0d709e97c

**Comment by xmonader** [comment]
Most likely caused by using different tfchain keyvalue store secret, and if that happens the grid3_client_ts won't be able to decrypt any deployments created with different secrets

**Comment by dmahmouali** [comment]
verifying

**Comment by dmahmouali** [comment]
## Verification:
### round 01:
- list the contracts and find if empty
- deployed new VM on play.dev.grid.tf
- list the contracts and find a new contract added
- the new VM deployment added to the deployment list
- delete the contract from polkadot.js.org
- the contract list back to be empty and the deployment list 

### round 02:
- list the contracts and find if empty
- deployed new VM on local ts_grid_client with filesystem as backend
- list the contracts on play.dev.grid.tf and find a new contract added
- no deployment added to the deployment list
- delete the contract
- the contract list back to be empty

### round 03:
- list the contracts and find if empty
- deployed new VM on local ts_grid_client with tfKVstore as backend with the same secret
- list the contracts on play.dev.grid.tf and find a new contract added
- one VM deployment added to the deployment list
- delete the contract
- the contract list back to be empty and the deployment list 

So I think it is normal behavior and maybe it was a wrong secret as @xmonader said.
