### ISSUE TITLE
UX: re-validate selected node upon new requirement / resources values when updated from UI

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#219]
### Description

after selecting a node, changing resources values from UI like CPU, memory, and toggling the public IP address should reactively revalidate the node and update the UI if it is not fit anymore

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/320

**Comment by sameh-farouk** [comment]
verified on play.dev.gridt.tf / latest commit b04a460798351dd92c568f209038f96950e3c6fa
