### ISSUE TITLE
cannot read properties of undefind

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#220]
on play.dev.grid.tf 
- create a profile 
- add account info
- click activate

![image](https://user-images.githubusercontent.com/64129/146053500-a285dafc-6e58-4aeb-9801-6ced49a8f950.png)
![image](https://user-images.githubusercontent.com/64129/146053514-c14a5ba8-1742-4a97-8982-5c9fa8e03573.png)

solution from @AhmedHanafy725 was to deactivate and activate the profile again which worked.

**Comment by mhost39** [comment]
Verifying...
