### ISSUE TITLE
dynamically choosing the gateway node 

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#221]
### Description

Even though the node to deploy VM is dynamically chosen through the deployment. the node to deploy gateway is hardcoded in peertube & funkwhale because it must be either 7 or 8 in dev net

### Steps to reproduce

Maybe there is a better way, which return a list and can select the first one.

### Logs/Alerts
https://github.com/threefoldtech/grid_weblets/blob/a9260e9681ddfa123b0f100e3deb3fb0d709e97c/src/utils/deployPeertube.ts#L48

**Comment by AhmedHanafy725** [comment]
It can be done dynamically like this

```ts
import { randomChoice } from "grid3_client" 
const nodes = await client.capacity.filterNodes({gateway: true})
const gwNodeId = randomChoice(nodes).node_id 
```
