### ISSUE TITLE
checking build files into git is redundant besides they do not match the source files

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#225]
### Description
nobody would commit the build files with every src code change for the sake of readable diffs, so it does not match the source files anyway and it serves no purpose for us now I believe. updating it continuously on dedicated build PR after every merge is also a tedious task.

I suggest either to
1- simply omit build files from git (remove already pushed build files/dirs and add them to .gitignore) 
2- or implement automated way (we can commit back the build files in the current ci/cd pipeline)

**Comment by sameh-farouk** [comment]
for me i prefer no 1 unless there is a good reason to keep it

**Comment by Omarabdul3ziz** [comment]
this was fixed on https://github.com/threefoldtech/grid_weblets/pull/696 by ignoring the build files.
and the GitHub action will regenerate these files on the hosting server
