### ISSUE TITLE
FR: contracts list - show more information like related deployment and payment history

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#226]
currently, the contracts list Weblet shows very limited details (id, and name only). As a user, I want to be able to see more information about the contact like related deployment, and also the payment history would be super useful.

UI-wise, we can have a `Show Details` button in the contract row like the one in the deployments list
![Screenshot from 2021-12-15 13-19-45](https://user-images.githubusercontent.com/42457449/146177663-dadb5d84-f27c-4b69-8a9f-d16cc574357b.png)

**Comment by MohamedElmdary** [comment]
Out Dated as we already added `billing rate`
