### ISSUE TITLE
allow the user to set config while deploying peertube 

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#227]
### Description

allow the user to set more environment variables while deploying. to update the configs of peertube instance

### Implementation

all the config that can be updated from env vars [here](https://github.com/freeflowuniverse/tf-peertube/blob/develop_threefold_login/support/docker/production/config/custom-environment-variables.yaml)

**Comment by xmonader** [comment]
No, go with sane defaults at this point. Don't work on it.
