### ISSUE TITLE
Show how much each contract is using up

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#228]
For the Contracts Management weblet:

use the information from https://github.com/threefoldtech/grid3_client_ts/issues/152#issuecomment-994766327 to show for each contract in the list, how much TFT it uses per month

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/258

**Comment by mhost39** [comment]
Verified 
![image](https://user-images.githubusercontent.com/31102305/146395496-c25abbe1-37e9-48f7-83b1-7cc57b2fe562.png)
