### ISSUE TITLE
Show version information

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#229]
Weblets should show version number (once released)

**Comment by asamirr** [comment]
Version number of?

**Comment by MohamedElmdary** [comment]
Cannot reproduduce

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/306

**Comment by mhost39** [comment]
can we Increase font an move it to bottom right of the screen
or it's will be better if we moved it to top north of the screen next to DEPLOYMENT
![image](https://user-images.githubusercontent.com/31102305/146937333-2daf3046-01ae-4a0f-800d-dcc65ab1ca97.png)

**Comment by mhost39** [comment]
and here it appears in two component 
![image](https://user-images.githubusercontent.com/31102305/146938242-fdeafbe7-b100-4fde-9d4a-349e0c837730.png)

**Comment by MohamedElmdary** [comment]
### Updated
#### PR
https://github.com/threefoldtech/grid_weblets/issues/229

**Comment by ashraffouda** [comment]
verified
