### ISSUE TITLE
select first node after nodes filter as a default selection 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/grid_weblets#230]

**Comment by ashraffouda** [comment]
https://github.com/threefoldtech/grid_weblets/pull/309

**Comment by sameh-farouk** [comment]
Verified on play.dev.grid.tf / latest commit 2dc02733467c74131def0524bd55e311f9a83d38
![Screenshot from 2021-12-21 21-54-33](https://user-images.githubusercontent.com/42457449/146989752-166d47f8-98ac-499f-b3e8-79eec9aa30a6.png)
