### ISSUE TITLE
UI: inconsistencies between the same text message shows in different weblets

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#231]
when there is no profile activated, there is an inconsistency between the message shown in contract Weblet and the same message shows on other Weblets

![Screenshot from 2021-12-15 16-25-32](https://user-images.githubusercontent.com/42457449/146204312-2dde4e36-53ab-43e7-9d0b-daff6b522621.png)

![Screenshot from 2021-12-15 16-25-41](https://user-images.githubusercontent.com/42457449/146204319-4256bba9-3536-43f4-8dad-1e8b9a962ff5.png)

**Comment by rkhamis** [comment]
let's unify to "Please activate a profile from the profile manager"

**Comment by sameh-farouk** [comment]
verifying.

> let's unify to "Please activate a profile from the profile manager"

@asamirr can you update the message to include `the` as reem was suggesting?

**Comment by asamirr** [comment]
Done!

**Comment by sameh-farouk** [comment]
Thanks @asamirr
Verified.
