### ISSUE TITLE
Add/remove workers from a kubernetes deployment

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#232]
should be able to add and remove workers

**Comment by MohamedElmdary** [comment]
@dmahmouali is that possible right now ?

**Comment by dmahmouali** [comment]
it will be possible after this fix: https://github.com/threefoldtech/grid3_client_ts/pull/169 by using the `update` function
```
const k = new K8SModel();
.
.
.
const grid3 = await getClient();
const res = await grid3.k8s.update(k);
```

**Comment by MohamedElmdary** [comment]
### Added
#### PR
https://github.com/threefoldtech/grid_weblets/pull/370
