### ISSUE TITLE
Weblets demo feedback

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#234]
- [x] Fix Plantery network ip [issue](https://github.com/threefoldtech/grid_weblets/issues/184)
- [x] Fix Selected items when remove one of them
- [x] empty workers for k8s in the beginning
- [x] Fix plantery in deployedlist
- [x] Remove the wording of `Browser sessions secret`, rename to `Profile Manager password`?
- [x] Disable or Remove `fuknwhale` & `peertube`

**Comment by rkhamis** [comment]
Profile Manager password is correct

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/235
