### ISSUE TITLE
Listing virtual machines shows "undefined"

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#238]
### Description

Listing of VMs shows `undefined`

### Steps to reproduce

This does not produce this issue most of the times

* Go to [play.dev.grid.tf](https://play.dev.grid.tf)
* Click `Virtual Machine` on the side bar under `Deployments` section (assuming no previous VM deployments were one)

### Logs/Alerts

![Screenshot from 2021-12-16 12-14-25](https://user-images.githubusercontent.com/511438/146352755-ad166a2d-be3c-4a2d-8e10-e79fa06cfefc.png)

**Comment by abom** [comment]
It's not there after a hard-refresh, will re-open if it showed again.

**Comment by abom** [comment]
Happened again, need to investigate why this happens.

**Comment by Omarabdul3ziz** [comment]
![Screenshot from 2021-12-16 15-25-06](https://user-images.githubusercontent.com/32527347/146380443-396a221a-277e-41c4-9148-cf1f90447210.png)

**Comment by asamirr** [comment]
Verified
![image](https://user-images.githubusercontent.com/9322121/146397844-9b74cd7d-73d1-4cf8-aee2-9087acc45b9e.png)
