### ISSUE TITLE
why users can see this component ?

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/grid_weblets#242]
![image](https://user-images.githubusercontent.com/31102305/146355199-4908c34d-5489-4935-965a-452832ffbb2c.png)

**Comment by MohamedElmdary** [comment]
At first it was planned to add a markdown editor in each page but it's kinda makes no sense now
should we remove it ? @rkhamis  @xmonader @abom

**Comment by xmonader** [comment]
Let's hide it for now
