### ISSUE TITLE
I can see other weblets without activating a profile and no feedback 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#244]
![image](https://user-images.githubusercontent.com/64129/146363199-caa70e03-973d-43ac-9846-d8e3b6aa9668.png)

The deploy button is disabled, yet there's no feedback for the user why

**Comment by xmonader** [comment]
We can also just show the message to activate profile manager if not activated in all of the weblets

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/254

**Comment by xmonader** [comment]
now it shows next to deploy 
![image](https://user-images.githubusercontent.com/64129/146418270-5520df0c-40da-4abc-84e1-8bd14c4855f1.png)

not the best thing ever, but good enough for this one, let's move to next milestone to have in the top of the weblet.

**Comment by sameh-farouk** [comment]
not able to verify this one.
it was delayed from grid_weblets 1.0.0 to grid_weblets 1.0.1 but this has not met @xmonader requirement below yet.

> not the best thing ever, but good enough for this one, let's move to next milestone to have in the top of the weblet.

**Comment by MohamedElmdary** [comment]
### Updated
#### PR
https://github.com/threefoldtech/grid_weblets/pull/321
