### ISSUE TITLE
remove alphine image from 3.0.1

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#246]
allow only ubuntu to be selectable when choosing vm image.
to be returned next week

**Comment by MohamedElmdary** [comment]
### Fixed
![image](https://user-images.githubusercontent.com/31689104/146369348-2954d2b1-077f-4b25-9a07-3103240bc9ea.png)

#### PR
https://github.com/threefoldtech/grid_weblets/pull/249

**Comment by MElborolossy** [comment]
Verified on play.dev.grid.tf
