### ISSUE TITLE
cursor in details dialogs implies that I can't copy anything

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#255]
![image](https://user-images.githubusercontent.com/64129/146384013-3543bedf-13b4-4e36-af95-8e4ea2d01437.png)

I need to go to json tab to do that

**Comment by MElborolossy** [comment]
I think you can, but the cursor is confusing
I still can select and ctrl+c

**Comment by xmonader** [comment]
you are definitely correct!

**Comment by MohamedElmdary** [comment]
### Updated
#### PR
https://github.com/threefoldtech/grid_weblets/pull/307

**Comment by MElborolossy** [comment]
Verified
