### ISSUE TITLE
clicking on the same page in sidebar gives router error

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#257]
![image](https://user-images.githubusercontent.com/64129/146387932-f6e4b026-4bb4-44cb-8d3e-b1deabfb1178.png)

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/259

**Comment by mhost39** [comment]
Verified 
![image](https://user-images.githubusercontent.com/31102305/146394517-a7747f2a-53e3-4b0b-8fad-c471e47319fa.png)
