### ISSUE TITLE
Kubernetes: cluster vms should be separated somehow in the details information

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#260]
![image](https://user-images.githubusercontent.com/64129/146390808-a23fc049-4658-44f1-a22a-a41e3c88cd3d.png)

Here the details dialog shows all of the workloads sequentially without any separator

**Comment by MohamedElmdary** [comment]
Will add tabs instead

**Comment by MohamedElmdary** [comment]
### Added
#### PR
https://github.com/threefoldtech/grid_weblets/pull/308

**Comment by sameh-farouk** [comment]
Verifying this.

**Comment by sameh-farouk** [comment]
verified on play.dev.grid.tf / latest commit 1303db4

![Screenshot from 2021-12-22 19-06-54](https://user-images.githubusercontent.com/42457449/147129519-ededfe60-a3e8-432b-8fb0-4465e3ac1cf2.png)
