### ISSUE TITLE
account balance not shows

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#267]
balance disappear after the `loading the balance` message. only profile name shows. no error in the console.

![Peek 2021-12-16 19-51](https://user-images.githubusercontent.com/42457449/146424386-677eb1b7-0f8d-4ef5-b2b0-a329124c66af.gif)

tried also hard reload and clear the browser cache and reload.

**Update :** 
checking the portal I discovered that I have no TFT left in my account, so we should display 0 TFT instead of nothing at all.

**Comment by MohamedElmdary** [comment]
@sameh-farouk  any idea of how to reproduce this issue ??

**Comment by abom** [comment]
For verification

**Comment by sameh-farouk** [comment]
![Screenshot from 2021-12-20 14-47-04](https://user-images.githubusercontent.com/42457449/146769438-1fb6819d-1389-4b59-bcdc-d5e38fdad1dc.png)

verified on play.dev.grid.tf / latest commit 57e1970fde487f
