### ISSUE TITLE
billing rate shown in scientific notation

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#268]
as a user, this is confusing me. the number is in scientific notation. also calculation-wise not sure if this is the correct rate. this is as low as 0.0000008999

![Screenshot from 2021-12-16 20-05-33](https://user-images.githubusercontent.com/42457449/146425370-08ca4162-6bc4-430a-b098-fb4c2a88c709.png)

**Comment by MohamedElmdary** [comment]
@xmonader  should we use [Decimal](https://www.npmjs.com/package/decimal) here ??

**Comment by abom** [comment]
I think we may hide very small values or just say it's less than e.g 1 TFT as @xmonader suggested.

**Comment by abom** [comment]
We can use decimal too, but do not know the right precision to use.

**Comment by MohamedElmdary** [comment]
We decided to add Less than 1 TFT / hour instead

**Comment by abom** [comment]
For verification

**Comment by dmahmouali** [comment]
verifying

**Comment by dmahmouali** [comment]
verified on play.dev.grid.tf

![image](https://user-images.githubusercontent.com/36021484/146679435-b6cb52e7-855a-474f-bb2d-167c1600dec3.png)
