### ISSUE TITLE
clean up dev logs

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#270]
Within the deployment tabs, I noticed a lot of debugging information is being outputted on the console log which may cause a vulnerability leak.

see: https://circles.threefold.me/project/test-tfgrid3/issue/71

**Comment by xmonader** [comment]
Actually, as this is running in the enduser browser only -and we don't collect logs-, we won't be able to debug otherwise/ I think it's fine to be that way.
