### ISSUE TITLE
In Caprover deployer, Deploy a Virtual Machine node selection field is required

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#271]
The form field "Node Selection" seems to be a mandatory field but can deploy without selecting an option.

**Comment by abom** [comment]
This gives the following validation error, I think we need a better human readable message!

![Screenshot from 2021-12-19 13-25-16](https://user-images.githubusercontent.com/511438/146673202-290bf042-b443-4d83-9bd6-1f28135aabf2.png)

**Comment by ashraffouda** [comment]
seems fixed on play.dev.grid.tf
play.grid.tf needs an update
