### ISSUE TITLE
CapRover admin panel is dead

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#273]
Steps

Deploy a CapRover instance
Using the deploy list below
Hit Admin Panel

Expected outcome: 
Get redirected to the admin panel

Actual outcome: 
Redirect to dead link: http://captain.domain/

**Comment by xmonader** [comment]
the caprover instance requires time to fully boot, maybe it's better we add a liveness check next to the instance in the listing e.g green as healthy and red with `likely down`

**Comment by sameh-farouk** [comment]
related to this issue https://github.com/threefoldtech/grid_weblets/issues/274

**Comment by MohamedElmdary** [comment]
verified
