### ISSUE TITLE
 Failed to deploy with CapRover

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#274]
see: https://circles.threefold.me/project/test-tfgrid3/issue/77

**Comment by abom** [comment]
The validation shows domain is not valid, but it "Deploy" button is still enabled

**Comment by MohamedElmdary** [comment]
It's not about the regex is valid or not
last `thursday` I removed disabled to add temp required version till we fix it

**Comment by MohamedElmdary** [comment]
### PR
https://github.com/threefoldtech/grid_weblets/pull/288

**Comment by MohamedElmdary** [comment]
verified
