### ISSUE TITLE
failed to deploy with kubernetes

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#275]
see: https://circles.threefold.me/project/test-tfgrid3/issue/76

Steps:

Fill in form with
```
name: K8S9e472b7c
cluster token: cff06127
public ssh key: local ssh key
network name: NWe6197e87
network IP range: 10.20.0.0/16
```

Hit Delpoy

## Expected outcome: 
Deploy a node using Kubernetes

## Actual outcome: 
Failed to deploy with the following error:
```
Validation failed. errors: An instance of G has failed the validation: - property masters[0].node_id has failed the following constraints: min, isInt 
```

**Comment by xmonader** [comment]
I expect there was a problem in choosing the node_id, let's have it in the backlog

**Comment by ashraffouda** [comment]
this happens when the user clicked deploy but didn't fill the master node fields, Deploy should be disabled until the user choose the min specs

**Comment by ashraffouda** [comment]
it is fixed on play.dev.grid.tf
play.grid.tf needs update
