### ISSUE TITLE
profile data logged to console

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#277]
see: https://circles.threefold.me/project/test-tfgrid3/issue/73

**Comment by dmahmouali** [comment]
Verifying

**Comment by dmahmouali** [comment]
Can't see any profile data on play.dev.grid.tf after adding a new profile and going to `CapRover` tap

![image](https://user-images.githubusercontent.com/36021484/146677870-acf8d269-3fa0-49ca-9cc1-8da506ecf28f.png)
