### ISSUE TITLE
Modify the distros name in the VM weblet UI to reflect the version as well

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#278]
### Description

Modify the distros name in the VM Weblet UI to reflect the version as well
Ubuntu -> Ubuntu-20.04
Alpine -> Alpine-3
as well CentOS-8

**Comment by MohamedElmdary** [comment]
### Updated
#### PR
https://github.com/threefoldtech/grid_weblets/pull/305

**Comment by dmahmouali** [comment]
verifying

**Comment by mhost39** [comment]
Verified 
![image](https://user-images.githubusercontent.com/31102305/146930859-5ad551e1-83e0-4d04-9a41-9b27d717fc6b.png)
![image](https://user-images.githubusercontent.com/31102305/146930897-a5ccbb89-8b2f-478e-9d21-714810d83257.png)
![image](https://user-images.githubusercontent.com/31102305/146930947-8310dd95-1ead-4c5e-81b5-8ff925349333.png)
