### ISSUE TITLE
should cross-linked any flist in personal repo to tf-apps repo as they appears in the UI

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#281]
### Description

it doesn't look right showing flists with our names in the UI.

in VM weblet, selecting other would show the flist name, which is in a personal repo. also deploying Kubernetes or any other deployment like peertube, funkwhale would show the flist name in the details, or the JSON from the UI. 

should cross-link any flist in personal repos to the tf-apps repo.
- https://hub.grid.tf/omar0.3bot/omarelawady-ubuntu-20.04.flist
- https://hub.grid.tf/omar0.3bot/omarelawady-funk-latest.flist
- https://hub.grid.tf/omarabdul3ziz.3bot/threefoldtech-peertube-v3.0.flist
- https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-centos-8.flist
- https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-alpine-3.flist
- https://hub.grid.tf/ahmed_hanafy_1/ahmedhanafy725-k3s-latest.flist

**Comment by xmonader** [comment]
@rkhamis let's see the promotion with @maxux please @sameh-farouk add yours in the list please

**Comment by sameh-farouk** [comment]
> 

Done

**Comment by maxux** [comment]
```
omar0.3bot/omarelawady-ubuntu-20.04.flist -> tf-official-apps
omar0.3bot/omarelawady-funk-latest.flist -> tf-official-apps
omarabdul3ziz.3bot/threefoldtech-peertube-v3.0.flist -> tf-official-apps
samehabouelsaad.3bot/abouelsaad-centos-8.flist -> tf-official-apps
samehabouelsaad.3bot/abouelsaad-alpine-3.flist -> tf-official-apps
ahmed_hanafy_1/ahmedhanafy725-k3s-latest.flist -> tf-official-apps
```

**Comment by sameh-farouk** [comment]
Can we rename the flists too to remove the docker repo's name part?

Eg, omar0.3bot/omarelawady-ubuntu-20.04.flist             -> tf-official-apps/ubuntu-20.04.flist

**Comment by maxux** [comment]
Renamed:
```
924K Dec 20 05:15 threefoldtech-ubuntu-20.04.flist
2.5M Dec 20 05:15 threefoldtech-funk-latest.flist
3.2M Dec 20 05:15 threefoldtech-peertube-v3.0.flist
646K Dec 20 05:15 threefoldtech-centos-8.flist
30K  Dec 20 05:15 threefoldtech-alpine-3.flist
2.0M Dec 20 05:15 threefoldtech-k3s-latest.flist
```

**Comment by mhost39** [comment]
Verified 
commit: ce7aab57c26e784c715d7758829a41d9b01e0bec
![image](https://user-images.githubusercontent.com/31102305/146937958-fe905343-5a4a-4ef6-a646-5f0d36b2391e.png)
![image](https://user-images.githubusercontent.com/31102305/146938011-55cdc53c-f4fa-48f8-9e1b-4639120cf9b5.png)
