### ISSUE TITLE
show balance in profiles weblet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#29]

**Comment by abom** [comment]
Balance is shown when the profile is activated

![Uploading Screenshot from 2021-12-02 04-11-37.png…]()

**Comment by abom** [comment]
Balance is shown when the profile is activated

![Screenshot from 2021-12-02 04-11-37](https://user-images.githubusercontent.com/511438/144344745-895cb8af-30c4-48d4-b235-41731a2a8df9.png)
