### ISSUE TITLE
CapRover weblet: better instructions for the root domain field 

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#291]
### Description

I saw the domain field confuse people recently, so I suggest that we add either **a confirmation message** when we press deploy or **required select box** (like when the user approve an agreement) with text:  
`You will need to point a wildcard DNS entry (A-record) for the domain you entered to this CapRover instance IP Address after deployment, otherwise, you won't be able to access the CapRover dashboard using this domain.`

plus displaying **small note under the domain name filed** with this text:
`If you don't know what Captain root domain is, please visit {link} for documentation.`

this could help clear the confusion.

**Comment by MohamedElmdary** [comment]
verified
