### ISSUE TITLE
"Balance is not enough" error message shows only in console log but should be visible as well in the UI

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#292]
### Description

with a very low balance, trying to delete a VM will fail silently. should display a clear message for the user.
ATM the error message shows only in the console log.

![Peek 2021-12-19 19-48](https://user-images.githubusercontent.com/42457449/146685410-a0fbae1e-ab98-44a1-85ca-7ae3d058646a.gif)

### Steps to reproduce

- with having less than 1 TFT try to delete a VM

**Comment by MohamedElmdary** [comment]
### PR
https://github.com/threefoldtech/grid_weblets/pull/294

**Comment by sameh-farouk** [comment]
to be verified

**Comment by sameh-farouk** [comment]
![Screenshot from 2021-12-20 18-54-50](https://user-images.githubusercontent.com/42457449/146805028-ecafd161-14e5-4077-96fe-3477a9ac317e.png)

verified on play.dev.grid.tf / last commit  6fc101175
