### ISSUE TITLE
remove coming soon tag from peertube & funkwhale weblet

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#310]
### Description

a better way to activate & deactivate peertube and funkwhale for testing cases

**Comment by MohamedElmdary** [comment]
### Updated
#### PR
https://github.com/threefoldtech/grid_weblets/pull/311

**Comment by sameh-farouk** [comment]
verified on play.dev.grid.tf / latest commit 2dc02733467c74131def0524bd55e311f9a83d38
![Screenshot from 2021-12-21 21-47-55](https://user-images.githubusercontent.com/42457449/146988919-6d3bdde2-33bc-4573-879e-475defb4b64a.png)
