### ISSUE TITLE
deployments show unnecessary warning to not leave the page

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#315]
### Description
I think it's safe to remove this warning as we are free to navigate to other pages in the play, however, we can use `onbeforeunload` to warn user if **he try to close the tab or navigate out of the site** (changing the URL)

![Screenshot from 2021-12-21 16-36-35](https://user-images.githubusercontent.com/42457449/146948144-2e8ccb7a-078c-4020-9156-2183e6bd1828.png)

**Comment by RafyAmgadBenjamin** [comment]
i have read about `onbeforeunload` event here what i found
![image](https://user-images.githubusercontent.com/46320202/150670132-e16334cd-183a-4b0d-9993-4342d7c55583.png)
![image](https://user-images.githubusercontent.com/46320202/150670137-525556fe-209e-4eb7-9ad5-d7084859d154.png)

actually, I found also that chrome and firefox automatically fire this message while we try to refresh 
![image](https://user-images.githubusercontent.com/46320202/150670155-ea0c4344-74f9-4742-9586-d91e96ac3e76.png)
![image](https://user-images.githubusercontent.com/46320202/150670167-f8f007c7-1d31-4571-a6b7-d0eceba90797.png)


still try to investigate how this event is fired, even i checked with Mohammed Rabie, if he did this event, he told me no he didn't so i need to find out how to stop this default event and fire our with a custom message
