### ISSUE TITLE
Add target mountpoint validation against rootfs '/' as it will never succeed.

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#316]
### Description
starting a VM with mounting disk to rootfs `/` never works, and now there is a validation in zos to not allow such deployments.

so let's add validation on Mount Point filed in Disks panel to not allow the user to proceed further with invalid mount point such `/`

### Steps to reproduce

- in disks, add a new disk and change the mount point to `/`
- press Deploy, and after a few seconds deployment will fail.

![Screenshot from 2021-12-21 20-31-28](https://user-images.githubusercontent.com/42457449/146982180-83b86072-c258-4dd3-a02e-860802ee1cd7.png)

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/355

**Comment by abom** [comment]
Verified

![Screenshot from 2021-12-23 18-59-57](https://user-images.githubusercontent.com/511438/147271189-462168b2-39f2-4f88-b543-21b20798e465.png)
