### ISSUE TITLE
Capacity filter: node ID label does not change when selected

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#317]
### Description

When choosing a node ID in capacity filter, the dropdown shows only one node and does not change if another node is selected.

### Steps to reproduce

* Select "Capacity Filter" then apply with selected options
* Try to select any node from the suggested list

### Logs/Alerts

https://user-images.githubusercontent.com/511438/147009604-4c2a2aa2-8292-4cc9-b402-3eebb74f244e.mp4

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/320

**Comment by sameh-farouk** [comment]
verified on play.dev.gridt.tf / latest commit b04a460798351dd92c568f209038f96950e3c6fa
