### ISSUE TITLE
"Invalid Mnemonics" message does not show until after changing a value

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#319]
In case of an "Invalid Mnemonics" error when attempting to activate a profile, the error does not appear until a field has been changed (editing the profile name or switching from devnet to testnet, for example).

**Comment by abom** [comment]
I don't think we do instant validation for mnemonics, as it's done by trying to activate this profile on the selected network, hence we cannot ensure that the entered value is correct by itself, we need to ensure it's already on the network. Also, currently, before "Activate" button is clicked, not validation is done for mnemonics field.

If it's a different issue, please give us the steps so we can try to reproduce.

**Comment by scottyeager** [comment]
Behavior has changed since I opened the issue. There was previously some validation before attempting to activate the profile.
