### ISSUE TITLE
Deploy button remain disabled after selecting a node from the capacity filter mode

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#325]
### Description
Deploy button remain disabled after selecting a node from the capacity filter mode

![Peek 2021-12-12 16-26](https://user-images.githubusercontent.com/42457449/147092773-cd280625-b2a9-49a4-bfd3-38306b9052d7.gif)

### Steps to reproduce
- don't try the Manual mode, refresh the page if you did.
- select the Capacity filter mode
- apply filters
- observe that the Deploy button remain disabled
- select different node
- observe that the Deploy button remain disabled

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/344

**Comment by abom** [comment]
Verified.
