### ISSUE TITLE
show "Your solution is now starting. Please be patient" for all solutions including CapRover

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#332]
This message is shown only in Peertube and Funckwhale deployments, should be there in any solution including CapRover

**Comment by sameh-farouk** [comment]
i think it is there for Caprover as well
![Screenshot from 2021-12-22 19-24-54](https://user-images.githubusercontent.com/42457449/147132537-83e1d559-fada-4e48-a7ff-e1e97d21b36c.png)

**Comment by abom** [comment]
Yes, as long as it's already there
