### ISSUE TITLE
failed to apply tfStoreRemove

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#335]
![image](https://user-images.githubusercontent.com/64129/147124621-77f33aa9-9700-4f0b-9de6-bc9186af340d.png)

reported by kristof

**Comment by sameh-farouk** [comment]
+1
I checked two instances of peertube from the VM deployments list and clicked delete. got this error after successful deletion.
`Failed to apply tfStoreRemove in module tfkvStore with test/170/machines/VMa65304f4VMs/contracts.json due to error: NoValueStored`
seems that after the deployments got deleted it tried again to delete it.

**Comment by asamirr** [comment]
Error couldn't be reproduced on devnet

**Comment by asamirr** [comment]
After some investigation and talks with Ahmed Hanafy, the only way this could happen again is by having two tabs open and deleting a deployment from one, navigating to the other tab and deleting it from there too. 

I did some tests and found that we already refresh the deployment list frequently so there's really tiny possibility this could occur.

**Comment by AhmedHanafy725** [comment]
> After some investigation and talks with Ahmed Hanafy, the only way this could happen again is by having two tabs open and deleting a deployment from one, navigating to the other tab and deleting it from there too.
> 
> I did some tests and found that we already refresh the deployment list frequently so there's really tiny possibility this could occur.

if it will be only reproducible by 2 tabs, this won't be resolved as TFChain doesn't support parallelism.

**Comment by asamirr** [comment]
> > After some investigation and talks with Ahmed Hanafy, the only way this could happen again is by having two tabs open and deleting a deployment from one, navigating to the other tab and deleting it from there too.
> > I did some tests and found that we already refresh the deployment list frequently so there's really tiny possibility this could occur.
> 
> if it will be only reproducible by 2 tabs, this won't be resolved as TFChain doesn't support parallelism.

It's not possible to since the delete button gets disabled once you confirm the deletion. It'll show the loading logo right after it starts deleting the deployment!

![image](https://user-images.githubusercontent.com/9322121/153751775-2aceb993-f7b9-41fb-b3be-f3739c63461d.png)

**Comment by waleedhammam** [comment]
> After some investigation and talks with Ahmed Hanafy, the only way this could happen again is by having two tabs open and deleting a deployment from one, navigating to the other tab and deleting it from there too.
> 
> I did some tests and found that we already refresh the deployment list frequently so there's really tiny possibility this could occur.

I tried this scenario but got another error
![Screenshot from 2022-02-21 13-22-17](https://user-images.githubusercontent.com/10658229/154945949-1ee9fbdb-7c32-43c4-a794-00411395e5c6.png)

**Comment by asamirr** [comment]
> > After some investigation and talks with Ahmed Hanafy, the only way this could happen again is by having two tabs open and deleting a deployment from one, navigating to the other tab and deleting it from there too.
> > I did some tests and found that we already refresh the deployment list frequently so there's really tiny possibility this could occur.
> 
> I tried this scenario but got another error ![Screenshot from 2022-02-21 13-22-17](https://user-images.githubusercontent.com/10658229/154945949-1ee9fbdb-7c32-43c4-a794-00411395e5c6.png)

That'd be because parallel operations aren't allowed on the grid!
