### ISSUE TITLE
the 'Back' button is not shown anymore after deployment 

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#336]
### Description
the 'Back' button is not shown anymore after deployment. it require a page refresh to shows the options again. tested on 1303db4652184dad49b04a377e6b1f4933c8bb12

### Steps to reproduce
I saw this after deploying both CapRover and PeerTube, possible there are other affected weblets.

![Screenshot from 2021-12-22 19-24-54](https://user-images.githubusercontent.com/42457449/147133024-031a5969-cab0-400a-816e-679b46ecd82d.png)

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/337
