### ISSUE TITLE
Upgrade to  0.0.36 of grid3_client

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#338]
### Description

currently used version 0.0.35 of grid_client have a known [issue](https://github.com/threefoldtech/grid3_client_ts/issues/161) that affect the validation of the nodes against a specific amount of SRU which fixed in the latest version 0.0.36. should be upgraded.

**Comment by MohamedElmdary** [comment]
### Updated
#### PR
https://github.com/threefoldtech/grid_weblets/pull/343
