### ISSUE TITLE
Profiles to be more intutive

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#34]
Profiles should be unlocked with a secret

first landing page shows two buttons:
   1. load profiles with previously created secret
   2. create a new secret to manage profiles

if "load" is chosen, make sure the secret used exists. if not, return wrong secret

then it goes to the profiles page
  
  any changes page should ask to save when navigating away or to discard changes

**Comment by MohamedElmdary** [comment]
### Fixed
Added message for each case

1. Entry page
![image](https://user-images.githubusercontent.com/31689104/142763121-82e8978e-7c80-4169-948f-fd2080005ef8.png)

2. After adding password and load or create
![image](https://user-images.githubusercontent.com/31689104/142763136-dee41b39-02b7-4d2b-a998-7ef48fdf7fa9.png)

3. Trying to load with a non existing password
![image](https://user-images.githubusercontent.com/31689104/142763147-4dd7f845-961a-4d2f-b0d2-b032b9296a37.png)

4. Trying to create an already existed password
![image](https://user-images.githubusercontent.com/31689104/142763159-d82bf8b1-8bfa-49bc-8c86-7960bd392c71.png)

5. Trying to load an existed password but has a wrong content (for example user updated localstorage)
![image](https://user-images.githubusercontent.com/31689104/142763174-7d1d567f-8bf3-44b5-9338-38d96689d35c.png)
