### ISSUE TITLE
update farming calculator

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#340]
updated formulas https://docs.google.com/spreadsheets/d/1K30cZoZIKj_ecICeCdBHsaLiH6qfdij5tfWdJRJaYs4/edit#gid=14074738

- make a release for www_simulator website

**Comment by MohamedElmdary** [comment]
#### PR
https://github.com/threefoldtech/grid_weblets/pull/341

**Comment by abom** [comment]
Simulator website is updated
