### ISSUE TITLE
increase spacing between apply capacity filter button and nodes found 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#345]
![image](https://user-images.githubusercontent.com/64129/147245971-b8facb48-fb71-424f-b22e-ae73c422b88b.png)

**Comment by MohamedElmdary** [comment]
This button will be Removed after this issue #176

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/355

**Comment by abom** [comment]
![Screenshot from 2021-12-23 18-27-30](https://user-images.githubusercontent.com/511438/147267676-821c06ae-3bbe-4fff-8607-3188667fbb30.png)
