### ISSUE TITLE
disk size in details should be in GB

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#346]
![image](https://user-images.githubusercontent.com/64129/147248866-19c311c9-a98f-493f-87aa-3c12f4d8120d.png)

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/355

**Comment by abom** [comment]
![Screenshot from 2021-12-23 18-54-21](https://user-images.githubusercontent.com/511438/147270577-5058e68e-69cc-4db8-91c3-d015f1066556.png)
