### ISSUE TITLE
UX: Details modal box show outside the visual view-port

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#348]
### Description

when clicking on the `show details` button, it will show the modal box at the top of the document regardless of the visible viewport. with a long list of deployments, the modal box could be completely invisible to the user. 

![Peek 2021-12-23 15-58](https://user-images.githubusercontent.com/42457449/147250794-5e039873-e891-4906-9351-118d02ebea2b.gif)

**Comment by Omarabdul3ziz** [comment]
this is fixed. it is not the case right now on the dev playground
clicking the `Show Details` button view the modal component in the full screen 
![Screenshot from 2022-02-03 14-47-21](https://user-images.githubusercontent.com/32527347/152345689-404fcb5f-93ae-4f19-ab29-d47824682a3a.png)
