### ISSUE TITLE
UX: show sorted deployments by creation order

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#349]
### Description

The current order is not understood, eg, in my CapRovr deployments list, the first one in the list is the last one I deployed, the second one is shown in the list is the last one I deployed, and the last one shown is the second one I deployed.

Should show sorted deployments by creation order instead so it is less confusing to the user.

![Screenshot from 2021-12-23 15-25-28](https://user-images.githubusercontent.com/42457449/147251113-06faec3c-a966-48f8-9b73-9d1ed3997adf.png)

**Comment by abom** [comment]
I think it's nice to have a sort-able table columns too.

**Comment by mohamedamer453** [comment]
Verified on devnet.

I deployed 4 VMs and named them according to their order of deployment and they appeared in the correct order.

![image](https://user-images.githubusercontent.com/101194226/177319590-d695166b-e086-42a0-b722-b9c320273685.png)


The sort-able columns were not added

> I think it's nice to have a sort-able table columns too.
