### ISSUE TITLE
change title

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#35]
change the title of "easy-docs" to "TF Playground"

**Comment by MohamedElmdary** [comment]
# Fixed

**Comment by abom** [comment]
Title has been changed, we need to change the default favicon though, currently it's Vuejs icon.

**Comment by MohamedElmdary** [comment]
### Fixed
- Added favicon

## PR
https://github.com/threefoldtech/grid_weblets/pull/116

**Comment by abom** [comment]
It's a puzzle icon now :)
