### ISSUE TITLE
UX: In the side menu, Contracts and Deployments should be listed after peertube and funckwhale

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#351]
### Description

UX: In the side menu, `Contracts` and `Deployments` should be listed after `PeerTube` and `Funckwhale`.
also, it could be shown in a separate section, eg `LISTS` in the same fashion as `Farming Calculator`.

![Screenshot from 2021-12-23 16-14-41](https://user-images.githubusercontent.com/42457449/147252304-01857e29-7038-4953-b2e4-20a265188753.png)

**Comment by rkhamis** [comment]
duplicate of #438
