### ISSUE TITLE
inconsistent values of disk size

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#357]
Deployed a VM with 50GB disk, but it showed as 53GB after deployment

![Screenshot from 2021-12-23 18-54-21](https://user-images.githubusercontent.com/511438/147270918-de11c722-e8e9-4557-b79d-1e74f4e65ab1.png)

**Comment by dmahmouali** [comment]
regarding [this calculation](https://github.com/threefoldtech/grid_weblets/blob/cc30bc2d87f10f4f203deb7a9b3c3112ad8cc53e/src/components/FormatData.svelte#L42): the 1 GB ( 1024*1024*1024*1 ) = 1.07
so in 50 GB it make the difference.

**Comment by asamirr** [comment]
Attached a 25 GB disk to a VM
![image](https://user-images.githubusercontent.com/9322121/147594343-69a86a7f-de9a-4d68-a5ad-8f4ace37d053.png)

But checking JSON details, it showed 26843545600 bytes which is equivalent to 26.8 GB
![image](https://user-images.githubusercontent.com/9322121/147594442-04f25c7e-89f1-4e6a-b5bd-a9d2739812d9.png)

**Comment by Omarabdul3ziz** [comment]
verified
53687091200 bytes = 50 gigabytes

![Screenshot from 2021-12-30 11-53-34](https://user-images.githubusercontent.com/32527347/147741442-6a777bd5-b344-4230-872b-0e5599184d55.png)

![Screenshot from 2021-12-30 11-55-04](https://user-images.githubusercontent.com/32527347/147741440-97b1d1a7-55b7-4c43-ab28-713fe361a5d4.png)

![Screenshot from 2021-12-30 11-56-32](https://user-images.githubusercontent.com/32527347/147741435-7d5c8d6b-ba20-48e4-a22d-0d84cc5d85d9.png)
