### ISSUE TITLE
Failed to deploy peertube due to invalid name

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#360]
![image](https://user-images.githubusercontent.com/31689104/147404848-80e67c48-2336-4c85-a3dc-81b4a1de167c.png)

probably `peertube` using the solution **name** to prefix network name and disk name which causes this issue

**Comment by asamirr** [comment]
Verified
![image](https://user-images.githubusercontent.com/9322121/147577784-16472a32-389e-4155-a95d-a101428d96bb.png)
