### ISSUE TITLE
Failed to deploy Funkwhale due to invalid name

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#361]
![image](https://user-images.githubusercontent.com/31689104/147404983-b4986258-e7dc-42f7-bc09-e9c5b83a2cda.png)

probably `Funkwhale` using the solution name to prefix network name and disk name which causes this issue

### Related Issues
https://github.com/threefoldtech/grid_weblets/issues/360

**Comment by Omarabdul3ziz** [comment]
That is right in both peertube & funkwhale there is a suffix added to the solution name (Net, VM, VMs, GW, ...)  and that to avoid the "multiple workloads with the same name" error
we can update the validator on the name input to be maxlenght=12 so we can add the prefix and still be the deployment name length=15
or we can extend the allowed max length from the grid_client to be more than 15 char
@AhmedHanafy725 @abom @MohamedElmdary

**Comment by asamirr** [comment]
Verified
![image](https://user-images.githubusercontent.com/9322121/147577134-db4b870a-3f3c-42ad-ac66-ab08e941dbb1.png)
