### ISSUE TITLE
Create a confirmation popup component instead of using a browser alert view

### ISSUE THREAD

**Issue by dmahmouali** [threefoldtech/grid_weblets#369]
What about creating a confirmation popup component instead of using a browser alert?

![image](https://user-images.githubusercontent.com/36021484/147466006-cd7bfb9d-c467-4b36-b6b6-82e5a8fec45d.png)

**Comment by abom** [comment]
I think it's a duplicate of #81?

**Comment by dmahmouali** [comment]
close for duplication
