### ISSUE TITLE
show a warning message when deleting deployments

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#374]
The same as deployment itself

**Comment by MohamedElmdary** [comment]
### Updated
- Added info `Deleteing Deployment`
![image](https://user-images.githubusercontent.com/31689104/147738491-52348827-09b4-4fc5-8b25-bafd15f59486.png)


### PR
https://github.com/threefoldtech/grid_weblets/pull/391

**Comment by mhost39** [comment]
Verified 

![image](https://user-images.githubusercontent.com/31102305/147750345-aef2fb27-6d35-4642-bebf-a74d619d7fe6.png)
