### ISSUE TITLE
Updating SelectNodeId input not triggering validation

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#375]
### Info & Related Issue
https://circles.threefold.me/project/test-tfgrid3/issue/116

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/376

**Comment by abom** [comment]
Needs validation

**Comment by mhost39** [comment]
Verified 
steps: 
set the input and filter the nodes 
after filter done changed the input 
![image](https://user-images.githubusercontent.com/31102305/147752107-59edced1-0849-4c09-a65b-4874b95d3bb9.png)
