### ISSUE TITLE
Possible conflicts in deployment names across different weblets

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#378]
### Description

Possible conflicts in deployment names across different weblets, see https://circles.threefold.me/project/test-tfgrid3/issue/133

### Suggestion

Construct a naming scheme with e.g. solution/deployment type for deployments (might need to remove or make the name limit higher)

**Comment by Omarabdul3ziz** [comment]
to reproduce this 
- deploy a vm 
![Screenshot from 2021-12-30 10-21-50](https://user-images.githubusercontent.com/32527347/147734331-9c58fd40-337e-4302-84d5-cfe93937b336.png)

- deploy a caprover with the same name.. conflict naming happens without the previous VM listed 
![Screenshot from 2021-12-30 10-22-34](https://user-images.githubusercontent.com/32527347/147734523-87d31205-653d-4179-9f36-da9c47bff224.png)

**Comment by abom** [comment]
### Other suggestions

1. Use metadata to store related information like names, solution type...etc, and just generate a unique ID for the actual deployment name
2.  Just mention in the docs for now that names need to be unique across all deployments as @Omarabdul3ziz suggested
3. Update the error message to mention the same as (2)

**Comment by abom** [comment]
See last comment at https://circles.threefold.me/project/test-tfgrid3/issue/133
We need to resolve this, and if any breaking changes will be introduced, we need to communicate this will and update the docs accordingly.

**Comment by AhmedHanafy725** [comment]
> See last comment at https://circles.threefold.me/project/test-tfgrid3/issue/133 We need to resolve this, and if any breaking changes will be introduced, we need to communicate this will and update the docs accordingly.

I think we should make use of the `projectName` in the grid client to split each deployment type from the others.

**Comment by AhmedHanafy725** [comment]
> > See last comment at https://circles.threefold.me/project/test-tfgrid3/issue/133 We need to resolve this, and if any breaking changes will be introduced, we need to communicate this will and update the docs accordingly.
> 
> I think we should make use of the `projectName` in the grid client to split each deployment type from the others. see https://github.com/threefoldtech/grid3_client_ts/blob/development/src/client.ts#L30

@abom, Applying this fix will introduce a breaking change, not sure if we should do it or not?

**Comment by AhmedHanafy725** [comment]
@waleedhammam can you please try again? this should be solved in #562

**Comment by waleedhammam** [comment]
**verified**

**steps**

- deployed instance of peertube named peer
- delete that deployment
- re-deploy that peer
- works ok

**Comment by waleedhammam** [comment]
**verified**

**steps**

- deployed instance of peertube named peer
- delete that deployment
- re-deploy that peer
- works ok
