### ISSUE TITLE
need to refresh page after deployment successfully for my deployment appear in Deployment List

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#379]
See https://circles.threefold.me/project/test-tfgrid3/issue/132

![success](https://user-images.githubusercontent.com/511438/147547642-02821c40-72f3-42eb-a028-57994731e5d0.png)

**Comment by Omarabdul3ziz** [comment]
tried to reproduce this but it works fine for me
![Screenshot from 2021-12-29 12-36-00](https://user-images.githubusercontent.com/32527347/147653706-b06c42e5-8c80-4a51-85a3-97dfde295219.png)

**Comment by mhost39** [comment]
Verified 
![image](https://user-images.githubusercontent.com/31102305/147751511-5b08f399-d8a6-4aad-a67d-d592889d67af.png)
