### ISSUE TITLE
Couldn't get free wireguard ports when trying to deploy a virtual machine

### ISSUE THREAD

**Issue by asamirr** [threefoldtech/grid_weblets#380]
Was trying to reproduce https://github.com/threefoldtech/grid_weblets/issues/379 then,
![image](https://user-images.githubusercontent.com/9322121/147554681-29defe0b-5541-4bcd-a036-e184f1bf4f23.png)

**Comment by MohamedElmdary** [comment]
![image](https://user-images.githubusercontent.com/31689104/147650180-70e79f58-0429-4cae-b761-bd8062090c2e.png)

**Comment by asamirr** [comment]
Verified! Successfully deployed one!
![image](https://user-images.githubusercontent.com/9322121/147923659-e63c4803-adb8-4381-a64a-a84e0cd59920.png)

![image](https://user-images.githubusercontent.com/9322121/147923714-72071004-2f47-4a7d-a8e0-bfe5b6d66b97.png)
