### ISSUE TITLE
Mountpoint can't be duplicated 

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#381]
In `vm` weblet disks can't have the same mountpoint

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/383

**Comment by xmonader** [comment]
![image](https://user-images.githubusercontent.com/64129/147750390-fba18a59-1d40-4164-b91c-0acb32120a33.png)
