### ISSUE TITLE
update documentation to reflect latest changes

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#385]

**Comment by MohamedElmdary** [comment]
### Updated
- Added docs for manage k8s workers

#### PR
https://github.com/threefoldfoundation/info_manual3/pull/30

**Comment by xmonader** [comment]
https://library.threefold.me/info/manual/#/manual__weblets_k8s

![image](https://user-images.githubusercontent.com/64129/147756549-e287bf4f-7933-49bc-929c-cc6bdf71fc36.png)
