### ISSUE TITLE
couldn't find a node

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/grid_weblets#386]
with testnet

when i select a node manual 
i got that node is up and has enough resources
![image](https://user-images.githubusercontent.com/31102305/147648767-11e3189c-77c3-4e53-9a11-56f8d762949c.png)

but when deploy got couldn't find a node
![image](https://user-images.githubusercontent.com/31102305/147648849-340f493e-24f1-4ab1-b297-a57255271e35.png)

**Comment by xmonader** [comment]
was caused by testnet outage
