### ISSUE TITLE
billing for devnet not work 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/grid_weblets#392]
with devnet deployed a VM with (2 cpu, 4 mem and 50G disk) 
the deployment was from 20 hours ago 
and till now It was not deducted from my balance any TFTs

![image](https://user-images.githubusercontent.com/31102305/147739629-dfd48aa0-b276-4784-918f-062dca296ad0.png)

**Comment by xmonader** [comment]
@DylanVerstraete @mhost39 please checkout what's happening

**Comment by DylanVerstraete** [comment]
What is the contract id ?

**Comment by DylanVerstraete** [comment]
My workloads on devnet are still getting billed

**Comment by DylanVerstraete** [comment]
I deployed a new contract and it's getting billed

**Comment by mhost39** [comment]
this is contract id 3758 and till now there are no deducted happend 
and VM running 
![image](https://user-images.githubusercontent.com/31102305/147755749-2f173348-33fc-466c-a837-4989d0dd4b4c.png)

```

{
    "version": 0,
    "contractId": 3758,
    "name": "VM027afd91",
    "created": 1640779657,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/tf-official-apps/threefoldtech-ubuntu-20.04.flist",
    "publicIP": null,
    "planetary": "301:ee1c:672e:9572:ed23:4ba5:e822:c89a",
    "interfaces": [
        {
            "network": "NWd67163a7",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 2,
        "memory": 4096
    },
    "mounts": [
        {
            "name": "DISK75c1a000",
            "mountPoint": "/opt/",
            "size": 53687091200,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVaulbZarLfnE/9flAtT85cezs46qDdgaCHdliQRST16WrJ6jukZvTpWjUo0K/v+UHmxCnkY4KLv3Yl1cWSUFdlSTe21hoK7xEyU9F21PbhzKQASQga/J4QUxyZpdMybzt9ndlFsOy7x0xNUSMljf38za2yHGcpKGRw1Ungd4PBWKv0sKTKYjhHoHCTa72NAc95EMFJpvfowVWJvsxgjcHjOSaQpRQiXb3eHfMj5I4h7yhJOFin7GVev6bSwPEJRN+ydGiCmv3paNGvJbFEOROIBAp6q78RDf4rNyf3Vr244yB8ffl6bKpPb4LA0Ntex+e7jaxzBWAboiWXxDEadG2P/RAfciXasICZXLcZTfjlbXJ1OHTe/aStEgy36IWvt/SwKcazG/2V0enc3UwE/SzeqGyPT9A8HhuMn9TB4cYOTh9146Gl63EtTBnFX3z5EqQwytFyyxXToqDOuJAMYB2gKHsB1ePhWZOLxiguOPlU3ZSHm9XI+wZEcBNJ6B2yOM= hassan@hassan-Inspiron-3576"
    },
    "entrypoint": "/init.sh",
    "metadata": "",
    "description": ""
}

```

**Comment by DylanVerstraete** [comment]
When did you create this contract?

**Comment by DylanVerstraete** [comment]
I looks like it's an issue with the node itself, we are going to investigate.

**Comment by mhost39** [comment]
it worked now 
![image](https://user-images.githubusercontent.com/31102305/147760748-94bbf66a-0726-4cfd-a00c-7242ba4961b6.png)

**Comment by muhamadazmy** [comment]
It worked because of the following:

The node had a big list of queued reports that needed to get pushed to the grid. For some reason that is known until the writing of this commit, the node wasn't actively pushing those reports.

I added some logging, and restarted the reporter process and this allowed the node to start pushing the reports again. We will keep an eye on it see if reporting stops at some point
