### ISSUE TITLE
SelectNodeId updating back to first node when changing tabs

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#394]
This issue appears when u're using a **SelectNodeId** component when a weblet that supports multi tabs `k8s`

Its might change workers selected nodes if user moved between tabs during filling cluster data

how to reproduce:
1. Go to k8s weblet
2. Go to `Master` tab
3. Select `capacity filter` from **Node Selection**
4. Click `Apply Filters and suggest Nodes`
5. Pick any node **not first one**
6. Go to `Workers` tab then get back to `Master`

**Comment by MohamedElmdary** [comment]
should be fixed in https://github.com/threefoldtech/grid_weblets/pull/405

**Comment by abom** [comment]
I think this is related to the answer to this question https://github.com/threefoldtech/grid_weblets/issues/176#issuecomment-1061239894

**Comment by AhmedHanafy725** [comment]
already solved in #579
