### ISSUE TITLE
Billing Rate increases for some reason

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#398]
Created a `k8s` cluster include **1 master** and **10 workers**

here is a table for pricing monitoring in 4 hours
**Time**|**Billing Rate**
:-----:|:-----:
11:00 AM|No Data Available
12:00 AM|1 TFT/Hour
01:00 PM|7 TFT/Hour
02:00 PM|11 TFT/Hour
03:00 PM|13 TFT/Hour

**Comment by xmonader** [comment]
As mentioned in the chat, this is related to the discount level (basically you get cheaper deployments when you have money in your wallet)
