### ISSUE TITLE
default memory is wrong in nodes filter

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#40]
![image](https://user-images.githubusercontent.com/64129/143274702-25cb5d22-dfb5-4acd-8904-2ff09a17ad6e.png)

**Comment by abom** [comment]
Now it's correct and linked to memory size selected for deployment

![Screenshot from 2021-12-02 05-58-47](https://user-images.githubusercontent.com/511438/144355146-ce6e224a-64ca-4bc7-b5f6-62417274ebe1.png)
