### ISSUE TITLE
deleting deployment logs are a bit confusing

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#402]
The message need to more clear, deleting is not a special type of deployment (can be a generic message that handles all types, not just "Deployments")

### Sreenshots

![Screenshot from 2021-12-31 00-02-24](https://user-images.githubusercontent.com/511438/147790821-12bcf74d-f2c7-4900-af0d-59f2feaf6848.png)

**Comment by MohamedElmdary** [comment]
Can you recommend a better **message** ? @abom @xmonader

**Comment by MohamedElmdary** [comment]
### Updated
#### PR
https://github.com/threefoldtech/grid_weblets/pull/413

**Comment by abom** [comment]
Verified
