### ISSUE TITLE
Workers not listed in `kubectl get nodes`

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#404]
![image](https://user-images.githubusercontent.com/31689104/147870043-6aac474c-4370-44e9-bc3d-6b7570c075cc.png)

**Comment by ashraffouda** [comment]
seems bad network config, the issue is not reproducable

**Comment by RafyAmgadBenjamin** [comment]
it is not reproducible to me too, I have deployed 5 workers and got all of them in the k8s
![image](https://user-images.githubusercontent.com/46320202/147929158-5316b6e0-a4b8-4e67-985f-105e3d5dc5e8.png)
