### ISSUE TITLE
community tools

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#406]
first set of community tools

- [x] taiga
- [x] mattermost
- [x] peertube
- [x] forum tool (discourse)

##  min requirements

- TF connect integrated
- planetary network support (always)
- public ip addr support (ipv4/6)
- automatic deployment (just ask for region)
- all with ubuntu 20.04
- use ufw firewall to only open relevant ports (ssh, http for planetary network, https when pub ip addr)
- make sure email address is asked for in the tool and visible to the users in the tool
- make sure the name shown is without .3bot (can be later)

**Comment by despiegk** [comment]
its not finished yet, jonas is working on items too, please link the stories from his team here.
We are waiting for more clean builders (docker) and better TFConnect integration.

**Comment by jdelrue** [comment]
https://github.com/threefoldtech/tf-images/issues/72

**Comment by xmonader** [comment]
@jdelrue why did you use another repo? please use either tf-images or the repo that we have for each solution.

**Comment by xmonader** [comment]
jimber can provide the flists to switch to in the future.
