### ISSUE TITLE
Mattermost weblet

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#407]
Make sure to have the minimum requirements in #406.

**Comment by MohamedElmdary** [comment]
### PR
https://github.com/threefoldtech/grid_weblets/pull/428

**Comment by mhost39** [comment]
Verifying 
https://github.com/threefoldtech/grid_weblets/pull/428  this pr need to merge

**Comment by sameh-farouk** [comment]
Verifying this locally on the `development_mattermost` branch.
wasn't able to verify this as there were multiple issues in the weblet UI and the running instance itself.

Issues:
![Screenshot from 2022-01-24 19-32-07](https://user-images.githubusercontent.com/42457449/150834582-e91fbb1b-ceec-4986-98ea-70eafa6d131a.png)

**mail server fields:**
- There are missing SMTP settings fields, to set a valid SMTP service you need a set of configuration which only two of them was provided in the Weblet UI:
SMTP Server host and SMTP Server Port was provided but missing fields are SMTP Server Username, SMTP Server Password, and Connection Security depending on what the SMTP server accepts.

- Please use a separate mail server tab like in Owncloud and Taiga Weblets and make sure to include all required fields for SMTP to work. 

**Fileds validations:**
- SMTP host field lacks the domain name validation.

**Fields default values:**
- The password filed wasn't filled with a generated password like other solutions.
- The SMTP port filed has an invalid default SMTP port, 8000. another valid SMTP ports should be considered instead, eg: 25, 465, 2525, 587  

deployment info:
the deployment succeeded message lack the relevant info, eg: the instance domain name. should be consistent with other solutions.
![Screenshot from 2022-01-24 18-23-41](https://user-images.githubusercontent.com/42457449/150835385-51d94c05-aeda-4d4d-a67e-01f5361c6e5e.png)

- the deployment list of the solution lacks the visit button. should be consistent with other solutions.
![Screenshot from 2022-01-24 18-24-31](https://user-images.githubusercontent.com/42457449/150837443-cc945446-c5b9-4415-8c9c-5230c444a44a.png)

**deployed Mattermost instance:**
- there is no option provided on the solution after deployment to log in using the admin credentials provided in the Weblet (the username and the password), instead, I can only create a new user account by using the TF connect app. The first user to log in with the TF connect app will have the system_admin role, which gives them access to the System Console.
![Screenshot from 2022-01-24 18-50-57](https://user-images.githubusercontent.com/42457449/150837563-b4f5e556-2b1d-4a8d-87fe-77a56bc7e7a9.png)

- the given SMTP hostname and the port from the Weblet UI weren't passed to the deployed instance. 

- there are errors in the console log: `Error: Plugins have been disabled. Please check your logs for details. user can't install plugins.`. visiting the marketplace user will have the error shown in the screenshot
![Screenshot from 2022-01-24 19-49-37](https://user-images.githubusercontent.com/42457449/150837057-527cdb0b-7605-45c9-add4-dcf0e7aa536c.png)

**other minor issues:**
please make filed names consistent with the other solutions.

**Comment by mhost39** [comment]
Verified with development branch
