### ISSUE TITLE
Update peertube weblet

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#408]
Make sure to have the minimum requirements in #406.

**Comment by Omarabdul3ziz** [comment]
## Features implementation tracking
Already exist: 
- [x] TF connect integrated
- [x] planetary network support (always)

To add:
- [ ] public ip addr support (ipv4/6)
- [ ] automatic deployment (just ask for region)

- [ ] use ufw firewall to only open relevant ports (ssh, http for planetary network, https when pub ip addr)
- [ ] make sure email address is asked for in the tool and visible to the users in the tool
- [ ] make sure the name shown is without .3bot (can be later)

**Comment by mhost39** [comment]
Verified with development branch
