### ISSUE TITLE
Forums (discourse) weblet

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#410]
Forked at https://github.com/freeflowuniverse/freeflow_forum

Make sure to have the minimum requirements in #406.

**Comment by RafyAmgadBenjamin** [comment]
I have reached our discourse forked repo and found that we maintain an image which deploy the whole thing, I have tested it and it is working but it takes while due to the lack of docs and description for the environment variables used in this image but it is working and I have tested the tf connect and it is working also

**Comment by RafyAmgadBenjamin** [comment]
we have faced some issues in building the image again regarding 
- SSH but now it builds successfully
- export PATH variables as we work on VM in ZOS

we created discourse weblets and is it working now with the image, still, we need to do more changes to the image to match the issue requirements

**Comment by Omarabdul3ziz** [comment]
Currently, the issues (while converting the base to be ubuntu 20.04) were fixed. and the image built successfully tagged with `threefolddev/discource:v1.6`. But there is something that keeps killing the unicorn server (which serves the ruby project) and the supervisor keeps restarting it. Now we are trying to figure out what causes that

**Comment by RafyAmgadBenjamin** [comment]
Now the image is running on ubuntu 20.04 and all is working good

**Comment by RafyAmgadBenjamin** [comment]
we update the image to include the firewall and support ipv4, and ipv6

**Comment by Omarabdul3ziz** [comment]
Currently, the images have all the minimum requirements mentioned. `threefolddev/discource:v3.0`


We moved the database creation and migration from the entrypoint to the dockerfile, to speed up deployment start time. * which was about 15 min *
Now nginx start immediately after the deployment is finished and keep responding with "Nginx: bad gateway" till unicorn server started * which it takes 5-7 min * 


We may write a custom HTML page for Nginx to show while the server is not ready. that contains "please wait for the server to be ready".

**Comment by RafyAmgadBenjamin** [comment]
### Done 
### Branch 
`development_discourse_weblet`
### Commit 
d042f657eb5998529ca7bf63e67cf64c62aed47c
### PR
https://github.com/threefoldtech/grid_weblets/pull/487

**Comment by asamirr** [comment]
Verified from development_discourse_weblet

![image](https://user-images.githubusercontent.com/9322121/150673146-8edcd847-52d3-4898-b5f1-193fe301a9ae.png)

![image](https://user-images.githubusercontent.com/9322121/150673133-06557018-d90f-4b6c-8fd8-43bd01a591f7.png)

**Comment by mhost39** [comment]
Verified in development branch
