### ISSUE TITLE
verify disk name duplicates before deploying a VM

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#411]
### Description

Disks can be added with duplicated names and the deployment fails, see https://circles.threefold.me/project/test-tfgrid3/issue/129

**Comment by MohamedElmdary** [comment]
Verified

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/414

**Comment by abom** [comment]
Verified.
