### ISSUE TITLE
changing capacity does not trigger re-validation

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#412]
https://circles.threefold.me/project/test-tfgrid3/issue/116

**Comment by Omarabdul3ziz** [comment]
That is not the case in play.dev either play.grid.
any change in (cpu, memory, storage, public ip) on all weblets triger revalidating 
![Screenshot from 2022-01-03 12-46-23](https://user-images.githubusercontent.com/32527347/147922298-c1158f89-2d15-4652-914e-bb7e1baaf7ef.png)
![Screenshot from 2022-01-03 12-46-31](https://user-images.githubusercontent.com/32527347/147922297-40bb1d74-dc72-4a18-9085-5ccfa5ff00cf.png)

**Comment by abom** [comment]
They mentioned the following in the original issue

> We can still reproduce it when deploying a VM, since changing the disk size after selecting a node, does not re-trigger validation, and the Deploy button remains active.

**Comment by abom** [comment]
I cannot reproduce it too, will close this for now and we can open another one later if exact steps were reported.
