### ISSUE TITLE
/opt/ as default field value to disk mount-point doesn't make sense 

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#416]
### Description

`/opt/` as default field value to disk mount-point doesn't make sense as it is reserved for the installation of add-on application software packages, instead, the use of subdirectories in `/mnt` as a mount point has recently been common and we should use `/mnt/` as a default parent directory value for the disk mount point filed concatenated with a lower case version of the disk name as a subdirectory.

check [Linux filesystem hierarchy standard](https://www.linuxjournal.com/content/filesystem-hierarchy-standard) for more info.
or the bigger [reference](https://www.pathname.com/fhs/pub/fhs-2.3.html) if in doubt.

so instead of 
![Screenshot from 2022-01-03 14-19-11](https://user-images.githubusercontent.com/42457449/147930025-ee71a42a-31b4-4013-8640-4b1e1ad57df4.png)

let's have something like
![Screenshot from 2022-01-03 14-24-29](https://user-images.githubusercontent.com/42457449/147930123-262f0b5a-0a17-40d7-880c-f3061d803abb.png)

**Comment by MohamedElmdary** [comment]
@abom @rkhamis Should we update disk mount point to follow this ? `/mnt/disk_name` respecting no duplication rules

**Comment by rkhamis** [comment]
okay.

**Comment by AhmedHanafy725** [comment]
> @AhmedHanafy725 if we specify "/mnt/disk_name", would zos have a problem if the parent directory doesn't exist?

No, it will create the parent directories

**Comment by sameh-farouk** [comment]
@MohamedElmdary The suggestion was to present a reasonable default value. But Disabling the field is not a good idea limiting the user options.

**Comment by abom** [comment]
@MohamedElmdary Please update the screenshot, it's already done in the PR

**Comment by Omarabdul3ziz** [comment]
verified on development playground
![Screenshot from 2022-02-08 12-59-47](https://user-images.githubusercontent.com/32527347/152974340-96c8352e-03a1-4108-8d7c-373348fc1d9e.png)
