### ISSUE TITLE
Remove redundant info from peertube and funkwhale

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#421]
previously, the deployment was not shown after deployment succeeded. so we need to add extra info in the successful message (domain, planetary IP) Now this info is listed in a better format in the deployment list so there is no need to keep them in the successful message. we can get enough with `Successfully deployed a Peertube instance` like other weblets. 

The current state 
![Screenshot from 2022-01-04 13-20-53](https://user-images.githubusercontent.com/32527347/148052445-83ad7f37-0358-4e5b-974f-68c55f2e0b8d.png)

what I meant
![Screenshot from 2022-01-04 13-28-50](https://user-images.githubusercontent.com/32527347/148052652-99dbf2e9-56de-4c4c-a4ce-0788750c35d1.png)

**Comment by asamirr** [comment]
Verified! 

![image](https://user-images.githubusercontent.com/9322121/153059465-df00b1ad-360f-4ac3-81c6-99588dec9a9c.png)
