### ISSUE TITLE
OWNCLOUD weblet

### ISSUE THREAD

**Issue by christopherhutton** [threefoldtech/grid_weblets#433]
### Description

we planning a softlaunch of oWNCLOUD on top of TF. GRID so we need a weblet to deploy this app on the grid. We do already have helm charts for 2.x 

### Implementation

intended deployment for th soft launch program is on MAINNET, 10k users, freemium for 3 months

### More

we need this avail by end january to co incide with the public launch

**Comment by waleedhammam** [comment]
I'm starting creating a weblet using the image in https://github.com/threefoldtech/vdc-solutions-charts/tree/master/charts/owncloud

**Comment by christopherhutton** [comment]
hi waleed

ive asked weynand herein to confirm we are using the correct version of
owncloud for this weblet

tx so much

**Comment by waleedhammam** [comment]
@christopherhutton Hello, the version here is 10.8

**Comment by christopherhutton** [comment]
perfect, tx

**Comment by waleedhammam** [comment]
fremuim option to continue in https://github.com/threefoldtech/www_owncloud/issues/1

**Comment by mhost39** [comment]
Verified 
![image](https://user-images.githubusercontent.com/31102305/150681440-20007c3c-a062-479d-8d90-b5caf8bf94df.png)
![image](https://user-images.githubusercontent.com/31102305/150681421-7e4ea50c-0cba-4479-af15-1c49ba3684eb.png)
