### ISSUE TITLE
Show amount billed even when it's under 1 TFT

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/grid_weblets#434]

**Comment by MohamedElmdary** [comment]
`Less than 1 TFT` most of time converts into **0.00000xx**

**Comment by DylanVerstraete** [comment]
It still provides more information then "less than 1 TFT"

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/519

**Comment by AhmedHanafy725** [comment]
billed amount now unitless
![image](https://user-images.githubusercontent.com/41957921/152689583-95dcf203-6a80-4098-9712-7000bfafd4b0.png)

**Comment by asamirr** [comment]
Verified!

![owncloud5](https://user-images.githubusercontent.com/9322121/152979472-5be7efbf-9c37-43a3-a83e-fc033edb82de.png)
