### ISSUE TITLE
When changing the values of cpu and memory in VM and setting the node selection, it didn't open the node options

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#436]
on: https://play.dev.grid.tf

![image](https://user-images.githubusercontent.com/41957921/148683363-45a5a68a-6167-449b-953b-11b08fa3645d.png)

![image](https://user-images.githubusercontent.com/41957921/148683539-f7a861f1-5186-4463-8f97-cf8ee7c54cb2.png)

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/437

**Comment by abom** [comment]
For verification

**Comment by dmahmouali** [comment]
verified on https://play.grid.tf/#/vm
