### ISSUE TITLE
Categorize the sidebar components 

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/grid_weblets#438]
![Screenshot from 2022-01-09 17-09-05](https://user-images.githubusercontent.com/26298009/148688416-bda2cf73-eddf-405d-bce7-b80e7ab4b59e.png)

move deployment and contracts to another tap e.g. My_Account  in the end of side bar to not confuse the user

**Comment by MohamedElmdary** [comment]
### Updated
#### PR
https://github.com/threefoldtech/grid_weblets/pull/441
