### ISSUE TITLE
Integrate public ipv6 in vms creation

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/grid_weblets#439]
Was included in https://github.com/threefoldtech/grid3_client_ts/releases/tag/1.0.5

Can be ipv4 only, ipv6 only or both
Note public ipv6 is free to use

**Comment by MohamedElmdary** [comment]
### Added
#### PR
https://github.com/threefoldtech/grid_weblets/pull/443

**Comment by abom** [comment]
For verification

**Comment by dmahmouali** [comment]
- VM
![image](https://user-images.githubusercontent.com/36021484/149788653-39be0c67-c787-4ef0-86e2-34dbc8e2c0b2.png)
```
PING 2a10:b600:1:0:ac4e:c7ff:fe1f:9195(2a10:b600:1:0:ac4e:c7ff:fe1f:9195) 56 data bytes
64 bytes from 2a10:b600:1:0:ac4e:c7ff:fe1f:9195: icmp_seq=1 ttl=55 time=13.9 ms
64 bytes from 2a10:b600:1:0:ac4e:c7ff:fe1f:9195: icmp_seq=2 ttl=55 time=13.2 ms
64 bytes from 2a10:b600:1:0:ac4e:c7ff:fe1f:9195: icmp_seq=3 ttl=55 time=13.2 ms

--- 2a10:b600:1:0:ac4e:c7ff:fe1f:9195 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 13.206/13.461/13.953/0.372 ms
```

**Comment by dmahmouali** [comment]
- K8s
![image](https://user-images.githubusercontent.com/36021484/149790859-fe073bc5-3a9e-42ea-8373-455b14f748eb.png)
![image](https://user-images.githubusercontent.com/36021484/149790938-98fbadf6-1611-4841-a81f-af387ed684af.png)
