### ISSUE TITLE
Smaller heading for Nodes Filter component

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#44]
![image](https://user-images.githubusercontent.com/64129/143294076-1d75178e-018f-4f85-af1a-1462e419737a.png)

**Comment by abom** [comment]
Verified

![Screenshot from 2021-12-02 05-55-06](https://user-images.githubusercontent.com/511438/144354958-3c98c1e5-db49-4965-beae-ada92e566997.png)
