### ISSUE TITLE
cannot see what nodeid is in details from VM

### ISSUE THREAD

**Issue by hossnys** [threefoldtech/grid_weblets#445]
https://github.com/threefoldtech/tf_operations/issues/556

**Comment by AhmedHanafy725** [comment]
requires https://github.com/threefoldtech/grid3_client_ts/issues/205

**Comment by AhmedHanafy725** [comment]
done in grid3 client version 1.0.6

**Comment by AhmedHanafy725** [comment]
grid client is already updated on play.grid.tf 

![image](https://user-images.githubusercontent.com/41957921/151699746-393d1fc0-de05-4267-b793-97b81414b2cf.png)
