### ISSUE TITLE
invalid disk size does not prevent deployment

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#447]
### Description

Invalid disk size does not prevent the user to deploy.

### Steps to reproduce

See https://circles.threefold.me/project/test-tfgrid3/issue/146

### Logs/Alerts

See https://circles.threefold.me/project/test-tfgrid3/issue/146

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/456

**Comment by dmahmouali** [comment]
Verified on https://play.grid.tf/#/vm
![image](https://user-images.githubusercontent.com/36021484/149780719-74710e27-3145-4817-b11b-2f2ff048ed0b.png)
