### ISSUE TITLE
Contract deletion failed

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#448]
### Description

See https://circles.threefold.me/project/test-tfgrid3/issue/148

**Comment by AhmedHanafy725** [comment]
it's related to this issue https://github.com/threefoldtech/tfchain/issues/115

**Comment by AhmedHanafy725** [comment]
seems working normally now

![image](https://user-images.githubusercontent.com/41957921/149170872-57cbee62-71d5-4c24-9d21-9cfb33969260.png)

![image](https://user-images.githubusercontent.com/41957921/149170857-7b61ac47-f9b9-4cb1-9498-34a34d4a6cce.png)

**Comment by dmahmouali** [comment]
Verified on https://play.dev.grid.tf
