### ISSUE TITLE
caprover updates

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#45]
1- show domain in the table? is that possible?
2- next to show details and delete button let's have "admin link" that goes to `captain.$domain`
3- tooltip that the default password in captain42
4- nodes filter in caprover needs fixing,

**Comment by abom** [comment]
Listing in caprover is a bit confusing, it shows VMs, k8s and caprover nodes in three tabs, all showing the same deployments.

**Comment by abom** [comment]
Verified

![Screenshot from 2021-12-02 05-50-35](https://user-images.githubusercontent.com/511438/144354760-b020b101-160f-48dd-bb3d-3ef0adc395ca.png)
