### ISSUE TITLE
`DeploymentList` weblet shows undefiend

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#450]
Issue info can be found here https://circles.threefold.me/project/test-tfgrid3/issue/130

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/451

**Comment by abom** [comment]
For verification

**Comment by dmahmouali** [comment]
Verified on https://play.grid.tf/#/deployedlist

![image](https://user-images.githubusercontent.com/36021484/149780047-5f8be46a-15ce-4daa-a340-1e0aaac65805.png)
![image](https://user-images.githubusercontent.com/36021484/149780164-9514683f-5975-415e-9a42-e3f51976d503.png)
![image](https://user-images.githubusercontent.com/36021484/149780197-0dd45b0f-6937-4c7a-a1ba-c5d960b71c78.png)
![image](https://user-images.githubusercontent.com/36021484/149780234-d5e85c75-2c40-4e5d-a99b-46d195f2cae1.png)
![image](https://user-images.githubusercontent.com/36021484/149780289-6c8f568a-7874-44f2-83f8-ab8e951f2d5d.png)
