### ISSUE TITLE
I deployed 2 VMs but they do not show up in the overview

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#460]
I deployed 2 VMs using play.grid.tf using my testnet profile. <img width="1273" alt="Screenshot 2022-01-13 at 17 57 18" src="https://user-images.githubusercontent.com/30384423/149374933-4cd3d1a7-86b2-4809-b14b-8121395921a1.png">The weblet reflects for a long time and then doesn't show any VM deploy. While 2 are running. 

<img width="1273" alt="Screenshot 2022-01-13 at 17 55 52" src="https://user-images.githubusercontent.com/30384423/149374847-5bbab052-b467-4498-aa43-e2c7681b8a09.png">

<img width="1273" alt="Screenshot 2022-01-13 at 17 57 18" src="https://user-images.githubusercontent.com/30384423/149374933-4cd3d1a7-86b2-4809-b14b-8121395921a1.png">

<img width="1273" alt="Screenshot 2022-01-13 at 17 55 34" src="https://user-images.githubusercontent.com/30384423/149374992-fe2358b8-7dea-44b4-ac58-c2384cf5fff0.png">

**Comment by MohamedElmdary** [comment]
@AhmedHanafy725 any idea about this deployments list issue ?

**Comment by gmachtel** [comment]
I imagine it was timeouts or sthg. I found them in the list at another moment.

**Comment by MohamedElmdary** [comment]
@gmachtel Great Thanks
