### ISSUE TITLE
CasperLabs validator node

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#461]
Needed as part of grant36

see 
- https://github.com/casper-network/casper-node 
- https://github.com/make-software/how-to-casperlabs/blob/master/docs/ubuntu/setup-mainnet-validator-from-scratch.md

**Comment by ranatrk** [comment]
@gmachtel The node starts and we are able to retrieve the status and show the node ip in the list  of peers. 

Do we need the node to bond and become funded or the end user will handle that once the node is setup?
https://github.com/make-software/how-to-casperlabs/blob/master/docs/ubuntu/setup-mainnet-validator-from-scratch.md#bond-to-the-network

- snippet of /status
```

**Comment by gmachtel** [comment]
I'd say it is sufficient for the first milestone of grant36. @despiegk @weynandkuijpers please advise about need to bond.

**Comment by waleedhammam** [comment]
verified

![image](https://user-images.githubusercontent.com/10658229/155107160-21503be3-38e0-4f3f-844c-4f0157c525c4.png)
