### ISSUE TITLE
Presearch weblet 

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#462]
Presearch is the biggest external community that has used eVDC. Their wiki still shows https://docs.presearch.org/nodes/vps-setup/threefold which is eVDC instructions (on TFGridv2). A weblet based solution for Grid 3 would look like:

**Minimal specs**
- Take users Presearch node registration code as environment variable
- Deploys a small VM with a public IP (1 vcpu and 512mb RAM is enough, but needs at least 1gb ssd)
- Installs Docker and launches `dockerd`
- Runs the Presearch container with:
```
docker stop presearch-node ; docker rm presearch-node ; docker stop presearch-auto-updater ; docker rm presearch-auto-updater ; docker run -d --name presearch-auto-updater --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock presearch/auto-updater --cleanup --interval 900 presearch-auto-updater presearch-node ; docker pull presearch/node ; docker run -dt --name presearch-node --restart=unless-stopped -v presearch-node-storage:/app/node -e REGISTRATION_CODE=$YOUR_REGISTRATION_CODE_HERE presearch/node ; docker logs -f presearch-node
```
- In case VM reboots for any reason, launches `dockerd` and Pre container again

**Nice to have**
- Allow user to also import their node identity by inputting its key pair somewhere in the process, either as env variable or on status dashboard. Keys are saved at `/var/lib/docker/volumes/presearch-node-storage/_data/.keys/`
- Reuse status dashboard website from VDC deployment found [here](https://github.com/threefoldtech/tf-images/tree/development/tfgrid2/presearch)
- Also allow exporting of keys to save node identity when node has generated a new one
- Perform some kind of authentication before allowing a reset via status site (easy way would be to have them input their registration code again, along with next item)
- Make registration code treated as a secret (show only last few characters)

**Maybe someday**
- Container runs as a zflist without a VM (this requires some automation to promptly create and deploy new flists whenever the Pre container is updated, because outdated nodes aren't allowed on the network)

__Important__ : 
- Pre nodes need a unique IPv4 egress
- Regular and mandatory updates are made in the docker file, so an auto update feature is necessary

**Comment by scottyeager** [comment]
I've edited the spec to clarify and simplify. Personally, I don't think TF Connect as an authentication method is a good idea here. It adds a dependency that doesn't otherwise exist. Ideally someone can buy TFT with btc or fiat to fund their TF Chain wallet and never need to touch Stellar TFT or the Connect app if they don't want to.

**Comment by gmachtel** [comment]
Ok I just wanted to use tf connect app as authentication mechanism to do updates. I once posted the status UI page from vdc on website and got the remark that restart could be abused if url is open for everyone. But indeed, shouldn’t be too complicated. Other possibilities to protect button ‘restart’ from pushing by anyone ?

**Comment by scottyeager** [comment]
Indeed, there is a minor security risk if the restart button is not somehow protected. In practice, this requires knowing the url of the page. Simply not sharing the url is usually enough.

That raises a design question here. Do we want to assign urls like the vdc does, or simply use the public IP? IP + some unique string (deployment name, maybe) could be enough to prevent guessing and abuse.

As I mentioned above, having the user provide their registration code again would be a simple additional security measure.

One more note from our call with Presearch, we can also pass in a node name and url when launching the container. These are environmental variables, I believe. Would need to check their names.

**Comment by RafyAmgadBenjamin** [comment]
Verifying this

**Comment by RafyAmgadBenjamin** [comment]
Verified
