### ISSUE TITLE
Deployment of a new VM with IP address on testnet for Freefarm using play.grid.tf gives 'no nodes available'

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#463]
<img width="1273" alt="Screenshot 2022-01-13 at 18 18 58" src="https://user-images.githubusercontent.com/30384423/149377876-326d4ab4-17bb-4f06-905a-96771edd31c2.png">

**Comment by rkhamis** [comment]
@gmachtel did freefarm on the eplorer have free ips?

**Comment by gmachtel** [comment]
yes there were IPs available then (but for some reason things were not captured)

**Comment by abom** [comment]
I think this need to be re-verified at https://play.test.grid.tf

**Comment by Omarabdul3ziz** [comment]
it works fine on play.test, I can get nodes available for both options ipv4 and ipv6 on freefarm
![Screenshot from 2022-03-13 11-57-57](https://user-images.githubusercontent.com/32527347/158054411-94ce0a9a-af1e-4883-9a4e-dcfd007944ae.png)
