### ISSUE TITLE
Set overlay in modal to be fixed and moving with screen

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#464]
Set overlay in modal to be fixed and moving with screen

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/465

**Comment by abom** [comment]
For verification

**Comment by dmahmouali** [comment]
Verified on https://play.dev.grid.tf/
