### ISSUE TITLE
Funkwhale failed to deploy due to inability to verify signature

### ISSUE THREAD

**Issue by asamirr** [threefoldtech/grid_weblets#467]
![image](https://user-images.githubusercontent.com/9322121/149780846-49c905d0-997e-4491-bdbc-cfe13636f743.png)

**Comment by AhmedHanafy725** [comment]
Verified
commit: 8ff29aab8fd85fa9771bb21546e6c155c56d0fdd

![image](https://user-images.githubusercontent.com/41957921/149797270-5274e862-2655-4571-8340-7411d90f7ca9.png)
