### ISSUE TITLE
validation against node_id 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#47]
when the user manually choose a node id we need to run checks against it and never allow deployment to go through

**Comment by abom** [comment]
Still does not validate against manually selected node IDs, shows ">Loading..."  message, with no errors

Steps to reproduce:
* Refresh and activate your profile
* Got to e.g. Virtual Machine deployer and select "Ubuntu"
* Write an invalid node ID e.g. "7878787"
* Click deploy

It will be loading forever

![Screenshot from 2021-12-02 04-28-30](https://user-images.githubusercontent.com/511438/144346566-0310af98-30eb-4e57-9469-2ac876f728fe.png)

**Comment by abom** [comment]
Another thing happened, when I tried to select node (3) with CapRover manually, it loaded for sometime, then just showed the form again without any errors or useful information shown.


https://user-images.githubusercontent.com/511438/144353525-09f0c028-20d6-414c-9911-0b3c378677c2.mp4

**Comment by abom** [comment]
@xmonader Suggested to the validation for node existence is done in-place, without changing the view to allow the user to modify it and try again instead of re-entering all information again.

**Comment by abom** [comment]
It should check using `https://gridproxy.<NETWORK>.grid.tf/nodes/<NODE ID>/status`, and the "Deploy" button is till not disabled if the node is not found.

Last note, the green message saying "Checking if node exists" can have a "..." at end or something and the whole text can be in red until it's validated, then it turns green.

**Comment by MohamedElmdary** [comment]
### Fixed

#### PR
https://github.com/threefoldtech/grid_weblets/pull/127

**Comment by ranatrk** [comment]
verified
![Screenshot from 2021-12-09 14-43-52](https://user-images.githubusercontent.com/17128393/145398750-fc01e562-5b79-464f-bcb6-bc1951f1820e.png)
![Screenshot from 2021-12-09 14-43-41](https://user-images.githubusercontent.com/17128393/145398754-4b7b0188-2ba7-4289-96ac-df560415746c.png)
![Screenshot from 2021-12-09 14-43-18](https://user-images.githubusercontent.com/17128393/145398759-9084af3d-31b1-4508-bdad-b521cc8fe491.png)
