### ISSUE TITLE
update farming calculator

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#470]
- needs to be inline with https://library.threefold.me/info/threefold#/tfgrid/farming/threefold__resource_units_calc_cloudunits
 - min token price

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/473

**Comment by asamirr** [comment]
![image](https://user-images.githubusercontent.com/9322121/150173982-53485dcf-8717-491c-8d06-aace72472aef.png)

**Comment by MohamedElmdary** [comment]
@asamirr can you provide the values used to produce negative cu and nu ?

**Comment by abom** [comment]
@asamirr @MohamedElmdary What is the status of this one? do you need any input from other team members?
