### ISSUE TITLE
Can't deploy Taiga's gateway

### ISSUE THREAD

**Issue by asamirr** [threefoldtech/grid_weblets#471]
It says there's another gateway name even after deleting all deployments and contracts from my account 
![image](https://user-images.githubusercontent.com/9322121/149793836-067d7873-a1c6-4a96-a2b8-ee573051bc81.png)

**Comment by AhmedHanafy725** [comment]
This can happen if the gateway's contract is deleted from the contracts tab, so the key in the TFKV store is still not removed.

**Suggested solution**
To invalidate the cache for the gateways by listing them while listing the VMs

**Comment by AhmedHanafy725** [comment]
**Verified**

commit: 0b6bc0175660f5fda6733efee479ed7271662d28

### steps
- deploy taiga with name `VMac7e2d85`
- delete the contracts 
- deploy taiga again with name `VMac7e2d85`

it worked fine
