### ISSUE TITLE
funkwhale: the generated password must be changed to be able to deploy

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#472]
no validation error is raised, but can't deploy unless the password is changed by adding or removing character

![image](https://user-images.githubusercontent.com/41957921/149793925-3a412001-7f6b-4024-9575-c2162f17688b.png)

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/473

**Comment by mhost39** [comment]
Verified
