### ISSUE TITLE
Deployments not always showing when sharing a substrate wallet

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_weblets#475]
### Description

We want several people to have access to the same deployments on play.grid.tf
This would be so within TF Ops team several people can manage the same deployments on the grid. We shared the mnemonic of the wallet and each add this as a profile on play.grid.tf. We are able to add the profile, see the account balance and list the deployed contracts under Deployment -> Contracts.
What does not seem to be working is listing the deployments. One person was able to list them, but another not. In the case of VM's, no VM's appear under Deployment -> Virtual Machine or Deployments.
When using other profiles on play.grid.tf everything is working fine. The issue only appears with a wallet / deployments someone else created, and another person is trying to list and manage them (using the same mnemonic and ssh public key as profile on play.grid.tf)

### Steps to reproduce

- Create profile and add name, net, mnemonics and public key
- Save and activate the profile
- Navigate to Deployment -> Virtual Machine: no virtual machines appear
- Navigate to Deployment -> Contracts: the deployed contracts do appear

### Logs/Alerts
Virtual Machines:
![image](https://user-images.githubusercontent.com/88312671/149806757-8290198b-d3a1-4da4-ba9c-90b5a7ed1bbc.png)

Contracts:
![image](https://user-images.githubusercontent.com/88312671/149806825-54aa978d-9566-4564-a81e-1657c5e6d219.png)

Deployments:
![image](https://user-images.githubusercontent.com/88312671/149806895-34375e90-e01e-48c7-8b59-7adfbc27f1d3.png)

Browser developer tools / console:
![image](https://user-images.githubusercontent.com/88312671/149807015-1fe21eb1-d391-4cf7-a9a0-9684a9218db7.png)

Don't hesitate to get in touch, I can show the issue if you want to debug.

**Comment by AhmedHanafy725** [comment]
@coesensbert can you also share with them the same password to activate the profile? 

as this password is used to decrypt the deployment info

![image](https://user-images.githubusercontent.com/41957921/149905403-0f9e4564-03e3-4de4-9e2b-b6123240d4d6.png)

**Comment by coesensbert** [comment]
Awesome, using the same profile manager password works! Thanks @AhmedHanafy725
