### ISSUE TITLE
The password icon (eye icon) should be the opposite

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#476]
opened -> when the password is shown
closed -> when the password is NOT shown

![image](https://user-images.githubusercontent.com/41957921/149906608-d7941b71-55ba-4e51-94c8-9cad37dcb811.png)

**Comment by MohamedElmdary** [comment]
I thought about it as
click `open eye` to open it (show password)
@AhmedHanafy725

**Comment by MohamedElmdary** [comment]
#### PR
https://github.com/threefoldtech/grid_weblets/pull/491

**Comment by AhmedHanafy725** [comment]
**Verified**

commit: 65747cfc733c962e3bb9c9a41801d1d8f0ac80f9

![image](https://user-images.githubusercontent.com/41957921/150337170-48940724-3f20-4cf6-b463-a38d2a180e9b.png)
