### ISSUE TITLE
validate mnemonic while saving the profile

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#48]

**Comment by MohamedElmdary** [comment]
Added but while activating

### Done

**Comment by abom** [comment]
Verified, it validates mnemonics when "Activate" is clicked

![Screenshot from 2021-12-02 05-53-16](https://user-images.githubusercontent.com/511438/144354733-df0e32e0-4bba-4a04-92d5-166ab4338aa1.png)
