### ISSUE TITLE
peertube and funkwhale create a useless contract on the access nodes

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#483]
as long as the user can't select the network name and has no access to the private network, there is no need for `addAccess` in the network configuration, as it creates a contract that slows down the deployment, also paying for it.

**Comment by AhmedHanafy725** [comment]
caprover as well

**Comment by RafyAmgadBenjamin** [comment]
verifying this

**Comment by RafyAmgadBenjamin** [comment]
Verified on `development` branch 
- I have checked this On VM
![image](https://user-images.githubusercontent.com/46320202/153211383-c8282c6a-859d-4320-b831-0818bb378fd2.png)
and also in peertube
