### ISSUE TITLE
Add a disclaimer to farming calculator

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#484]
issue info at https://circles.threefold.me/project/despiegk-product_tfgrid3_roadmap/us/373?milestone=184

**Comment by MohamedElmdary** [comment]
### Updated
#### PR
https://github.com/threefoldtech/grid_weblets/pull/485

**Comment by asamirr** [comment]
Verified!

![image](https://user-images.githubusercontent.com/9322121/150160544-9ee3d967-5e81-4b4d-b83c-bd1b6d1403b6.png)
