### ISSUE TITLE
Weblet: vm name need validation 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/grid_weblets#486]
![1](https://user-images.githubusercontent.com/31102305/150128191-ec61b852-7c82-47c3-a962-9bb6af1aabe3.png)

**Comment by rkhamis** [comment]
@mhost39 it's up to the user what to name their deployment.
what validation do you want to add here?

@AhmedHanafy725 are we in line in validation with zos?

**Comment by mhost39** [comment]
> @mhost39 it's up to the user what to name their deployment. what validation do you want to add here?
> 
> @AhmedHanafy725 are we in line in validation with zos?

The name can accepts numbers only 
is this accepted that name can by only number?

**Comment by AhmedHanafy725** [comment]
> @AhmedHanafy725 are we in line in validation with zos?

yes, also it's more restricted to alphanumeric only.

@mhost39 did you try it and it didn't work?

**Comment by mhost39** [comment]
i can deploy with name as a number and this not make sense
![image](https://user-images.githubusercontent.com/31102305/151829894-512c6c6b-730f-4c9e-9cdb-a8a44ab8546c.png)

**Comment by RafyAmgadBenjamin** [comment]
verifying this

**Comment by RafyAmgadBenjamin** [comment]
## Verified
on https://play.dev.grid.tf/#/

![image](https://user-images.githubusercontent.com/46320202/153413170-281778c5-31a1-46a5-b4c1-c92b7704ef50.png)
