### ISSUE TITLE
Disconnect the grid client after finishing the execution

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#49]
After deploying, listing, and deleting, the grid client should be disconnected

**Comment by abom** [comment]
[Not all occurrences](https://github.com/threefoldtech/grid_weblets/search?q=grid.connect) of `client.connect()` is accompanied by `client.disconnect()`. IMO, A better solution is to share an instance as long as the tab/browser is open, then add `disconnect()` call when the window is closed in `window.onbeforeunload` or `window.beforeunload`.

**Comment by AhmedHanafy725** [comment]
The connection pool is implemented on the inner tfgrid client and all these clients are disconnected on `window.onbeforeunload`.

### suggestions
- We can have a connection pool as well on the outer grid3 client.
- Add a flag on the inner tfgrild client `connected` once the connect method is called so it won't connect again.

**Comment by abom** [comment]
This is already handled by grid client (see https://github.com/threefoldtech/grid3_client_ts/pull/129)
