### ISSUE TITLE
Can't deploy Discourse after filling all required fields

### ISSUE THREAD

**Issue by asamirr** [threefoldtech/grid_weblets#495]
Tried to deploy an instance from branch "development_discourse_weblet"

![image](https://user-images.githubusercontent.com/9322121/150671425-864b5014-0f72-40b0-9967-2e3550cd2326.png)

**Comment by Omarabdul3ziz** [comment]
Filling the input fields in the Mail Server tab is required.

Discourse needs SMTP server to be configured right so it can send the verification main to the admin mail you provided

**Comment by asamirr** [comment]
Thanks @Omarabdul3ziz it worked fine! 

![image](https://user-images.githubusercontent.com/9322121/150672127-37d58c22-7cdd-4243-9d15-9b9c40d8cfd9.png)

But don't you think we should place the warning message in the "Config" tab so the user wouldn't be confused?

**Comment by rkhamis** [comment]
let's make it a required field

**Comment by Omarabdul3ziz** [comment]
already all mail server fields are required

**Comment by mhost39** [comment]
Verified 
![image](https://user-images.githubusercontent.com/31102305/152148394-49f41de2-c67a-451f-9710-ec1ec4d615dd.png)
