### ISSUE TITLE
Rootfs sizing is too limiting

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#500]
Rootfs size is currently calculated as:

```
const x = (cpu_in_cores * (memory_in_mb / 1024)) / 8;
return Math.max(x, 50);
```

This means a deployment with 1 vcpu and 1gb of RAM gets 125mb rootfs. This is too small. According to CU calculations, this deployment consumes at least .25 CU. Since farmers are expected to have 50gb SSD per CU, I would expect at least 12.5gb of SSD attached for the root filesystem.

Is this calculation implemented as intended? If so, why?

**Comment by scottyeager** [comment]
@rkhamis or @MohamedElmdary, any thoughts on this?

**Comment by coesensbert** [comment]
+1 on this one.
Had several deployments where i attached a disk, but something else consumed space on / so got "disk quota exceeded".
Would be nice to be able to set the root_fs_size, like we can when deploying with terraform

**Comment by despiegk** [comment]
this was not intended, something went wrong in translation to engineering.

@muhamadazmy please can you remind us what we discussed?

was something like 500MB for VM < 4 GB mem and 2 GB for one + 4 GB (this is just for the root)
and lets not forget the images are flists, which means only new data counts for this.

this is included storage in the CU

ofcourse intent is people add zmounts for additional storage e.g. mount there /opt or whatever ... makes sense

**Comment by muhamadazmy** [comment]
> was something like 500MB for VM < 4 GB mem and 2 GB for one + 4 GB (this is just for the root) and lets not forget the images are flists, which means only new data counts for this.
> 
> this is included storage in the CU

You are correct. The limitation set by ZOS, is 500MB (rootfs space)  for small machines (less that 8 CU (cpy x mem)) and 2G minimum limit for bigger machines.

Note, User can ask any size bigger than the limit (the rootfs is also billed)
For all VMs, you can attach as many disks to your VM (zmount) which you pick the size with no limits (unless the node can't provide the requested capacity).

the difference between a rootfs and zmount is that a zmount is a separate worklaod so you can delete the VM and reuse the disk with another VM. unlike the rootfs which is the root of your system and is deleted with the VM.

**Comment by abom** [comment]
We should allow the user to choose a size bigger or equal to ZOS limit

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/543

**Comment by asamirr** [comment]
Verified! Rootfs size updated to all solutions!

**Comment by asamirr** [comment]
Verified!
