### ISSUE TITLE
Owncloud: Update Owncloud image to use Redis as memory caching

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#503]
on fresh deployed Owncloud instances, we get these warnings in the admin dashboard. 
![Screenshot from 2022-01-25 15-45-36](https://user-images.githubusercontent.com/42457449/150988617-5bcc49a4-05eb-4f87-a472-4ce7df9a4bc8.png)

2 of them are critical to the instance performance and should be fixed in our image

> You can significantly improve OwnCloud server performance by using memory caching. This is the process of storing frequently requested objects in memory for faster retrieval later. 

> File locking is enabled by default, using the database locking backend. This places a significant load on your database. Using memcache.locking relieves the database load and improves performance. Admins of ownCloud servers with heavy workloads should install a memory cache .

Redis is recommended for a single Owncloud server.

https://doc.owncloud.com/server/10.8/admin_manual/configuration/server/caching_configuration.html

**Comment by sameh-farouk** [comment]
fixed #524

**Comment by asamirr** [comment]
Verified!
