### ISSUE TITLE
Owncloud: missing SMTP Encryption type in mail server configuration 

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#504]
![Screenshot from 2022-01-25 16-00-43](https://user-images.githubusercontent.com/42457449/150990850-739650b4-b502-4fbd-a7dc-730d91a97eb3.png)

SMTP service won't work unless we specify the type of encryption the mail server use. either STARTTLS or SSL/TLS

**Comment by asamirr** [comment]
Verified
