### ISSUE TITLE
Cannot run locally - 404 error for the any weblet window

### ISSUE THREAD

**Issue by nbabenko** [threefoldtech/grid_weblets#506]
1. Went through the README manual step by step
https://github.com/threefoldtech/grid_weblets#readme
2. On the "Run The Playground" step when I run "npx serve docs" and open http://localhost:3000/ weblets are not loading.
3. Browser log:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
notification.wc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
profiles.wc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/build/elements/vm.wc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/build/elements/kubernetes.wc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/build/elements/deployedlist.wc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/build/elements/caprover.wc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/build/elements/farmingcalculator.wc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/build/elements/funkwhale.wc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/build/elements/peertube.wc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/build/elements/taiga.wc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/build/elements/owncloud.wc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/build/elements/contractslist.wc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)`
```

<img width="1387" alt="Screenshot 2022-01-26 at 1 09 54 PM" src="https://user-images.githubusercontent.com/4426772/151152935-952494e1-b727-4153-a6d0-4cc3a56cfa3e.png">

4. Same issue for other weblets. 

**My environment:**
macOS 12.1
Brave Browser Version 1.34.80 Chromium: 97.0.4692.71 (Official Build) (arm64) 
(same issue for Google Chrome latest version)

mykolababenko@Mykolas-MacBook-Air grid_weblets % npm version
{
  'svelte-app': '1.0.0',
  npm: '8.1.2',
  node: '16.13.2',
  v8: '9.4.146.24-node.14',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '93',
  nghttp2: '1.45.1',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l+quic',
  cldr: '39.0',
  icu: '69.1',
  tz: '2021a',
  unicode: '13.0',
  ngtcp2: '0.1.0-DEV',
  nghttp3: '0.1.0-DEV'
}

**Comment by MohamedElmdary** [comment]
can you check this video and try again ?
https://user-images.githubusercontent.com/31689104/149097600-be76b899-32a7-498d-96b8-b645a54a2232.mp4

**Comment by MohamedElmdary** [comment]
@nbabenko Did you check the video and tried again ?

**Comment by rkhamis** [comment]
@nbabenko i'll close this since you don't seem to have an issue anymore
