### ISSUE TITLE
Node Selection filters are removed when tab is changed

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#51]
### Steps

on virtual machine
1- Set CPU, memory, and node selection filters
2- Go to the disks tab
3- Go back to config 

### Result

Node selection filters are gone

### Expected

Node selection filter should be still set

**Comment by MohamedElmdary** [comment]
### Fixed

#### PR
https://github.com/threefoldtech/grid_weblets/pull/117

**Comment by abom** [comment]
Verified.
