### ISSUE TITLE
Lost deployed workload list since gridproxy/explorer upgrade

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_weblets#511]
### Description

Since we upgraded the Gridproxy and Explorer on Dev and Testnet, i'm not able to list any deployments i had on play.grid.tf
![image](https://user-images.githubusercontent.com/88312671/151523867-b16c6157-a47e-4734-8e48-e213e7f4d604.png)

### Steps to reproduce

Login, activate profile and try to list previous deployments

**Comment by scottyeager** [comment]
I have observed the same behavior.

**Comment by asamirr** [comment]
Verified on Devnet
![workloadlisting](https://user-images.githubusercontent.com/9322121/151698207-7a2020c7-a009-49d2-ac66-59b9ef04949f.gif)
