### ISSUE TITLE
Capacity validation blocking all deployments

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#512]
I can't currently deploy anything via weblets, apparently because capacity detection is not working properly. The capacity filter never returns any nodes, and manual selection will not allow deployments to proceed on any node.

**Comment by asamirr** [comment]
Just deployed a VM with CentOS and a Funkwhale instance using the Capacity Filter on Devnet.
Here's Funkwhale's link for verification:

https://fw98capvalid.gent01.dev.grid.tf

**Comment by scottyeager** [comment]
Indeed, seems resolved now.
