### ISSUE TITLE
Separate devnet, testnet and mainnet into different playgrounds

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#514]
since we can have node upgrades that make deployments on different nets incompatible, we should have:

- [x] play.dev.grid.tf  ---> only deploys on devnet. this should have latest development. can be broken.
   - [x] add a disclaimer to say "This is a development environment. We're still ironing out the kinks. if there are any issues please let us know [here](https://circles.threefold.me/project/test-tfgrid3/issues)"
- [x] play.test.grid.tf ---> only deploys on testnet. this should have the latest draft release. anything here should have been verified internally.
   - [x] add a disclaimer to say "This is a testing environment. We're still ironing out the kinks. if there are any issues please let us know [here](https://circles.threefold.me/project/test-tfgrid3/issues)"
 - [x] play.grid.tf ----> only deploys on mainnet. should have the latest release.

**Comment by asamirr** [comment]
Solved and kept in draft until the infra is ready https://github.com/threefoldtech/grid_weblets/pull/516
