### ISSUE TITLE
Mattermost need to add in deployment list

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/grid_weblets#522]
![image](https://user-images.githubusercontent.com/31102305/152146083-ba10119c-061f-4202-8dbb-0ca93bdb3be4.png)

**Comment by AhmedHanafy725** [comment]
Verified 

![image](https://user-images.githubusercontent.com/41957921/152358691-0b8dc4df-ec55-4839-890c-44c5d955111c.png)
