### ISSUE TITLE
Failed to deploy as network's name exceed the max length 

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#534]
- discourse
can be reproduced by entering a 15 characters name for the deployment
- kubernetes 
can be reproduced by entering more that 15 characters for the network's name

![image](https://user-images.githubusercontent.com/41957921/152676534-a2d0d49b-4d0d-4fd2-a32b-df64cd4b2944.png)

**Comment by MohamedElmdary** [comment]
verified

**Comment by asamirr** [comment]
Just deployed an instance with a 15 character name
![image](https://user-images.githubusercontent.com/9322121/153180053-17edbafa-19ba-41bc-82d1-5343c8778729.png)
