### ISSUE TITLE
branches & documentation

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/grid_weblets#545]
create a branch for 1.2.1 release
make sure right code is there

code for 1.2.2 needs to be on other branch = goes to devnet

development will be 1.2.1 

after verification -> master

document how to build 1.2.1 & how to use it

**Comment by xmonader** [comment]
release branches release_1.1.4 and release_1.2.0 branches been created, however the build process in this repo is configured as follows

preleases -> trigger staging env changes
releases -> triggers main env changes
