### ISSUE TITLE
Balance not updated in playground after TFT transfer from Stellar over bridge

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#546]
On mainnet

I transferred 500 TFT over bridge using portal from Stellar to tfchain-mainnet. 
Play.grid.tf doesn't update, even not after hard refresh. 
Portal shows correct balance. 
<img width="213" alt="Screenshot 2022-02-09 at 14 27 42" src="https://user-images.githubusercontent.com/30384423/153210790-160fc205-579b-476b-b767-8bc67120163c.png">
<img width="1280" alt="Screenshot 2022-02-09 at 14 27 34" src="https://user-images.githubusercontent.com/30384423/153210878-cfd7bd54-db01-4601-bf7d-77a727577c2b.png">
<img width="1280" alt="Screenshot 2022-02-09 at 14 27 10" src="https://user-images.githubusercontent.com/30384423/153210965-babfcb27-b3cf-4063-82e9-0b95d5e343a5.png">

**Comment by MohamedElmdary** [comment]
Balance is update once every 1 min

**Comment by gmachtel** [comment]
Now it seems to work
