### ISSUE TITLE
can't get balance for weblet account 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/grid_weblets#547]
with https://play.grid.tf/
![image](https://user-images.githubusercontent.com/31102305/153234128-0304c93e-9192-474e-981f-bf6b436bafe4.png)

**Comment by AhmedHanafy725** [comment]
@mhost39 are you sure your profile is activated?

**Comment by sameh-farouk** [comment]
also could you try to clean you browser cache and check again

**Comment by mhost39** [comment]
> 

yes activated and i used this account in deployment before

**Comment by abom** [comment]
I think we need to re-verify this.

@mhost39 Please provide more information about used network or try to verify on any network.

**Comment by mhost39** [comment]
i tried it now and worked fine
