### ISSUE TITLE
show the spec alongside the package/flavor name

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#549]
### Description
- we could display the spec after the flavor name. E.g. Minimum (CPU:2, RAM:4) so the user can have a better insight about what he will get.
- it would be better to rename the field `Capacity Package`  —> `Solution Flavor` or `Server Flavor`

**Comment by rawdaGastan** [comment]
- That's how it looks after changes.
- Hanafy suggested that we add a vertical space for the options (I agree with him) but unfortunately after some tries I found that 
` Unfortunately, WebKit browsers do not support styling of <option> tags yet, except for color and background-color`
So if we need to change them I think we will create a custom select options 
[
![Screenshot from 2022-06-23 15-14-04](https://user-images.githubusercontent.com/47260239/175324408-176d2bc9-ea43-41f2-9506-03007ffe603e.png)
](url)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The `Capacity Package` was changed to `Solution Flavor` and now it shows the specs of each `Flavor`.

![image](https://user-images.githubusercontent.com/101194226/179391054-4b694e75-b7c3-4a9b-a14f-dfc35b24f433.png)

**Comment by sasha-astiadi** [comment]
@sameh-farouk Flavour is not the right english word. Can we change all things that say Flavour into 'Set Up'?
