### ISSUE TITLE
Mattermost: move SMTP settings fields to separated tab for consistency's sake 

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#550]
### Description
in Mattermost weblet, move SMTP settings fields to a separated tab for consistency's sake, similar to the other solutions with SMTP settings Discourse/Owncloud/Taiga.

**Mattermost:**
![Screenshot from 2022-02-09 18-36-24](https://user-images.githubusercontent.com/42457449/153246642-702886cd-6391-4611-8b31-d030cb97788a.png)
**Discourse:**
![Screenshot from 2022-02-09 18-39-48](https://user-images.githubusercontent.com/42457449/153247063-a636e199-32cc-4bd2-b603-d7ece032cc9b.png)

**Comment by mohamedamer453** [comment]
Verified in #617 

Mattermost SMTP setting were moved to a separate tab to be consistent with the rest of the Weblets.

![image](https://user-images.githubusercontent.com/101194226/175288779-82eeccb6-fe30-4bdd-b77a-4a36d81e47f0.png)

![image](https://user-images.githubusercontent.com/101194226/175288832-fb0adcf4-265d-4dd5-8398-c300ed4d9ba2.png)
