### ISSUE TITLE
Failed deployment on play.test

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#553]
please see: https://circles.threefold.me/project/test-tfgrid3/issue/178

**Comment by AhmedHanafy725** [comment]
couldn't reproduce this issue on testnet or devnet, but a better error message is added on grid3_client

**Comment by AhmedHanafy725** [comment]
currently available on play.dev.grid.tf

**Comment by ranatrk** [comment]
couldn't reproduce, 
- successfully deployed on node 1 and 12 a vm
- successfully deployed on different nodes other than 1 and 12 multiple kubernetes clusters
