### ISSUE TITLE
Mainnet: failed deployment after successful vm creation via play.grid.tf

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_weblets#558]
### Description
Via play.grid.tf we deployed a vm on node 8 (freefarm) with pub ipv4 & ipv6. So far so good, removed the vm again.

Right after that we wanted to deploy on a GE farm (GreenEdge-Enterprise-Vienna2), node 306, where we encountered the following error:
![failed-deployment-main](https://user-images.githubusercontent.com/88312671/153902748-419f243d-4686-48d0-b396-5ef6cfa4ea8b.png)

The error seems to state there was a failure of creating the network on node 8 (which is a node with public config). It also complains about a failed signature verification, which we suspect comes from play.grid.tf.

### Steps to reproduce

- Create VM with pub ipv4 & 6 on node 8
- Delete the deployment
- Create a VM with same config on node 306

### Logs/Alerts

![image](https://user-images.githubusercontent.com/88312671/153903356-1afff8b3-5cec-4ffb-b0ff-e21e9b9907f5.png)

**Comment by xmonader** [comment]
CC @AhmedHanafy725

**Comment by AhmedHanafy725** [comment]
it's related to deployment update and it's solved here https://github.com/threefoldtech/grid3_client_ts/issues/228 but not released yet

**Comment by AhmedHanafy725** [comment]
mainnet 1.2.0 is just released.

**Comment by AhmedHanafy725** [comment]
### verification steps

- create a Kubernetes cluster with a network's name `test`
- create another cluster with the same network's name `test`

**Comment by asamirr** [comment]
Verified! Deployed 2 clusters using same network name for both!

![image](https://user-images.githubusercontent.com/9322121/157032140-99f80e6e-7633-4536-a24b-08a7c6ea3270.png)

![image](https://user-images.githubusercontent.com/9322121/157032259-0feb050a-d2df-44d4-aa47-c3c11a70b634.png)
