### ISSUE TITLE
Taiga description need to update  

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/grid_weblets#559]
Taiga is not  social platform to enjoy and share music
https://library.threefold.me/info/manual/#/manual__weblets_taiga
![image](https://user-images.githubusercontent.com/31102305/154026461-3674e8db-d1bc-4339-b27a-53c6a815138a.png)

**Comment by asamirr** [comment]
Fixed now!
https://library.threefold.me/info/manual/#/manual__weblets_taiga
