### ISSUE TITLE
When Deleting a deployment, it deletes only the machine

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#562]
### Steps to reproduce

- Deploy peertube
![image](https://user-images.githubusercontent.com/41957921/154500453-0b6e4645-679d-4a7f-8583-97f1793be197.png)

- Check the contracts tab (there will be 3 contracts)
![image](https://user-images.githubusercontent.com/41957921/154500411-5f9f9e36-48f5-489e-81b1-1bbd8d19df1e.png)

- Delete the deployment from the solution tab or deployment list
![image](https://user-images.githubusercontent.com/41957921/154500908-e403a5eb-ebfc-4ef4-be42-ff92c21dc512.png)

- Check the contracts tab again
![image](https://user-images.githubusercontent.com/41957921/154500889-75862b39-fbd8-418e-83f5-27cedbf10c66.png)

### Result 
2 contracts are not deleted (the gateway ones)

### Expectation 
Deleting deployment should delete any related contracts to this deployment.

**Comment by waleedhammam** [comment]
verified also on play.dev.grid.tf
