### ISSUE TITLE
apply capacity packages on Presearch

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#564]
Presearch weblet still has the old way to choose the hardware specs. it needs the `SelectCapacity` component to be applied.
![Screenshot from 2022-02-20 11-34-23](https://user-images.githubusercontent.com/32527347/154836691-39b064dc-6937-425b-a6c3-7336ae7e929e.png)

**Comment by waleedhammam** [comment]
![Screenshot from 2022-02-22 12-46-42](https://user-images.githubusercontent.com/10658229/155116908-a34d2996-260b-4554-b5ce-d3ab94479575.png)
verified on play.dev.grid.tf
