### ISSUE TITLE
undefined js variable

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#567]
https://circles.threefold.me/project/test-tfgrid3/issue/181

**Comment by MohamedElmdary** [comment]
We not able to reproduce this issue

**Comment by abom** [comment]
It's firefox, I think we need to mention which browsers do we support at least in docs or readme.

**Comment by asamirr** [comment]
I just updated the docs stating Google Chrome as the browser we're supporting at the moment with more browsers to be supported soon!
