### ISSUE TITLE
Discourse: Admin e-mail doesn't arrive

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#573]
I set up a discourse instance on devnet (https://play.dev.grid.tf), but the e-mail for admins never arrived, despite 'resend' etc. Not in spambox either. ContractID 8006. 

<img width="1280" alt="Screenshot 2022-02-23 at 08 28 34" src="https://user-images.githubusercontent.com/30384423/155277397-315f07aa-2a2e-472f-93ed-e477da8b41a7.png">

**Comment by asamirr** [comment]
Seems like there might be a problem with you mail server. Verified here!
![image](https://user-images.githubusercontent.com/9322121/157465666-aed61520-1a9d-42a8-9e74-b181100fe5cf.png)

![image](https://user-images.githubusercontent.com/9322121/157465729-742e1e5c-e7e8-4598-818c-a6d55258cb0e.png)
