### ISSUE TITLE
CasperLabs and Presearch not selectable as 'deployed solution' on testnet

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#576]
No tab in playground to see the deployed installations of CasperLabs and Presearch. 

Does it make sense to have a separate tab for each solution ? Will become messy soon. 
But of course, we need to be able to see the deployments.

**Comment by abom** [comment]
There's a tab already for CasperLabs and Presearch, can be reached from `My Account -> Deployments`
