### ISSUE TITLE
Presearch node suddenly stopped working, ssh into machine revealed minimisation happened

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#577]
PRE weblet on play.dev.grid.tf, ran since Feb 17 (devnet). 
PRE node was suddenly disconnected on Feb 23. 

I ssh'd into the VM, it appeared to be 'minimized'. Is this the reason that it stopped working ? If so, automated minimisation needs to be deactivated. 
Dockers were also stopped (is obviously the reason that node was disconnected), but I guess it's due to the minimisation process. 

ContractID 7838 on devnet. 

<img width="524" alt="Screenshot 2022-02-23 at 14 46 12" src="https://user-images.githubusercontent.com/30384423/155331696-58b89d25-ee4a-456b-8118-d192a690f190.png">

I had to unminimize and restart the dockers to make it working again.

**Comment by abom** [comment]
I think we need to investigate how this "minimization" happened, and if anything from our side caused it.

**Comment by gmachtel** [comment]
Please do so. Info is acailable in the issue.

**Comment by AhmedHanafy725** [comment]
I remember at that day a reboot was done for devnet's nodes, maybe that was the reason

**Comment by gmachtel** [comment]
OK that could explain. But does this mean that rebooting a node anywhere in the grid will make that workloads on it won't restart ? Will have to be tested thoroughly, this is not desirable behaviour.

**Comment by OmarElawady** [comment]
Is the machine still running? If it's can you print the output of `uptime`, `zinit list`, `zinit status dockerd`, and `zinit log`?

And can you please clarify how did you restart docker? The [image](https://github.com/threefoldtech/tf-images/blob/development/tfgrid3/presearch/Dockerfile) is running on top of zinit. So if docker got killed, zinit should restart it.

By default, the image is `minimized` so this shouldn't be an issue.

Zinit had an [issue](https://github.com/threefoldtech/tf-images/issues/77) that might have caused this, but the output of the commands should indicate if it's or something else.

**Comment by gmachtel** [comment]
Hm, I stopped it. Now a new one is running, I’ll reopen when issue reoccurs.
