### ISSUE TITLE
Go back to explicit resource selection i.o. capacity package in PRE weblet

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#578]
Workload selection has been changed from an explicit mentioning (ex. 1 CPU, 1024 MB memory, 10 GB disksize) to a 'capacity package' (minimum, standard, recommended, custom), without explicit mention on what it means. 

For the Presearch weblet, this absolutely doesn't make sense, because
- the container has a fix size, specified on their wiki: https://docs.presearch.org/nodes/setup#hardware-specification . So no need to select multiple options. 
- however, when crawling and indexing features will be created, these sizes might change, so it needs to be modifiable
- people are used to select explicitly what they want, this gives them 'control' 

Once change is made, doc can be updated in their wiki https://docs.presearch.org/nodes/vps-setup/threefold which still points to eVDC on TFGrid2. 
Would be a good use case to test out whether people will hoard TFTs so they benefit from the 60% price reduction in usage.

**Comment by abom** [comment]
These capacity packages were requested by https://github.com/threefoldtech/grid_weblets/issues/489, also, I think no need to remove these "packages" as there's already a custom option where the user have the choice to configure required capacity.

We can discuss if this is not clear enough, because any changes to capacity filter would affect all other weblets, not only Presearch.

**Comment by abom** [comment]
If the only issue is that terms like "Minimum", "Standard"...etc are not clear, then we need to update the docs to explain what is meant.

**Comment by gmachtel** [comment]
It’s not that they’re not clear, for a weblet such as presearch it’s useless. Please go to one explicit size, and keep it adaptable.

**Comment by gmachtel** [comment]
Presearch was not mentioned in #489 !

**Comment by abom** [comment]
As discussed with @rkhamis and @xmonader

* On hover we should show a tip explaining these packages
* And add a flag to disable packages and allow only custom values.

**Comment by gmachtel** [comment]
Status?

**Comment by MohamedElmdary** [comment]
Remove `SelectPackages` from `Presearch` weblet and used the recommended (1 CPU, 1024 MB memory, 10 GB disksize) values as default

#### PR
- https://github.com/threefoldtech/grid_weblets/pull/637

**Comment by gmachtel** [comment]
For now this is ok, but as soon as crawling/indexing (end of May/early June) functionality appears, is there a way to explicitly specify the resources ? I see the selection has become impossible now.
