### ISSUE TITLE
Kubernetes node selection changes with tab switching

### ISSUE THREAD

**Issue by ranatrk** [threefoldtech/grid_weblets#579]
### Description

When deploying kubernetes cluster, and selecting a node to deploy the master on then switching to the worker tab to select its resources and node, the node selection is reset to the first one in the drop down when switching back to the master tab (and vise versa when switching from masters to the workers tab)
The deployment occurs with that node instead of the node originally selected by the user. 

example run: the drop down's first node is node 1, after choosing node 18 and doing the switching between tabs the master was deployed on node 1

### Steps to reproduce
- In masters tab of kubernetes deployment, select capacity finder, and select a node other than the first one
- switch to the workers tab, select the configurations there then switch back to the master's tab
- the node selection in the drop down is the first node rather than the one previously selected

### Logs/Alerts
example of switching back: switches to first item in list(node 2)
![Screenshot from 2022-02-27 12-49-31](https://user-images.githubusercontent.com/17128393/155879540-86c25993-a24c-4ffa-a962-c747778819c0.png)

example after deployment when first item in list was used(node 1)

```

{
    "masters": [
        {
            "version": 0,
            "contractId": 3199,
            "nodeId": 1,
            "name": "WR5996a85f",
            "created": 1645955636,
            "status": "ok",
            "message": "",
            "flist": "https://hub.grid.tf/tf-official-apps/threefoldtech-k3s-latest.flist",
            "publicIP": {
                "ip": "185.206.122.145/24",
                "ip6": "2a10:b600:1:0:6c56:faff:fe2f:aa89/64",
                "gateway": "185.206.122.1"
            },
            "planetary": "300:2589:76ee:f44e:34fc:da49:b72c:b913",
            ......
        }
    ],
    "workers": [
        {
            "version": 0,
            "contractId": 3199,
            "nodeId": 1,
            "name": "WR82134216",
            "created": 1645955640,
            "status": "ok",
            "message": "",
            "flist": "https://hub.grid.tf/tf-official-apps/threefoldtech-k3s-latest.flist",
            "publicIP": null,
            "planetary": "300:2589:76ee:f44e:aaa:724d:26e5:7b4",
            ......
        }
    ]
}

```

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR

**Comment by abom** [comment]
For validation

**Comment by Omarabdul3ziz** [comment]
verified on development playground

the case now. it sticks with the selected node id after switching tabs. However, switching tabs triggers the filter to research again and return with the selected node again. is that ok?
