### ISSUE TITLE
peertube: .gent01.dev.grid.tf is hardcoded in peertube weblet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#58]
![image](https://user-images.githubusercontent.com/64129/143488506-be6b793a-ccd0-4c72-b313-17f122e0554a.png)
```
PEERTUBE_WEBSERVER_HOSTNAME: name + ".gent01.dev.grid.tf",
```

**Comment by waleedhammam** [comment]
verified
fixes at: https://github.com/threefoldtech/grid_weblets/blob/development/src/utils/gatewayNode.ts and 
https://github.com/threefoldtech/grid_weblets/blob/2a92a85aca934541455f5f3ff26cce31e05ea674/src/utils/deployPeertube.ts#L51
