### ISSUE TITLE
Installation dependencies are not complete

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/grid_weblets#580]
When following the installation instructions, a few things should be added.

Dependemcy:
- rollup (sudo apt install rollup)
- svelte (npm install --save-dev svelte rollup-plugin-svelte)
- commonjs (npm install @rollup/plugin-commonjs --save-dev)
- node-resolve (npm install @rollup/plugin-node-resolve --save-dev)
- rollup-plugin-terser (npm i rollup-plugin-terser --save-dev)
- svelte-preprocess (
- plugin-typescript (npm i plugin-typescript)

Then I did ```npm update```
And then ```npm audit fix```
And then ```npm  install```

**Comment by xmonader** [comment]
please check

**Comment by abom** [comment]
Currently we use `yarn`, could you please try to follow [the docs here](https://github.com/threefoldtech/grid_weblets#installation) and report any issues if any?

**Comment by abom** [comment]
Can re-open if it's still an issue after following the docs.
