### ISSUE TITLE
show large or small numbers in decimal format 

### ISSUE THREAD

**Issue by mhost39** [threefoldtech/grid_weblets#581]
![image](https://user-images.githubusercontent.com/31102305/156076036-c51d9826-fca8-4d4d-a25d-d11f915b3c53.png)

**Comment by Omarabdul3ziz** [comment]
this fixed now
![image](https://user-images.githubusercontent.com/32527347/175285648-089fc110-8712-4ce0-8e0a-24675324f392.png)

**Comment by mohamedamer453** [comment]
Fixed and Verified in #735 


![image](https://user-images.githubusercontent.com/101194226/175288251-1d3ced85-4269-4f66-9e82-ff0de3f9c9dd.png)
