### ISSUE TITLE
Profile manager: can't remove first profile

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_weblets#582]
### Description

In the profile manager, it's not possible to remove the profile you added first

### Steps to reproduce

- open the playground
- open the profile manager
- no cirlce with an X on the first profile

![image](https://user-images.githubusercontent.com/88312671/156176286-77ed7974-56f0-437b-a85e-5f07c4945830.png)

**Comment by MohamedElmdary** [comment]
This isn't a bug ... I have added this logic because
1- Deleting all profiles will show won't be a good `UX`
2- if no profiles at all you will get `null` error
