### ISSUE TITLE
Mainnet: deployments via play.grid.tf seem to be broken

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_weblets#583]
### Description

Deploying via play.grid.tf almost always results in the following error. Example is for node with ID 307:
![node-307-play](https://user-images.githubusercontent.com/88312671/156202833-526e183d-5501-4fcf-9c0b-cac3ce36a8d5.png)
While it works via terraform:
![node-307-terraf](https://user-images.githubusercontent.com/88312671/156202928-ed265f88-3154-479c-ba76-3d69326a9839.png)

With node 527 it did not work in both cases:
![node-527-play](https://user-images.githubusercontent.com/88312671/156203080-48959bbc-dc3d-41c7-b29b-6925cc9b3f73.png)
![node-527-terraf](https://user-images.githubusercontent.com/88312671/156203094-dd0771fb-f50b-444d-9bf9-24349345d859.png)

Node 8 and 13 that appear in these errors are the Freefarm public nodes on mainnet.
We tested several other random nodes and the result is the same. Every deployment via play fails, and mostly it works via terraform.

### Steps to reproduce

Deploy via play.grid.tf on any node

**Comment by coesensbert** [comment]
Related tickets:

- https://github.com/threefoldtech/test_feedback/issues/6
- https://github.com/threefoldtech/home/issues/1185

**Comment by coesensbert** [comment]
Tried many today, got one successful deployment with contract ID 409 on node 422

![image](https://user-images.githubusercontent.com/88312671/156207508-def32990-da6d-4aab-852e-f6ced2440dd8.png)

**Comment by asamirr** [comment]
Just deployed a funkwhale instance and all seems good! 
![image](https://user-images.githubusercontent.com/9322121/157029305-912285e5-e423-47c4-96cb-74d9ec235569.png)
