### ISSUE TITLE
failed to get deployment contract

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#587]
got this error while trying to deploy peertube in play.dev on different nodes
![Screenshot from 2022-03-07 15-45-32](https://user-images.githubusercontent.com/32527347/157047840-83b4e506-ebc5-4d1d-a4bf-8678ce08c7ee.png)

**Comment by asamirr** [comment]
Deployed more than an instance and it was okay!

**Comment by asamirr** [comment]
Verified and working now
![Uploading image.png…]()
