### ISSUE TITLE
TC442: Deployment of OwnCloud

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#588]
When provisioning OwnCloud, the generated password is provided by default
Errors, 
1. after changing the password, the password is not accepted on the control panel, it keeps the default password which was provided
2. If there is the new deployment or the page is refreshed, the password doesn't change either

Otherwise the deployment works fine and the password can be changed from the admin panel and users can be created

**Comment by Omarabdul3ziz** [comment]
can't reproduce this. changed the password and it works fine
