### ISSUE TITLE
funkwhale: .gent01.dev.grid.tf is hardcoded in the domain

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#59]
![image](https://user-images.githubusercontent.com/64129/143488641-b5652e99-2d82-47c1-a4af-3dc1c8c62808.png)
```
  vm.env = {
      FUNKWHALE_HOSTNAME: name + ".gent01.dev.grid.tf",
  }
```

**Comment by asamirr** [comment]
https://github.com/threefoldtech/grid_weblets/commit/6b514733649f868d465e8910daf1eee88ac8de26

**Comment by waleedhammam** [comment]
verified
