### ISSUE TITLE
TC447: Deploy Taiga

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#590]
After Taiga deployment, there are 2 visible errors:

1. On the login page when logging in (Visit button) with the admin credential provided 
![taiga](https://user-images.githubusercontent.com/65153287/156477474-a2e27dcb-b513-4179-a799-fb2d9fbea042.png)

2. When clicking on the Admin Panel, the opened Web page shows
```
502 Bad Gateway
nginx/1.19.10
```

**Comment by Omarabdul3ziz** [comment]
the first part was an issue with threefold connect and it is solved now. tracked at https://github.com/threefoldtech/threefold_connect/issues/416

the second part duplicated of https://github.com/threefoldtech/grid_weblets/issues/593
