### ISSUE TITLE
User reports that deployments seems to require a HDD

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#592]
I noticed a problem when trying to deploy a presearch node on [play.grid.tf 1](http://play.grid.tf/) It seems that it is only possible to select nodes with hard drives (not ssd’s). The same for casperlabs and caprover. The inverse for owncloud . See forum post https://forum.threefold.io/t/presearch-node-weblet/2359

**Comment by asamirr** [comment]
All deployments are using SSD disks at the moment.

**Comment by gmachtel** [comment]
So if a node has no HDD, no issue ? Seems to be contradictory with user report [here](https://forum.threefold.io/t/presearch-node-weblet/2359/5)

**Comment by gmachtel** [comment]
User reports he wants to deploy a PRE node on his own node 855 on mainnet, but for some reason it refuses, even though it has sufficient SSD, CPU, memory. It has no public IPs however, is that the issue ? 
<img width="1277" alt="Screenshot 2022-04-04 at 13 46 08" src="https://user-images.githubusercontent.com/30384423/161537794-1543c4c1-63ed-4f2e-87bf-5753d22aa52d.png">

**Comment by gmachtel** [comment]
Error received: "Node(855) might be down or doesn't have enough resources." Which seems strange given the ample available resources.

**Comment by asamirr** [comment]
Presearch nodes do require the availability of a public IP. The capacity filter should be taking care of that before you deploy.
