### ISSUE TITLE
weblet Taiga deployment has "gateway error" for admin panel.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/grid_weblets#593]
deployment on **main** net, details:
<img width="389" alt="image" src="https://user-images.githubusercontent.com/13766992/157000965-ebbc6d7b-04b1-450c-8472-a8cc16cb1dae.png">

Visit Taiga page works
Visit Admin page gives `502 Bad Gateway`

<img width="427" alt="image" src="https://user-images.githubusercontent.com/13766992/157001156-848cf6e7-51f6-4b68-bb40-bb88023d3ad4.png">

**Comment by sameh-farouk** [comment]
looks like this is a memory **starvation issue** with the minimum specs, also other things were broken like tf-connect.

when testing with the recommended specs things start to works as they should be, if OP can confirm that he has that issue only on the minimum flavor then we could give Tiaga some love and increase the memory spec for that flavor or maybe enable the swap.

```
root@vmiqtallaxur:/docker# free -h
              total        used        free      shared  buff/cache   available
Mem:          972Mi       776Mi        56Mi        88Mi       139Mi        12Mi
Swap:            0B          0B          0B
```

**Comment by asamirr** [comment]
Just deployed a "Recommended" instance and it works 
![image](https://user-images.githubusercontent.com/9322121/158192168-54f94a52-5b6d-408c-8945-331cfb25d461.png)

**Comment by asamirr** [comment]
Updated the minimum package specs and verified on dev playground!
