### ISSUE TITLE
TC413: Check for maximym disk space error

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#595]
Cannot see the option for adjusting the disk size as specified in the test case

https://app.testlodge.com/a/26076/projects/40893/runs/629224/run?selected=26706915

**Comment by abom** [comment]
Need to re-validate this issue on play.test.grid.tf

**Comment by Omarabdul3ziz** [comment]
verified on play.test.dev and play.grid and the validation works if failed the deploy button is disabled
