### ISSUE TITLE
deployed list is not showing correctly

### ISSUE THREAD

**Issue by ashraffouda** [threefoldtech/grid_weblets#597]
### Description

I deployed a peertube instance and the `visit` and `show details` buttons were not visible and the horizontal scroll doesn't exist to move to this part of the page, I had to zoom out the page to be able to click them 
also if u noticed the components are floated awy from the right side in the following pic
![Screenshot from 2022-03-09 12-42-25](https://user-images.githubusercontent.com/1689456/157426478-b29d6ae0-79c3-47be-90d0-989526efd2d7.png)
![Screenshot from 2022-03-09 12-46-08](https://user-images.githubusercontent.com/1689456/157426577-bc375b22-068c-40fe-bdda-e9a5d2d11a43.png)

**Comment by asamirr** [comment]
Couldn't reproduce it but it's probably a glitch from the browser that happened to happen somehow.

**Comment by asamirr** [comment]
It's probably because of zooming in or small screens. Might need to introduce horizontal scrolling to it!

**Comment by Omarabdul3ziz** [comment]
verified on play.dev
![Screenshot from 2022-03-20 17-36-23](https://user-images.githubusercontent.com/32527347/159170256-7a662cd8-d169-4bb4-a6db-5af5c5938bfe.png)
