### ISSUE TITLE
Kubernetes name validation not working

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#601]
in both the master and workers tabs when entering a name with non-alphanumeric characters the deploy button is not disabled in testnet.
![image](https://user-images.githubusercontent.com/101194226/157399306-8b80b6ec-87ad-4d71-919f-66e26c6a6c80.png)

This error appeared after pressing the deploy button.
![image](https://user-images.githubusercontent.com/101194226/157399535-8265db17-a208-4923-9d3b-abd64b3dbec8.png)

**Comment by Omarabdul3ziz** [comment]
verified on play.dev
