### ISSUE TITLE
deleting a solution should ask for confirmation

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#61]
![image](https://user-images.githubusercontent.com/64129/143489926-6e624aa5-114b-4aa7-b744-59c65300d033.png)

Right now it doesn't ask

**Comment by abom** [comment]
Closing this for now and adding a feature request to use modals instead, which I think would be more consistent.

![Screenshot from 2021-12-02 06-06-14](https://user-images.githubusercontent.com/511438/144355793-18c13321-7088-4b2d-b3e3-8f0b16158d97.png)
