### ISSUE TITLE
mattermost: postgres disk has an issue

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#615]
on deployed mattermost instance from dev playground, mattermost server did not start with this error
```bash
postgres: could not access directory "/var/lib/postgresql/12/main": No such file or directory
```

locally tried to remove the disk from the deployment script 
```typescript
vm.disks = []
```
and it works fine

**Comment by mohamedamer453** [comment]
Closing this issue and adding it as a reference for a related issue #641 for more details/logs.
