### ISSUE TITLE
UX: no need for kubernetes ssh key input field

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#616]
there is no need for asking about the ssh key again. we can take it's value from `profile.sshKey` as in other weblets

![Screenshot from 2022-03-22 14-47-58](https://user-images.githubusercontent.com/32527347/159486410-d6ed89e5-b02c-4d4a-bd2a-434c15589417.png)

**Comment by xmonader** [comment]
I agree let's remove it

**Comment by mohamedamer453** [comment]
Verified on devnet.

The `Public SSH Key` was removed from the Kubernetes deployment tab.

![image](https://user-images.githubusercontent.com/101194226/170999913-174716ab-f55c-4309-bd2f-831d0cbc5724.png)
