### ISSUE TITLE
mattermost: modalbox doesn't show up after successful deployment

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#617]
the scenario on all the weblets once you got a successful deployment the `Modal` component shows up with the details of the deployment. 

![Screenshot from 2022-03-22 16-12-12](https://user-images.githubusercontent.com/32527347/159501483-f528a5a3-45be-4887-993a-ee1a5d033d74.png)

that is not the case on mattermost it just give the `Successfully deployed mattermost` message then you should open the modalbox with `Show Details` button

![Screenshot from 2022-03-22 16-11-10](https://user-images.githubusercontent.com/32527347/159501245-c2bcd641-9ce6-41ad-9ac8-371efe49e553.png)

it will be better if all the weblets follows the same scenario showing the details after it deployed

**Comment by mohamedamer453** [comment]
The issue is still valid and the modal box doesn't appear after a successful deployment.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The modalbox is now displayed after a successful deployment like all the other deployments.

![image](https://user-images.githubusercontent.com/101194226/168088810-573686c4-aafb-4bdf-a3cc-0aa5cb4f4808.png)

and the mail configuration was added to a separate tab to be consistent with all the other deployments.

![image](https://user-images.githubusercontent.com/101194226/168088915-597cf414-38e2-4452-92a6-6d25f95c4096.png)
