### ISSUE TITLE
Can't reach Taiga through YggIP 

### ISSUE THREAD

**Issue by asamirr** [threefoldtech/grid_weblets#618]
Steps to reproduce:

1. Deploy a Taiga instance.
2. Copy the Yggdrasil IP and paste in the browser in this form "http://[301:a9bd:9b77:ce71:8003:c47e:1f0e:27d4]:9000/discover"

Then you'll find this page!
![image](https://user-images.githubusercontent.com/9322121/159512317-2ea6672e-def6-47e8-88e9-f5442f942c0a.png)

**Comment by abom** [comment]
Can we at least re-verify?

**Comment by mohamedamer453** [comment]
Verified on testnet weblets v1.4.1-rc2

It worked using http://[302:1eb4:b62c:8ba6:ba39:6730:1645:bb42]:9000/discover 

![image](https://user-images.githubusercontent.com/101194226/166906169-4d66d5ff-68cb-4a3a-bd71-465017a2b99c.png)

but it took too long to work around 15 - 20 mins after deployment and before that it didn't show the image in the issue but i gave `Connection Timed Out`  and during the time when it wasn't working i also wasn't able to access the VM with the ygg ip.


Here are the logs from running `zinit log` [Taiga_logs.txt](https://github.com/threefoldtech/grid_weblets/files/8630473/Taiga_logs.txt)

**Comment by sameh-farouk** [comment]
> but it took too long to work around 15 - 20 mins after deployment and before that it didn't show the image in the issue but i gave Connection Timed Out and during the time when it wasn't working i also wasn't able to access the VM with the ygg ip.

FYI, image initialization time (pulling images, starting the containers, DB migrations) was less than 5 minutes in the early flist testing. let us check if this is reproducible.

**Comment by mohamedamer453** [comment]
I tired to reproduce this issue again and the instance was deployed at 11:01 and after a minute (11:02) it loaded but i still wasn't able to access it and i got this page

![image](https://user-images.githubusercontent.com/101194226/169001428-9c43d58e-a4bf-4232-b678-627f992bcbe0.png)

and after 2 mins (11:03) it loaded successfully through Yigg IP and and the whole time i was able to ssh to the vm unlike last time.

![image](https://user-images.githubusercontent.com/101194226/169001836-699510ed-b99b-42de-bb70-2f23b822604b.png)

and at the same time the admin panel was also working without any issues

**Comment by sameh-farouk** [comment]
the error shown immediately after deployment is expected. the solution isn't fully started yet. I think 2 minutes is not bad for a heavy solution like taiga.

**Comment by mohamedamer453** [comment]
I was unable to reproduce this issue and i tried with another instance on a different node and i got the same results (Approx. 2 mins until everything was working) which is very acceptable for a heavy solution as taiga as @sameh-farouk mentioned.
