### ISSUE TITLE
no need for public ip option on discourse

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#619]
discourse is the only solution weblet that enables the public IP option.
![Screenshot from 2022-03-23 11-32-53](https://user-images.githubusercontent.com/32527347/159668510-d2cf45f6-bdec-41e7-9e95-eeb1c001a756.png)

and there is no need for it the solution gateway has a backend as planetary IP
https://github.com/threefoldtech/grid_weblets/blob/d5f3dd323d83f0735933c3d9b187888f987ac8f8/src/utils/deployDiscourse.ts#L126

enabling the public IP or not will not affect the solution as its value is not used. it will be better to remove these two IPs options so all the weblet has a similar interface. 
also, it may lead to the misunderstanding that discourse requires a public IP which will lead to reserve unnecessary Public IP

**Comment by mohamedamer453** [comment]
Verified on devnet.

The network options were removed from the configuration.

![image](https://user-images.githubusercontent.com/101194226/175811528-b342f512-075b-4ebc-b4c7-e9aa61ead24c.png)
