### ISSUE TITLE
caprover listing is broken on validate_node_support branch

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#62]
![image](https://user-images.githubusercontent.com/64129/143490801-e24f9305-b81b-4fd8-b836-5e66676f62ad.png)

better check is checking in vm.flist name to include caprover.

**Comment by abom** [comment]
Working on latest deployed release/version.

![Screenshot from 2021-12-02 05-50-35](https://user-images.githubusercontent.com/511438/144355395-1319b20a-5d33-4b9e-a08e-0d61462acb6e.png)
