### ISSUE TITLE
Threefold validators solution

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#631]
Should be a straightforward solution, requires https://github.com/threefoldtech/threefold_hub/issues/16

**Comment by mohamedamer453** [comment]
Verified on devnet.

TFhub Validator Deployment was added to the weblets.

![image](https://user-images.githubusercontent.com/101194226/174788905-ce76936c-927e-4c12-933c-fab4226a0999.png)

and i was able to successfully deploy a validator and  ssh to it.

![image](https://user-images.githubusercontent.com/101194226/174789072-bd9f912e-0dd7-451a-9da5-aa8135e34a00.png)
