### ISSUE TITLE
Filtering by country doesn't work on play.grid.tf

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#634]
On this setup, at least there should be freefarm nodes shown. But no nodes are shown. 

<img width="1277" alt="Screenshot 2022-04-04 at 16 36 19" src="https://user-images.githubusercontent.com/30384423/161567781-e8fb58d7-27d4-4f87-82f5-51c68c3b65e6.png">

**Comment by coesensbert** [comment]
Same issue from ops repo: https://github.com/threefoldtech/tf_operations/issues/781

**Comment by mohamedamer453** [comment]
verified on https://play.dev.grid.tf

Filtering by country is working now on all deployments and shows the online nodes in this country.

![Screenshot from 2022-04-13 11-51-45](https://user-images.githubusercontent.com/101194226/163152691-37f80687-dbde-4f0a-a0c7-a8d2afcc6c22.png)
