### ISSUE TITLE
deployment ends with an Error despite it being fully working

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#644]
### Description

sometimes the deployment process ends with an Error which gives hints that deployment wasn't succeeded.

however, despite the deployment process ending with an error, surprisingly a minute later, the deployment would show up on the deployment list and can be reached with no issue. from the user's perspective, this is confusing behavior, and properly the user will try again to deploy the solution and will end up with unintended multiple instances.

I suggest increasing client retries to get the deployment and better error messages when there is difficulty to reach the server after deployment. maybe something like:
`the deployment can't be reached, it could be a temporary network issue. If the problem continues, please contact the support team.`

![Screenshot from 2022-04-11 14-39-19](https://user-images.githubusercontent.com/42457449/162813894-01993400-c2d3-4e83-9382-97205a897605.png)

![Screenshot from 2022-04-11 14-12-57](https://user-images.githubusercontent.com/42457449/162813989-0923e586-9997-496c-b78e-99b59420b9e2.png)

**Comment by AhmedHanafy725** [comment]
couldn't reproduce on the latest version, please reopen if it's still happening
