### ISSUE TITLE
Failed to deploy more than 1 worker in k8s cluster

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#646]
### How to reproduce ?
1. Create `k8s` cluster
2. Try to add worker
3. 1st one will be deployed
4. others won't deploy

@AhmedHanafy725 mentioned that **network** didn't update

**Comment by MElborolossy** [comment]
Tested on devnet 17/4/2022
- First create k8s with one master (Node 1) and one worker (Node 3)
- Add 2 workers separately (One on Node 5, the other on Node 6) after that and as shown added successfully
- Listing workers after deploying them
![Screenshot from 2022-04-17 15-46-25](https://user-images.githubusercontent.com/11272864/163717429-33fc758b-bc46-4ff8-8e05-01043027d039.png)
- Check from the master that all nodes are ready
![Screenshot from 2022-04-17 15-47-07](https://user-images.githubusercontent.com/11272864/163717434-7548ef6a-c2a6-4a6e-ac07-9810faf690d5.png)
