### ISSUE TITLE
Billing Rate not work/show in the contracts weblet.

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#651]
### Description

Billing Rate does show in the contracts weblet, but shows in the deployments weblet for same contract ids.

![Screenshot from 2022-04-19 23-28-55](https://user-images.githubusercontent.com/42457449/164105353-c7b25d81-9708-4233-b2e6-03fa37111737.png)

![Screenshot from 2022-04-19 23-29-12](https://user-images.githubusercontent.com/42457449/164105361-2a220135-6985-41d0-b9e3-e6a9abae8f17.png)

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
- https://github.com/threefoldtech/grid_weblets/pull/680
