### ISSUE TITLE
Improve capacity planning by including/excluding dedicated nodes

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#652]
This will be done on grid3_client https://github.com/threefoldtech/grid3_client_ts/issues/263, so it will require upgrading the grid3_client on weblets once it's done.
And also the manual filter needs to take this into consideration.

**Comment by mohamedamer453** [comment]
This was already verified in #662 and the capacity filter doesn't show dedicated nodes unless they're rented by the same user.
and for the manual filter it was verified in #728  and now a message mentioning that this node is dedicated and you can check the portal for more information.

![image](https://user-images.githubusercontent.com/101194226/177178218-a8ba358b-c195-428b-869e-0b0aa9a24dc1.png)
