### ISSUE TITLE
Weblets: Deployments Invalid Certificates

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#657]
Tested on https://play.test.grid.tf

After deploying multiple instances and accessing them through the weblets the connection is not secure and the certificates appear to be invalid.

### Owncloud

![Screenshot from 2022-04-17 14-52-53](https://user-images.githubusercontent.com/101194226/163715173-71bd5e2b-80a9-42be-8541-bfce6cfa2692.png)

### Mattermost

![Screenshot from 2022-04-17 16-04-37](https://user-images.githubusercontent.com/101194226/163718026-be042d4d-76d7-4c0d-9a5f-c094a2425538.png)

### Taiga

![Screenshot from 2022-04-17 16-20-53](https://user-images.githubusercontent.com/101194226/163718679-801dfc44-564a-4525-8a11-cbbe01626bb0.png)

![Screenshot from 2022-04-17 16-22-32](https://user-images.githubusercontent.com/101194226/163718720-ba2b888c-5dc9-44f7-b689-45dc99b212f5.png)

### Discourse

![Screenshot from 2022-04-17 16-27-44](https://user-images.githubusercontent.com/101194226/163718971-b3315dc1-ade0-4221-b5c7-db09fa793f8f.png)

### Peertube

![Screenshot from 2022-04-17 16-37-39](https://user-images.githubusercontent.com/101194226/163719395-c0a06f93-f7d5-4e18-8538-4fa0eb6ea8e4.png)

### Funkwhale

![Screenshot from 2022-04-17 16-44-13](https://user-images.githubusercontent.com/101194226/163719621-aa2eb283-9fc1-4315-a09f-5cdd9ecc547c.png)

### Casperlabs

![Screenshot from 2022-04-17 16-55-23](https://user-images.githubusercontent.com/101194226/163720056-d2b70bf1-7a12-4b77-b3a7-a36a195ab2c9.png)

**Comment by abom** [comment]
@OmarElawady Can be the same DNS issue we faced before?

**Comment by OmarElawady** [comment]
Yes it was because of a missing DNS NS record for the acme challenge. Added by @hossnys and should be working now.

**Comment by hossnys** [comment]
yes ,missing NS record added and new deployments works fine with certificates now 

![Screenshot from 2022-04-26 16-18-33](https://user-images.githubusercontent.com/26298009/165733418-916e562e-a8df-4436-8019-2e53b5de3ae7.png)

**Comment by mohamedamer453** [comment]
Verified on testnet weblets v1.4.1-rc2

The certificates for the deployments are valid now.

![image](https://user-images.githubusercontent.com/101194226/166939295-92f91822-e236-4235-9229-2844629f7525.png)
