### ISSUE TITLE
Weblets: Presearch Registration Code input validation

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#658]
Tested on devnet.

The Presearch Registration Code field doesn't have validation for length, special characters. and it also doesn't have an error message for when the field is left empty, it only disables the deploy button without mentioning that the field shouldn't be left empty.

No error message when left empty

![image](https://user-images.githubusercontent.com/101194226/163421075-be932233-957e-4a92-b06c-8f57d2a4d672.png)

The field accepts special characters and no minimum length and also no defined format for the registration code.

![image](https://user-images.githubusercontent.com/101194226/163421494-f7291522-4273-45ce-9148-b866248a4671.png)

**Comment by mohamedamer453** [comment]
Validation and error messages for empty field, min length, special characters was added.

![image](https://user-images.githubusercontent.com/101194226/167870890-aa3bff0d-7d98-493b-a8ff-60b1835c862a.png)

![image](https://user-images.githubusercontent.com/101194226/167871036-5749f9cd-d232-4aba-a647-f4eed9b6bf59.png)

![image](https://user-images.githubusercontent.com/101194226/167871146-f466c012-a7c9-412b-9ff1-df9bad80f60b.png)

However validation for max length was not added 

![image](https://user-images.githubusercontent.com/101194226/167871322-f0b1b91e-a4ae-426a-8e26-14989d443679.png)

I'm not entirely sure what is the correct format for a Presearch Registration Code, but i think that it shouldn't accept an input that long. for reference that's the code i entered to test the max length.
```
b2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943eab2aaf670de9053181010a42dbc2943ea
```
also i think the error message could be simplified and improved 

- Current

`That is not looks like a valid presearch registration code`

- Suggested

`Invalid Presearch Registration Code`

**Comment by xmonader** [comment]
@Omarabdul3ziz please check the suggested error

**Comment by mohamedamer453** [comment]
Verified on devnet.

The error message was simplified and improved.

![image](https://user-images.githubusercontent.com/101194226/168464452-95a8232e-58c1-46ea-a356-59b9543169e7.png)

Validation for max length was added.

![image](https://user-images.githubusercontent.com/101194226/168464492-26695d3e-c878-497b-a243-3e08583247df.png)
