### ISSUE TITLE
mainnet kubernetes cluster deployment broken

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/grid_weblets#660]
When using the weblet to deploy a kubernetes cluster (on mainnet) the weblets present a positive and successful deployment:
<img width="1171" alt="Screen Shot 2022-04-05 at 9 30 24 AM" src="https://user-images.githubusercontent.com/13766992/161685146-0e83cff2-81ae-4601-90f2-f2a1ccfa4362.png">
--
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/13766992/161685192-12bab5d5-acc6-4b2b-8efc-1e0b3477d344.png">
--
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/13766992/161685229-a3115ff2-bc33-4097-9d4f-96f4bec8913b.png">
But the cluster does not work:  remote login in (ssh) to the master and listing the cluster nodes:

```
root@WR3fbe7480:/etc/rancher/k3s# kubectl get nodes
NAME         STATUS   ROLES                  AGE   VERSION
wr3fbe7480   Ready    control-plane,master   25m   v1.22.7+k3s1
root@WR3fbe7480:/etc/rancher/k3s#
```

And remote login on the worker node:

```
root@WR917db509:~# kubectl get nodes
W0405 05:30:12.336407     322 loader.go:221] Config not found: /etc/rancher/k3s/k3s.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?
root@WR917db509:~#
```

**Comment by rkhamis** [comment]
@mohamedamer453 can you verify that this is not an issue?

**Comment by rkhamis** [comment]
@ramezsaeed @mohamedamer453 can you guys check?

**Comment by mohamedamer453** [comment]
Tested on testnet Weblets v1.4.1-rc2

After deploying a k8s cluster with a master and 1 worker i was able to access both of them and by applying the command `kubectl get nodes` to both of them i got the following results.

### Master
```
root@WR9f2a6c56:~# kubectl get nodes
NAME         STATUS   ROLES                  AGE   VERSION
wr5588705d   Ready    <none>                 12m   v1.22.7+k3s1
wr9f2a6c56   Ready    control-plane,master   12m   v1.22.7+k3s1
```

![image](https://user-images.githubusercontent.com/101194226/164472422-1022971b-0265-4007-abc7-2a75ad1fbf0a.png)


### Worker
```
root@WR5588705d:~# kubectl get nodes
W0421 13:51:05.890602    1622 loader.go:221] Config not found: /etc/rancher/k3s/k3s.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?

```

![image](https://user-images.githubusercontent.com/101194226/164473097-090771da-5fda-4229-905e-709328736a8b.png)

**Comment by mohamedamer453** [comment]
Tested on testnet Weblets v1.4.1-rc2

After deploying a k8s cluster with a master and 2 worker i was able to ssh to the master and the workers.

And by applying the command `kubectl get nodes` for the master i got the following result.

### Master

![image](https://user-images.githubusercontent.com/101194226/168586163-37790a0b-3618-42f1-ad8d-529ab7e8c9be.png)

```
root@Master:~# kubectl get nodes
NAME      STATUS   ROLES                  AGE     VERSION
master    Ready    control-plane,master   4m49s   v1.22.7+k3s1
worker1   Ready    <none>                 4m36s   v1.22.7+k3s1
worker2   Ready    <none>                 4m18s   v1.22.7+k3s1
```

### Workers
After further discussion with @AhmedHanafy725 i was informed that the K8s commands like `kubectl get nodes` are not allowed in the worker nodes so that's why it produces an error when executed in the worker node.
