### ISSUE TITLE
Deployment on Dedicated Nodes Error Messages

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#662]
Tested on devnet

Trying to deploy on any of the nodes available on the dedicated nodes tab in the [portal](https://portal.dev.grid.tf/) without reserving a node gives an error as it is supposed to but the error is not clear or user friendly
```
Error: Failed to create contract on node: 21 due to Failed to apply createNodeContract in module smartContractModule with 21,,fcc667bbad59c37d2eb093e63fceed80,0 due to error: undefined
```
![image](https://user-images.githubusercontent.com/101194226/164200810-76ce3c86-7c52-4b53-a818-ad6466a3fd2f.png)

Suggestion: Dedicated nodes should not be available in the capacity filter for deployment once they are reserved or marked as dedicated nodes and available for reservation or they could be available in the capacity filter but marked as reserved/dedicated node.

**Comment by Omarabdul3ziz** [comment]
WIP on updating the capacity filter to include dedicated nodes only for the tenant. these changes will affect grid3_client and weblets.
issues:
- https://github.com/threefoldtech/grid3_client_ts/issues/263
- https://github.com/threefoldtech/grid_weblets/issues/652
- https://github.com/threefoldtech/tfgridclient_proxy/issues/129

**Comment by abom** [comment]
Should be re-added to `now` when we have other clients ready.

**Comment by mohamedamer453** [comment]
Closing this issue since it's verified on Weblets and Ts_client and the only issue left is related to terraform.

and will follow the issue [here](https://github.com/threefoldtech/terraform-provider-grid/issues/226)
