### ISSUE TITLE
caprover adding node to cluster failed with unclear message, improve reporting

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/grid_weblets#664]
![image](https://user-images.githubusercontent.com/6021844/153348616-2cbb3e70-f521-442c-aeb7-c3db45a9aa54.png)

was on mainnet

was also not very clear, what is the pub key asked for?

**Comment by abom** [comment]
Tracked at https://github.com/freeflowuniverse/caprover-frontend/issues/7 and updated the image tag in #648

**Comment by mohamedamer453** [comment]
Verified on Devnet.
Validation was added to the Grid Configurations.

Validation for empty required fields

![image](https://user-images.githubusercontent.com/101194226/166949823-78f49b9c-d2a3-4207-a28b-d054d3354aae.png)

Validation for Store Secret length

![image](https://user-images.githubusercontent.com/101194226/166949164-cba27f8a-303d-4f05-b9a2-3e3799e07998.png)

Validation for the Mnemonics  

![image](https://user-images.githubusercontent.com/101194226/166950763-b509987b-1c72-45cb-866e-b988951bd7d8.png)


also the user can't enter invalid Mnemonics for the used network 

![image](https://user-images.githubusercontent.com/101194226/166951602-beb1e388-3456-47ac-857c-e1783de8b74f.png)
