### ISSUE TITLE
long mnemonics input validation

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#670]
kds reported that long texts doesn't work (and doesn't fail with an error message)

**Comment by xmonader** [comment]
For me it works just fine ![image](https://user-images.githubusercontent.com/64129/166921027-5023584b-2bf6-4266-a5ad-be6045002266.png)

**Comment by xmonader** [comment]
@mohamedamer453 please check.

**Comment by mohamedamer453** [comment]
Tested it on testnet, devnet and mainnet and it's working for me.

![image](https://user-images.githubusercontent.com/101194226/166924374-2cd5c531-038d-4115-ac1b-5fa21916cf53.png)

**Comment by xmonader** [comment]
@despiegk can you provide more info please?

**Comment by mohamedamer453** [comment]
Verified again on 

### Devnet

![image](https://user-images.githubusercontent.com/101194226/167813427-acd7a79f-f4c8-4c25-ab9a-799335398e34.png)

### Testnet

![image](https://user-images.githubusercontent.com/101194226/167813531-141ce1bb-07e6-4a93-a9d2-86bfd884b2e4.png)

### Mainnet

![image](https://user-images.githubusercontent.com/101194226/167814075-bb2ae990-f966-4b03-8dae-b85e26da98fd.png)

When the user enters a long or invalid Mnemonics and clicks on activate a clear error message is presented and the user isn't logged in with the invalid Mnemonics.

Please reopen the issue if there's more information or steps on how to reproduce the mentioned issue.
