### ISSUE TITLE
Improve weblets error handling experience 

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#674]
We're looking forward to improving weblets experience in the context of network losing or servers connections are broken or can't be reached

Please feel free to suggest whatever you want ... Thanks

**Comment by xmonader** [comment]
given that we are communicating with multiple things e.g gridproxy, tfchain, we need to consider the possibility of these components being down, e.g periodic checks on a health endpoint or disabling the interactions with the system.

**Comment by MohamedElmdary** [comment]
Currently we have improved the weblets UX so this issue is outdated
