### ISSUE TITLE
upgrade discalimer link

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#677]
![image](https://user-images.githubusercontent.com/64129/167375250-9207db51-4285-472a-9f13-62cdfd33a056.png)

right now it links to https://circles.threefold.me/project/test-tfgrid3/issues instead of https://github.com/threefoldtech/test_feedback

**Comment by mohamedamer453** [comment]
Verified on devnet.

Now the link redirects to [test_feedback](https://github.com/threefoldtech/test_feedback/issues) repo
