### ISSUE TITLE
Titan V2.1 has only SSD

### ISSUE THREAD

**Issue by andhartl** [threefoldtech/grid_weblets#68]
Please remove 10000GB HDD capacity.

Titan V2.1 has only 1000GB SDD

**Comment by MohamedElmdary** [comment]
### Fixed
removed hdd field & set hdd value to 0

**Comment by abom** [comment]
Verified

![Screenshot from 2021-12-02 04-17-36](https://user-images.githubusercontent.com/511438/144345311-67516bd3-0631-4bf2-a8db-a705e8f0301f.png)
