### ISSUE TITLE
Capacity filter does not match manual verification, deployment failed because disk resources unavailable

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#682]
User attempted deploying a Kubernetes VM and saw this error:

![image](https://user-images.githubusercontent.com/17682591/167697963-c77d9766-f7f5-494d-afed-13f4715ca696.png)

Choosing node 3 manually for the same deployment shows this:

![image](https://user-images.githubusercontent.com/17682591/167698065-722d9662-ac1c-4b58-9e1c-0a8e291c0587.png)

However, node 3 is included in capacity filter results for deployment with the same resources (namely 100GB disk):

![image](https://user-images.githubusercontent.com/17682591/167699121-ff6986a6-8ab6-4300-b31e-9f0c22683733.png)

It seems the node's SSD is full:

![image](https://user-images.githubusercontent.com/17682591/167698841-a1b075a6-3f06-4ce8-9cb3-11b78e5fdc33.png)

**Comment by mohamedamer453** [comment]
This issues is already fixed on devnet and verified here #741. and currently all the nodes are reflected correctly in the Manual Filter.
