### ISSUE TITLE
Add weblet description and documentation link 

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#685]
per solution make sure there's a small description of what the user is going to deploy and a link to the documentation in the manual.

**Comment by MohamedElmdary** [comment]
like this ?
![image](https://user-images.githubusercontent.com/31689104/167842840-6920e15f-1139-41cb-aa52-032ee28e779b.png)

**Comment by xmonader** [comment]
Should be available here https://library.threefold.me/info/manual/#/manual__weblets_home and when in doubt please ask :)

**Comment by renauter** [comment]
@MohamedElmdary 
The link to documentation is OK
But between solution title and documentatton link a small and brief description should describe what the solution is and what it does.
The short description should  be high level, easy to understand for technical but NON specialist users

**Comment by mohamedamer453** [comment]
Verified on devnet.

Description and documentation links were added for each deployment and all the links redirect to the correct sections in the documentation.
 
However there are a couple of small typos in 

### Kubernetes
there is a space missing here `Kubernetes is the standard container orchestration tool.On the TF grid,` before `On the TF grid`

### Casperlabs
there is also a space missing `Casper Networkis a `

**Comment by mohamedamer453** [comment]
After the description was added to the profile manager the buttons became too close to each other.

### Fullscreen

![image](https://user-images.githubusercontent.com/101194226/168022049-97d4c35d-10f0-4bf8-96ba-ab7430530bae.png)

### Minimized 

![image](https://user-images.githubusercontent.com/101194226/168023613-e9dcb1e7-98ab-4ce3-b8da-1d1fe4ea7ff0.png)

also in when the browser is minimized the title `Profile Manager` is too close to the description text.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The typos in Kubernetes and Casperlabs description were fixed. and the spaces between the buttons in the profile manager we adjusted.

### Fullscreen

![image](https://user-images.githubusercontent.com/101194226/168077420-18187139-4389-4155-853d-ca05601b1707.png)

### Minimized

![image](https://user-images.githubusercontent.com/101194226/168077524-95ec9b07-05ac-49e2-a319-63694908a5de.png)
