### ISSUE TITLE
Update Styling

### ISSUE THREAD

**Issue by ehab-hassan** [threefoldtech/grid_weblets#687]
need to update color to to match with ThreeFold

**Comment by mohamedamer453** [comment]
Verified on devnet.

The styling and colors were updated for the weblets to match the unified ThreeFold Colors.

This update includes:

- Updated Colors.
- Updated Fonts.
- New Deployment/Solutions Icons in the sidebar.
- New  Actions Icons in the deployment list.

## Before

![image](https://user-images.githubusercontent.com/101194226/174790521-d92543f9-574a-4ff5-90f2-1368504b42e3.png)

## After

![image](https://user-images.githubusercontent.com/101194226/174790170-248628ed-8bc1-4450-87eb-0cb50e8fca17.png)
