### ISSUE TITLE
Identify the current network mainet / testnet / devnet

### ISSUE THREAD

**Issue by renauter** [threefoldtech/grid_weblets#690]
Should be easy for the user to identify on which network he is going to deploy solution
Now the only way to identify it is looking at the URL

### Suggestion

I suggest to put some global information about the network on top left of the web page (on top of deployment list maybe)
The information would be the name of the network: TFChain version x.x.x

- For mainnet no need to specify
- For tesnet and devnet put some obvious identifying tag such as the one here:

![image](https://user-images.githubusercontent.com/73958772/167875935-88ba4c15-bb4a-4e6c-8820-80874f61c013.png)

Any other ideas?

### To go further

Give the possibility to change network on playground (simple link to dev / test / main network URL)
Obs: without preserving profile manager configuration associated to a given password
Be able to switch the same way as illustrated above for example
TO BE DISCUSSED

![image](https://user-images.githubusercontent.com/73958772/167885686-e98a79e0-067b-4f5d-9778-5c8f56ca1f2b.png)

**Comment by xmonader** [comment]
Network is clear based on the URL of the website (play.dev.grid.tf, play.test.grid.tf, play.grid.tf)

**Comment by maayarosama** [comment]
Added an Identifier for the current network in the sidebar, but it might need some styling @samaradel

**Comment by mohamedamer453** [comment]
Verified on devnet.

A network identifier was added in the sidebar.

![image](https://user-images.githubusercontent.com/101194226/183290560-5e62b1ff-68e8-44c3-8dff-2333c906a102.png)


*** will update this issue once it's released on the rest of the networks
