### ISSUE TITLE
Simplify getting started documentation

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#694]
Quoting @xmonader 

> the getting started docs in grid weblets are really complicated, yarn or npm, use package lock or not, which directories, docs and easy docs

### Suggestions
* As we only track the yarn lock file, we can say we only wok with `yarn`
* Update the build scripts to eliminate the need to copy build output to other directories (if possible)

**Comment by mohamedamer453** [comment]
Verified
The weblets docs were simplified and by cloning the repo and executing the 2 commands available in the Getting Started docs 
```
yarn deps  
yarn serve:app    
```
i was able to build and run the weblets locally.

![image](https://user-images.githubusercontent.com/101194226/169013707-9ebccb02-a172-42ce-9eda-2ac4ee6b0948.png)
