### ISSUE TITLE
Grid update / graphql update breaks old VM's?

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/grid_weblets#695]
![image](https://user-images.githubusercontent.com/13766992/168069500-d8f68506-5e30-4ad3-aa2c-4d11c56afc4d.png)

Copied from: https://github.com/threefoldtech/tf_operations/issues/866

**Comment by weynandkuijpers** [comment]
Lost access to another VM: 
![image](https://user-images.githubusercontent.com/13766992/168070342-4cf8c5b9-5906-4171-bb97-d12a79e6fb49.png)

**Comment by weynandkuijpers** [comment]
now I lost all my VM's....  And the balance has been frozen / not counting down also.

I now lost 3 VM for which two were for external projects:
- pokt reference install
- digithree services

twin:64.

**Comment by weynandkuijpers** [comment]
I only have VM's deployed:
<img width="908" alt="image" src="https://user-images.githubusercontent.com/13766992/168231943-68af0213-a490-4a76-abd6-d86e452e62a7.png">
So one VM is presented why there are more active contracts:
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/13766992/168232086-3ad31de5-6c0b-4418-8f86-2f6ea08a6aa1.png">

The wallet does not countdown either.

**Comment by ramezsaeed** [comment]
please re-open if u can reproduce
