### ISSUE TITLE
Weblets: Profile manager Input Validation.

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#698]
Tested on testnet Weblets v1.4.1-rc2

The input validation for Profile Manager is not working correctly in some fields.

### Profile Name

Validation for min/max length should be added and be consistent with the rest of the name fields in the weblets (min: 2, max: 15)

![image](https://user-images.githubusercontent.com/101194226/168462818-a166f03e-82d1-4a9c-a6c7-95cd7dd83580.png)

![image](https://user-images.githubusercontent.com/101194226/168462900-b4cd1644-9c4a-4adc-8949-6a4ef4ec981b.png)

Validation for Special characters/Spaces should be added.

![image](https://user-images.githubusercontent.com/101194226/168462846-f834395b-f973-4ec9-a51c-88967685ee7e.png)

### Public SSH

Validation for min/max length and correct format.

### Error messages 

All the error messages/validation warning messages in the profile manager appears after the user clicks on activate not in real-time like all the other fields in the weblets.

**Comment by mohamedamer453** [comment]
Validation for the name field was added however it doesn't disable the `Activate` button when there's an error.

![image](https://user-images.githubusercontent.com/101194226/169685659-63a1702e-92f1-40f6-b1ee-900d4ec8c972.png)

and there's still no validation for the `Public ssh Key` (Format)
for reference validation like the one available in github.

![image](https://user-images.githubusercontent.com/101194226/169686361-c20add50-b453-4f44-89d1-7d0adc8d0fe9.png)


and the error messages for `Public ssh Key` and `Mnemonics` only appear after the `Activate` button is clicked.

![image](https://user-images.githubusercontent.com/101194226/169685786-7fedb251-22e2-4ab4-ba39-c514d101f43b.png)

**Comment by mohamedamer453** [comment]
> Validation for the name field was added however it doesn't disable the `Activate` button when there's an error.
> 
> ![image](https://user-images.githubusercontent.com/101194226/169685659-63a1702e-92f1-40f6-b1ee-900d4ec8c972.png)
> 
> and there's still no validation for the `Public ssh Key` (Format) for reference validation like the one available in github.
> 
> ![image](https://user-images.githubusercontent.com/101194226/169686361-c20add50-b453-4f44-89d1-7d0adc8d0fe9.png)
> 
> and the error messages for `Public ssh Key` and `Mnemonics` only appear after the `Activate` button is clicked.
> 
> ![image](https://user-images.githubusercontent.com/101194226/169685786-7fedb251-22e2-4ab4-ba39-c514d101f43b.png)

The issues mentioned here weren't fixed.

**Comment by AhmedHanafy725** [comment]
I think it's okay to validate mnemonics with [bip93](https://www.npmjs.com/package/bip39)

**Comment by mohamedamer453** [comment]
Validation appears to be added to the Profile Name, Mnemonics, and Public SSH Key and the validation disables the `Activate` button for the mentioned fields but the existing error messages are not visible anymore and there are no error messages for the new validations.

as it can be seen in the following screenshots when any of the three fields is left empty there are no error messages but the `Activate` button is disabled which means that the validation is working but the error messages are not visible.

![image](https://user-images.githubusercontent.com/101194226/174566861-f4ceea1c-174d-4b8a-8065-abfe8fbd4801.png)

![image](https://user-images.githubusercontent.com/101194226/174567002-b37efe30-d2a2-4f3f-b1d2-4b9dbd089e82.png)

![image](https://user-images.githubusercontent.com/101194226/174567193-69a74885-0a04-4682-822e-9f27872ffd02.png)

**Comment by zaelgohary** [comment]
![image](https://user-images.githubusercontent.com/40770501/174576960-935eaf00-4ccc-458f-aa1d-e68cb0565dd8.png)

I tried to create a new profile and the validation messages are shown in case of an invalid field as per the screenshot above.

**Comment by zaelgohary** [comment]
validation was removed when the QR code was added. it's fixed now.

**Comment by mohamedamer453** [comment]
Verified on devnet.

Validation was added for `Mnemonics` and `Public SSH Key` fields and error messages were fixed for all of the fields. and the `Activate` button is disabled when there's an error in any of the fields.

### Profile Name

- Empty Field

   ![image](https://user-images.githubusercontent.com/101194226/174772341-0334e769-596b-44f3-9341-9366d37de9fb.png)

- Min/Max Length

   ![image](https://user-images.githubusercontent.com/101194226/174771133-7d83973c-83b8-461a-944d-39226dc7ff25.png)

   ![image](https://user-images.githubusercontent.com/101194226/174771215-bfb14f5f-dc8e-4f3d-bbef-d53139cab057.png)

- Alphanumeric only.

   ![image](https://user-images.githubusercontent.com/101194226/174771343-994f94ac-7834-4c19-9e16-230602bb4ef8.png)

   ![image](https://user-images.githubusercontent.com/101194226/174771421-ae7639d2-0a27-4d71-8b8a-61bd068bffdd.png)


- Can't start with a number, a non-alphanumeric character or a whitespace.

   ![image](https://user-images.githubusercontent.com/101194226/174771557-e5cd2b5e-500e-466c-a17b-c88e1267c493.png)

   ![image](https://user-images.githubusercontent.com/101194226/174771652-38e5c04e-c4da-41d3-b48a-27fbaa45b394.png)

   ![image](https://user-images.githubusercontent.com/101194226/174771735-dceec383-e011-4b3d-b011-97821a91ea0e.png)

### Mnemonics

   Validation was added to this field other than the validation that is already done after activating the profile.

- Empty Field 

   ![image](https://user-images.githubusercontent.com/101194226/174772568-2b483142-2931-4df8-8661-56b882253fc2.png)

- Invalid Mnemonics

   verified by generating multiple random Mnemonics using the bip39 format from [here](https://iancoleman.io/bip39/).

   the field doesn't accept any values that doesn't follow the bip39 format.

   ![image](https://user-images.githubusercontent.com/101194226/174773327-d8d46329-e830-4593-b7cc-882cd7cf709e.png)


### Public SSH Key

Format validation was added to this field to accept only ssh keys that start with valid key formats like 

- `ssh-rsa AAAAB3NzaC1yc2`

   ![image](https://user-images.githubusercontent.com/101194226/174774079-4d3fd6a5-403c-4234-bc47-d24482108d83.png)

- `ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNT`

   ![image](https://user-images.githubusercontent.com/101194226/174775024-0e58dd9e-03f5-42ca-b1ba-1423493d6a39.png)

- `ecdsa-sha2-nistp384 AAAAE2VjZHNhLXNoYTItbmlzdHAzODQAAAAIbmlzdHAzOD`

   ![image](https://user-images.githubusercontent.com/101194226/174775273-c5b44a13-299f-4b96-a75c-39f4377557db.png)

- `ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1Mj`

   ![image](https://user-images.githubusercontent.com/101194226/174775505-f2666b1f-2f0a-4c67-8bee-cc458e58030a.png)

- `ssh-ed25519 AAAAC3NzaC1lZDI1NTE5`

   ![image](https://user-images.githubusercontent.com/101194226/174775651-d66c9404-3da2-4bdf-b435-3ec7715d9c6a.png)

- `ssh-dss AAAAB3NzaC1kc3`

   ![image](https://user-images.githubusercontent.com/101194226/174775805-82b2e37d-8626-4cbc-8cbd-6038d592ddde.png)

**Comment by mohamedamer453** [comment]
There's only a small issue left when you try to add a new profile.

The validation messages are activated for all the fields even before the user types anything.

![image](https://user-images.githubusercontent.com/101194226/174776880-2a81fb4e-de92-4b01-9cdd-ea67b385d5ff.png)

i think the messages should only appear when a validation is triggered in one of the fields.

**Comment by AhmedHanafy725** [comment]
> There's only a small issue left when you try to add a new profile.
> 
> The validation messages are activated for all the fields even before the user types anything.
> 
> ![image](https://user-images.githubusercontent.com/101194226/174776880-2a81fb4e-de92-4b01-9cdd-ea67b385d5ff.png)
> 
> i think the messages should only appear when a validation is triggered in one of the fields.

@mohamedamer453 can we have this in a separate issue and close this one if the validation is working well?

**Comment by mohamedamer453** [comment]
Verified on devnet.

Closing this issue since all of the validations for the profile manager were fixed and working as expected and the issue for the validation message will be followed in #852
