### ISSUE TITLE
Weblets: Numeric Fields Input Validation

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#699]
Tested on testnet Weblets v1.4.1-rc2

All the fields that are supposed to only accept numeric input (CPU, Memory, Disk, Root File System, Node ID) also accepts invalid inputs like 
```
-
+
e
```

![image](https://user-images.githubusercontent.com/101194226/168462208-edfe12fd-8f79-4798-841c-357084c7b35c.png)

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/809

**Comment by MohamedElmdary** [comment]
@mohamedamer453 will double check it thanks

**Comment by MohamedElmdary** [comment]
### Fixed
https://github.com/threefoldtech/grid_weblets/pull/811

**Comment by mohamedamer453** [comment]
### Root File System

 The Root File System field is currently broken:

- Empty field
 
   Unlike other fields it can't be empty and when you try to clear the field the value in the field is changed to zero and this zero can't be deleted from the field.

   ![image](https://user-images.githubusercontent.com/101194226/173587498-d8256f78-ae1d-4c3f-b351-2919e2965b1f.png)

- Spaces, Special Characters, Characters, `+`, `-`, `e`
   
    When any of the mentioned conditions is typed in the field the value is changed to `NaN`

   ![image](https://user-images.githubusercontent.com/101194226/173587843-06e83d9c-c60d-4969-9304-95a8e5dfabd4.png)

- This field should accept decimal values unlike the other numeric fields


### CPU

- Empty field

   ![image](https://user-images.githubusercontent.com/101194226/173583731-fd56fdcc-0033-4626-b56c-79b9ed4b294f.png)

- Spaces

   ![image](https://user-images.githubusercontent.com/101194226/173583785-6072ed5a-ebbe-4c64-8b1b-222c7cf1e56d.png)

- Special Characters

   ![image](https://user-images.githubusercontent.com/101194226/173583909-9da4dd01-c599-406b-9d4b-58d4904c1340.png)

- Characters

   ![image](https://user-images.githubusercontent.com/101194226/173584438-0fdba2f2-76d0-4d91-9ec8-3a28b5322f5d.png)

- `+`

   ![image](https://user-images.githubusercontent.com/101194226/173583994-c22d08e2-1023-40be-9c38-bc637db20aa1.png)

- `-`

   ![image](https://user-images.githubusercontent.com/101194226/173584088-9ceaddde-e247-41f6-95a3-1e5e8f33d315.png)

- `e`

   ![image](https://user-images.githubusercontent.com/101194226/173584536-c2e2914c-ca32-4bfa-bbf5-81ad73dd7349.png)

- Adding Zeros Before the Value

   ![image](https://user-images.githubusercontent.com/101194226/173592805-e98a8d37-a190-4b07-adfa-c79e9ae2a1ff.png)

### Memory

- Empty field

   ![image](https://user-images.githubusercontent.com/101194226/173584715-f9d89e1d-1c8a-4e2b-80bb-ef269d8d7dda.png)

- Spaces

   ![image](https://user-images.githubusercontent.com/101194226/173584822-39b36427-5f10-4615-ac97-22ac9d1b72bb.png)

- Special Characters

   ![image](https://user-images.githubusercontent.com/101194226/173584913-2d02ad3c-6fec-43ad-b6cd-9436abde92f9.png)

- Characters

   ![image](https://user-images.githubusercontent.com/101194226/173585017-3d92cfc6-cc44-433e-b2ad-743d13aea21e.png)

- `+`

   ![image](https://user-images.githubusercontent.com/101194226/173585094-0bc5dc4f-90c1-405c-961b-3b0dcfac91b0.png)

- `-`

   ![image](https://user-images.githubusercontent.com/101194226/173585148-10d118ed-ba82-496c-95ba-bf8a198a9412.png)

- `e`

   ![image](https://user-images.githubusercontent.com/101194226/173585226-3c03d640-533c-4966-b93d-4312b5138859.png)

- Adding Zeros Before the Value

   ![image](https://user-images.githubusercontent.com/101194226/173593017-b5225546-72b0-426c-8f71-baee84502a68.png)


### Disk

- Empty field

   ![image](https://user-images.githubusercontent.com/101194226/173585558-04dacb91-cdc6-471f-8617-272fb78662c1.png)

- Spaces

   ![image](https://user-images.githubusercontent.com/101194226/173585729-3435ce1a-a344-4042-938f-0eb987d5e1e9.png)

- Special Characters

   ![image](https://user-images.githubusercontent.com/101194226/173585807-06c90e5d-b1f8-4a64-9b1d-3558679e9ff7.png)

- Characters

   ![image](https://user-images.githubusercontent.com/101194226/173585904-691aa062-8d34-4417-bc5f-0b24155a00f9.png)

- `+`

   ![image](https://user-images.githubusercontent.com/101194226/173585978-72643b65-c2aa-4f42-afbd-3e7622484f61.png)

- `-`

   ![image](https://user-images.githubusercontent.com/101194226/173586046-cd144c08-238d-40b3-a853-be8476178db9.png)

- `e`

   ![image](https://user-images.githubusercontent.com/101194226/173586140-0f1a35f1-fb90-4876-a517-af5af19438c0.png)

- Adding Zeros Before the Value

   ![image](https://user-images.githubusercontent.com/101194226/173593246-523c43f8-97e5-4028-bc86-08036c15e7ca.png)


The validation for `CPU`, `Memory` and `Disk` Fields is working and the `Deploy` button was disabled in all the mentioned cases.

The `Root File System` field is broken as mentioned above.

and the  issue mentioned before was fixed and these error messages don't appear anymore after changing the values in these fields.

> Now when i change anything in a numeric field and try to deploy i get an error.
> 
> ### VM
> ![image](https://user-images.githubusercontent.com/101194226/173345534-77d8d3b3-e474-4c5f-aca1-4aa21b9f54ec.png)
> 
> ### K8s
> ![image](https://user-images.githubusercontent.com/101194226/173345782-8b7fa46a-ad5f-40f0-bc0c-9048e7f4d844.png)

**Comment by mohamedamer453** [comment]
Another bug was found in the `Root File System` field.

When you reach a certain limit (more than 16 characters) the field start to change that value you enter for example i was typing `2`

and after typing the 17th `2` it changed to `4`

![image](https://user-images.githubusercontent.com/101194226/174072827-be9fc406-2928-41c8-b295-a4968d2781a3.png)

and the 18th `2` changed to zero

![image](https://user-images.githubusercontent.com/101194226/174072958-d75f708d-d255-447a-82a4-b16d14fa1b19.png)

and the 19th `2` changed the `4` to `3`

![image](https://user-images.githubusercontent.com/101194226/174073047-274082be-6bcf-436e-b43f-074c4f21d6f2.png)

and the 20th `2` changed last 4 digits to zeros 

![image](https://user-images.githubusercontent.com/101194226/174073213-4858f671-3408-44c4-8144-99dd16bb5917.png)

and the 21st `2` changed to zero

![image](https://user-images.githubusercontent.com/101194226/174073260-0ccf30ba-1cef-4426-92fd-1c8a1d851062.png)

and then the 22nd and 23rd `2` changed  the value to scientific format `2.222222222222222e+21` 

![image](https://user-images.githubusercontent.com/101194226/174073624-a1d1e0bb-3f3a-44cd-93b2-c87fcb5db950.png)

![image](https://user-images.githubusercontent.com/101194226/174073668-0fe79f4f-1b29-4126-843e-6e436bc20813.png)

and the 24th `2` changed the value to `infinity`

![image](https://user-images.githubusercontent.com/101194226/174073710-1e476dd1-67a5-42f4-ae21-5fcb411590f9.png)

and the 25th `2` changed the value to `NaN`

![image](https://user-images.githubusercontent.com/101194226/174073760-14b68b64-bcca-41ed-844d-eae099540764.png)

### Steps to reproduce 
- Keep typing any digit multiple time in the `Root File System` field and after the 16th digit you will start to see the pattern mentioned above.

**Comment by mohamedamer453** [comment]
The `Node ID` field in the manual filter also suffers from the same issues in the Root FS field.

anything other than digits is turned to `NaN`

![image](https://user-images.githubusercontent.com/101194226/175804837-3fd8c45e-71bd-41d3-9e83-dd912624b1dc.png)

and adding more than 16 digit causes the same scenario mentioned above.

![TF Playground (1)](https://user-images.githubusercontent.com/101194226/175805107-5d498a52-6ad4-4ef3-be1e-8c193fe570f9.gif)

**Comment by mohamedamer453** [comment]
The issues in the `Root File System` and `Node ID` fields were not fixed.

![TF Playground (17)](https://user-images.githubusercontent.com/101194226/177305676-9138cfa9-8a8d-4daa-9624-9911c26efe67.gif)

**Comment by A-Harby** [comment]
> The issues in the `Root File System` and `Node ID` fields were not fixed.
> 
Tested on Devnet, however the problem remains unresolved.
![image](https://user-images.githubusercontent.com/109473873/187073117-33314465-d626-4aab-88c8-5195378d6dcf.png)

**Comment by MohamedElmdary** [comment]
Wish it's fixed this time https://github.com/threefoldtech/grid_weblets/pull/975

**Comment by mohamedamer453** [comment]
Verified on devnet.

- For both the `Root FS` and `Node ID`  fields, a maximum of 15 character was added and the user can't enter anything more than 15 characters. so the case where the input was changed to and imaginary number then to NaN doesn't happen anymore.

   ![image](https://user-images.githubusercontent.com/101194226/187206196-9238e2e2-3e79-444c-ad5d-6736c7bd3263.png)

- for special characters like `-`, `e` an error message will appear that the value must be positive 

    ![image](https://user-images.githubusercontent.com/101194226/187207318-01916c5a-7818-4031-88ea-9df836aa8f2a.png)

- and for other special characters like `+` it will be replaced by the value you enter once you enter a valid number.

   ![TF Playground (23)](https://user-images.githubusercontent.com/101194226/187207750-dcf2d5be-f773-4c74-a70d-4d70753a359d.gif)
