### ISSUE TITLE
profile manager menu

### ISSUE THREAD

**Issue by rkhamis** [threefoldtech/grid_weblets#70]
do something like github/google/taiga of managing profiles
needs to be more clear

loaded profile should always be visible across all pages

when navigating anywhere else, should close

![image](https://user-images.githubusercontent.com/8425762/143847120-a35c0f8d-d370-4277-ad37-33f953f9ddc7.png)
 something like this

**Comment by MohamedElmdary** [comment]
### Updated
![image](https://user-images.githubusercontent.com/31689104/144040488-8e085cc6-5718-4c26-a6f4-185a18ccca14.png)
![image](https://user-images.githubusercontent.com/31689104/144040554-e0b19110-a8f2-45de-9b69-cced1bf2b584.png)
