### ISSUE TITLE
Weblets: Mattermost input validation

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#707]
Tested on testnet Weblets v1.4.1-rc2

The input validation for mattermost is not working correctly in some fields.

### Name field

Produces an error in case of non-alpha numeric values or when the name starts with a number, space or special character. but the deploy button is not disabled.

![image](https://user-images.githubusercontent.com/101194226/168079643-746c1522-9db4-4521-8d5a-9077113e7b2d.png)

![image](https://user-images.githubusercontent.com/101194226/168079712-4d461685-1d57-4389-b83e-ac9e13433b7e.png)

### SMTP Username field

Validation for this field was added on devnet but it also doesn't disable the deploy button when there's an error.

### SMTP Server field

![image](https://user-images.githubusercontent.com/101194226/168081062-9496a2f9-81f0-412d-9167-dd9fb9054e6c.png)

this field also doesn't disable the deploy button

### SMTP Password

Validation for min/max length needs to be added.

![image](https://user-images.githubusercontent.com/101194226/168113814-562942cf-761f-4ebf-b4a3-c4c7dbb9575f.png)

![image](https://user-images.githubusercontent.com/101194226/168113754-fe37f3c4-0586-471e-94b0-92aa90e713dd.png)

### SMTP Port

All the validation for this field is working except for whitespaces it triggers the error but the button is not disabled.

![image](https://user-images.githubusercontent.com/101194226/168114567-39b209a0-04df-4459-86f6-ceee03e438ab.png)

**Comment by mohamedamer453** [comment]
Verified on Devnet.

### Name Field.

The `Deploy` button is now disabled when there's an error.

![image](https://user-images.githubusercontent.com/101194226/170447105-c02190e0-9d9a-4dfc-9512-75751d821899.png)

### SMTP Username Field

The `Deploy` button is now disabled when there's an error.

![image](https://user-images.githubusercontent.com/101194226/170449391-e443e438-7f9c-4c27-aa16-a91d9e20a784.png)

### SMTP Server

The `Deploy` button is now disabled when there's an error.

![image](https://user-images.githubusercontent.com/101194226/170450031-fe761def-d93c-4592-8e15-15d341faa04d.png)


### SMTP Port

The `Deploy` button is now disabled when there's an error.

![image](https://user-images.githubusercontent.com/101194226/170450339-8ad866fa-463c-4089-ab08-c39b378a1031.png)


### SMTP Password

![image](https://user-images.githubusercontent.com/101194226/170450867-30789799-d498-45ec-9c5e-6bc7031fe84f.png)

![image](https://user-images.githubusercontent.com/101194226/170450925-f202398b-dcc7-402e-bc2a-be4f973dba20.png)



But since mattermost doesn't require SMTP configuration 

![image](https://user-images.githubusercontent.com/101194226/170451227-e4c2ef2e-1982-4141-a9de-9bd44ed42cc4.png)

The `SMTP Password` and `SMTP Port` fields should not be required and should not disable the `Deploy` button

**Comment by mohamedamer453** [comment]
### Password field 

The password field is not required anymore but the error message still appears when the field is left empty.

![image](https://user-images.githubusercontent.com/101194226/172340328-a695cc94-de66-49e7-ae42-685d6a368400.png)

### SMTP Port field

This field is still required and disables the `Deploy` button when it's left empty.

![image](https://user-images.githubusercontent.com/101194226/172341098-68564b16-2783-40ac-9992-cf1cb45fa8fc.png)

**Comment by Omarabdul3ziz** [comment]
> 

these should be resolved in this pr https://github.com/threefoldtech/grid_weblets/pull/779

**Comment by mohamedamer453** [comment]
The fields are not required anymore but the `Deploy` button is not disabled when there's an error with one of the optional fields.

### Password field

![image](https://user-images.githubusercontent.com/101194226/172573538-43e0f680-35c6-4545-ae39-d735bb95eeb2.png)

![image](https://user-images.githubusercontent.com/101194226/172573617-c4a987a6-a87e-45e7-83a8-358a0815f783.png)

### SMTP Port field

![image](https://user-images.githubusercontent.com/101194226/172573687-b3c43ba4-96c4-4e31-8aac-dcada9d4df9d.png)

### SMTP Server

![image](https://user-images.githubusercontent.com/101194226/172573910-8ab7bccd-76f7-4e91-b6cf-f518c5eae680.png)

### SMTP Username

![image](https://user-images.githubusercontent.com/101194226/172574021-c799ac09-4946-4633-b348-a2aa29cd57be.png)

**Comment by maayarosama** [comment]
The SMTP fields are now optional and also disable the deploy button when there's an error message.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The `Deploy` button is now disabled when there's an error with any of the optional fields.

### SMTP Username

![image](https://user-images.githubusercontent.com/101194226/173570205-f246b68a-64a1-49f0-aa8f-f72dea27e491.png)

### SMTP Password

![image](https://user-images.githubusercontent.com/101194226/173570274-8fdd75b0-8d03-43ba-8d08-06f49c0dc4c9.png)

![image](https://user-images.githubusercontent.com/101194226/173570322-9499985f-3e5c-486d-aa2c-ddf16315149d.png)

### SMTP Server

![image](https://user-images.githubusercontent.com/101194226/173570405-0be9a65a-914f-4408-9ac8-dacdc588cc75.png)

### SMTP Port

![image](https://user-images.githubusercontent.com/101194226/173570466-7ca567fa-2e0d-4598-a7de-e3d89fe9f5c1.png)

![image](https://user-images.githubusercontent.com/101194226/173570529-36e25d01-fd77-48dd-8ca4-59ef88d0696a.png)
