### ISSUE TITLE
Peertube deployment and documentation inconsistencies 

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#709]
In the Weblets documentation https://library.threefold.me/info/manual/#/manual__weblets_peertube  for PeerTube, we can see that we have an ability to assign a public IP to the instance

![image](https://user-images.githubusercontent.com/65153287/168559101-00854ec1-b863-42de-88da-c0ab2e672add.png)

But on the actual deployment screen this option is now gone

![image](https://user-images.githubusercontent.com/65153287/168559462-77f5173c-1c20-4320-b2aa-251693c834f5.png)

If you choose any of the pre-packages or custom, it only creates IPv6 IP address by default.

Disabled IPv4 checkbox is available from the details screen

![image](https://user-images.githubusercontent.com/65153287/168559788-6daea555-8bc8-4770-bc67-c1c6242e6d8a.png)

**Comment by Omarabdul3ziz** [comment]
docs updated at commit `6d7b215f4fe8d756346b0595635b5b6afb69177a` on https://github.com/threefoldfoundation/info_manual3

**Comment by mohamedamer453** [comment]
The first part of the doc was updated with the current look of the weblet.

![image](https://user-images.githubusercontent.com/101194226/172347933-a2610a7d-ce6b-48a8-8e52-541ab2b7bd14.png)

but there's still 2 screenshots with the old config that had the `Public IP` option

![image](https://user-images.githubusercontent.com/101194226/172348051-04ce2c47-d6c2-4a3c-aae2-114bf1b18038.png)

![image](https://user-images.githubusercontent.com/101194226/172348159-5995dbd0-639e-40ad-a800-92b3e01f5a43.png)

**Comment by Omarabdul3ziz** [comment]
docs updated by deleting the outdated screenshots at commit `384aa5acb3bfc3efa86a4a67019bda8a22102597` on https://github.com/threefoldfoundation/info_manual3 
issue for operation to release https://github.com/threefoldtech/tf_operations/issues/918

**Comment by mohamedamer453** [comment]
Verified.
The [docs](https://library.threefold.me/info/manual/#/manual__weblets_peertube) were updated and the old screenshots with the outdated `Public IP` option were removed.
