### ISSUE TITLE
Weblets: Kubernetes Cluster Token Input Validation

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#710]
There is no input validation for the Cluster Token field in the kubernetes deployment.
 
The deploy button only gets disabled when the field is empty and there's no error message when the field is empty.

![image](https://user-images.githubusercontent.com/101194226/167866493-21498db6-d659-426b-b87c-a7c65df4d43f.png)

Also there is no min/max characters validation or any messages about the format of the token.

![image](https://user-images.githubusercontent.com/101194226/167866682-ed2606f5-9aa6-4ad5-a50c-3ed0fbfa6054.png)

![image](https://user-images.githubusercontent.com/101194226/167866810-6421e57c-0556-4b61-8a4c-9a91b8f22dc9.png)

and special characters are allowed 

![image](https://user-images.githubusercontent.com/101194226/167867021-e5f38429-e915-4e26-ac0f-fe8486880115.png)

also i was able to successfully deploy a cluster with a cluster token value of `1` as you can see below in the deployment details.

```
"env": {
                "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576",
                "K3S_TOKEN": "1",
                "K3S_DATA_DIR": "/mnt/data",
                "K3S_FLANNEL_IFACE": "eth0",
                "K3S_NODE_NAME": "WR95dea9b5",
                "K3S_URL": ""
            },
```

**Comment by zaelgohary** [comment]
@mohamedamer453 What is the format needed for the token to be valid?

**Comment by mohamedamer453** [comment]
@zaelgohary 
Actually i wan't sure what the correct format of this token is or supposed to be so that's why i mentioned this in the issue.
`or any messages about the format of the token.` 

But nonetheless i think that some kind of validation needs to be added for this field so that the user is not allowed enter values that might break the deployment.

**Comment by mohamedamer453** [comment]
Verified on devnet.

Validation and error messages were added for this field and the `Deploy` button is disabled when there's an error.

### Empty Field

![image](https://user-images.githubusercontent.com/101194226/170998866-8e934816-0329-4777-ad9f-76b4d09fd3a9.png)

### Min/Max

![image](https://user-images.githubusercontent.com/101194226/170999050-157ae2fe-dbd8-43cc-8ef0-37f032cd629c.png)

![image](https://user-images.githubusercontent.com/101194226/170998986-6b164642-02c5-4f98-a19e-dc9958faf404.png)
