### ISSUE TITLE
Profile Manager:  Polkadot mnemonics / TFChain secret 

### ISSUE THREAD

**Issue by renauter** [threefoldtech/grid_weblets#711]
Once user creates an account in TFConnect, add some TFTs on TFChain and wants to use them to deploy on playground he needs to go to Profile Manager and provide menmonics of the associated wallet from Polkadot browser extension
The Mnemonics input in this case (when Polkadot account is imported) is the TFChain secret
This is not clear for user and should be explicitly specified

![image](https://user-images.githubusercontent.com/73958772/168863088-0b9dee58-b4e3-404f-94b5-4e4647f03d49.png)

#### Suggestions

Change "Mnemonics" to "Polkadot Mnemonics or TFChain secret"
Another solution would be to add some little help button after "Mnemonics" to explain what Mnemonics field could be filled with depending on the case

**Comment by A-Harby** [comment]
Verified on Devnet.

![image](https://user-images.githubusercontent.com/109473873/181504866-c90a719b-2d03-48e8-badd-d40530e67b05.png)
