### ISSUE TITLE
Virtual machine low memory validation - TC408

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#714]
1. when the resource was deployed with min available disk space with "250" MB it failed with error:

"Validation failed. errors: An instance of k has failed the validation: - property workloads[2].data.compute_capacity.memory has failed the following constraints: min"

2.  when the resource was deployed with min available disk space with "+250" MB it failed with error:

"Validation failed. errors: An instance of k has failed the validation: - property workloads[2].data.compute_capacity.memory has failed the following constraints: min"

version - v1.4.1-rc2 testnet

**Comment by xmonader** [comment]
this depends on the image, which image are we talking about?
