### ISSUE TITLE
Capacity validation blocks Presearch deployment

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#719]
While attempting to deploy Presearch weblet, the following errors are observed in browser console when using capacity filter or validating a manually selected node:

![image](https://user-images.githubusercontent.com/17682591/169618309-0b7cdd53-5313-4a9d-8127-3ac33b2b1a56.png)

This blocks deployment. If another weblet is selected from the side bar then Presearch is selected again, the error "Please activate a profile from the profile manager" is shown, even though the profile is still active.

**Comment by MohamedElmdary** [comment]
Already fixed it a week ago and it's live on https://play.dev.grid.tf/#/presearch now!
