### ISSUE TITLE
Kubernetes: Missing Manage Workers Button after the latest release on devnet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#724]
### Description

After the new UI update on devnet The `Manage Workers` Button is missing.

### Manage Kubernetes Button

How it looked before the UI update (currently on testnet)

![image](https://user-images.githubusercontent.com/101194226/169698639-a33a7dbf-063d-41fb-9275-f9f5207efcf1.png)

It's missing after the update and only the `Show Details` icon is available.

![image](https://user-images.githubusercontent.com/101194226/169698548-14be7fee-4e25-4fa0-aa28-b7ef606b447c.png)

### Steps to reproduce

- Navigate to https://play.test.grid.tf
- Deploy a K8s Cluster.
- Navigate to the Deployment List

**Comment by xmonader** [comment]
@samaradel @Omarabdul3ziz please check this regression
