### ISSUE TITLE
there's a different name for the deployment when i click on details

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#731]
When creating a deploy, a name is assigned, but in the Deployment List and details they differ
for Peertube , Funkwhale ,  Discourse , Taiga , ownCloud , Presearch , casperlabs

Deployment list 
![image](https://user-images.githubusercontent.com/65153287/169529157-bd5cc064-9edb-4c8f-b7cb-fed07a752df0.png)

Details 
![image](https://user-images.githubusercontent.com/65153287/169529180-e8363e6c-5b27-4368-85be-faf948159ac3.png)

**Comment by Omarabdul3ziz** [comment]
Actually, it is not a bug. 

The agreed naming rules say (ex: deploy peertube with name peert)
- the deployment itself should have the name from the input > `peert`
- the domain name follows the format `<weblet-code><twin-id><deployment-name>` > `pt29peert`
- the single VM, disk and network should be `<code><random-10digit>` > `vmfpdmiufr8m`, `netfpdmiufr8m`, `diskfpdmiufr8m`


with these rules we make sure we don't get conflicts for  the same deployment workloads.


The deployment list shows the deployment's name exactly as from the input.
![Screenshot from 2022-05-24 18-08-17](https://user-images.githubusercontent.com/32527347/170082250-bba9a6b2-f5e2-4786-a917-03918076da9d.png)

but the names in the modal data are for the VM, net, and disk
![2022-05-24_18-08](https://user-images.githubusercontent.com/32527347/170082275-ca8c45ec-fe95-4969-9cbc-27971233447c.png)

**Comment by xmonader** [comment]
Ah I see now, thanks for the clarification @Omarabdul3ziz
