### ISSUE TITLE
 No.22 - Test case: TC182 Cluster Token Validation

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#732]
Version v1.4.1-rc2
Deployed on Testnet

Тhere is no established validation in the input "Cluster Token"
For ex. i can deployed with Cluster Token - K3S_TOKEN": "e4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccce4a06ccc"
or   "K3S_TOKEN": "0"

**Comment by xmonader** [comment]
duplicate of https://github.com/threefoldtech/grid_weblets/issues/710
