### ISSUE TITLE
Incorrectly displays the Billing Rate on the Contracts list page (scientific notation)

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#735]
v1.4.2 , testnet

The number should show the exact amount charged, for example 0.0521 TFT.
But on the Contracts List show - 7e-7 TFT/hour
![screenshoteasy - 2022-05-19T134446 645](https://user-images.githubusercontent.com/65153287/169278976-80187043-f84f-463a-873b-d3461d717f44.png)

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/749
