### ISSUE TITLE
No.26 - Test case: TC665 Disk name/Mount path validations

### ISSUE THREAD

**Issue by dmitri-alleo** [threefoldtech/grid_weblets#737]
v1.4.1-rc2

VM - Disk Name

In the input "Disk Name" when entering invalid values - the show error message. Status Deploy Button - disable
![screenshoteasy - 2022-05-18T113107 813](https://user-images.githubusercontent.com/65153287/168994694-f9a657d6-0410-4786-b2ed-8c8a4a3cce7c.png)

**Comment by xmonader** [comment]
@Omarabdul3ziz check with @OmarElawady what needs to happen on unix paths validations (go simple)

and diskname just limit it to alphabet characters + digits with support for underscores only

**Comment by OmarElawady** [comment]
Afaik, the path name in linux doesn't have a restriction on any printable characters in its name (the ones relevant since we are doing it via the frontend). @Omarabdul3ziz tested with `strings.printable_chars` as the path name and it worked. It must be absolute (starts with `/`), be nonempty, and can't be "/".

Linux has a restriction on the path total length of 4096 and filename length of 255 bytes.

**Comment by mohamedamer453** [comment]
Verified on devnet.

Validation for the `Disk Name` field was added.

### Can't be empty

![image](https://user-images.githubusercontent.com/101194226/170454654-36d394b9-1631-4245-a37a-c1d07cea1d76.png)

### Min/max Length

![image](https://user-images.githubusercontent.com/101194226/170455863-00f717e2-d3b7-4bcc-8e50-d4a5e429c59a.png)

The actual max length is 32 and the validation is triggered at `>32` but the message says `Name must be at most 15 characters`

![image](https://user-images.githubusercontent.com/101194226/170456093-24a30c7a-98ec-4773-a9a5-d1e67d43d917.png)


### Can't start with a special character, numeric value, space.

![image](https://user-images.githubusercontent.com/101194226/170455239-f8cd9d5f-71d3-450e-8697-eb75cc798dd9.png)

When a space or a special character is added at the start the `Deploy` button is disabled but there's no error message.

![image](https://user-images.githubusercontent.com/101194226/170455324-0b5f9a45-26c6-42a2-9c96-a80f96ac03cf.png)

![image](https://user-images.githubusercontent.com/101194226/170455590-85b377c6-52ac-4b19-83fd-f22cfb4d20ac.png)


### Mount Point

When the errors mentioned above are triggered in the `Disk Name` field they aren't also triggered in the `Mount Point` field

and when you trigger an error in the `Mount Point` field and then write a valid name in the `Disk Name` field the error doesn't disappear in the `Mount Point` field until you write anything in it.

- Cleared the `Mount Point` field to produce an error.
    ![image](https://user-images.githubusercontent.com/101194226/170457757-3dbb824a-6ee6-4e40-be9f-9835d11b1c43.png)

- Then added a valid name in the `Disk Name` field and it was auto completed.
    ![image](https://user-images.githubusercontent.com/101194226/170457810-76ac06be-9a36-4bd2-94da-ad7de5ca3663.png)

- The error only goes from the `Mount Point` field when you write anything in it.
![image](https://user-images.githubusercontent.com/101194226/170457929-315c173c-f282-491d-bc7a-ab337014741e.png)

**Comment by mohamedamer453** [comment]
Also the unit for the Size (GB) needs to be added like the rest of the weblets 

![image](https://user-images.githubusercontent.com/101194226/170464131-b3a56049-86cf-4f76-b330-4b09868d6ab2.png)

example: 

![image](https://user-images.githubusercontent.com/101194226/170464197-9fc1769e-ae7a-4fb3-9865-4d61346f3416.png)

**Comment by mohamedamer453** [comment]
> Also the unit for the Size (GB) needs to be added like the rest of the weblets
> 
> ![image](https://user-images.githubusercontent.com/101194226/170464131-b3a56049-86cf-4f76-b330-4b09868d6ab2.png)
> 
> example:
> 
> ![image](https://user-images.githubusercontent.com/101194226/170464197-9fc1769e-ae7a-4fb3-9865-4d61346f3416.png)

This was solved here #748

**Comment by mohamedamer453** [comment]
### Max length

The max length was changed to 15 to as it appears in the validation message. and the `Deploy` button is disabled when there's an error.

![image](https://user-images.githubusercontent.com/101194226/172342001-3db037f5-1107-4107-9514-7ae20eb2e532.png)

### Can't start with a special character, numeric value, space.

- Space

   ![image](https://user-images.githubusercontent.com/101194226/172342732-49348477-af80-4965-ac76-2e9c75b16974.png)

- Numeric Value

   ![image](https://user-images.githubusercontent.com/101194226/172342842-9377c34d-34ee-46e6-bcc7-a834d8285aa7.png)

- Special Character

   There's still an issue with this part, when only 1 special character is added at the start it's doesn't trigger the validation and it's allowed but when it start with more than 1 special character or if there's a special character anywhere else in the name the validation is triggered and the `Deploy` button is disabled.

   - Starts with one special character
   
       ![image](https://user-images.githubusercontent.com/101194226/172343578-8f503473-7558-425d-8838-2c78197c23fe.png)

  - Starts with more than 1 special character
     
      ![image](https://user-images.githubusercontent.com/101194226/172343986-aded41ba-b96e-475a-a10e-73fd3c99a4ff.png)

  - Special character anywhere else in the name

      ![image](https://user-images.githubusercontent.com/101194226/172344175-304807ea-d926-4a53-b90b-ac4816730ea4.png)


### Mount Point 

The issue with the mount point is still not fixed. when an error is produced in the `Mount Point` field then a valid input is entered in the `Name` field it will automatically write the same valid name in the `Mount Point` field but the error message doesn't go away from the `Mount Point` field.

![image](https://user-images.githubusercontent.com/101194226/172345607-7fc2f4aa-5e5d-4b8e-9aec-175a6abb1241.png)


### Steps to reproduce the Mount Point field issue

-  Navigate to the `Disks` tab in the VM Weblet
- Add a disk
- Clear the `Mount Point` Field
- Write any valid name in the `Name` field
- You will see that the valid name was auto completed in the `Mount Point` field but there's still an error message in the mentioning that the `Mount point is required`

**Comment by mohamedamer453** [comment]
### Mount Point

The mount point field is now independent from the disk name field and will not be auto completed from the disk name field so the previously mentioned issue is not valid anymore.

And the validations for the Mount point field are working as expected.

- Empty Field

   ![image](https://user-images.githubusercontent.com/101194226/173792618-3e568af5-91ed-487a-aab0-cf801fd6a99f.png)

- Format

   ![image](https://user-images.githubusercontent.com/101194226/173792713-994d0551-4eea-475f-8b58-be62e7dd76e4.png)


### Disk Name

For the disk name field the previously mentioned issue was not fixed





> * Special Character
>   There's still an issue with this part, when only 1 special character is added at the start it's doesn't trigger the validation and it's allowed but when it start with more than 1 special character or if there's a special character anywhere else in the name the validation is triggered and the `Deploy` button is disabled.
>   
>   * Starts with one special character
>     ![image](https://user-images.githubusercontent.com/101194226/172343578-8f503473-7558-425d-8838-2c78197c23fe.png)

and when you deploy with one special character at the start you get this error.

![image](https://user-images.githubusercontent.com/101194226/173794241-33610427-e228-41b5-97b8-e6a5b7ca34dc.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

### Disk Name

The disk name field now produces an error and disables the `Deploy` button when only 1 special character is added before the name.

![image](https://user-images.githubusercontent.com/101194226/173831691-4cc608ef-2053-404c-8fda-44a231aa2d8c.png)
