### ISSUE TITLE
the manual node selection seems broken

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#741]
### Description

on play.dev.grid.tf b56b9d5, manual node selection cannot validate the same node returned from the capacity filter. 

### Steps to reproduce

on Owncloud weblet , with standard package, check nodes returned from the capacity filter, then try to enter it one by one on the manual mode
![Peek 2022-05-25 12-39](https://user-images.githubusercontent.com/42457449/170246109-25d37bfe-b3c3-49d5-b53c-f7c4cc0521bd.gif)

**Comment by MohamedElmdary** [comment]
The issue doesn't relate to OwnCloud itself ... there is a bug in the grid3_client filter or our calculation in the manual filter ... trying to figure it.

**Comment by AhmedHanafy725** [comment]
this happens because of the over-provisioning in sru which is gonna be removed in the next grid3_client release.

**Comment by AhmedHanafy725** [comment]
this should be resolved now

**Comment by mohamedamer453** [comment]
Verified on devnet.

All the nodes available in the Capacity filter can also be selected through the manual filter without any issues.

![image](https://user-images.githubusercontent.com/101194226/170472230-8f3287c7-42c7-4124-8d54-2d69eda323ea.png)

![image](https://user-images.githubusercontent.com/101194226/170475176-296eb771-e7a3-40fb-9c6b-084f2c34e81a.png)

![image](https://user-images.githubusercontent.com/101194226/170475275-4a8e85b7-95d7-4694-8623-1f2742e9b5a1.png)

![image](https://user-images.githubusercontent.com/101194226/170475362-47ffe2e8-1b10-437f-81db-90ebdfcb221a.png)

![image](https://user-images.githubusercontent.com/101194226/170475440-7a454eed-4c1e-4e21-b06c-d45e111afab2.png)

![image](https://user-images.githubusercontent.com/101194226/170475477-8c98efce-a9db-480b-93f0-4154347fb05f.png)

![image](https://user-images.githubusercontent.com/101194226/170475699-3f8d06b6-9a1e-4035-9768-2683803f3a96.png)

![image](https://user-images.githubusercontent.com/101194226/170475706-b59be292-3839-4395-aeff-6477e00a78a2.png)

![image](https://user-images.githubusercontent.com/101194226/170475743-193f0c6f-d493-49a9-a2b9-05503bcef17c.png)

![image](https://user-images.githubusercontent.com/101194226/170476255-16959387-9953-48a5-8a87-e7bce7d8b523.png)

![image](https://user-images.githubusercontent.com/101194226/170476307-6e607391-8063-478b-8fc4-8969991ac823.png)

![image](https://user-images.githubusercontent.com/101194226/170476339-18dde70b-fa86-477c-af12-43ce91dd17bd.png)

![image](https://user-images.githubusercontent.com/101194226/170476492-a1705826-8cd3-426e-8f9b-f36c29b2cf81.png)

![image](https://user-images.githubusercontent.com/101194226/170476613-1c81b1bf-34f6-4fc6-b6bf-211bd94f7956.png)

![image](https://user-images.githubusercontent.com/101194226/170476677-c6d5e6c8-2b8c-41f1-8a73-59c07dda626d.png)



However some nodes are not appearing in the capacity filter but appearing in the Manual filter 

for example: Nodes `23, 24, 25, 26`

![image](https://user-images.githubusercontent.com/101194226/170477444-b2abed16-a499-4e41-9def-c0f3d3710851.png)

![image](https://user-images.githubusercontent.com/101194226/170477480-21901333-a0d2-49be-8e06-0b2ecf9dfefd.png)

![image](https://user-images.githubusercontent.com/101194226/170477520-9cfdb12e-9cd2-4eb9-8e4f-d04b7b87db38.png)

![image](https://user-images.githubusercontent.com/101194226/170477574-646bb602-3f48-4e4a-981c-2b6c4a227051.png)

**Comment by mohamedamer453** [comment]
> 
> However some nodes are not appearing in the capacity filter but appearing in the Manual filter
> 
> for example: Nodes `23, 24, 25, 26`
> 
> ![image](https://user-images.githubusercontent.com/101194226/170477444-b2abed16-a499-4e41-9def-c0f3d3710851.png)
> 
> ![image](https://user-images.githubusercontent.com/101194226/170477480-21901333-a0d2-49be-8e06-0b2ecf9dfefd.png)
> 
> ![image](https://user-images.githubusercontent.com/101194226/170477520-9cfdb12e-9cd2-4eb9-8e4f-d04b7b87db38.png)
> 
> ![image](https://user-images.githubusercontent.com/101194226/170477574-646bb602-3f48-4e4a-981c-2b6c4a227051.png)


@sameh-farouk @AhmedHanafy725  i just want to check if this is normal behavior or not since these nodes were not available in the capacity filter.

**Comment by sameh-farouk** [comment]
@mohamedamer453 I think this is normal but let's wait for a confirmation from @AhmedHanafy725

**Comment by AhmedHanafy725** [comment]
no, these nodes are down, they shouldn't be available in the manual selection

**Comment by mohamedamer453** [comment]
Verified on devnet.

now the manual filter only shows the same nodes available in the capacity filter as online and all the other nodes appear as offline/unavailable. even the nodes that were appearing online even though they were down `23,24,25,26` are now appearing offline.
