### ISSUE TITLE
Add validation before deployment

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#75]
- [x] Store password in sessionStorage
- [x] Validate user got at least 2 tft before deploy
- [x] Show correct password in `caprover` in tooltip
- [x] Show Balance for user
- [x] Update DeployedList to remove head if tab is passed

**Comment by MohamedElmdary** [comment]
### Phase 2
- Add validator in Input component
- Update balance after deployment
- Prevent validate node if user using automatic selection

**Comment by waleedhammam** [comment]
verified on play.dev.grid.tf
