### ISSUE TITLE
Couldn't get free wg ports for node 329 mainnet

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#751]
![image](https://user-images.githubusercontent.com/64129/170850512-a5766ddc-6f24-4dcb-89ee-79d3a4c40942.png)

reported by kds, please investigate the reason, and maybe it's better if nodes list in gridproxy to list only nodes with wiregurad ports available?

**Comment by xmonader** [comment]
This means that the node didn't respond to the RMB message, or it's offline

**Comment by mohamedamer453** [comment]
Verified.

It was a network problem at the time and i tried deploying on node 329 and the deployment was successful.

![image](https://user-images.githubusercontent.com/101194226/183294692-35e13192-2172-43bc-9293-fe7a4619ba33.png)
