### ISSUE TITLE
Unable to SSH to machines on node 74 (Testnet)

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#753]
Tested on testnet weblets v1.4.2
### Description

After successfully deploying a Discourse instance i was unable to access it and it kept giving `Bad Gateway` and i was not able to ssh to the vm

![image](https://user-images.githubusercontent.com/101194226/170875649-3a04958f-84b9-4200-a79c-e9ba21149898.png)

![image](https://user-images.githubusercontent.com/101194226/170875627-9bdd3d3b-5012-436b-8e02-7a89080c1816.png)

### Steps to reproduce

- Navigate to https://play.test.grid.tf/
- Navigate to the Discourse tab.
- Configure your instance and click on `Deploy`

### Logs/Alerts

- Deployment Details

```
{
    "version": 0,
    "contractId": 5639,
    "nodeId": 74,
    "name": "vmdebtosfyem",
    "created": 1653833823,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/rafybenjamin.3bot/threefolddev-discourse-v4.0.flist",
    "publicIP": null,
    "planetary": "300:ec71:feb1:1a9d:9b28:895b:aef2:1698",
    "interfaces": [
        {
            "network": "nwdebtosfyem",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 1,
        "memory": 2048
    },
    "mounts": [
        {
            "name": "diskdebtosfyem",
            "mountPoint": "/var/lib/docker",
            "size": 53687091200,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576",
        "DISCOURSE_HOSTNAME": "dc451dc20f25bbe.gent01.test.grid.tf",
        "DISCOURSE_DEVELOPER_EMAILS": "amerm@incubaid.com",
        "DISCOURSE_SMTP_ADDRESS": "smtp.gmail.com",
        "DISCOURSE_SMTP_PORT": "587",
        "DISCOURSE_SMTP_ENABLE_START_TLS": "true",
        "DISCOURSE_SMTP_USER_NAME": "amerm@incubaid.com",
        "DISCOURSE_SMTP_PASSWORD": "123456789",
        "THREEBOT_PRIVATE_KEY": "M11m6UhH4CoJA2DbqKCJCx0ppTi3dOoSFHELp6YUX1M=",
        "FLASK_SECRET_KEY": "8ea19b34"
    },
    "entrypoint": "/.start_discourse.sh",
    "metadata": "",
    "description": "discourse machine/node",
    "corex": false
}
```

**Comment by mohamedamer453** [comment]
when i checked on the instance now it appeared to be working but it has been stuck on this page for about 20 mins 

![image](https://user-images.githubusercontent.com/101194226/170944783-336180f6-4060-48cf-a77e-9fa4edf4a3a1.png)

and i found this error in the console 

```
Failed to load resource: the server responded with a status of 502 ()
```

![image](https://user-images.githubusercontent.com/101194226/170944916-2db33896-8044-4ab0-9bf2-5d1fd0eb00f4.png)


and again i wasn't able to ssh to the vm but i got a different error this time 

![image](https://user-images.githubusercontent.com/101194226/170945114-b226cd99-e5dd-404b-af0f-d71d9837f887.png)

**Comment by mohamedamer453** [comment]
I deployed another discourse instance on node `5` and it's working fine without any issues and i was able to ssh to the vm of this instance.

![image](https://user-images.githubusercontent.com/101194226/170960794-2963eb47-dd87-4490-a350-30e723002382.png)

- Deployment Details

```
{
    "version": 0,
    "contractId": 5692,
    "nodeId": 5,
    "name": "vmlrchwkixur",
    "created": 1653901742,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/rafybenjamin.3bot/threefolddev-discourse-v4.0.flist",
    "publicIP": null,
    "planetary": "300:9c4a:29ac:6e0b:af39:f540:fd3a:a456",
    "interfaces": [
        {
            "network": "nwlrchwkixur",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 1,
        "memory": 2048
    },
    "mounts": [
        {
            "name": "disklrchwkixur",
            "mountPoint": "/var/lib/docker",
            "size": 53687091200,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576",
        "DISCOURSE_HOSTNAME": "dc451testdiscourse12.gent01.test.grid.tf",
        "DISCOURSE_DEVELOPER_EMAILS": "amerm@incubaid.com",
        "DISCOURSE_SMTP_ADDRESS": "smtp.gmail.com",
        "DISCOURSE_SMTP_PORT": "587",
        "DISCOURSE_SMTP_ENABLE_START_TLS": "true",
        "DISCOURSE_SMTP_USER_NAME": "amerm@incubaid.com",
        "DISCOURSE_SMTP_PASSWORD": "abc123456",
        "THREEBOT_PRIVATE_KEY": "lLmOuKwUCHIYkXz5PaW8hd1OeqbVqJ2E1+i7vOCa6Qk=",
        "FLASK_SECRET_KEY": "697cd62a"
    },
    "entrypoint": "/.start_discourse.sh",
    "metadata": "",
    "description": "discourse machine/node",
    "corex": false
}
```

Also i tried deploying again on node `74` and i received the same errors as the original issue.

- `Bad Gateway` when i try to access the instance.
- Unable to ssh to the machine with this error `ssh: connect to host 300:ec71:feb1:1a9d:2d25:268b:e86f:8333 port 22: Connection refused`
   
   ![image](https://user-images.githubusercontent.com/101194226/170963808-530eef4b-3eb3-4062-9d4c-54666a4143d2.png)

- Deployment Details

```
{
    "version": 0,
    "contractId": 5699,
    "nodeId": 74,
    "name": "vml9mkumxrat",
    "created": 1653902818,
    "status": "ok",
    "message": "",
    "flist": "https://hub.grid.tf/rafybenjamin.3bot/threefolddev-discourse-v4.0.flist",
    "publicIP": null,
    "planetary": "300:ec71:feb1:1a9d:2d25:268b:e86f:8333",
    "interfaces": [
        {
            "network": "nwl9mkumxrat",
            "ip": "10.20.2.2"
        }
    ],
    "capacity": {
        "cpu": 1,
        "memory": 2048
    },
    "mounts": [
        {
            "name": "diskl9mkumxrat",
            "mountPoint": "/var/lib/docker",
            "size": 53687091200,
            "state": "ok",
            "message": ""
        }
    ],
    "env": {
        "SSH_KEY": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC533B35CELELtgg2d7Tsi5KelLxR0FYUlrcTmRRQuTNP9arP01JYD8iHKqh6naMbbzR8+M0gdPEeRK4oVqQtEcH1C47vLyRI/4DqahAE2nTW08wtJM5uiIvcQ9H2HMzZ3MXYWWlgyHMgW2QXQxzrRS0NXvsY+4wxe97MMZs9MDs+d+X15DfG6JffjMHydi+4tHB50WmHe5tFscBFxLbgDBUxNGiwi3BQc1nWIuYwMMV1GFwT3ndyLAp19KPkEa/dffiqLdzkgs2qpXtfBhTZ/lFeQRc60DHCMWExr9ySDbavIMuBFylf/ZQeJXm9dFXJN7bBTbflZIIuUMjmrI7cU5eSuZqAj5l+Yb1mLN8ljmKSIM3/tkKbzXNH5AUtRVKTn+aEPvJAEYtserAxAP5pjy6nmegn0UerEE3DWEV2kqDig3aPSNhi9WSCykvG2tz7DIr0UP6qEIWYMC/5OisnSGj8w8dAjyxS9B0Jlx7DEmqPDNBqp8UcwV75Cot8vtIac= root@mohamed-Inspiron-3576",
        "DISCOURSE_HOSTNAME": "dc451dcb8b3bb32.gent01.test.grid.tf",
        "DISCOURSE_DEVELOPER_EMAILS": "amerm@incubaid.com",
        "DISCOURSE_SMTP_ADDRESS": "smtp.gmail.com",
        "DISCOURSE_SMTP_PORT": "587",
        "DISCOURSE_SMTP_ENABLE_START_TLS": "true",
        "DISCOURSE_SMTP_USER_NAME": "amerm@incubaid.com",
        "DISCOURSE_SMTP_PASSWORD": "abc123456",
        "THREEBOT_PRIVATE_KEY": "XfZGSaoVhpwHuRUD328Rtl6nUcYiRvvBiwv9z82vZB8=",
        "FLASK_SECRET_KEY": "08a5191c"
    },
    "entrypoint": "/.start_discourse.sh",
    "metadata": "",
    "description": "discourse machine/node",
    "corex": false
}
```

**Comment by mohamedamer453** [comment]
The problem appears to be with node `74` because i tried to deploy a vm on it and it was deployed successfully but again i wasn't able to shh to them vm with the same error `ssh: connect to host 300:ec71:feb1:1a9d:447d:3b27:3e3:5417 port 22: Connection refused`

and the same with a k8s cluster, successfully deployed but unable to ssh to the master `ssh: connect to host 300:ec71:feb1:1a9d:d511:d961:f859:4da1 port 22: Connection refused`

**Comment by Omarabdul3ziz** [comment]
to debug tried some scenarios on test net (v1.4.2):
- deployed discourse on another node than 74: and it works on the node (1) and it works properly and be able to ssh to it.
- deployed another solution on the same node (74): peertube for example and it works.

but for several times tried to deploy discourse on node 74 but every time I got this error
![Screenshot from 2022-06-08 13-24-29](https://user-images.githubusercontent.com/32527347/172641710-7b2c2459-3ea0-4f42-8c5a-e6ec768e3abf.png)
as discussed with @OmarElawady it looks that especially this node (74) takes too long to mount this flist (discourse4.0) which makes it fails and that is due to the large size of the flist

**Comment by hossnys** [comment]
here are the node logs when tried to deploy vm there 
![Screenshot from 2022-06-12 18-11-29](https://user-images.githubusercontent.com/26298009/173242559-9df47935-300d-4c0f-965c-f3f54889612a.png)

will try to check the node itself tomorrow with Bert to dig more into that.

**Comment by coesensbert** [comment]
The node has memory issues. Bettertoken guys will do a memtest and replace. Will update here once resolved.

![image](https://user-images.githubusercontent.com/88312671/173364090-4f5033bf-d10a-40a5-bb3a-d5276fc48f74.png)

**Comment by coesensbert** [comment]
Node 74 was memtested for 3 days, it had 3 full passes without a single error found. BetterToken reseated all ram and brought the node back online. No kernel hardware error's for now.

![image](https://user-images.githubusercontent.com/88312671/174098342-fbd0ad74-dc5a-43c6-a226-0115d58be6ef.png)

**Comment by Omarabdul3ziz** [comment]
tested again on test net `v1.4.3-rc1` 
deployed a `vm`, `peertube` and multiple `discourse` instances and all works file.
