### ISSUE TITLE
Casperlabs Deployment Failed to be ready after 5 minutes 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#755]
Tested on testnet weblets v1.4.2

### Description

Casperlabs deployment failed to be ready after 5 minutes.

![image](https://user-images.githubusercontent.com/101194226/170876121-a74471be-8341-4bc5-9666-baa8aefda278.png)

The deployment was on node `186`

I tried another deployment on node `8` and it was successful and i was able to access the dashboard

**Comment by mohamedamer453** [comment]
I tried deploying again on node `186` and it also didn't work giving the same error.

![image](https://user-images.githubusercontent.com/101194226/170954973-e3d2530a-3173-4eed-b9b5-6dc13386939b.png)

however i randomly deployed  casperlabs instances on nodes `1,8,15,187` and they all were deployed and working without any issues.

**Comment by ramezsaeed** [comment]
@mohamedamer453 
please report the failed node in which Farm.
we also need Zos versions.

**Comment by mohamedamer453** [comment]
From the explorer:

- Node ID: 186
- Farm ID: 1
- Farm Name: FreeFarm


How can i get the Zos version ?

**Comment by Omarabdul3ziz** [comment]
trying to debug that on testnet (v1.4.4-rc1). and it looks like it is a node problem. I opened issues on testnet

casperlabs instance with (2 Cores, 2GB RAM): success
casperlabs instance with (2 Cores, 4GB RAM): fail
casperlabs instance with (2 Cores, 5GB RAM): fail
peertube instance with (2 Cores, 2GB RAM): success
peertube instance with (2 Cores, 4GB RAM): fail
VM with (2 Cores, 2GB RAM): success
VM with (2 Cores, 2GB RAM): fail

**Comment by mohamedamer453** [comment]
Verified on testnet

The issue was fixed and node `186` is working with casperlabs and other deployments without any issues. i tried to replicate the deployment with the standard configuration and with the configurations mentioned in the comments above and all of them were successful. Listed below are the configurations of the different deployments that i tried on node `186` and all of them were successful. 

### Deployments

- `Casperlabs  (CPU: 1,   Memory: 256MB, SSD: 50GB)    Successful`
- `Casperlabs  (CPU: 1,   Memory: 4GB, SSD: 100GB)     Successful`
- `Casperlabs  (CPU: 2,   Memory: 2GB, SSD: 100GB)     Successful`
- `Casperlabs  (CPU: 2,   Memory: 4GB, SSD: 100GB)     Successful`
- `Casperlabs  (CPU: 2,   Memory: 4GB, SSD: 100GB)     Successful`
- `Casperlabs  (CPU: 16, Memory: 5GB, SSD: 150GB)      Successful`
- `Full VM     (CPU: 2,   Memory: 2GB, SSD: 15 GB)     Successful`
- `Full VM     (CPU: 20, Memory: 5GB, SSD: 50 GB)      Successful`


### Environment 

- Network: `Testnet`
- Node: `186`
- Weblets Version: `v1.7.0-rc3`
