### ISSUE TITLE
Update farming calculator

### ISSUE THREAD

**Issue by renauter** [threefoldtech/grid_weblets#758]
### Adjust and update 

- [x] Titan V2.1 (V3?) default price is not 2200 USD, should be 800 USD ? see get 3node on [marketplace](https://marketplace.3node.global/index.php)
- [ ] Update certified nodes (see formulas from [spreadsheet](https://docs.google.com/spreadsheets/d/1K30cZoZIKj_ecICeCdBHsaLiH6qfdij5tfWdJRJaYs4/edit#gid=14074738))
  - [x] certified node % (25% higher rewards for CU/SU)
  - [ ] gold certified farm % (certified 50% higher rewards for CU/SU, not cumulative with certified node %)
see gold certified farming (=> all nodes are certified?) on [doc](https://docs.google.com/document/d/1HfSYtszi8VV1IrKKaFWI44NiOg5-NQOf8inE2CpX3nU/edit)

Check box needs to be updated here:

![image](https://user-images.githubusercontent.com/73958772/171004837-fdf1087e-4880-421f-a631-53737fae6763.png)

 and converted to **radio box** (node from gold certified farm is already certified node, not cumulative)
 We would have 3 categories of nodes, something like:
 - certification:
   - [ ] no certification (default)
   - [ ] certified node
   - [ ] node belongs to gold certified farm

**Comment by xmonader** [comment]
> certified node % (25% higher for CU/SU
if this means increasing the CU and rewards for titans by 25% then it's fine.

>  gold certified farm % (certified 50% higher for CU/SU, not cumulative with certified node %)

Need more information on what gold certified farm is, how it supposed to be in the UI

**Comment by renauter** [comment]
Updated issue with link to gold certified farm description doc

@despiegk can you check that specs correspond to what expected?

**Comment by renauter** [comment]
Ok so "certified farms" means all nodes are certified and "gold certified farms" is a subset of it with a specific "gold" farming policy
