### ISSUE TITLE
Feature request: Show a message when a contract is in grace period

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/grid_weblets#762]
A contract can be in following state when the user runs out of balance: `GracePeriod(startBlockNumber)`

It would be nice if the webpage can display a message that the user has to fund his wallet or his contract will be canceled in X hours

**Comment by mohamedamer453** [comment]
Verified on devnet.

The Contracts List now shows the state of the contracts in grace period and the expiration date for these contracts if the user didn't fund the account.

![image](https://user-images.githubusercontent.com/101194226/179392299-b6b2666f-20dd-4875-b948-01b8a60c48a3.png)

**Comment by DylanVerstraete** [comment]
Awesome, looks good :+1:
