### ISSUE TITLE
Better filtering infra by capacity filter (currently very cumbersome)

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#769]
Currently I can't select nodes which meet certain criteria, like
- a node belonging to a farm that has public IPv4 addresses 
- use capacity filter to select farms that are ONLY on devnet, testnet or mainnet
This makes the search for the right infrastructure very cumbersome.

**Comment by AhmedHanafy725** [comment]
> * a node belonging to a farm that has public IPv4 addresses

that's already what the public ip filter is doing, the results of this filter should be nodes whose farms have public ipv4 addresses
![image](https://user-images.githubusercontent.com/41957921/172045843-a246eeda-e9bc-4c78-bc86-a886afcf10a2.png)




> * use capacity filter to select farms that are ONLY on devnet, testnet or mainnet

each env is working against different infrastructure (different zos versions, different gridproxy versions) which won't work if we make the playground work with all of them

**Comment by gmachtel** [comment]
What I mean is that way too many farms are visible in capacity filter. This is the view for devnet. There are only 2 farms defined on testnet. 
And also there only choose farms that have IP addresses available. 
I know that on node level the result is ok. I'd like to have a proper filter on farm level. 

See <img width="1309" alt="Screenshot 2022-06-05 at 13 23 45" src="https://user-images.githubusercontent.com/30384423/172048221-72968539-98e1-45fb-b53f-9a0f093511cd.png">

**Comment by xmonader** [comment]
Just to make it clear, do you want the farms listing to also filter out farms that don't have public IPs?

Note: we won't merge devnet, testnet, mainnet information in the same project.

**Comment by gmachtel** [comment]
Well, at this moment you DO merge devnet, testnet and mainnet. Snapshot is taken from devnet.

If you ask for a public IP, indeed, it’s confusing for a user to be able to select a farm which has no public IPs available, and then find no nodes.

**Comment by gmachtel** [comment]
Fact that on devnet I can select farms 1984: animalfarm, … which are farms that do no exist on devnet.

**Comment by xmonader** [comment]
> Fact that on devnet I can select farms 1984: animalfarm, … which are farms that do no exist on devnet.

These are devnet farms of Azmy.

**Comment by gmachtel** [comment]
Not correct: it’s the full list of all farms also on mainnet. The list is endless! Has Azmy also created my_little_pony etc ???

**Comment by xmonader** [comment]
@gmachtel double-check the explorer(s), 24 farms on devnet 
![image](https://user-images.githubusercontent.com/64129/172200754-039d4f5a-7777-47b8-8981-19c532427af6.png)

testnet has 2 or 3 and mainet has 2000+, clearly your screenshot doesn't have 2000+. it's showing what is on devnet. in your next response include screenshots from the explorer the contradict what being shown in the listing.

**Comment by gmachtel** [comment]
OK sorry, then suggestion remains only to show farms that have IPv4 addresses if you choose that you need a IPv4

**Comment by mohamedamer453** [comment]
The Capacity filter now displays the farms with public ips only and when the `Public IPv4` filter is not active it doesn't show all the farms and still shows the farms with public ips only.

it can be verified from here https://gridproxy.dev.grid.tf/farms 

The only farms shown in the capacity filter 

![image](https://user-images.githubusercontent.com/101194226/173624018-49e39d48-c4db-46b9-a787-18f46088892a.png)

are the ones with pubic ips

**Comment by mohamedamer453** [comment]
Verified on devnet.

When the `Public IPv4` filter is deactivated all the farms appear including the ones without public IPS.

![image](https://user-images.githubusercontent.com/101194226/174016430-06ed69a2-e68f-415d-ace7-5b7964e8401c.png)

And when it's activated it only shows the farms with available public IPS.

![image](https://user-images.githubusercontent.com/101194226/174016579-4dd069d7-2bd0-488a-9991-6af837f41398.png)

and it can also be verified from here https://gridproxy.dev.grid.tf/farms
