### ISSUE TITLE
Add support for QAnet

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#774]
requires: https://github.com/threefoldtech/grid3_client_ts/issues/286

**Comment by mohamedamer453** [comment]
Verified.

Support for QA net was added to grid_weblets and https://play.qa.grid.tf is live now and all the deployments are working according to the current version `v1.4.3-qa1` and more info about the status of this version can be check from [this](https://app.testlodge.com/a/26076/projects/40893/runs/642469) test run available on TestLodge.
