### ISSUE TITLE
When choosing a Capacity Package not displayed details 

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#783]
Min , Standart , recommended are not displaying details abou CPU , Memory , Disk (GB)
But if i selected Custom i see this details
![Peek 2022-06-01 12-11](https://user-images.githubusercontent.com/106578096/171377810-03320b8c-301a-45c7-86c2-c147bc63ce65.gif)

Version v1.4.2
Deployed on Testnet

**Comment by rkhamis** [comment]
Perhaps we should only show the specs next to the name

**Comment by AhmedHanafy725** [comment]
duplicate of #549
