### ISSUE TITLE
Rename Deployment List names and order

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#784]
look screenshot
![image](https://user-images.githubusercontent.com/106578096/171378438-a30ef382-78ed-45ca-ac8a-15b4e16c5a2a.png)

Version v1.4.2
Deployed on Testnet

**Comment by mohamedamer453** [comment]
Verified on devnet.

The order of the deployment list was changed to match the order of the deployments in the sidebar.

![image](https://user-images.githubusercontent.com/101194226/179392562-855e2607-65b0-4020-ba30-997b50323e99.png)
