### ISSUE TITLE
The "Back" and "Unlock" button are missing in the Profile Manager in TF Playground

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#786]
The "Back" button is missing
![image](https://user-images.githubusercontent.com/106578096/171379214-0aded724-0c33-4c62-91a1-a8e341268953.png)
"Unlock" Store button is missing
![image](https://user-images.githubusercontent.com/106578096/171379387-0b61caea-9773-4dc4-b26e-56571475b552.png)

Version v1.4.2
Deployed on Testnet
No.2 - Test case: TC394

**Comment by mohamedamer453** [comment]
[TC394](https://app.testlodge.com/a/26076/projects/40893/suites/195824?expand_section=337535#case_3403412) was updated. the outdated names were replaced the current names.

`Back` Button -> `Deactivate` Button.

![image](https://user-images.githubusercontent.com/101194226/173225294-d5a805c8-0a40-41c5-a44d-fce164c1b76a.png)

`Unlock` Button -> `Load Profiles` Button.

![image](https://user-images.githubusercontent.com/101194226/173225317-f7436991-a31d-4517-92c4-1a74db85990f.png)
