### ISSUE TITLE
Virtual Machine Input/Configuration Validation work not correctly

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#787]
1. Create VM with this MIN data 
![screenshoteasy - 2022-06-01T132514 323](https://user-images.githubusercontent.com/106578096/171383656-71ae8791-a4b1-40c7-bb76-91f9e1bbab9d.png)
Error mess: Validation failed. errors: An instance of k has failed the validation: - property workloads[1].data.compute_capacity.memory has failed the following constraints: min
![image](https://user-images.githubusercontent.com/106578096/171383553-ac8caffe-a8f7-4215-801f-535827146fe6.png)
2. Disk name with many symbols breaks layout (gif)
![Peek 2022-06-01 13-43](https://user-images.githubusercontent.com/106578096/171386770-56e47f06-75c7-4c78-9d3a-cbf824ed4547.gif)
3. No error message when inputs SSH key is empty 
![screenshoteasy - 2022-06-02T082531 138](https://user-images.githubusercontent.com/106578096/171558855-c321cfea-9ebc-457b-9d06-17ddcd966c84.png)

No.32 - Test case: TC716
Version v1.4.2
Deployed on Testnet

**Comment by maayarosama** [comment]
1.There was a validation error on creating a vm with the min data provided
![Screenshot from 2022-06-14 12-32-19](https://user-images.githubusercontent.com/66883096/173557593-70b3e330-21e0-448f-8c48-250cbd79fa4f.png)
However by adjusting the memory to 256 the vm was deployed successfully with the min data allowed.
![Screenshot from 2022-06-14 13-52-30](https://user-images.githubusercontent.com/66883096/173570883-e7d55ba7-23e1-42e7-8f07-836423dceb1d.png)

2. Disk name has a maximum validation of 15 characters.

![Screenshot from 2022-06-14 13-54-52](https://user-images.githubusercontent.com/66883096/173571356-f9a3051c-6f55-4a23-ab59-0cb7d86fc904.png)

**Comment by maayarosama** [comment]
@dmitri-alleo You're working on Testnet which isn't updated yet as we're working on Devnet, So there might be some differences.

**Comment by mohamedamer453** [comment]
1- This error was related to an incorrect memory validation message and it was fixed in #780 

2- Disk name validation was fixed and verified in #737 

3- Validation for Environment Variables `Key` and `Value` fields was added 

   ![image](https://user-images.githubusercontent.com/101194226/174047952-84e1930d-e42e-4775-b1a2-5c3b9563c302.png)

 and validation messages appear when the user clears the fields
