### ISSUE TITLE
Wrong Password shown in deployment view

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#79]
I found password to log into caprover in the json, but in the overlay 'captain42' is shown (which doesn't work). 
<img width="1264" alt="Screenshot 2021-11-30 at 13 53 48" src="https://user-images.githubusercontent.com/30384423/144052862-60fb764a-cc9d-43f6-b3b2-df5119ba2299.png">

**Comment by abom** [comment]
Verified, it shows the correct password now.
