### ISSUE TITLE
Peertube Verify not work correclty 

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#790]
1. Create Peertube with MIN data (select custom package)
![screenshoteasy - 2022-06-02T084518 653](https://user-images.githubusercontent.com/106578096/171561251-56aa6996-79ad-4b90-b9e4-b7d84ef1a834.png)
error message : 
![image](https://user-images.githubusercontent.com/106578096/171562686-27c3ef81-32b1-45db-8142-2bc02c7bae63.png)
Version v1.4.2
Deployed on Testnet
No.35 - Test case: TC719

**Comment by rawdaGastan** [comment]
This issue is solved now:
- Disk, memory and cpu have a limit validation

![790](https://user-images.githubusercontent.com/47260239/172828608-4f082460-11ea-45cc-bf47-cb265e960872.png)
