### ISSUE TITLE
During the testing of email sending with OwnCloud got an error related to PHP configuration on the server

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#792]
Error : A problem occurred while sending the email. Please revise your settings. (Error: Connection could not be established with host smtp.freesmtpservers.com :stream_socket_client(): unable to connect to none://smtp.freesmtpservers.com :2525 (Unable to find the socket transport &quot;none&quot; - did you forget to enable it when you configured PHP?))

![image](https://user-images.githubusercontent.com/106578096/171815794-ec792c85-eba3-4081-b54b-b9a79605ed7b.png)

SMTP data 
![image](https://user-images.githubusercontent.com/106578096/171815935-0a13bfd3-17a1-4eb3-b133-a2d92c3f49e6.png)

No.263 - Test case: TC712
Version v1.4.2
Deployed on Testnet

**Comment by sameh-farouk** [comment]
I think the mail server configuration is incorrect.
Could you try to enter 25 as a port number instead of 2525

**Comment by Omarabdul3ziz** [comment]
*Daily Updates*

Still debugging, but I had a different error ( Bad Credential ). still trying with different smtp configurations 
![image](https://user-images.githubusercontent.com/32527347/196223927-b4091cd6-ccf3-4bcd-b1b2-9ebab1e49cd6.png)

**Comment by Omarabdul3ziz** [comment]
mostly it is a bad smtp configurations, i used my gmail after i configure it to accept IMAP and it works fine 
![Untitled](https://user-images.githubusercontent.com/32527347/196402854-c9ddfd4b-021b-4a99-9f43-c8fe1b8587cb.png)
