### ISSUE TITLE
Add validation for "Name" input.VM.Disks

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#793]
add an error message when entering incorrect data
![screenshoteasy - 2022-06-04T100742 798](https://user-images.githubusercontent.com/106578096/171988758-924ece6b-b60f-4e5e-925c-f80c118ec45b.png)

Version v1.4.2
Deployed on Testnet

**Comment by rawdaGastan** [comment]
This issue is solved now:
- Disk name is limited to at most 15 characters

![793](https://user-images.githubusercontent.com/47260239/172830059-d526a55e-5cc7-40a4-b9cb-6132a6053903.png)
