### ISSUE TITLE
Mattermost Verify input/configuration validation not work correctly

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#794]
1. Create Mattermost with MIN data (select custom package)
![screenshoteasy - 2022-06-02T090407 290](https://user-images.githubusercontent.com/106578096/171563592-413aad40-df5d-499b-af81-f23cd7fe1f50.png)
Error mess: 
![image](https://user-images.githubusercontent.com/106578096/171564060-9925e635-f5f5-476e-a20b-766704ebab23.png)
2. SMTP is empty and hasn't error message
![screenshoteasy - 2022-06-02T090714 911](https://user-images.githubusercontent.com/106578096/171563986-dd7dbd6d-8c64-40d6-adfe-8aa9465d2b40.png)
Version v1.4.2
Deployed on Testnet
No.37 - Test case: TC721

**Comment by rawdaGastan** [comment]
This issue is solved now:
- Disk, memory and cpu have a limit validation 

![794-1](https://user-images.githubusercontent.com/47260239/172838381-4ac47307-b9ae-47d9-9a0d-bc1ad62f7bf8.png)

- SMTP server is optional and it won't break the deployment.
