### ISSUE TITLE
Taiga Input/Configuration Validation not work correctly 

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#796]
1. Password is empty and hasnt error mess
![screenshoteasy - 2022-06-02T092332 664](https://user-images.githubusercontent.com/106578096/171566252-0920488a-f885-4598-adfe-1d1436ce1754.png)
2. Create Taiga with MIN data (select custom package) 
![screenshoteasy - 2022-06-02T092423 349](https://user-images.githubusercontent.com/106578096/171566362-db281a80-67a6-4065-86ef-5721bdb3641c.png)
Error mess: 
![image](https://user-images.githubusercontent.com/106578096/171566412-1151aeec-2ec9-46d7-ba35-1c7d89b1b40d.png)
Version v1.4.2
Deployed on Testnet
No.39 - Test case: TC723

**Comment by rawdaGastan** [comment]
This issue is solved now:
- Password has a non empty validation
- Diask, cpu and memory have a limit validation 

![796](https://user-images.githubusercontent.com/47260239/172831842-7c06b166-8d7a-433f-b5a1-42919067bb68.png)
