### ISSUE TITLE
OwnCloud Input/Configuration Validation not work correctly

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#797]
1. Password is empty and hasnt error mess
![image](https://user-images.githubusercontent.com/106578096/171566611-26d71c93-9e99-40dc-92e4-5680093f22d4.png)
2. Create ownCloud with MIN data (select custom package)
![image](https://user-images.githubusercontent.com/106578096/171566680-0532c844-bc32-411e-a146-529e5bb22dd2.png)
Error mess : 
![image](https://user-images.githubusercontent.com/106578096/171566715-170da8f8-fa8e-4fcd-afd5-cac4553a2a3d.png)
Version v1.4.2
Deployed on Testnet
No.40 - Test case: TC724

**Comment by rawdaGastan** [comment]
This issue is now solved. 
- password has a non empty validation
- cpu, memory and disk have a limit validation.

![Screenshot from 2022-06-09 12-21-16](https://user-images.githubusercontent.com/47260239/172826044-7053b8c1-082b-4781-8d13-651c3cd15b45.png)
