### ISSUE TITLE
Casperlabs Input/Configuration Validation not work correctly

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#798]
Create Casperlabs with MIN data (select custom package)
![image](https://user-images.githubusercontent.com/106578096/171567118-00939d45-daf2-4224-8545-4e82a0c4ef34.png)
Error mess : 
![image](https://user-images.githubusercontent.com/106578096/171567150-df8d66f5-7100-4c0b-8501-368e5de579a1.png)
Version v1.4.2
Deployed on Testnet
No.42 - Test case: TC726

**Comment by rawdaGastan** [comment]
This issue is solved now.
- Disk, memory and cpu have a limit validation.

![798](https://user-images.githubusercontent.com/47260239/172828018-f6114181-c2d5-4002-a948-c204fb4d8419.png)
