### ISSUE TITLE
Show a QR code to transfer money directly to my account

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/grid_weblets#799]
Probably a button in the profile manager, where I can click `Send money` and it shows me QR Code similiar to the one on portal to transfer money from stellar to tfchain using a twin_id and bridge address

Need to consider testnet bridge address (to be used for devnet) and mainnet bridge address to be used for testnet and mainnet, as these networks use real money.

**Comment by xmonader** [comment]
cc @rkhamis @AhmedHanafy725

**Comment by mohamedamer453** [comment]
Verified on devnet.

The QR Code was added in the profile manager and it can be scanned through the Threefold Connect App. The Wallet Address and Twin ID are sent correctly through the QR Code and they are matching with the ones available in the portal.

![image](https://user-images.githubusercontent.com/101194226/174563947-15601a6d-d587-40dc-91ff-cb49ae3c7471.png)

![image](https://user-images.githubusercontent.com/101194226/174563530-9bf973c5-a551-41dc-b7fb-2289a0a9c869.png)

![image](https://user-images.githubusercontent.com/101194226/174563856-e5f8331b-91fb-4dcd-b12c-b3d7beb8629a.png)
