### ISSUE TITLE
Nodes list keeps loading

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/grid_weblets#803]
### Description

Nodes list keeps displaying "loading..." when changing filters (enable / disable ipv4)

### Logs/Alerts

![Screenshot from 2022-06-12 10-42-55](https://user-images.githubusercontent.com/47260239/173225695-687dccb1-669b-4264-8a38-90f17ecae517.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

After Enabling and Disabling the `Public IPv4` filter multiple times and checking the nodes list it no longer displays `Loading...` instead it displays `Please select a node id`

![image](https://user-images.githubusercontent.com/101194226/173620545-5506fced-7e1c-449a-bc30-ca2a68b90da4.png)
