### ISSUE TITLE
The "Save" button does not work correctly. In the Profile Manager modal

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#804]
Steps:

1. Click Add Profile
2. Don`t fill the inputs
3. Click "Save" button
Act res: New profile created
Ex res: New profile doesn't create. Error mess " Fill mandatory inputs "
![Peek 2022-05-31 12-53](https://user-images.githubusercontent.com/106578096/171378977-8913d2ce-fb92-4eae-9ebf-d663e7f1c1c6.gif)

version v1.4.2
Deployed on Testnet

**Comment by mohamedamer453** [comment]
Verified on devnet.

The `Save` button is  now disabled when the fields are empty or when the validation is triggered in one of the fields.

![image](https://user-images.githubusercontent.com/101194226/179390874-f00668d6-bd0f-472d-b03e-9ef72579de6c.png)

![image](https://user-images.githubusercontent.com/101194226/179390911-c3763c24-683e-4148-866f-aaee83ff63e2.png)

and it saves the user data normally when all of the inputs are valid.
