### ISSUE TITLE
Solutions using unofficial images

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#808]
### Description

Some of the solutions in the weblets are using unofficial images.

### Peertube

- https://hub.grid.tf/omarabdulaziz.3bot/omarabdul3ziz-peertube-v3.1.1.flist

   ![2022-06-01_12-21](https://user-images.githubusercontent.com/101194226/173319527-368321e7-d825-45da-949f-ae6d0807f40c.png)

### Funkwhale

- https://hub.grid.tf/asamirr.3bot/asamirr-tf-funkwhale-dec21.flist

   ![2022-06-13_10-00](https://user-images.githubusercontent.com/101194226/173319665-8a854a9d-4d70-48bd-a05a-4a045a6167bd.png)

### Mattermost

- https://hub.grid.tf/ashraf.3bot/ashraffouda-mattermost-latest.flist

   ![2022-06-13_10-04](https://user-images.githubusercontent.com/101194226/173319965-719c7b5a-625d-4c7a-9127-85ac1049b8e3.png)

### Discourse

- https://hub.grid.tf/rafybenjamin.3bot/threefolddev-discourse-v4.0.flist

   ![2022-06-13_10-09](https://user-images.githubusercontent.com/101194226/173320018-84bee022-89a7-419b-91e4-5663810df883.png)

### Taiga

- https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-grid3_taiga_docker-latest.flist

   ![2022-06-13_10-13](https://user-images.githubusercontent.com/101194226/173320069-b1860b09-73e6-4762-97d5-8588d9734815.png)

### ownCloud

- https://hub.grid.tf/samehabouelsaad.3bot/abouelsaad-owncloud-10.9.1.flist

   ![2022-06-13_10-17](https://user-images.githubusercontent.com/101194226/173320126-fa201780-1dc1-4af6-9c12-c7270fb16c85.png)

### Presearch

- https://hub.grid.tf/omarabdul3ziz.3bot/omarabdul3ziz-presearch-v2.2.flist

   ![2022-06-13_10-20](https://user-images.githubusercontent.com/101194226/173320179-3b3960cd-5721-4b65-ad57-9f22103d5547.png)

### Casperlabs

- https://hub.grid.tf/ranatarek.3bot/ranatrk-casperlabs-latest.flist

   ![2022-06-13_10-23](https://user-images.githubusercontent.com/101194226/173320241-a7e5ad57-c35d-4f68-8eaf-a51b5691336b.png)

**Comment by maxux** [comment]
`omarabdulaziz.3bot/omarabdul3ziz-peertube-v3.1.1.flist` -> `tf-official-apps/peertube-v3.1.1.flist`
`asamirr.3bot/asamirr-tf-funkwhale-dec21.flist` -> `tf-official-apps/funkwhale-dec21.flist`
`ashraf.3bot/ashraffouda-mattermost-latest.flist` -> `tf-official-apps/mattermost-latest.flist`
`rafybenjamin.3bot/threefolddev-discourse-v4.0.flist` -> `tf-official-apps/discourse-v4.0.flist`
`samehabouelsaad.3bot/abouelsaad-grid3_taiga_docker-latest.flist` -> `tf-official-apps/grid3_taiga_docker-latest.flist`
`samehabouelsaad.3bot/abouelsaad-owncloud-10.9.1.flist` -> `tf-official-apps/owncloud-10.9.1.flist`
`omarabdul3ziz.3bot/omarabdul3ziz-presearch-v2.2.flist` -> `tf-official-apps/presearch-v2.2.flist`
`ranatarek.3bot/ranatrk-casperlabs-latest.flist` -> `tf-official-apps/casperlabs-latest.flist`

**Comment by mohamedamer453** [comment]
Verified on devnet

All of the solutions are now using official images.

### Peertube

- https://hub.grid.tf/tf-official-apps/peertube-v3.1.1.flist

   ![image](https://user-images.githubusercontent.com/101194226/174029623-21205bc7-3d18-4b0b-8d9c-6c53c96a604c.png)


### Funkwhale

- https://hub.grid.tf/tf-official-apps/funkwhale-dec21.flist

   ![image](https://user-images.githubusercontent.com/101194226/174030240-635695cf-de89-48f9-a552-652a5cdc2673.png)


### Mattermost

- https://hub.grid.tf/tf-official-apps/mattermost-latest.flist

   ![image](https://user-images.githubusercontent.com/101194226/174031310-61ba532f-2ae7-45e5-b8a7-246a3fb4fa60.png)


### Discourse

- https://hub.grid.tf/tf-official-apps/discourse-v4.0.flist

   ![image](https://user-images.githubusercontent.com/101194226/174032422-662cc661-ba1b-4ee1-8e62-f251b27d2a0d.png)


### Taiga

- https://hub.grid.tf/tf-official-apps/grid3_taiga_docker-latest.flist

   ![image](https://user-images.githubusercontent.com/101194226/174033352-4cada004-b8a0-42b3-a7c3-0c5917e6c750.png)


### ownCloud

- https://hub.grid.tf/tf-official-apps/owncloud-10.9.1.flist

   ![image](https://user-images.githubusercontent.com/101194226/174034671-b76b9b3e-0f93-4f83-8180-24d9d505af3a.png)


### Presearch

- https://hub.grid.tf/tf-official-apps/presearch-v2.2.flist

   ![image](https://user-images.githubusercontent.com/101194226/174035262-6fe30601-e311-419c-b058-e6ca1759a6d9.png)


### Casperlabs

- https://hub.grid.tf/tf-official-apps/casperlabs-latest.flist

   ![image](https://user-images.githubusercontent.com/101194226/174035883-98840241-58f7-4997-bab8-65c5fad522f2.png)
