### ISSUE TITLE
details modal "close" button is not clickable

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#81]
Closing button ("x") is not clickable as shown in the following screenshot, maybe it's blocked by the menu button?

![Screenshot from 2021-12-01 08-09-38](https://user-images.githubusercontent.com/511438/144193627-3e0eb6a6-d467-4db1-b625-1699ecc83f7a.png)

**Comment by MohamedElmdary** [comment]
its not relevant any more as u can close modal by clicking anywhere on the overlay

**Comment by abom** [comment]
Verified

**Comment by abom** [comment]
Make sure it's there and clickable if so in latest version

**Comment by mhost39** [comment]
Verified
