### ISSUE TITLE
Kubernetes: Add worker configuration missing some Resource Units

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#837]
### Description

The `CPU` Field in the Manage workers modal box is missing the resource unit (Cores)

![image](https://user-images.githubusercontent.com/101194226/175000867-b2f11892-2820-4296-a291-23ef75b33445.png)

it needs to be changed from `CPU` to `CPU(Cores)` to be consistent with the rest of the weblets.

**Comment by rawdaGastan** [comment]
@mohamedamer453  do you want it to be changed in the bar ? like Disk(GB)

**Comment by mohamedamer453** [comment]
@rawdaGastan Sure, that would look better and same for Memory (GB)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The unit (Cores) was added  to the `CPU` field.

![image](https://user-images.githubusercontent.com/101194226/175888376-905f7a44-d53e-4b0c-bf05-b697ab2fb46f.png)

And units were also added to `CPU` and `Memory` columns in the workers list.

![image](https://user-images.githubusercontent.com/101194226/175888466-44fa4b8f-da84-44e1-ad63-4bbfa78b28d1.png)
