### ISSUE TITLE
New solutions using unofficial images

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#841]
### Description

New solutions are using unofficial images.

### TFhub Validator

- https://hub.grid.tf/ashraf.3bot/ashraffouda-threefold_hub-latest.flist

   ![image](https://user-images.githubusercontent.com/101194226/175017220-7369cb18-e964-425e-af0b-dd7aa6bc5913.png)

### Node Pilot

- https://hub.grid.tf/maxux42.3bot/maxux-nodep.flist

   ![image](https://user-images.githubusercontent.com/101194226/175016198-e03d579f-af38-4c09-8975-201c8c7dadab.png)

**Comment by xmonader** [comment]
@maxux please promote these flists

**Comment by maxux** [comment]
`ashraf.3bot/ashraffouda-threefold_hub-latest.flist` -> `tf-official-apps/threefold_hub-latest.flist`
`maxux42.3bot/maxux-nodep.flist` -> `tf-official-vms/node-pilot-zdbfs.flist`

**Comment by mohamedamer453** [comment]
Verified on devnet.

### TFhub Validator

- https://hub.grid.tf/tf-official-apps/threefold_hub-latest.flist

   ![image](https://user-images.githubusercontent.com/101194226/175812148-71b57c12-3fd4-44af-833a-44a6a7e99402.png)

### Node Pilot

- https://hub.grid.tf/tf-official-vms/node-pilot-zdbfs.flist

   ![image](https://user-images.githubusercontent.com/101194226/175812249-9287d7e0-1980-4717-aa2f-46bafbc7e8c9.png)
