### ISSUE TITLE
Typo - Change "vaildator" to "validator"

### ISSUE THREAD

**Issue by renauter** [threefoldtech/grid_weblets#846]
On top right of screenshot

![image](https://user-images.githubusercontent.com/73958772/175301492-2383641e-ccaf-4e8a-8465-78702624e8a2.png)

Here seems where it needs to be changed

![image](https://user-images.githubusercontent.com/73958772/175301595-ef77da66-bfc0-4f7b-9231-f0834d42d0d8.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The typo in the URL was changed from `vaildator` to `validator`

and by checking the solution itself the typo is not repeated anywhere else

![image](https://user-images.githubusercontent.com/101194226/175819105-2bf73281-d433-42dd-be8d-0e2897c3b363.png)
