### ISSUE TITLE
Kubernetes: hide the table's head if no workers are deployed

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#851]
in Kubernetes manage workers pop-up

![image](https://user-images.githubusercontent.com/41957921/175817204-e221351a-a1dd-4f1d-862f-d7d60c02a0e3.png)

**Comment by A-Harby** [comment]
Verified on devnet.

Successfully didn't appear in either 
1- when deploying with master with no workers.
2- when deploying with workers and then deleting them.
3- when deploying only master with no workers then adding worker and delete it back.

![image](https://user-images.githubusercontent.com/109473873/179956482-14ba94e3-6ae0-4c9b-aaa7-0d5f3f6f0a7c.png)
