### ISSUE TITLE
contract list shows different payment info

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/grid_weblets#856]
### Description

When checking the payment info of kubernetes deployment and the one in the contract list. It was not the same.
contact ID: 630

![issue1](https://user-images.githubusercontent.com/47260239/175819640-278de1f6-f38b-4c4e-a8cf-07c14f17404d.png)

![issue2](https://user-images.githubusercontent.com/47260239/175819650-f38e6818-8cc8-4418-8119-053199b5dba9.png)

### Steps to reproduce

- Deploy a K8s Cluster.
- After the deployment is complete open the contract list.
- Check the contract of the same deployment.

**Comment by mohamedamer453** [comment]
Verified on devnet.

i have a deployed k8s cluster with matching billing rates for the deployment and the contract.

![image](https://user-images.githubusercontent.com/101194226/177302080-346b3d2a-9416-47d2-a151-faf1b106ce5d.png)

![image](https://user-images.githubusercontent.com/101194226/177301610-53f30018-4eea-471a-aaf8-d6803b94dca2.png)
