### ISSUE TITLE
msg does not disappear after deployment

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/grid_weblets#858]
### Description

`Your solution is now starting. Please be patient` does not disappear after successful deployment and makes the user waits for nothing.
![issue4](https://user-images.githubusercontent.com/47260239/175821140-3f69b49b-de81-4caa-aa2b-5aa969784a3d.png)

### Implementation

I think we should remove it or replace it with `Your deployment is ready` for example.

**Comment by khaledyoussef24** [comment]
"Your solution is now starting. Please be patient" still does not disappear after successful deployment and makes the user waits for nothing.
![Screenshot from 2022-10-24 08-49-12](https://user-images.githubusercontent.com/110984055/197465090-54c04a8e-fbaa-4774-8e26-924df375c2dd.png)

**Comment by zaelgohary** [comment]
It disappears after 2 minutes as some solutions take time to start.

**Comment by khaledyoussef24** [comment]
20 minutes passed and it is still on the page may be latest changes aren't pushed ?
![Screenshot from 2022-10-26 08-47-39](https://user-images.githubusercontent.com/110984055/197954670-babf8ad3-d7a0-4bce-b653-5b699e6af52f.png)
![Screenshot from 2022-10-26 08-44-47](https://user-images.githubusercontent.com/110984055/197954676-5bc1c25b-f310-4a60-81e4-3597e0069d6b.png)
![Screenshot from 2022-10-26 08-36-14](https://user-images.githubusercontent.com/110984055/197954680-40ffc910-5ded-4a2a-9ed4-ea6371cde850.png)

**Comment by zaelgohary** [comment]
@khaledyoussef24 Please test locally as the latest changes won't be reflected until the next release.
