### ISSUE TITLE
kubernetes master's name starts with WR 

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/grid_weblets#859]
### Description

- master node in kubernetes name starts with WR (couldn't recogize it is the master node).
![issue5](https://user-images.githubusercontent.com/47260239/175821364-32c306d1-1ae5-451d-ac3d-d5c8f1d135a7.png)

### Implementation

- Change the name of the master to start with `MR` for example.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The master's name now starts with `MR` instead of `WR`

![image](https://user-images.githubusercontent.com/101194226/176416524-aa6c4811-2346-4f38-b07f-ce5477975b14.png)
