### ISSUE TITLE
`Node ID` when `Node Selection` is automatic is confusing  

### ISSUE THREAD

**Issue by RafyAmgadBenjamin** [threefoldtech/grid_weblets#86]
- When you select the `Node Selection` automatic then you see `Node ID`, it is a little bit confusing for the user
- If you choose the prefered configuration including mem, cpu, country,... and forget to press on `Apply Filters` you won't find nodes and it is also confusing 
![image](https://user-images.githubusercontent.com/46320202/144226067-fd105779-d36e-4fcf-9dc1-5285b43e889e.png)

I suggest hiding `Node ID` section tells the user to press `Apply filters`, then after pressing on the button we show a message for example
``` We filtered the nodes that fit your configuration, please choose now which node you want to use```
then we show `Node ID` section
something like this to explain what happened and what he should do now

**Comment by MohamedElmdary** [comment]
Automatic means showing suggestions for nodes that has the required resources

**Comment by xmonader** [comment]
It's now named Capacity filter option
