### ISSUE TITLE
simulator input for the token price (at start of end of 5 year period) does not accept `.` in decimal notation.

### ISSUE THREAD

**Issue by weynandkuijpers** [threefoldtech/grid_weblets#869]
Trying to input `0.08` in the perdio of registration (or any other decimal number) is impossible.  Same for the after 5 years "maximum token price".  No decimal input is possible.

<img width="423" alt="image" src="https://user-images.githubusercontent.com/13766992/174051136-fc43ee30-01ac-4afe-a46d-3345833c0409.png">

**Comment by AhmedHanafy725** [comment]
on https://simulator.grid.tf/, it accepts fraction number 
![image](https://user-images.githubusercontent.com/41957921/176164551-fe903840-e333-474f-affd-4804699c03a2.png)

**Comment by ramezsaeed** [comment]
@weynandkuijpers can u please check again and re-open if u still have an issue.
