### ISSUE TITLE
Simulator - choosing Titan and certified doubles reward boost

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#870]
After a recent change in the simulator code, the 25% reward boost for certification is applied twice when the Titan profile is chosen.

For steps to reproduce the issue and screenshots, see [this forum post](https://forum.threefold.io/t/tf-simulator-issues/3022/6).

## Desired behavior

Certified nodes get a 25% reward boost, regardless of whether the Titan profile is selected or not. Additionally, when a user selects the Titan profile, "Certified" should be selected automatically. All Titans are certified, so it doesn't make sense to select uncertified by default.

**Comment by MohamedElmdary** [comment]
After some investment in this issue here is why it's 25% reward boost

```py
# Total Reward In TFT
totalRewardInTft = cuRewardInTft + suRewardInTft + nuRewardInTft
```

#### CU
```py
# Reward  In TFT CU
cuRewardInTft = tftRewardPerCu * cu

# TFT Reward Per CU
tftRewardPerCu = (rewardPerCu / price) * tftBaseReward;

# Reward Per CU
if (Diy) or (Titan and not Certified) then 2.4
if Titan and Certified then 2.4 * 1.25 # Increase by 25%
```

#### SU
```py
# Reward  In TFT SU
suRewardInTft = tftRewardPerSu * su

# TFT Reward Per SU
tftRewardPerSu = (rewardPerSu / price) * tftBaseReward;

# Reward Per SU
if (Diy) or (Titan and not Certified) then 1
if Titan and Certified then 1.25 # Increase by 25%
```

#### TFT Base Reward
```py
# Same for Diy & Titan
if Certified then 1.25
if not Certified then 1
```

**Comment by scottyeager** [comment]
Any update on when we can expect a fix on this @ramezsaeed, @MohamedElmdary, @rkhamis?

**Comment by A-Harby** [comment]
Verified on Devnet.
DIY
![image](https://user-images.githubusercontent.com/109473873/231139716-c5c0ba18-88cb-49b7-835e-8243396548ae.png)
Titan uncertified
![image](https://user-images.githubusercontent.com/109473873/231140045-64cafc42-9251-4ddb-96db-72bc2f3f5632.png)
And titan certified as forum post calucated it should be 353 which is 25%.
![image](https://user-images.githubusercontent.com/109473873/231140441-b5cdbf11-0ff7-44c0-af68-d1d2671c5851.png)

Titan certified
![image](https://user-images.githubusercontent.com/109473873/231140187-df1b9bab-3cbb-4387-bc9a-bd749de700a3.png)
