### ISSUE TITLE
PRE weblet on testnet: not able to find any node on testnet for PRE node without public IPv4

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#873]
Found 3 farms with nodes on testnet: Freefarm, Freefarm2 and hctestfarm. 

With public IPv4 not selected, I can't find any node to deploy a PRE weblet on. 1/farm should be possible (but I don't know ofc whether it is not already deployed by someone else).

**Comment by gmachtel** [comment]
worked now on hctestfarm (contractID 8715), worked with farmid 23, nodeID 95. Did anything change ? Not for freefarm nor freefarm2 ? dad anything change ? (might be that both farms already had a PRE node running, but no idea how to detect that. 

I now cancelled the workload 8715 on testnet, so can be checked.

**Comment by Omarabdul3ziz** [comment]
currently, I was checking this and found that
- `freefarm2` is marked as dedicated so you need to have a rented node on it to be able to deploy on this farm. 
- and for `hctestfarm` "Only has one node 95" found a presearch deployment without a publicIp so i thought this why it is not available. but it looks this contract is yours so it is not the problem.
![Image](https://user-images.githubusercontent.com/32527347/177547896-d070e374-d744-4536-8bc6-1dcb6c95c2de.png)

- still checking the `FreeFarm` but it has many nodes so most probably there is also a pre deployment without public IP. but i will make sure

**Comment by Omarabdul3ziz** [comment]
- `FreeFarm` also has a presearch deployment without public IP

  ![Untitled (1)](https://user-images.githubusercontent.com/32527347/177553077-b0c553a2-6db4-4252-8950-d9b7dee41c9a.png)

- and rechecked the capacity filter and now it list `Node (95)` as available

**Comment by gmachtel** [comment]
OK, please also filter out farms that don't have any online nodes available. Not only for Presearch, this should be a filtering that works for any weblet. On testnet, atm (July 6), only FarmIDs 1, 23 and 204 have nodes online. Only a list of 3 farms should appear in the capacity filter io 3 pages.
