### ISSUE TITLE
TC724 - ownCloud Input/Configuration Validation

### ISSUE THREAD

**Issue by VenyaPanou** [threefoldtech/grid_weblets#874]
1. show a clear error mes for password input
![screenshoteasy (9)](https://user-images.githubusercontent.com/106578096/175258865-f08d8acc-aa39-4dc4-98d4-f03778c5199b.png)
TC724
Weblets: v1.4.3-qa3
https://play.qa.grid.tf/#/
Portal: https://portal.qa.grid.tf/

**Comment by mohamedamer453** [comment]
All validations are working for this field and validation messages for min/max length are working but the validation message for empty field isn't working.

![TF Playground (12)](https://user-images.githubusercontent.com/101194226/177180300-edbd7203-ee86-4fef-b0d4-6c95f80b4339.gif)

**Comment by mohamedamer453** [comment]
The empty field validation message is  still not working.

![image](https://user-images.githubusercontent.com/101194226/179391803-fdf74fe0-333c-44d8-8596-9237c10d133a.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The validation message was added.

![image](https://user-images.githubusercontent.com/101194226/179395857-5a25de6d-88fe-4d5e-b0f8-8141e26f5c67.png)
