### ISSUE TITLE
mainnet : deploying a PRE node on mainnet keeps on spinning

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#878]
play.grid.tf (so mainnet)

I try to deploy a PRE node on freefarm with public IPv4. But it keeps on spinning. 

<img width="1263" alt="Screenshot 2022-06-29 at 15 43 53" src="https://user-images.githubusercontent.com/30384423/176454914-bdda676d-53e1-4e65-a2f6-fa7e4739bed2.png">

**Comment by ramezsaeed** [comment]
should be resolved once main net is updated with Alpha-6

**Comment by gmachtel** [comment]
When is that planned ? Be aware that people already USE the weblets to deploy a PRE node. So current behaviour leads to bad user experience.
