### ISSUE TITLE
Deploy fails for second vm without reloading deploy form

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_weblets#881]
### Description

Deploying a second vm fails if the deployment form is not reloaded or refreshed, even if you change the second vm name.

### Steps to reproduce

- Deploy a vm
- Once done click back 
- Deploy a second vm with a different name (same specs) on a different node. Regarding of the node you choose, consistently results in:
![image](https://user-images.githubusercontent.com/88312671/176629043-14c80a53-cfb5-4558-8092-4ab15cb16bbf.png)

- Workaround 1: Refresh the page or load a different weblet, then load the 'Virtal Machine' weblet again. Deploying will work then.
- Workaround 2: Deploy the second vm on the same ZOS nodes as the first vm

### Logs/Alerts

![image](https://user-images.githubusercontent.com/88312671/176629466-4181c162-8e0e-46ea-a357-892dfbcc7259.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

You can now deploy without reloading the weblet and it will not cause the mentioned error. And it will only cause an error if the VM Name was not changed.

![TF Playground (21)](https://user-images.githubusercontent.com/101194226/179393651-ae7c2abd-bdce-4f7d-b269-f80f13e7f536.gif)
