### ISSUE TITLE
Deployment List broken on devnet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#888]
### Description

After a successful deployment when you close the deployment details modal box the deployment does not appear in the Deployment List and you have to reload the page for the list to work again.

![TF Playground (13)](https://user-images.githubusercontent.com/101194226/177182143-3c4b6caf-1b77-4557-9d6e-e318d8678c77.gif)

and in case of Kubernetes the deployment doesn't appear in the list even if you refresh the page

![TF Playground (14)](https://user-images.githubusercontent.com/101194226/177182876-ef06d232-6304-4272-9802-14a77c0700b0.gif)

****Note: The deployment seen in the list is an old deployment and the new one did not appear even after reloading the page

and there's a weird behavior when you switch to another deployment tab instead of refreshing the page

![TF Playground (15)](https://user-images.githubusercontent.com/101194226/177184514-486f3a9e-afb5-4269-8344-b0b9d28b26b4.gif)

The deployments disappear and there's a message asking you to activate your profile through the profile manager.

**Comment by zaelgohary** [comment]
fixed with PR https://github.com/threefoldtech/grid_weblets/pull/884

**Comment by mohamedamer453** [comment]
Verified on devnet.

- The VM deployment list was fixed and it shows the deployments without reloading the page.

   ![TF Playground (19)](https://user-images.githubusercontent.com/101194226/179392922-7e53f6bf-2133-48e9-9293-b59a2f100f87.gif)

- The Kuberenetes deployment list was also fixed and new deployments appear normally in the list.

   ![TF Playground (20)](https://user-images.githubusercontent.com/101194226/179393080-3c9ab8ff-aa8e-4fc7-b103-2344905fa603.gif)
