### ISSUE TITLE
can't delete vm from the deployment list

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#889]
![image](https://user-images.githubusercontent.com/41957921/177185936-e7d37201-5685-4c35-a844-f3ac7677b30f.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

VM deletion from the deployment list is working now. and i was able to successfully delete a vm from the deployment list.

![image](https://user-images.githubusercontent.com/101194226/179392723-5af55412-28fa-4037-a615-ee63e2db8ebd.png)
