### ISSUE TITLE
interaction  should be disabled before activating any profile

### ISSUE THREAD

**Issue by abom** [threefoldtech/grid_weblets#89]
This would cause issues like this

![Screenshot from 2021-12-02 04-23-50](https://user-images.githubusercontent.com/511438/144346001-5e412696-cc36-437e-9b2a-8b247122d845.png)

Suggestion: disable interactions with any weblet that requires user profile to be activated, we can auto-activate single profiles or add a **default** property to the profile that should be auto-activated.

**Comment by MohamedElmdary** [comment]
### Fixed
Disabled button if there is no profile

#### PR
https://github.com/threefoldtech/grid_weblets/pull/152

**Comment by abom** [comment]
@MohamedElmdary If no profiles are activated, the only thing the user can interact with is the node filter?

**Comment by MohamedElmdary** [comment]
@abom yes
for other deploy components its already disabled if there is no active profile

**Comment by waleedhammam** [comment]
verified
