### ISSUE TITLE
SSH key should be optional

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#896]
Some users are reporting confusion or difficulty with the requirement for an SSH public key in the profile manager, when SSH is not a requirement for all solutions (Presearch, Caprover, OwnCloud). At the same time, providing a key is the only way for users to access workloads by SSH, thus it should be emphasized.

## Currently
SSH public key field must be filled to create a new profile.

## Suggested
Allow a user to create a profile with no SSH key. Also add some text to the SSH key field indicating that it is the only way to use SSH:

**Public SSH Key (required to use SSH with deployments)**

**Comment by AhmedHanafy725** [comment]
the usage of the sshkey can be added to the placeholder, but making it optional will be a problem because some users will leave it empty as it's not required, and then they will complain that they can't reach their vms, k8s, ...

**Comment by scottyeager** [comment]
This is the same problem we already have: users are complaining because they must provide an SSH key for deployments that don't require SSH. These are users who sometimes have never used SSH before, don't have keys, and don't already know how to generate them.

A solution to handle both concerns could be to add a checkbox with a label like "Enable SSH". If the box is checked, then public SSH key must be entered to proceed, otherwise the field accepts no input.

**Comment by Kiludude** [comment]
I wonder, what happens to these deployments when something goes wrong? These people don't have ssh access, so they just destroy their deployment and create another one?
It just seems strange to me that you would deploy something, without any way of accessing it in case something breaks.

**Comment by coesensbert** [comment]
@scottyeager Deploying a workload with no way to log into it later on will bring frustrations later on and a bad experience for users in my opinion. There are many many reasons why one would login to any kind of workload, doesn't even have to be in case of troubles. Also less experienced users can learn, ask help or let a more experienced users login for them.
If there is no key, nobody (not even us if they come and ask for help) can do anything to help. You can only destroy and recreated.

Can the keys not be generated by us or in the browser, and being send to them? With a clear warning to keep them safe, like with wallet keys.

**Comment by mohamedamer453** [comment]
Verified on devnet.

The ssh Key is now an optional field in the profile manager.

![image](https://user-images.githubusercontent.com/101194226/184649298-16406dad-79ed-4334-a344-c941ccc41db9.png)

and there's a tooltip that warns the users that they will not be able to access their deployments if there's no ssh key. and the placeholder of the field mentions the usage of the ssh key.

also when the ssh key option is enabled and the field is left empty the `Activate`, `Add Profile`, `Save` buttons are disabled.

![image](https://user-images.githubusercontent.com/101194226/184651564-6b9eac92-0e95-4446-a668-eadea43e3cc3.png)

and the buttons are enabled again once a valid ssh key is entered. and all validations for this field are still working correctly

![image](https://user-images.githubusercontent.com/101194226/184651755-c28051aa-c126-41db-8ad3-fef85e26422d.png)
