### ISSUE TITLE
filter the available farms for presearch

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#900]
in the capacity filter on the presearch node, it lists all the farms even if it is not available to deploy presearch on which may be a little confusing. will be better if we filter the farms to only list the available nodes for presearch

**Comment by khaledyoussef24** [comment]
checked and tried more nodes  and deployed a presearch on node 95 on test net
![Screenshot from 2022-08-21 08-46-05](https://user-images.githubusercontent.com/110984055/185779224-66a224a0-8952-473c-863f-3d63fc24368b.png)

![Screenshot from 2022-08-21 08-41-29](https://user-images.githubusercontent.com/110984055/185779222-b54530b5-38e7-48ae-ab08-5249184ec847.png)
