### ISSUE TITLE
Add relation between contracts and deployments

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#902]
deployment's info can be added to the contract's metadata, so it can keep always the relation between them.

### Deployment
data to be added to the contract
```json
{
"type":  "<vm, kubernetes, or gateway>",  
"name": "<name of the deployment or domain name in case of gateway>",
"projectName": "<project name used in this solution>"
}
```

### Contracts' Table
add 2 columns `solution name` and `solution type`
`solution name`: should be the name in the contract's metadata directly
`solution type`:
in the case of the type is `kubernetes` -> `Kubernetes`
`gateway` -> `gateway`
`vm` -> `projectName`, if the `projectName` is empty, then it should be `Virtual Machine`

**Comment by A-Harby** [comment]
Here I Deployed 1 Kubernetes master with 5 workers (each separately by adding them after deploying master with no worker)  and Vm
![photo_2022-07-20_16-49-23](https://user-images.githubusercontent.com/109473873/180013513-4541ccdd-ef19-4cc9-a110-3f97e53519bf.jpg)

Need clarification if this is normal behavior and is it supposed not to mention worker names 
And why is their 3 solution with same name (K8)
![image](https://user-images.githubusercontent.com/109473873/180013187-e5ee6ed1-0489-498a-8b73-d94670855bab.png)

**Comment by rawdaGastan** [comment]
There is a problem in updating the master node when adding workers and will be solved here 
- https://github.com/threefoldtech/grid3_client_ts/issues/327

**Comment by khaledyoussef24** [comment]
##verified metadata now is not effected by deploying workers
verified on devnet
##steps made to verify this case

1. go to https://play.dev.grid.tf/
2. deploay a k8s master.
3. check the contract details.
4. return to k8s tab and go to deployed k8s.
5. add worker.
6. go to contracts.
7. check if the metadata if it is still there.
![Screenshot from 2022-08-23 13-16-04](https://user-images.githubusercontent.com/110984055/186146211-c2fe3f49-36b7-41e4-a5ab-3067c1ac0b63.png)
![Screenshot from 2022-08-23 13-20-01](https://user-images.githubusercontent.com/110984055/186146231-8d6db850-a805-4155-8056-7da0e7ebcd6a.png)
