### ISSUE TITLE
deployment name is not consistent

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/grid_weblets#908]
### Description

Deployment's name in the JSON object is different from the one in the deployment list
- Peerube
- Owncloud
- Funkwhale
- Discourse
- Taiga
- presearch
- casperlabs

### Steps to reproduce

- deploy a peertube instance

![Screenshot from 2022-07-14 11-32-07](https://user-images.githubusercontent.com/47260239/178970662-4b4474b3-9eec-4452-8056-a96b9ad2f957.png)

![Screenshot from 2022-07-14 11-32-12](https://user-images.githubusercontent.com/47260239/178970691-0982664a-50a3-40e9-b5ae-5eb1340fdf6e.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The same name that is displayed in the deployment list is available in the Deployment details.

![image](https://user-images.githubusercontent.com/101194226/179393913-84289117-b2fe-4829-81ab-24f9d5d57553.png)

![image](https://user-images.githubusercontent.com/101194226/179393935-4112e8d3-6bbe-4c48-80aa-1e224543d3af.png)

![image](https://user-images.githubusercontent.com/101194226/179393959-2c51f907-cc9f-4e3f-acf2-6331d82d9d47.png)
