### ISSUE TITLE
Add heading on contract's view with contracts wiki link

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#909]
it's not available now on the currently deployed wiki, but this should be added once the wiki gets updated.

**Comment by AhmedHanafy725** [comment]
wiki link to be added: https://library.threefold.me/info/manual/#/manual__tfchain_home

**Comment by mohamedamer453** [comment]
Verified on devnet.

A quick start docs link was added in the contracts description section and it redirects the user to https://library.threefold.me/info/manual/#/manual__tfchain_home

![image](https://user-images.githubusercontent.com/101194226/189672529-204eb663-5fa8-4957-83fc-9ee88393d156.png)
