### ISSUE TITLE
Can't add workers in kubernetes

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/grid_weblets#914]
### Description

Cannot add workers or update kubernetes

### Steps to reproduce

- deploy a kubernetes instance
- add a worker

### Logs/Alerts

![Screenshot from 2022-07-17 12-00-21](https://user-images.githubusercontent.com/47260239/179399353-527dfce3-a946-4dca-837d-9211600211bb.png)

**Comment by A-Harby** [comment]
Verified on Devnet.

worker can be added successfully into deployed kubernetes master (with or without having workers added before)
![image](https://user-images.githubusercontent.com/109473873/179972782-26237c60-466b-45bf-8e1f-2ab2213f7f02.png)
