### ISSUE TITLE
cancel contracts weblet

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#92]
Add a weblet to cancel contracts. 

- List all active contracts 
- Delete contract button https://github.com/threefoldtech/grid3_client_ts/blob/development/scripts/delete_all_contracts.ts
- Delete all contracts option

**Comment by MohamedElmdary** [comment]
### Added 
#### PR
https://github.com/threefoldtech/grid_weblets/pull/183

**Comment by waleedhammam** [comment]
verification blocked waiting for PR merge and release

**Comment by waleedhammam** [comment]
verified
![Screenshot from 2021-12-14 16-18-02](https://user-images.githubusercontent.com/10658229/146016372-e8b4fa46-5e85-4a4a-87e3-e32eaa1f18cf.png)
