### ISSUE TITLE
A worker is added despite not having enough resources in the node.

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#923]
### Description

When adding a worker to a Kubernetes master already deployed and selecting a node that does not have enough resources, an alert appears with a failed to deploy message, but after reloading the page, the worker will be listed.

### Steps to reproduce

1. Navigate to https://play.dev.grid.tf/#/
2. Choose Kubernetes on the left side menu, fill in the arguments, and deploy the master with no workers.
3. Navigate to the deployment list and click on Manage Workers.
4. Fill in the info for the new worker and click on Add Worker.
5. Repeat step 4, including selecting the same node, till an alert message appears: "Failed to deploy."
![1](https://user-images.githubusercontent.com/109473873/180026447-5e6bd6d1-5fbe-4e9c-8094-12678ee92fda.png)
![2](https://user-images.githubusercontent.com/109473873/180026488-9f6e7cde-9049-41e2-8471-9a8fb54732c6.png)
6. Reload the page and navigate to the deployment list and click on Manage Workers (failed to deploy workers will be listed).
![3](https://user-images.githubusercontent.com/109473873/180026500-827c3087-d155-4bbc-8976-a2c3b5031297.png)

### Logs/Alerts

U can ssh to all previous worker expect the one failed to deploy.
![4](https://user-images.githubusercontent.com/109473873/180026510-3bf01d7d-4c78-4277-9f4b-650c828bb55c.png)
Json
![5](https://user-images.githubusercontent.com/109473873/180026527-10f87818-571b-4405-970b-7e64971d60aa.png)

**Comment by AhmedHanafy725** [comment]
was that on the same node id?

**Comment by A-Harby** [comment]
Yes, the third worker (with failed to deploy alert) was added after the deployment of two workers on the same node (17) .

**Comment by khaledyoussef24** [comment]
the same problem still but now "the failed to deploy worker then refresh to doesn't have a Planetary Network IP.

![Screenshot from 2022-09-19 05-58-01](https://user-images.githubusercontent.com/110984055/190948090-2eba26fa-aa19-43bc-846a-8ea4d7cc179f.png)

Steps to reproduce

1. Navigate to https://play.dev.grid.tf/#/
2. Choose Kubernetes on the left side menu, fill in the arguments, and deploy the master with no workers.
3. Navigate to the deployment list and click on Manage Workers.
4. Fill in the info for the new worker and click on Add Worker.
5. Repeat step 4, including selecting the same node, till an alert message appears: "Failed to deploy."
![Screenshot from 2022-09-19 05-56-18](https://user-images.githubusercontent.com/110984055/190948104-b58fac2a-241c-401a-bf20-e3da164cf16d.png)
![Screenshot from 2022-09-19 05-56-37](https://user-images.githubusercontent.com/110984055/190948126-bf08b7f8-8c6f-47a6-8fa4-4fe364f07b2e.png)


6. refresh the page to find that the "failed to deploy" worker is added 
![Screenshot from 2022-09-19 05-58-01](https://user-images.githubusercontent.com/110984055/190948153-6ee75e81-41af-4ca0-b8b3-08a89534140f.png)

**Comment by rawdaGastan** [comment]
@khaledyoussef24 Solved in the client. It will be solved in weblets after releasing the new version of the client.

**Comment by khaledyoussef24** [comment]
Steps to verify

1. Navigate to https://play.dev.grid.tf/#/
2. Choose Kubernetes on the left side menu, fill in the arguments, and deploy the master with no workers.
3. Navigate to the deployment list and click on Manage Workers.
4. Fill in the info for the new worker and click on Add Worker.
5. once there is no enough resources you won't be apply to try to deploy

![Screenshot from 2022-10-23 15-28-50](https://user-images.githubusercontent.com/110984055/197395080-88734931-858b-4c14-83a0-56871d7cdd8c.png)
