### ISSUE TITLE
incorrect link for node pilot quick start documentation

### ISSUE THREAD

**Issue by sameh-farouk** [threefoldtech/grid_weblets#924]
the link in the top of the node pilot weblet refer to the VM doc.
should instead refer to https://library.threefold.me/info/manual/#/manual__weblets_nodepilot

![Screenshot from 2022-07-20 20-32-29](https://user-images.githubusercontent.com/42457449/180056782-78110ca8-b352-449d-892c-5e2d9e36116c.png)

**Comment by A-Harby** [comment]
verified on Devnet.

Quick start documentation link directs to correct link https://library.threefold.me/info/manual/#/manual__weblets_nodepilot
