### ISSUE TITLE
Delete selected button color

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/grid_weblets#925]
### Description

Color of the point needs to be changed

### Steps to reproduce

- Open contracts list
- Select one contract
- Delete selected
- Click cancel button in the alarm 

### Logs/Alerts

![Screenshot from 2022-07-21 11-06-51](https://user-images.githubusercontent.com/47260239/180176398-54c93fe5-f440-482c-83e1-87f8f1ec796c.png)

**Comment by A-Harby** [comment]
Verified on Devnet.

Text is readable and clear.

When button is disabled
![image](https://user-images.githubusercontent.com/109473873/181503971-2032972b-0715-40d6-b8aa-02e4109a1458.png)

when button is enabled.
![image](https://user-images.githubusercontent.com/109473873/181504260-b62bbc2e-4077-4d24-8a36-07d5b7cc0b7e.png)
