### ISSUE TITLE
Show unlocked/locked tokens in balance

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/grid_weblets#930]
When a contract is deployed, tokens are locked every hour. The balance just shows the total of my tokens on my account but not that I have locked tokens as well. We need to show both `free` and `locked` balances

**Comment by A-Harby** [comment]
Verified on Devnet.

![image](https://user-images.githubusercontent.com/109473873/181564199-3c4da562-8cb8-4a45-b5fd-6e1a118eefa1.png)
