### ISSUE TITLE
Change cores label to vcores

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#936]
When specifying capacity levels for a reservation, the CPU label currently says (Cores). Propose to update this to (vCores).

**Comment by mohamedamer453** [comment]
Verified on devnet.

Throughout the weblets the `Cores` label was changed to `vCores` 

![image](https://user-images.githubusercontent.com/101194226/184643450-26a13d96-884e-485b-bb03-6c9a4d9d89f3.png)

![image](https://user-images.githubusercontent.com/101194226/184643574-cc9016d4-2b53-4708-a9ed-49bb3f0dde09.png)

![image](https://user-images.githubusercontent.com/101194226/184643680-8c95a07c-1970-48c1-8b93-38b3d03c1b4d.png)
