### ISSUE TITLE
HELM: so Ops can take over deployment

### ISSUE THREAD

**Issue by coesensbert** [threefoldtech/grid_weblets#937]
Since the playground is running on DO and we should phase out, would it be possible to make a helm deployment of the playground?
This way Ops can run it on the production k8s cluster

**Comment by AhmedHanafy725** [comment]
it will be nice also to have a github workflow to auto deploy it on the cluster

**Comment by mohamedamer453** [comment]
Verified.

I was able to run the weblets through the created helm chart by creating a k8s cluster on the grid and a domain that points to the clusters IP then i followed the chart installation steps from [here](https://github.com/threefoldtech/grid_weblets/blob/development/weblets-chart/README.md) and it worked without any issues.

![image](https://user-images.githubusercontent.com/101194226/186645526-808cd51c-a741-4ed4-9593-fcb51a43c69d.png)

![image](https://user-images.githubusercontent.com/101194226/186645447-7480012a-d554-4f88-842d-72b0f6834cda.png)


> it will be nice also to have a github workflow to auto deploy it on the cluster

and this will be followed in #969
