### ISSUE TITLE
better way to find gateway nodes 

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#94]
Use `FilterOptions` for a better way to find the nodes which have a gateway, instead of `.getAccessNodes()`.

![Screenshot from 2021-12-02 12-11-21](https://user-images.githubusercontent.com/32527347/144401796-28792488-5bc6-4ea7-ba1d-8dece8960fc4.png)

**Comment by rkhamis** [comment]
what does this relate to @Omarabdul3ziz ?

**Comment by Omarabdul3ziz** [comment]
[here](https://github.com/threefoldtech/grid_weblets/blob/2a92a85aca934541455f5f3ff26cce31e05ea674/src/utils/gatewayNode.ts#L3) I used `getAccessNodes()` to filter the nodes which have public access to deploy a gateway on it (for peertube or funkwhale)
there is a better way to do that with `FilterOptions: {gatway: true}`
the old way works but this is just a better way. i am waiting to finish the all in one peertube image to make all refactoring once.
