### ISSUE TITLE
not reasonable rootfs size

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#941]
tried to deploy presearch instance on node 41 devnet  and according to the script it has
- 1 core cpu
- 1 GB ram

and got `3.7T` disk
![image](https://user-images.githubusercontent.com/32527347/183433883-d3c4aca9-f4f2-4d1b-98f3-8008b2919d21.png)

**Comment by scottyeager** [comment]
You see the full size of the underlying physical disk where the rootfs is allocated, in this case. Only mounted volumes properly display their quota size. See here: https://github.com/threefoldtech/zos/issues/1579

That said, I do think the attached volume is oversized (only a small key pair is stored there) and that too much RAM is reserved (runs fine on 512mb, which is what Presearch recommends).

Presearch node operators tend to be very cost conscious. Slimming down this deployment to the bare minimums can save over half the deployment costs (.16 TFT per hour for the weblet as currently configured, versus .07 TFT per hour for 1cpu/512mb ram/.5gb rootfs/no attached volume).

**Comment by mohamedamer453** [comment]
Verified on devnet.

The resources for presearch were reduced. the memory is now set to 512mb and the disk mounted in `/var/lib/docker` was removed.

![image](https://user-images.githubusercontent.com/101194226/201040111-4b7dda77-e9b8-4307-b956-3c440ddb3857.png)

and now it's deployed with the rootfs only without the attached volume and 512mb of ram, and it's working without any issues.

![image](https://user-images.githubusercontent.com/101194226/201040323-1f03d5d2-7b1d-427e-9ad3-3db5f2c86510.png)

![image](https://user-images.githubusercontent.com/101194226/201040380-d8717f8f-6e99-4af9-89f4-070d7b8c041c.png)

**Comment by scottyeager** [comment]
Thanks @Omarabdul3ziz and @mohamedamer453 for circling back on this 👍🏻
