### ISSUE TITLE
Implement solution provider on contract create

### ISSUE THREAD

**Issue by DylanVerstraete** [threefoldtech/grid_weblets#942]
related: https://github.com/threefoldtech/grid3_client_ts/issues/341

When a contract is created for a user in the weblets I would pass solution provider id `1`. 

When the upgrade is live on devnet I will create a solution provider called `Weblets`, where we then can test this functionality

**Comment by alichaddad** [comment]
Provider is missing from qa and test net. Should be added.

**Comment by DylanVerstraete** [comment]
Solution provider for qa created & approved!

**Comment by DylanVerstraete** [comment]
Solution provider for testnet created & approved!


Both providers have ID = 1

**Comment by mohamedamer453** [comment]
Verified on devnet.

Contracts created from the weblets now have `solutionProviderID` as `1`.

![image](https://user-images.githubusercontent.com/101194226/230907210-ca5eb51d-418a-4fd2-abd0-51382156f0bd.png)

It's also available on qanet and testnet but its value is still `0`.

![image](https://user-images.githubusercontent.com/101194226/230907430-6953fc32-505e-4868-a9ad-79a492fa9358.png)

![image](https://user-images.githubusercontent.com/101194226/230907464-179f1925-ed83-44fd-bda6-2e9f521bc60c.png)

Will keep an eye on the solutionProviderID once it's deployed there and will reopen this issue if it wasn't updated after the release.
