### ISSUE TITLE
Workflow to edit singleton profile

### ISSUE THREAD

**Issue by scottyeager** [threefoldtech/grid_weblets#944]
## Background

Currently, if a user wants to edit their profile when they only have a single profile in their manager, they must deactivate the entire profile manager and enter their password again. The alternative when multiple profiles are in a manager is to activate a different profile and edit the inactive one.

## Request: 

A better way to edit singleton profiles. Maybe the simplest way to do this is allow deactivating the currently active profile, so that no profile is active.

## Further consideration

The red deactivate button that appears in the upper right corner to deactivate the profile manager looks like it might achieve deactivating a profile. This button could be called "Lock" instead

**Comment by AhmedHanafy725** [comment]
the profile manager is changed, and this issue is outdated now
