### ISSUE TITLE
Minimum allowed disk size is not correct.

### ISSUE THREAD

**Issue by AbdelrahmanElawady** [threefoldtech/grid_weblets#945]
on `play.dev.grid.tf` `Disk Size` says "Minimum allowed disk size is 15 GB."
![Screenshot 2022-08-08 121400](https://user-images.githubusercontent.com/60783742/183396879-0a360f9c-75f3-4dd2-98f3-4cbfc59e5d24.png)

typing 15 removes the warning but doesn't give `Deploy` option
![Screenshot 2022-08-08 121437](https://user-images.githubusercontent.com/60783742/183397121-93220830-645f-447f-95a9-84c308157426.png)

typing 16 works just fine
![Screenshot 2022-08-08 121501](https://user-images.githubusercontent.com/60783742/183397233-bfcc4e03-89d4-4a55-8123-ef401d9287b8.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The disk validation was fixed and now when you enter `15` the `Deploy` button will not be disabled.

![image](https://user-images.githubusercontent.com/101194226/184645660-ddd69c67-815c-44e1-b5fd-ecfa60e5ca12.png)

and any value less than `15` will trigger the validation. and will also disable the `Deploy` button.

![image](https://user-images.githubusercontent.com/101194226/184645766-3e158a9c-487a-41e1-aa92-cecc816b4d2a.png)
