### ISSUE TITLE
the optional SMTP server validation 

### ISSUE THREAD

**Issue by A-Harby** [threefoldtech/grid_weblets#949]
### Description

In Mattermost, Taiga, and Owncloud, using an SMTP server is optional; nevertheless, if a user chooses to use one, every input must be checked to ensure that it is not empty and is in the proper format before deployment. 

### More

If you can deploy here without providing a username, how can a user log into the STMP server after?
![test 2](https://user-images.githubusercontent.com/109473873/184145562-df8ec7fe-b7a2-440c-9e3f-1b132e1fb1d1.png)

suggestion
First, create an on/off switch for the optional stmp server, and if the user chooses to have one, validate each input.

**Comment by zaelgohary** [comment]
Created a switch in all SMTP tabs which will enable/disable validations for mentioned inputs.

**Comment by khaledyoussef24** [comment]
### verified on devnet

steps made to verify this issue

1. open playground
2. go to mattermost tab
3. put the deployment capacity
4. enable the smtp switch
5. the validations will be enabled 


![Screenshot from 2022-10-26 09-10-07](https://user-images.githubusercontent.com/110984055/197959140-21d8407b-d937-4d63-99a7-5d3bee368d7f.png)


![Screenshot from 2022-10-26 09-10-16](https://user-images.githubusercontent.com/110984055/197959136-c70d0678-71d4-43de-b809-b7c17d1ae15d.png)

![Screenshot from 2022-10-26 09-10-27](https://user-images.githubusercontent.com/110984055/197959130-0df2c6b4-8fa2-4474-bc5b-b621092ba18c.png)
