### ISSUE TITLE
cannot login to owncloud throught threefold connect

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#950]
### Description 

Cannot login to owncloud through threefold connect.
it gives Internal Server Error

![owncloud](https://user-images.githubusercontent.com/110984055/183903775-992707fb-8c94-4f40-874d-dfb4bcafe940.png)
.
### Steps to Reproduce

- deployed from owncloud tab in weblets.
- navigated to the address of the own cloud.
- tried to login through threefold connect.

**Comment by Mahmoud-Emad** [comment]
This issue should be fixed after fix this [issue](https://github.com/threefoldtech/grid_weblets/issues/948#issuecomment-1217852777)

**Comment by khaledyoussef24** [comment]
solved and tested

![Image](https://user-images.githubusercontent.com/110984055/185870550-842e0099-c76a-424c-a0df-7c1fdcf80f7b.png)
