### ISSUE TITLE
Subsquid weblet solution

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/grid_weblets#951]
### Description

Create a new weblet solution for Subsquid indexer.

### Implementation

Based on the docker compose in the Subsquid archive repo https://github.com/subsquid/squid-archive-setup, An flist should be created and deployed on a vm.
### More

https://github.com/threefoldtech/home/issues/1174

**Comment by mohamedamer453** [comment]
Verified on devnet.

A new solution was added for subsquid indexer was added in the weblets.

![image](https://user-images.githubusercontent.com/101194226/186387566-86c47107-7b5d-46b0-afd0-8d5a01f37e40.png)

and i was able to deploy an instance successfully using one of the endpoints mentioned [here](https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/endpoints/production.ts). and it worked and i was able to perform operations on the graphql instance like getting the metadata/blocks.

![image](https://user-images.githubusercontent.com/101194226/186388153-bd262898-4600-4672-a2a2-ecfaacf475c8.png)


- Test case/verification steps can be found [here](https://app.testlodge.com/a/26076/projects/40893/suites/195824?expand_section=311053#case_3678431).
