### ISSUE TITLE
Adding a profile without an active twin 

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#952]
### Description

I was able to add a profile on devnet weblets that doesn't have an active twin on devnet the mnemonics passed the validation even though there is no twin on devnet with these mnemonics.

![image](https://user-images.githubusercontent.com/101194226/184655697-da291841-0fa8-4679-8709-156b0766e89d.png)

after creating the profile the `Twin ID` and `QR Code` are not loaded but the address is loaded (maybe because the same mnemonics are used for a twin on testnet so the address is the same.)

### Steps to reproduce

- Navigate to https://play.dev.grid.tf/
- Click on the profile manager and sign in or create a new one.
- Click on add profile.
- Add the mnemonics of an account that doesn't have a twin on devnet.

**Comment by rawdaGastan** [comment]
It is solved in the grid client

**Comment by khaledyoussef24** [comment]
### verified on devnet

**steps made to verify:**

1. create an account from polka dot extension
2. copy the Mnemonics and save it
3. create the account and don't confirm a twin
4. go to weblets
5. try to create profile with the menemonics you have already save
6. the user won't be created

[Screencast from 11-01-2022 04:01:44 PM.webm](https://user-images.githubusercontent.com/110984055/199254475-487a561c-0709-4151-8a5f-96680566885f.webm)
 
we can add a message to that shows that twin is not found or created.
