### ISSUE TITLE
Add documentation link to subsquid weblet

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/grid_weblets#957]
### Description

Add the Quick start documentation reference link to the Subsquid weblet solution, Once it's added to info_manual3 repo. 

### More

https://github.com/threefoldfoundation/info_manual3/issues/89

**Comment by mohamedamer453** [comment]
Docs for subsquid were added in https://github.com/threefoldfoundation/info_manual3/pull/90, however some parts of the docs are outdated. for example:

- There is a public IPv6 option mentioned [here](https://github.com/threefoldfoundation/info_manual3/pull/90/files#diff-adc04a8a4545dfd4b2f3e9f05725d643a0ab8ada2683c7f3b3caf8f5e4a90b84R17), while it's not present in the latest version of the weblets.
- Planetary IP option was hidden in #971.
- Ability to select a solution flavor/custom specs were added.
- Ability to select a gateway node was added. 
- In the weblets there is no link in the description section to redirect the user to the docs.
- The included configuration [screenshot](https://github.com/threefoldfoundation/info_manual3/pull/90/files#diff-54f294b7e63419cac8dcdc4676bccc059ed73486403cf5856746f951a5be42e6) is not up to date with all of the new options mentioned above.

![image](https://user-images.githubusercontent.com/101194226/188309359-1eae7cf2-7f90-4482-b282-3e2973d4076e.png)

**Comment by mohamedamer453** [comment]
Most of the comments mentioned above are resolved since i was verifying on an outdated version of the docs. the updated version can be found [here](https://github.com/threefoldfoundation/info_manual3/blob/development/wiki/weblets/weblets_subsquid.md). and only a couple of issues are still left.


> * There is a public IPv6 option mentioned, while it's not present in the latest version of the weblets.

> * In the weblets there is no link in the description section to redirect the user to the docs.

**Comment by mohamedamer453** [comment]
Verified on devnet.

A quick start documentation link was added in the description section and it redirects the user to the [subsquid docs](https://library.threefold.me/info/manual/#/manual__weblets_subsquid)

![image](https://user-images.githubusercontent.com/101194226/189669908-79c8730f-e04b-4a44-bcd7-057fd1e16425.png)
