### ISSUE TITLE
Filtering nodes in nodepilot

### ISSUE THREAD

**Issue by rawdaGastan** [threefoldtech/grid_weblets#959]
### Description

- Filtering nodes in nodepilot shows some available nodes although there are no public IPs available.

### Steps to reproduce

- deploy a nodepilot instance

### Logs/Alerts

![Screenshot from 2022-08-21 14-25-56](https://user-images.githubusercontent.com/47260239/185790885-285fd499-e6ca-4d00-8e11-fa658039c63f.png)

**Comment by AhmedHanafy725** [comment]
this is related to https://github.com/threefoldtech/tfchain_graphql/issues/53
some IPs are already deleted from the chain, but still not synced to graphql so they appear as free public IPs in the capacity filter

**Comment by khaledyoussef24** [comment]
verified on devnet made node pilot deployments using node filtering and it now shows that only nodes with public IPs
![Screenshot from 2022-09-19 06-35-55](https://user-images.githubusercontent.com/110984055/190950535-bb465d39-f398-447b-a36a-842fd625de19.png)
