### ISSUE TITLE
All in one Peertube weblet

### ISSUE THREAD

**Issue by Omarabdul3ziz** [threefoldtech/grid_weblets#96]
Run the required services ( Redis & Postgres ) on the same VM with peertube

**Comment by abom** [comment]
Please check https://github.com/threefoldtech/tf-images/tree/master/peertube, it seems it already have it all, just make sure to expose a data volume and maybe we can update it to use zinit later.

**Comment by asamirr** [comment]
Was incomplete and outdated

**Comment by Omarabdul3ziz** [comment]
https://github.com/threefoldtech/tf-images/blob/peertube/peertube_2/Dockerfile

Here a stage Dockerfile that create an image contains:
- redis-server
- postgresql
- configured peertube service 

We still working on:
- adding nginx with a certified domain
- expose the ports. so it can be accessed from the host browser

**Comment by Omarabdul3ziz** [comment]
The docker image was working well but the deployed image with the flist keep crashing.
working with @ashraffouda to ssh into the VM and trace what causes that.
