### ISSUE TITLE
no contracts are created

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#961]
### Description

the test was made on https://play.dev.grid.tf/

1. login into your account.
2. make any deployments (k8s,vms,etc...).
3. after making deployments you can check for your machines in deployments.
4. no contracts are found in the contract tab even though they are found in deployments. 
![Screenshot from 2022-08-23 09-32-57](https://user-images.githubusercontent.com/110984055/186100437-b9d62319-cc97-42b3-9a4e-42e6c5580f2a.png)
![Screenshot from 2022-08-23 09-33-05](https://user-images.githubusercontent.com/110984055/186100446-fbc45777-28ed-4239-aa77-1116b339dac1.png)

**Comment by DylanVerstraete** [comment]
Will be fixed when graphql is back in sync @hossnys is now doing that.

**Comment by hossnys** [comment]
graphql sync completed

**Comment by khaledyoussef24** [comment]
the test was made on https://play.dev.grid.tf/

1. login into your account.
2. make any deployments (k8s,vms,etc...).
3. after making deployments you can check for your machines in deployments.
4. contracts are found in the contracts tab


![Image](https://user-images.githubusercontent.com/110984055/186400099-f79331db-d5c9-4c78-9249-fa7f6bde828e.png)
