### ISSUE TITLE
Add CPU and memory fields to the subsquid solution

### ISSUE THREAD

**Issue by maayarosama** [threefoldtech/grid_weblets#966]
### Description

Add a Cpu and memory fields to the subsquid deployer as the process might go faster if more resources are allocated.

**Comment by khaledyoussef24** [comment]
##verified on devnet

1. go to https://play.dev.grid.tf/#/subsquid
2. insert the info of the subsquid you want to deploy
3. deploy the unit
4. after the success of the deployment cpu and memory will be available to see
![Screenshot from 2022-08-24 21-26-29](https://user-images.githubusercontent.com/110984055/186507898-e67ffce9-dcae-47cc-94b1-f01b6d17007d.png)
![Screenshot from 2022-08-24 21-26-43](https://user-images.githubusercontent.com/110984055/186507914-bb61513e-438c-4303-9c79-bd757c5638df.png)
![Screenshot from 2022-08-24 21-26-20](https://user-images.githubusercontent.com/110984055/186507928-6e9dee2e-d238-4b6e-b622-b1b319f710ba.png)
