### ISSUE TITLE
New Presearch release systematically brought nodes down

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/grid_weblets#968]
Presearch changed release to 1.0.13. Normally then also auto-updater should execute. It was probably launched but the result was that all PRE nodes I had on TF Grid went down, exit occurred (see screenshot). I could restart manually, see also screenshot, but exopectation is that the weblet takes care of it without manual intervention. 
<img width="997" alt="Screenshot 2022-08-24 at 12 59 24" src="https://user-images.githubusercontent.com/30384423/186596762-8515a092-e775-4dc4-bfaf-1be62703e74c.png">

**Comment by scottyeager** [comment]
Note that the `prerestorer` service is only responsible for copying the restored keypair into the docker volume. There's no need to run it again after the VM starts.

I think I see why the node container didn't restart. Compare the instruction command [given by Presearch](https://docs.presearch.org/nodes/setup):

```
docker stop presearch-node ; docker rm presearch-node ; docker stop presearch-auto-updater ; docker rm presearch-auto-updater ; docker run -d --name presearch-auto-updater --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock presearch/auto-updater --cleanup --interval 900 presearch-auto-updater presearch-node ; docker pull presearch/node ; docker run -dt --name presearch-node --restart=unless-stopped -v presearch-node-storage:/app/node -e REGISTRATION_CODE=$YOUR_REGISTRATION_CODE_HERE presearch/node ; docker logs -f presearch-node
```

And the contents of `/etc/zinit/prenode.yaml `:

```
exec: |
  bash -c '
    docker run -dt --name presearch-node -v presearch-node-storage:/app/node -e REGISTRATION_CODE="$PRESEARCH_REGISTRATION_CODE" presearch/node
  '
```

Our command is missing the `--restart=unless-stopped` flag for both the updater service and the node container itself.

**Comment by Omarabdul3ziz** [comment]
check the comment https://github.com/threefoldtech/tfgrid-sdk-ts/issues/130

**Comment by mohamedamer453** [comment]
Verified in https://github.com/threefoldtech/tfgrid-sdk-ts/issues/130

**Comment by gmachtel** [comment]
2 questions around this: 
- Is it already available on testnet ? I just received again a few disconnection messages, and I see the same happening. 

See <img width="1017" alt="Screenshot 2022-08-31 at 14 12 12" src="https://user-images.githubusercontent.com/30384423/187675539-fcf9885a-466b-49ee-bdff-3a54dd73b448.png">

- does the implementation solve the issue also for existing deployments ?
