### ISSUE TITLE
Create a github workflow to auto deploy the weblets helm chart on the cluster

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#969]
it will be nice also to have a github workflow to auto deploy it on the cluster

_Originally posted by @AhmedHanafy725 in https://github.com/threefoldtech/grid_weblets/issues/937#issuecomment-1212075090_

**Comment by AhmedHanafy725** [comment]
closing in favor of https://github.com/threefoldtech/tf_operations/issues/1220
