### ISSUE TITLE
Subsquid: Hide planetary option in the deployment

### ISSUE THREAD

**Issue by AhmedHanafy725** [threefoldtech/grid_weblets#971]
the planetary option is mandatory for deploying the gateway's workload, so if someone disables it, it will be broken.

![image](https://user-images.githubusercontent.com/41957921/187032887-41cbb5cf-3778-4cd8-b46b-7b77cd14e22b.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.
The `Plantary Network` option was hidden.

![image](https://user-images.githubusercontent.com/101194226/187249457-e79f53eb-9af5-4f1e-b2b7-7de924d80ce8.png)
