### ISSUE TITLE
Failed to delete deployments on devnet

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#978]
### Description

I had 3 subsquid instances deployed from the weblets and when i tried to delete the 3 instances i got the following error for all the contracts related to these instances.

![image](https://user-images.githubusercontent.com/101194226/187407299-0b4e0f79-f398-4117-96b9-eee34d1661e4.png)

![image](https://user-images.githubusercontent.com/101194226/187406237-cf376408-0edd-4ba0-9108-190df4556f61.png)

![image](https://user-images.githubusercontent.com/101194226/187406605-90429628-caa9-4e90-8578-a4575a86fe74.png)

![image](https://user-images.githubusercontent.com/101194226/187406960-3240c2ad-1be6-4c5f-9e96-d8fe1ce3ecf3.png)

![image](https://user-images.githubusercontent.com/101194226/187405888-84236b41-410b-42b9-8800-66c72c8e2fba.png)

and when i tried to access the contract information form the chain , the state of the contracts were `CanceledByUser`

![image](https://user-images.githubusercontent.com/101194226/187409120-483fb557-f932-4a43-9d16-f0ed51efea80.png)

the contracts are still available in the weblets and the deployments are also available but the deployments are not working.

**Comment by ramezsaeed** [comment]
please re-verify

**Comment by mohamedamer453** [comment]
Verified on devnet.

Deployment deletion is working now and i was able to delete multiple different deployments on different nodes without any errors.

![TF Playground (24)](https://user-images.githubusercontent.com/101194226/187649251-8d9f6612-d618-431a-af69-6df673922c95.gif)


also contract deletion is working without any errors.

![TF Playground (25)](https://user-images.githubusercontent.com/101194226/187652099-15fd007e-7042-4798-9788-940bd5f5a820.gif)
