### ISSUE TITLE
Public IP filtering is not working correctly

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#981]
### Description

I was trying to deploy a casperlabs instance on node `11` and then i received an error that the farm doesn't have enough public ips even though node 11 appeared normally in the capacity filter.

![image](https://user-images.githubusercontent.com/101194226/187935344-a91fd3d3-6d88-4fc5-85d2-8eec289c8e18.png)

and the same thing happened on `node 30`

![image](https://user-images.githubusercontent.com/101194226/187935743-dab307f0-aace-4356-94a4-28a9ded4ecca.png)

**Comment by rawdaGastan** [comment]
duplicate 
- https://github.com/threefoldtech/grid_weblets/issues/959

**Comment by mohamedamer453** [comment]
Closing this one and the issue will be followed in #959
