### ISSUE TITLE
Deploy Button is not disabled when a gateway node is not selected in some cases

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#982]
### Description

The `Deploy` button is not disabled when a gateway is not selected. in some cases. for example after a successful deployment or an error when you click on `Back` you will find the same configuration that you had before deployment but the `Gateway Node` option will not be selected and the `Deploy` button will be enabled so if you change the deployment name and click on `Deploy` it'll try to deploy without a `Gateway node` and will result in an error.

![TF Playground (27)](https://user-images.githubusercontent.com/101194226/187941513-0e5d318e-769b-4d71-a352-087949e3bf45.gif)

![TF Playground (26)](https://user-images.githubusercontent.com/101194226/187940756-6a93969c-c356-4624-a021-16f368a2de29.gif)

![image](https://user-images.githubusercontent.com/101194226/187939929-73fd4e0a-6552-475d-94ad-53aaf7ce329d.png)

**Comment by mohamedamer453** [comment]
The issue is still present. and the deploy button was not disabled.


![TF Playground (28)](https://user-images.githubusercontent.com/101194226/187970134-1b570e68-de99-41f6-9a0f-04e021be4536.gif)

**Comment by MohamedElmdary** [comment]
While deploying any instance the `SelectGatewayNode` component gets destroyed from the app and its **state** is gone however the state for the parent is still the same so this makes the issue

**Comment by MohamedElmdary** [comment]
### Fixed
#### PR
https://github.com/threefoldtech/grid_weblets/pull/985

**Comment by mohamedamer453** [comment]
Verified on devnet.

The deploy button now gets disabled when you click on `Back` after a successful deployment or after encountering an error.

![TF Playground (29)](https://user-images.githubusercontent.com/101194226/188308886-92449a08-a708-455e-9fb0-c766c8fa427b.gif)
