### ISSUE TITLE
the manual filter is not working in weblets

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#990]
### manual capacity filter is not working 
Search for similar issues first, if not complete the following template

1. Navigate to [play ground](https://play.qa.grid.tf/)
2. Configure any deployment.
3. Choose the capacity filter.
4. Verify that every node available in the nodes list from the capacity filter is also available from the manual filter.
5. it gives node error when choosing it in the manual filter
![Screenshot from 2022-09-05 16-52-51](https://user-images.githubusercontent.com/110984055/188476933-692b2619-20f0-47bf-9600-cf48a3426fec.png)
![Screenshot from 2022-09-05 16-53-26](https://user-images.githubusercontent.com/110984055/188476940-3fe178f2-5c04-4c7e-80c0-2a1bfece49b6.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

All the nodes that appear in the capacity filter are also available for deployment from the manual filter.

for a normal deployment like a vm with no public IPs

[Untitled_ Sep 8, 2022 10_08 AM.webm](https://user-images.githubusercontent.com/101194226/189071877-3c61d3cb-51da-45a1-926e-01559d27f6ca.webm)

and for a deployment that needs a public ip by default like casperlabs

[Untitled_ Sep 8, 2022 10_13 AM.webm](https://user-images.githubusercontent.com/101194226/189071981-cced8acd-4628-4af0-8589-35eff3c80a18.webm)

and i've also tried the nodes that were not available in the capacity filter and non of these nodes were available for deployment.
