### ISSUE TITLE
Selecting Gateway Node is getting reset

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/grid_weblets#991]
### the gateway node field is getting reset when choosing another tab in the following

1. Mattermost
2. Discourse
3. Taiga
4. Owncloud

choose the gateway in any of the above deployments:

1. fill the configurations.
2. choose the gateway.
3. go to other tab(SMTP Server ,mail server ).
4. when returning to the configurations tab only the gateway choice is getting a reset and you have to choose it again.

![Screenshot from 2022-09-05 17-14-53](https://user-images.githubusercontent.com/110984055/188479778-4677e768-6671-4a86-b5a2-dab63b0b2cb1.png)
![Screenshot from 2022-09-05 17-15-04](https://user-images.githubusercontent.com/110984055/188479783-059e3883-f506-41e2-ba6b-bcff1e547fc7.png)
![Screenshot from 2022-09-05 17-15-19](https://user-images.githubusercontent.com/110984055/188479785-798b670b-1f2c-4f3a-ba95-21a86ccd8eb6.png)

**Comment by mohamedamer453** [comment]
Verified on devnet.

The gateway selection is not getting reset anymore when you switch to another tab.

![TF Playground (30)](https://user-images.githubusercontent.com/101194226/189062646-f9ab4f16-8ad5-499b-968e-36f1bae26415.gif)

**Comment by mohamedamer453** [comment]
Reopening since i didn't see that the deploy button was disabled when you return from the other tab and you have to deselect the gateway and select it again for the deploy button to be enabled again.

[TF Playground.webm](https://user-images.githubusercontent.com/101194226/189633762-89d072f3-e45c-4637-b267-f6934ab44b71.webm)

**Comment by mohamedamer453** [comment]
Verified on devnet

The button is not disabled anymore when you return to the other tab.

[TF Playground (1).webm](https://user-images.githubusercontent.com/101194226/189647676-16094746-d687-435f-be94-0024bf9cb237.webm)
