### ISSUE TITLE
`SelectCapacity` Component get reset when changing tab or deploy

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/grid_weblets#993]
https://user-images.githubusercontent.com/31689104/188615777-b3d78e9f-a090-4924-9c1f-e81232e003e5.mp4

**Comment by khaledyoussef24** [comment]
### the problem still exists
**tried on devnet**
steps made

1. open weblets
2. go to discourse
3. choose gateway
4. go to mail server tab
5. the config screen won't open

[Screencast from 10-25-2022 09:22:35 AM.webm](https://user-images.githubusercontent.com/110984055/197709975-5802d1f8-efd4-45b9-9f5f-eaf694c037fd.webm)

**Comment by khaledyoussef24** [comment]
### verified on devnet

now the capacity doesn't get a reset

1. open weblets
2. go to discourse
3. choose gateway
4. go to mail server tab
5. go back to config verify that capacity as you choose it
