### ISSUE TITLE
Unable to reach CapRover Instance after successful deployment

### ISSUE THREAD

**Issue by mohamedamer453** [threefoldtech/grid_weblets#999]
Tested on `qanet` Weblets `v1.5.0-qa4`

### Description

After deploying a CapRover instance from the weblets, i was able to access the instance and create a self-hosted registry but when i tried to add my `Grid Configuration` in the setting it kept loading and when i refreshed the page i was unable to access the page. 

![image](https://user-images.githubusercontent.com/101194226/188899510-b237f071-414c-465d-ade7-d9c743d50bb3.png)

and when i tried to ssh to the vm i got disconnected multiple times with this error 
```
root@testvm2:~# client_loop: send disconnect: Broken pipe
```
and after a while i was able to ssh without disconnections and i got the logs by running `zinit log`

[caprover_logs.txt](https://github.com/threefoldtech/grid_weblets/files/9506917/caprover_logs.txt)

but again as you can see in the logs i got disconnected again with the same error mentioned above.

**Comment by mohamedamer453** [comment]
The instance is stable now and it works without any disconnections but the problem with the grid configurations is still present when i entered my gird configs and set the network to `dev` it kept loading forever but it worked when i changed the network to `test` and my configs were saved and i was able to deploy a caprover worker node on the gird as seen in the screenshot below


![image](https://user-images.githubusercontent.com/101194226/189144061-dbe827ae-cc80-47c1-92bf-a166d9e42862.png)

![image](https://user-images.githubusercontent.com/101194226/189144279-07ed08ad-2cc9-4442-a2e7-7d60d06d0543.png)

![image](https://user-images.githubusercontent.com/101194226/189144379-13fb0ead-d597-4495-8f97-fd21e06b6283.png)

![image](https://user-images.githubusercontent.com/101194226/189144454-98e397e1-d251-4fc7-a75a-e95f71d531e2.png)

**Comment by AhmedHanafy725** [comment]
@MohamedElmdary this needs an update for the grid3 client on the caprover's image
